### DISCUSSION TITLE
[Proposal] Extend multipart properties in mixins

### DISCUSSION THREAD

**Discussion by SevenOutman** [less/less.js#3674] [Ideas]
There're several CSS properties that supports multiple parts, e.g. `transition`. Sometime we want to write mixins that extends these properties, for example, below is a mixin meant to add background-color transition to a class.

```less
.add-background-transition() {
  transition: background-color 0.3s;
}
```

But applying this mixin will not result in transition to be extended but overwritten:

```less
.class {
  transition: color 0.3s;
  .add-background-transition(); // resulting in missing text-color transition
}
```

So I think it would be great if Less supports extending properties like transition:

```less
.add-background-transition() {
  +transition: background-color 0.3s; // a leading plus sign indicates extending
}

.class {
  transition: color 0.3s;
  .add-background-transition(); // resulting in transition: color 0.3s, background-color 0.3s;
}
```

**Comment by matthew-dean** [comment]
You can already do this.
```less
.add-background-transition() {
  transition+: background-color 0.3s;
}

.class {
  transition+: color 0.3s;
  .add-background-transition();
}
```
Result:
```css
.class {
  transition: color 0.3s, background-color 0.3s;
}
```

**Reply by SevenOutman** [reply]
That's cool! But I don't see it in documentation. Did I miss something?

**Reply by iChenLei** [reply]
@SevenOutman https://lesscss.org/features/#merge-feature

**Reply by SevenOutman** [reply]
@iChenLei Thanks!

**Reply by SevenOutman** [reply]
One further question: is there ability to de-merge such properties? Like:

```less
.no-text-transition() {
  transition-: color;
}
```
