### DISCUSSION TITLE
Missing whitespace in import causes translation to stop

### DISCUSSION THREAD

**Discussion by zhusjfaker** [less/less.js#3691] [General]
**To reproduce:**

a.less
```less
.a {
  font-size: 16px;

  .b {
      margin: 0;
      color: #000;
  }
}
```
index.less
```less
@import"./a";

.a {
    font-size: 16px;

    .b {
        margin: 0;
        color: #000;
    }
}
```

**Current behavior:**

gen css ->

```css
@import "./a";
.a {
  font-size: 16px;
}
.a .b {
  margin: 0;
  color: #000;
}
```
**Expected behavior:**

```css
.a {
  font-size: 16px;
}
.a .b {
  margin: 0;
  color: #000;
}
.a {
  font-size: 16px;
}
.a .b {
  margin: 0;
  color: #000;
}
```

**Environment information:**

- `less` version: 3.13.0
- `nodejs` version:  v16 lts
- `operating system`: darwin | macos
