### DISCUSSION TITLE
Can I use mixin/namespace guards like header guards in c++.

### DISCUSSION THREAD

**Discussion by wusikijeronii** [less/less.js#3697] [Q&A]
Hello. I am less beginner and I want something as in the pseudocode below:
```css
#windows() {

    .modal() {
        @MODALWINDOW: true;

        #window-modal when (VALIDATEWINDOW) {
            &:extend(#window-validate);
        }

        #window-modal when (not VALIDATEWINDOW) {
            background-color: red;
        }
    }

    .validate() {
        @VALIDATEWINDOW: true;

        #window-validate when (MODALWINDOW) {
            &:extend(#window-modal);
        }

        #window-validate when (not MODALWINDOW) {
            background-color: tomato;
        }
    }
}
```

I use a widget-based component system and this way is most comfortable for me. But it isn't a necessary thing. I just wanna know - can I do it. It works if I use true/false defined variables before `#window` namespace ('cos if I define a variable in the namespace root each one when I call mixins I will null variables). I also tried to create a separate namespace for defines but when I use `.... when (#somenamespace[@variable])` I get an error.
