### DISCUSSION TITLE
Problems with double && compilation

### DISCUSSION THREAD

**Discussion by junquanDong** [less/less.js#3746] [Q&A]
I have a puzzled question. 
The && selector is not ideal when compiled.
Please see the code snippet.

Code:
```less
[type=password]{
  .a{
    &&-b{
      color:red;
    }
  }
}
```

Compile Code:
```less
[type=password] .a[type=password] .a-b {
  color: red;
}
```

preset:
```less
[type=password] .a.a-b {
  color: red;
}
```
