### DISCUSSION TITLE
How to interpolate variable at mixin in a list?

### DISCUSSION THREAD

**Discussion by wqcstrong** [less/less.js#3804] [Q&A]
There have a mixin:

```less
#tooltip() {
  .planet-1() {
    left: 1px;
    top: 1px;
  }
  .planet-2() {
    left: 2px;
    top: 2px;
  }
  .planet-3() {
    left: 3px;
    top: 3px;
  }
  .planet-4() {
    left: 4px;
    top: 4px;
  }
  .planet-5() {
    left: 5px;
    top: 5px;
  }
  .planet-6() {
    left: 6px;
    top: 6px;
  }
  .planet-7() {
    left: 7px;
    top: 7px;
  }
  .planet-8() {
    left: 8px;
    top: 8px;
  }
}
```

I looped the mixin by `range(8)` and I would like to bind the parent and child class:

```less
each(range(8), {
  .parent:nth-of-type(@{index}) {
    .tooltip {
      /* ❌ Error */
      /* Is there any ways to interpolate the @{index} */
      #tooltip.planet-@{index}();
    }
  }
});
```

As the comment said, is there any ways to fixed? Or there have better solution?

The preview link: https://lesscss.org/less-preview/#eyJjb2RlIjoiXG5cbiN0b29sdGlwKCkge1xuICAucGxhbmV0LTEoKSB7XG4gICAgbGVmdDogMXB4O1xuICAgIHRvcDogMXB4O1xuICB9XG4gIC5wbGFuZXQtMigpIHtcbiAgICBsZWZ0OiAycHg7XG4gICAgdG9wOiAycHg7XG4gIH1cbiAgLnBsYW5ldC0zKCkge1xuICAgIGxlZnQ6IDNweDtcbiAgICB0b3A6IDNweDtcbiAgfVxuICAucGxhbmV0LTQoKSB7XG4gICAgbGVmdDogNHB4O1xuICAgIHRvcDogNHB4O1xuICB9XG4gIC5wbGFuZXQtNSgpIHtcbiAgICBsZWZ0OiA1cHg7XG4gICAgdG9wOiA1cHg7XG4gIH1cbiAgLnBsYW5ldC02KCkge1xuICAgIGxlZnQ6IDZweDtcbiAgICB0b3A6IDZweDtcbiAgfVxuICAucGxhbmV0LTcoKSB7XG4gICAgbGVmdDogN3B4O1xuICAgIHRvcDogN3B4O1xuICB9XG4gIC5wbGFuZXQtOCgpIHtcbiAgICBsZWZ0OiA4cHg7XG4gICAgdG9wOiA4cHg7XG4gIH1cbn1cblxuZWFjaChyYW5nZSg4KSwge1xuICAudG9vbHRpcDpudGgtb2YtdHlwZShAe2luZGV4fSkge1xuICAgIC5iYXIge1xuICAgICAgLyogSXMgdGhlcmUgYSB3YXkgdG8gaW50ZXJwb2xhdGUgdGhlIEB7aW5kZXh9ICovXG4gICAgICAjdG9vbHRpcC5wbGFuZXQtQHtpbmRleH0oKTtcbiAgICB9XG4gIH1cbn0pOyIsImFjdGl2ZVZlcnNpb24iOiI0LjEuMyJ9

**Comment by krsdcbl** [comment]
The issue you ran into is, i think (someone correct me if I'm mistaken): 
You cannot call a mixin by using interpolated variables to reference its name.

(though you may declare a variable that calls the mixin as it's value like `@var: .mixincall();`, and then trigger it as `@var();` - as described in the [Aliasing Mixins](https://lesscss.org/features/#mixins-feature-mixin-aliasing-feature) section)

To maybe aide with your problem, if your goal was to iteratively print increasing positions for nth-children, u wouldn't need all the `#tooltip()` abstraction but could achieve this with just the `each` loop:
```less
each(range(8), 
{
     .tooltip:nth-of-type(@{index}) 
     {
          .nest-as-desired,
          .or-prepend-a-parent & 
          {
               @step: 10;
               @target-position: unit((@index * @step), px);
               
               left: @target-position;
               top: @target-position;
          }
     }
});


```
