### DISCUSSION TITLE
Why i can't change a less global variable in a @media element

### DISCUSSION THREAD

**Discussion by ghost** [less/less.js#3807] [Q&A]
The varibles are all static in less.

In this code:
```less
.a() {
  background-color: #000;
}

@media screen and (max-width: 700px) {
  .a() {
    background-color: #fff;
  }
}

body {
  .a();
}
```
In any case, the background color of body is black.

How can i change the background-color without JavaScript?
