### DISCUSSION TITLE
Provide a mechanism to dereference nested mixin structure

### DISCUSSION THREAD

**Discussion by Bilge** [less/less.js#3810] [Ideas]
Given the following Less, there is no way to dereference the value of `@inner-background`.

```less
.tag(@background, @color: tint(@background, 68%)) {
  color: @color;
  background: @background;
  @inner-background: tint(@background, 28%);

  >span {
    background: @inner-background;
  }
}
```

Although we can dereference top-level properties, e.g. `.tag(red)[color]`, we cannot dereference variables or nested structure. All of the following are invalid:

* `.tag(red)[>span background]`
* `.tag(red)[>span.background]`
* `.tag(red).span[background]`
* `.tag(red).span()[background]`

However, as an interesting aside, `.tag(red)[@inner-background]` _is_ valid.
