### DISCUSSION TITLE
How to make infinite border-radius?

### DISCUSSION THREAD

**Discussion by f1refa11** [less/less.js#4227] [Q&A] [answered]
tried `border-radius: calc(infinity * 1px);`(which works in CSS), but LESS showed an error: `Could not parse call arguments or missing ')'`.

**Comment by iChenLei** [comment, marked as answer]
```less
.main {
   e("border-radius: calc(infinity * 1px);");
}
```
or
```less
.main {
   border-radius: e("calc(infinity * 1px)");
}
```
Try `e` function as workaround.
