### DISCUSSION TITLE
How will Less support CSS `@layer`?

### DISCUSSION THREAD

**Discussion by trusktr** [less/less.js#4263] [General]
`@layer` is out in all browsers. Does Less have a plan on how to support it? With `@import` syntax?

**Comment by matthew-dean** [comment]
Just tested in Less 4.2.0:
```less
@layer test {
  ul {
    li {
      foo: bar;
    }
  }
}
```
Outputs:
```
@layer test {
  ul li {
    foo: bar;
  }
}
```

Is there an issue?
