### DISCUSSION TITLE
Provide error when mixin results in `[object Object]` value

### DISCUSSION THREAD

**Discussion by uncenter** [less/less.js#4304] [Ideas]
I have a mixin called `rgbify`, as seen below:

```less
#rgbify(@color) {
  @rgb: red(@color), green(@color), blue(@color);
}
```

It can be used as `color: #rgbify(#fff)[];`, and note the `[]` to capture the return value(s). Without the `[]` (just `#rgbify(#fff)`), Less outputs `[object Object]` as the value for wherever the mixin is used. I most definitely did not mean to have the value be `[object Object]`, and I'm hoping Less could error when it encounters a value like that - otherwise i have no good way of knowing I missed it if I'm not looking carefully/specifically for that mistake.

![image](https://github.com/user-attachments/assets/9e5b0649-fd0c-4589-b1f0-da14c20b6105)

**Comment by matthew-dean** [comment]
I marked this as a bug at first, until I read it a little more carefully and yeah, this is more like a feature request. Returning a mixin body to assign to a property is undefined behavior.

**Reply by uncenter** [reply]
>  Returning a mixin body to assign to a custom property is undefined behavior.

Hmm what? This isn't what I'm referring to. Custom properties are irrelevant here, the result of the mixin could be given to any CSS color-related property. The mixin works fine, my request is that Less should error when a mixin's return value isn't properly accessed - in this case with either `[]` to collect all or `[@rgb]` - causing it to result in that [object Object] string.

**Reply by matthew-dean** [reply]
@uncenter Sorry yes I meant any property, not specifically a custom property. I'm just noting why it's rendering "[object Object]" has to do with Less attempting to render the mixin as a value. IIRC there _was_ an error that was added to be thrown in some instances of trying to render rule sets, but there must be an implementation bug here. So... could be a bug or feature request. Like... since it's supposed to error in the original implementation, that's kind of a bug. But also the docs don't say what should happen is all I mean, so making sure it does error as a documented feature would be good.

That's just of words to say that what you're reporting is valid (I've already created an issue ticket from it) and it's not important how it's labelled.

**Reply by matthew-dean** [reply]
Related, if you write:
```less
#rgbify(@color) {
  @rgb: red(@color), green(@color), blue(@color);
}

.test {
  fg: #rgbify(red) l;
}
```
...you get:
```css
.test {
  fg: @rgb: 255, 0, 0; l;
}
```
...which doesn't make sense either and should error.

**Reply by uncenter** [reply]
Right. I just wish you could have a default return value in mixins... but alas, `[]` will do.

**Reply by matthew-dean** [reply]
@uncenter You do have a default return value in mixins, which is the set of rules. Do you mean you wish that when rendering a set of rules does not make sense, it would return a particular value?

**Reply by uncenter** [reply]
Well I mean I wish you could return a "default" *variable* from a mixin, because something like this isn't a "rule" and doesn't work:

```less
#rgbify(@color) {
  red(@color), green(@color), blue(@color)
}

:root {
  color: #rgbify(red);
}
```
I guess what I really want is something like Sass's functions: https://sass-lang.com/documentation/at-rules/function/.
