### DISCUSSION TITLE
How to generate percentage for keyframes?

### DISCUSSION THREAD

**Discussion by SergeVDev** [less/less.js#4317] [General]
Hello everyone!

I'm looking for a way of making a keyframes template with an arbitrary step count.

Unfortunately, neither…

```
@keyframes test-7
{
    each(range(7),
    {
        @{value}%
        {
            a: b;
        }
    });
}
```

…nor…

```
@keyframes test-7
{
    each(range(7),
    {
        %("%d", @value)
        {
            a: b;
        }
    });
}
```

…don't work.

**Comment by dosubot** [comment]
Hey, @SergeVDev! I'm here to help you out with any bugs or questions you might have. Let's tackle this together!


To generate percentages for keyframes using Less, you can use the `percentage` function to format numbers as percentages. Here's how you can modify your code to achieve this:

```less
@keyframes test-7 {
    each(range(7), {
        @{percentage(@value / 7)} {
            a: b;
        }
    });
}
```

In this example, `@value / 7` calculates the percentage step based on the total number of steps (7 in this case), and `percentage()` converts it to a percentage format. This should generate the desired keyframes with percentage steps.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/27f5e4d7-351a-43b0-b4b2-d46732893d3f?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/27f5e4d7-351a-43b0-b4b2-d46732893d3f?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/27f5e4d7-351a-43b0-b4b2-d46732893d3f?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/27f5e4d7-351a-43b0-b4b2-d46732893d3f?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/27f5e4d7-351a-43b0-b4b2-d46732893d3f?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/27f5e4d7-351a-43b0-b4b2-d46732893d3f?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/27f5e4d7-351a-43b0-b4b2-d46732893d3f?feedback_type=other)</sup>

**Reply by matthew-dean** [reply]
@dosu This is a hallucination. `@{}` is not an expression validator; it only can be used for an interpolated variable reference.

This would work, however.
```less
@keyframes test-7 {
    each(range(7), {
        @percent: @value * 1%;
        @{percent} {
            a: b;
        }
    })
}
```
