### DISCUSSION TITLE
How to set props AND return values from a mixin?

### DISCUSSION THREAD

**Discussion by SergeVDev** [less/less.js#4336] [General]
I would like to set properties **and** return a value from a mixin just in one call. For instance, for the following mixin:

```
.test-fn(@param1, @param2, @param3, @param4, @param5)
{
	prop1: (@param1 + @param2 + @param3 + @param4 + @param5);

	@return: (@param1 * 2 + @param2 * 2 + @param3 * 2 + @param4 * 2 + @param5 * 2);
}
```
I should make two calls:

```
.test-fn(7, 35, 8, 4, 20);                // Output prop1
prop2: .test-fn(7, 35, 8, 4, 20)[];       // Output prop2
```

to have both `prop1` and `prop2` defined. Is there a compiling mode, when using a result (`[]`) doesn't prevent outputting properties? I suppose, it's so intuitive.

**Comment by dosubot** [comment]
To achieve setting properties and returning a value from a mixin in a single call, you can use the unnamed lookups feature in Less. This allows you to call a mixin and look up its final value without preventing the output of properties.

Here's how you can modify your mixin and use it:

```less
.test-fn(@param1, @param2, @param3, @param4, @param5) {
  prop1: (@param1 + @param2 + @param3 + @param4 + @param5);
  @return: (@param1 * 2 + @param2 * 2 + @param3 * 2 + @param4 * 2 + @param5 * 2);
}

div {
  .test-fn(7, 35, 8, 4, 20); // This will output prop1
  prop2: .test-fn(7, 35, 8, 4, 20)[]; // This will output prop2
}
```

Using `.test-fn(7, 35, 8, 4, 20)[]` will allow you to access the final value calculated in the mixin, while still outputting the properties defined within it <sup>[[1]](https://github.com/less/less-docs/blob/master/content/features/mixins-as-functions.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/e3ab0242-28aa-4ded-acf5-6480c72649c3?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/e3ab0242-28aa-4ded-acf5-6480c72649c3?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/e3ab0242-28aa-4ded-acf5-6480c72649c3?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/e3ab0242-28aa-4ded-acf5-6480c72649c3?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/e3ab0242-28aa-4ded-acf5-6480c72649c3?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/e3ab0242-28aa-4ded-acf5-6480c72649c3?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/e3ab0242-28aa-4ded-acf5-6480c72649c3?feedback_type=other)</sup>
