### DISCUSSION TITLE
A plugin for concatenating lists

### DISCUSSION THREAD

**Discussion by SergeVDev** [less/less.js#4341] [General]
I want to add a function for concatenating lists:

```
@list1:
	'../images/layer1.png',
	'../images/layer2.png',
	'../images/layer3.png';

@list2:
	'../images/layer4.png',
	'../images/layer5.png',
	'../images/layer6.png';

@list: concat(@list1, @list2);

// The same as:
@list:
	'../images/layer1.png',
	'../images/layer2.png',
	'../images/layer3.png',
	'../images/layer4.png',
	'../images/layer5.png',
	'../images/layer6.png';
```

What do I write in here?

```
functions.add('concat', function (list1, list2)
{
	return list1.value.concat(list2.value); // Not working: length(@list) returns 1.
});
```

Something with `return new tree.List()`? I cannot find a documentation for writing plugins.

**Comment by matthew-dean** [comment]
Why not just do this?
```less
@list1:
	'../images/layer1.png',
	'../images/layer2.png',
	'../images/layer3.png';

@list2:
	'../images/layer4.png',
	'../images/layer5.png',
	'../images/layer6.png';

.test {
  list: @list1, @list2;
}
```
