### ISSUE TITLE
mixin collisions with class names

### ISSUE THREAD

**Issue by Soviut** [less/less.js#1007]
I'm pretty sure I've already seen this brought up before, but I've run into an issue with a mixin colliding with a similarly named class. This has forced me to prefix my mixing with an underscore.

The cause of this issue stems from the fact that mixins are allowed to be called without brackets, in an effort to make them blend into normal CSS syntax. However, this seems unnecessary since normal CSS never uses dot syntax inside the body of a selector; Only attributes, colons, values and semi-colons.

I propose that calling a mixin should _require_ the brackets in the same way SASS prefixes mixin calls with `@include`. Requiring the brackets doesn't change the way LESS works, is simpler than the SASS include statement, and would make the following is possible:

``` less
// mixin
.alert() {
  color: red;
}

// actual class selector
.alert {
  .alert();
}
```
