### ISSUE TITLE
Allow include tag names like H1, H2, ... as mixins

### ISSUE THREAD

**Issue by al6x** [less/less.js#1011]
What do You think about allowing to use tag elements like H1, H2, ....  as mixins? 

**Use Case**

I'm using Twitter Bootstrap and create header for page. Currently, because I can't reuse styles from `H1` element I has to put extra stuff into HTML and code looks like that:

``` HTML
<div class='header'>
  <h1>
    <a href='#'>Some text</a>
  </h1>
</div>
```

``` LESS
.header {
  h1 {
    float: left;
  }
}
```

But if it would be possible to reuse styles on `H1` the HTML code could be more clean:

``` HTML
<div class='header'>
  <a href='#' class='header-title'>Some text</a>
</div>
```

``` LESS
.header {
}
.header-title {   
  float: left;
  // Including
  .h1()
}
```

At fist I though to post an issue to Twitter Bootstrap project and ask them to create alias for every tag name (like `.h1` for `H1`), but then realized that it would be better if LESS allow to use tags as mixins.

What do You think?
