### ISSUE TITLE
extend like sass

### ISSUE THREAD

**Issue by Most** [less/less.js#1014]
less 1.4.0 converts:

``` css
ul.inline li { display: inline-block; }
nav ul { &:extend(.inline); }
```

to:

``` css
ul.inline li, ulnav ul li { display: inline-block; } 
```

Notice **ulnav ul li** selector. 
Similar code in sass 3.2.1:

``` css
ul.inline li { display: inline-block; }
nav ul { @extend .inline; }
```

produces

``` css
ul.inline li, nav ul li { display: inline-block; }
```
