### ISSUE TITLE
parameter mixin generates mixin twice

### ISSUE THREAD

**Issue by lancevo** [less/less.js#1023]
I'm using Less Compiler v.1.3.0, and it generates parameter mixin css twice/

mixin

``` css
.transition (@arg) {
    -webkit-transition: @arg;
    -moz-transition: @arg;
    -ms-transition: @arg;
    -o-transition: @arg;
    transition: @arg;
}
```

using mix-in

``` css
.nav {
  .transition(all 0.5s);
}
```

generated css  

``` css
.nav {
    -webkit-transition: all 0.5s;
    -moz-transition: all 0.5s;
    -ms-transition: all 0.5s;
    -o-transition: all 0.5s;
    transition: all 0.5s;
    -webkit-transition: all 0.5s;
    -moz-transition: all 0.5s;
    -ms-transition: all 0.5s;
    -o-transition: all 0.5s;
    transition: all 0.5s;
}
```
