### ISSUE TITLE
Class stacking - bug or feature?

### ISSUE THREAD

**Issue by wielgosm** [less/less.js#1026]
I'm not sure if the following is a bug or a feature. I couldn't find a less.js group / forum to discuss this, so here it goes.

I used to be able to do something like this:

``` less
.item {
    color: white;
    &.blue { background-color: blue; }
}
.item-blue {
    .item;
    .item.blue;
}
```

...Which resulted in:

``` less
.item {
  color: white;
}
.item.blue {
  background-color: blue;
}
.item-blue {
  color: white;
  background-color: blue;
}
.item-blue.blue {
  background-color: blue;
}
```

At more recent versions this behavior changed and now compiling the file results in a syntax error.

``` text
$ lessc tmp.less
NameError: .item.blue is undefined in /home/www/tmp.less:7:1
6       .item;
7       .item.blue;
8 }
```

Versions:

``` text
$ lessc --version
lessc 1.3.0 (LESS Compiler) [JavaScript]
$ node --version
v0.8.9
$ npm --version
1.1.61
```

Thanks!
