### ISSUE TITLE
// comments parsing error

### ISSUE THREAD

**Issue by iPirat** [less/less.js#1032]
a "// comment" should be stripped off before parsing rest of LESS.

example: 

``` CSS
@font-face {
    font-family: 'MyFont';
    src: local('MyFont'), // user may have the font locally
      url('MyFont.woff'), // woff for ie9
      url('MyFont.eot'); // opentype for ff, chrome, and others
}
```

this will result in following CSS:

``` CSS
@font-face {
  font-family: 'MyFont';
  src: local('MyFont'), // user may have the font locally url('MyFont.woff'), // woff for ie9 url('MyFont.eot');
}
```

ecpected CSS:

``` CSS
@font-face {
  font-family: 'MyFont';
  src: local('MyFont'), url('MyFont.woff'), url('MyFont.eot');
}
```

(in case, it is relevant: I'm using rhino 1_7R4 and less-rhino-1.3.1.js)
