### ISSUE TITLE
Using a general purpose CSS Selector as a mixin.

### ISSUE THREAD

**Issue by gaurav21r** [less/less.js#1048]
**Mixins**

Just like in mixins
```css
.border-radius(@radius){
   border-radius : @radius;
   moz-border-radius : @radius;
   webkit-border-radius : @radius;
}

a {
   .border-radius (2px);
}
```
**Compiles to**
```css
a {
   border-radius : 2px;
   moz-border-radius : 2px;
   webkit-border-radius : 2px;
}
```
Lets have
```css
input[type="text"]{
   border: 1px solid blue;
}
.inputbox {
   input[type="text"];
}
```
**compile to**
```css
.inputbox{
   border: 1px solid blue;
}
```

**Use Case**

The main Use Case where our organisation's engineers are facing problems is when the underlying HTML is not under our control. When does that happen? JavaScript Frameworks! Take jQuery UI, Dojo, extJs, Google Closure, YUI and the like.

We really like BootStrap and would like to see it as the de facto UI framework for the web. I am sure everyone will agree, BootStrap is by far the biggest project using Less. Although amazing *websites* have been created with BootStrap, we don't see major JS Web *Apps* use BootStrap, because the HTML for their various widgets is not under our control and LESS doesn't provide any other solution.

**SaSS / Stylus**
SaSS3 has @extend that [does exactly](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#extend) what I'm talking about. 

Stylus also has @extend that [does the same](http://learnboost.github.com/stylus/docs/extend.html).

**Similarity to CSS**
The syntax as mentioned above in my example is intuitive. The makers of LESS want it to resemble CSS as much as is possible. I second that and I think this is the best way to do it. Even better than an @extend

**References**
There is already a fix for this as give [here](http://stackoverflow.com/questions/13533957/using-a-general-purpose-selector-as-a-mixin-in-less-css/13560929#13560929) We plan to test it out deeper and submit a Pull Request

The issue is already referenced [here](https://github.com/cloudhead/less.js/issues/1011), while it is the same issue, I felt the domain of the problem and the magnanimity of its importance should be further highlighted.

Hats of to LESS btw, the best thing to happen to CSS since CSS3 :)
