### ISSUE TITLE
Using "contrast(..)" in a CSS3 filter definition throws error

### ISSUE THREAD

**Issue by ghost** [less/less.js#1090]
Using the CSS3 contrast [filter](http://html5-demos.appspot.com/static/css/filters/index.html) throws an error in 1.3.2 from the command line:

``` css
.test {
  filter: contrast(2.0);
}
```

Throws an error:

> non_object_property_loadError: error evaluating function 'contrast': Cannot read property '0' of undefined in styles.less

Seems like LESS is expecting a color as an input, which should not apply in this case.

A workaround is to escape any value that contains `contrast`:

``` css
.test {
  filter: ~"contrast(2.0)";
}
```
