### ISSUE TITLE
merging duplicate selectors

### ISSUE THREAD

**Issue by euskadi31** [less/less.js#1101]
Hi,

It would be great if LESS output could be configured to more intelligently compress output. Here are some examples:

```
# Combine multiple declarations
# LESS                             # Preferred Output                 # Current Output
body { border: solid #ccc; }       body{border:3px solid #ccc;}       body{border:solid #ccc;}
body { border-width: 3px; }                                           body{border-width:3px;}

# LESS                             # Preferred Output                 # Current Output
body { color: #ccc; }              body{color:#ccc;cursor:pointer;}   body{color:#ccc;}
body { cursor: pointer; }                                             body{cursor:pointer;}          

# Ignore overridden declarations
# LESS                             # Preferred Output                 # Current Output
body { border: 2px solid #400; }   body{border:3px solid #ccc;}       body{border:2px solid #400;}
body { border: 3px solid #ccc; }                                      body{border:3px solid #ccc;}
```

Now imagine I have about 50 selectors repeating in each file. The problem is that compiled css is too large and to messy. There are also another use cases. For example, you may use some base stylesheet in many projects.

Example:

base.less

``` css
header {
    border: 1px solid #eee;
    .border-radius(5px);
}
```

style1.less

``` css
@import "base.less";

header {
    .border-radius(1px);
}
```

output

``` css
header {
    border: 1px solid #eee;
    -webkit-border-radius: 1px;
       -moz-border-radius: 1px;
            border-radius: 1px;
}
```

What you think?
