### ISSUE TITLE
get value of this property

### ISSUE THREAD

**Issue by vwasteels** [less/less.js#1121]
I am looking for this functionnality : 
http://stackoverflow.com/questions/12933908/less-css-get-value-of-this-property

so I could write : 

``` css
@hover: 20;
a:hover { color: this+@hover; }
```

and it would apply no matter what the original color is
