### ISSUE TITLE
Block comment inside media query with nested query present causes compiled CSS syntax error

### ISSUE THREAD

**Issue by kamranayub** [less/less.js#1122]
I am testing LESS 1.3.3 in the browser (less.js).
## Test Case

``` css
@media (max-width: 1200px) {
    /* this breaks the compiler output */
    body { font-size: 20px; }

    @media (max-width: 900px) {     
        body { font-size: 11px; }
    }
}

// Just for use case illustration
@media (max-width: 800px) { }
```
## LESS Output

``` css
@media (max-width: 1200px) {
  {
    /* this breaks the compiler output */

  }
  body {
    font-size: 20px;
  }
}
@media (max-width: 1200px) and (max-width: 900px) {
  body {
    font-size: 11px;
  }
}
```
## Use Case

In our project, we organize our LESS partials by breakpoint. 

```
modules
 |_ large
    - _header.less
 |_ medium
    - _header.less
 |_ small
main.less
```

**main.less example**

``` css
// Example
@media (max-width: @breakpointLarge) {
    @import "modules/large/_header";
}
@media (max-width: @breakpointMedium) {
    @import "modules/medium/_header";
}
```

Sometimes there's a one-off fix at a specific width that we need to include for a component. We have a single file (above) that imports each breakpoint, to make modifying the overall site breakpoints easier. Because we don't want to create one-off breakpoint files and manually import them into the main file, we put the definitions inside one of the existing breakpoint partials (i.e. `Large\_header.less`) wherever the breakpoint would occur (in the test case, 900px breakpoint is in-between 1200px (large) and 800px (small)).
## Comments

This is frustrating for many reasons, as I'm sure you can see (documentation). I use CSSDOC syntax so I use block comments all over.

Single line comments (`//`) are not affected since they are ignored in the output.
