### ISSUE TITLE
::-webkit-scrollbar-* are ignored by v1.3.3

### ISSUE THREAD

**Issue by hozumi** [less/less.js#1152]
Hi,
I recently upgraded less from 1.1.5 to 1.3.3, and found that ::-webkit-scrollbar-\* style doesn't work.
I tested following style in "client-side" usage.

``` css
.webkit-scrollbar-gray {
    overflow-y: scroll;
    ::-webkit-scrollbar {
        width: 10px;
        height: 16px;
    }
    ::-webkit-scrollbar-thumb {
        background-color: rgba(155, 155, 155, 0.5);
        -webkit-box-shadow: inset 1px 1px 0 rgba(255,255,255,0.10),inset 0 -1px 0 rgba(255,255,255,0.07);
    }
    ::-webkit-scrollbar-button {
        width: 0;
        height: 0;
        display: none;
    }
    ::-webkit-scrollbar-corner {
        background-color: transparent;
    }
}
```

Please let me know if I am missing something.
Thanks.
