### ISSUE TITLE
Bug of Advanced Usage of &

### ISSUE THREAD

**Issue by githubkevin** [less/less.js#1158]
if we got

``` less
.grandparent { 
  .child, .sibling { 
    .parent & {
       color: black; 
    }
   }
 }
```

will output :

``` css
.parent .grandparent .child,
.parent .grandparent .sibling {  color: black; }
```

instead of :

``` css
grandparent .parent  .child,
grandparent .parent  .sibling {  color: black; }
```

which means it doesn't work for more then 2 nested layers.
