### ISSUE TITLE
Wrong css statement order

### ISSUE THREAD

**Issue by nitriques** [less/less.js#1164]
Sometimes, it is useful to set the same css property multiple times, in order to create cross-browser code.

In 1.3.1, this mixin

``` css
#add-grayscale {
   /* Firefox 4+ */
  filter: url(~"data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
  filter: gray; /* IE 6-9 */
 -webkit-filter: grayscale(100%);
}
```

is rendered in a different order, which breaks the cross-browser abilities.

``` css
#add-grayscale {
 -webkit-filter: grayscale(100%);
  filter: gray; /* IE 6-9 */
   /* Firefox 4+ */
  filter: url(~"data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
}
```

I think there should be at least a parameter in order to prevent this behavior.
