### ISSUE TITLE
Selector Interpolation does not work with Media Queries

### ISSUE THREAD

**Issue by yene** [less/less.js#1204]
``` CSS
@palm: ~"@media only screen and (max-width: 480px)";

header p {
   @{palm} {
     display: none;
   }
}
```

should generate

``` CSS
@media only screen and (max-width: 480px) {
  header p {
    display: none;
  }
}
```

instead generates

``` CSS
header p @media only screen and (max-width: 480px) {
  display: none;
}
```
