### ISSUE TITLE
Repeated comments break selectors

### ISSUE THREAD

**Issue by tmcw** [less/less.js#1224]
The case

``` css
#foo,
// bar
// blah
.bar {
  background:#000;
  }
```

Breaks with a ParseError, while a single comment does not. I think the solution here is a `.eatComments()` method which implements 'comments allowed here'.
