### ISSUE TITLE
Debug info should not be placed inside @keyframes

### ISSUE THREAD

**Issue by stephenhutchings** [less/less.js#1246]
When compiling with `--line-numbers=mediaquery`, inserts `@media -sass-debug-info` before each frame, which break webkit's keyframe animations.

``` css
@-webkit-keyframes "FADEIN" {
  @media -sass-debug-info{filename{font-family:file\:path/to.less}line{font-family:\0000001}}
  0% {
    opacity: 0.0;
  }
  @media -sass-debug-info{filename{font-family:file\:path/to.less}line{font-family:\0000002}}
  100% {
    opacity: 1.0;
  }
}
```

See https://github.com/nex3/sass/issues/247#ref-commit-ed2247a for similar issue in SASS compiler which has been fixed.
