### ISSUE TITLE
Mixins with concatenated/nested selectors are undefined

### ISSUE THREAD

**Issue by radium-v** [less/less.js#1248]
Hi,

I'm running into an issue when trying to reference a mixin that's named with a & combinator.

Example:

``` less
.sprite {

    .sprite(@x, @y, @w, @h) {
        background: transparent url(sprite.png) @x @y no-repeat;
        height: @h;
        width: @w;
    }

    &-derp { // .sprite-derp
        .sprite(-20px, -30px, 100px, 15px);
        display: block;
    }
}

.box {
    &:after {
        .sprite-derp;
        content: ' ';
        position: absolute;
    }
}
```

Should output:

``` css

.sprite-derp {
    background-position: -20px -30px;
    height: 15px;
    width: 100px;
    display: block;
}

.box:after {
    background-position: -20px -30px;
    height: 15px;
    width: 100px;
    content: ' ';
    position: absolute;
}
```

Would it be possible to implement this functionality, or am I just doing it wrong?
