### ISSUE TITLE
Local variables undefined if mixin is calling a local mixin and in turn is called from an outer scope

### ISSUE THREAD

**Issue by Piedone** [less/less.js#1250]
Consider the following code (simplified example of course):

``` less
.container
{
    .colored(@color)
    {
        background-color: @color;
    }

    @red: #f00;

    .red
    {
        .colored(@red);
    }
}

.test
{
    .container.red;
}
```

Expected result:
.test is substituted with the following:

``` css
.test
{
    background-color: #f00;
}
```

Actual result:
Syntax error: variable @red is undefined

This can be a general LESS syntax issue as the same error happens with some other parsers I tried too.

Any thoughts?
