### ISSUE TITLE
Source maps and multiline selectors.

### ISSUE THREAD

**Issue by simme** [less/less.js#1275]
Hi,

Seems like multiline selectors won't work with source maps:

``` css
@source-map-line-thingy
.foobar,
.baz {
  background: #fff;
}
```

Would be sweet if LESS could compress selectors to one line when the mediaquery option is present to make it work cross all CSS :)
