### ISSUE TITLE
Nested selector redundancy on merge

### ISSUE THREAD

**Issue by geedmo** [less/less.js#1280]
Using nested selector, when merging it result in CSS with redundant declarations.

Example

``` less
.right {
  margin-left: 100%;
  .active {
    margin-left: 0;
  }
}
.bottom {
  margin-bottom: 100%;
  .active {
    margin-bottom: 0;
  }
}
/* merged */
.bottom-right { 
 .bottom;
 .right;
}
```

Generated code merges fine the parent selector rules, but nested selector has a redundant declaration

``` css
.right {
  margin-left: 100%;
}
.right .active {
  margin-left: 0;
}
.bottom {
  margin-bottom: 100%;
}
.bottom .active {
  margin-bottom: 0;
}
/* merged ok */
.bottom-right {
  margin-bottom: 100%;
  margin-left: 100%;
}
/* redundant */
.bottom-right .active {
  margin-bottom: 0;
}
.bottom-right .active {
  margin-left: 0;
}
```

Tested with all versions online at http://less2css.org/
