### ISSUE TITLE
Multiple use of unlocking mixin within the same scope

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#1291]
This is about "unlocking mixins" feature #73. I'm not sure whether this is a feature or a bug, but I'm guessing a bug.

If the same mixin is called twice, only mixins from the second call are imported. First import mixins are ignored.

This:

``` css
.bananas() {
  height: 11px;
}
.apples(@width) {
  .bananas() {
    width: @width;
  }
}

.apples(55px); // this one does not return any mixins
.apples(99px);

#test {
  .bananas();
}
```

Actual result:

``` css
#test {
  height: 11px;
  width: 99px;
}
```

Expected result:

``` css
#test {
  height: 11px;
  width: 55px;
  width: 99px;
}
```

It does not seem to be terribly important, I mostly need to know whether it works as intended or not.
