### ISSUE TITLE
Selectors Level 4 selectors fail to parse

### ISSUE THREAD

**Issue by timmywil** [less/less.js#1292]
These Level 4 Selectors currently fail to parse and will be considered valid some time in the future. I may have missed some, but I went through the spec and I think these are all of them.

``` css
/* http://dev.w3.org/csswg/selectors4/#column-combinator */
col.selected || td {}
/* http://dev.w3.org/csswg/selectors4/#idref-combinators */
label:matches(:hover, :focus) /for/ input,
label:matches(:hover, :focus):not([for]) input {}
/* http://dev.w3.org/csswg/selectors4/#subject */
!ol > li:only-child {}
/* http://dev.w3.org/csswg/selectors4/#attrnmsp */
@namespace foo "http://www.example.com";
[foo|att=val] { color: blue }
[*|att] { color: yellow }
[|att] { color: green }
```
