### ISSUE TITLE
Inline CSS comments don't compile correctly

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [less/less.js#1302]
There is a very good style for coding CSS that is indexing the explanation content above a given selector and then reference it in an inline comment, widely used in [normalize.css](https://github.com/necolas/normalize.css/).
I use css comments (instead of silent ones) when I want the content appearing in the compiled source (for browser debugging purposes).

Unfortunately the following snipped gives me a different output compared to what is expected.

LESS code:

``` CSS
/*
 * 1. The display is changed because of some circunstance.
 */
.test {
  display: none; /* 1 */
}
```

Resulted CSS:

``` CSS
/*
 * 1. The display is changed because of some circunstance.
 */
.test {
  display: none;
  /* 1 */

}
```

Expected CSS:

``` CSS
/*
 * 1. The display is changed because of some circunstance.
 */
.test {
  display: none; /* 1 */
}
```

I could not find anything like this being discussed before.
Any reason for this behavior?
