### ISSUE TITLE
Global mixins and mixins inside namespaces handle scopes differently

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#1316]
Scoping of global mixins is handled differently then scoping of mixin inside namespaces:
- If I call mixin directly, it does not look into callers scope until it searched whole mixins scope. It will go through all parents, including the global scope.
- If I call mixin from namespace, it searches only local scope and then proceeds to callers scope. Anything defined in definition parents scope is ignored.

Should they behave differently? If no, which version is correct?

Direct mixin call - mixin searches definition space first. It will never hit the caller:

``` css
/* define global mixin and variable */
.content() { 
  mixin:global;
}
@content: global;

/* mixin to be called */
.mobile() {
    variable: @content;
    .content();
}

.big-desktop-button {
  /* define local mixin and variable */
  .content() { 
    mixin:caller;
  }
  /* call mixin */
  @content: caller;
  .mobile();
}
```

compiles into:

``` css
.big-desktop-button {
  variable: global;
  mixin: global;
}
```

If I place exactly the same mixin into a namespace, output changes:

``` css
.content() { 
  mixin:global;
}
@content: global;

#namespace() {
  .mobile() {
    variable: @content;
    .content();
  }
}

.big-desktop-button {
  .content() { 
    mixin:caller;
  }
  @content: caller;
  #namespace > .mobile();
}
```

compiles into:

``` css
.big-desktop-button {
  variable: caller;
  mixin: caller;
}
```

The same effect happens with variables and mixins defined in namespace itself:

``` css
#namespace() {

  .content() { 
    mixin:namespace;
  }
  @content: namespace;

  .mobile() {
    variable: @content;
    .content();
  }
}

.big-desktop-button {
  .content() { 
    mixin:caller;
  }
  @content: caller;
  #namespace > .mobile();
}
```

compiles into:

``` css
.big-desktop-button {
  variable: caller;
  mixin: caller;
}
```

Tested on 1.4.0-beta-b4 with windows node.js.
