### ISSUE TITLE
Combining Media Query Variables

### ISSUE THREAD

**Issue by shshaw** [less/less.js#1330]
I have variables set up to manage my breakpoints in responsive stylesheets. Combining variables into one media query with the "and" combiner returns an error, for example: `@media @thinScreen and @shortScreen { .Container { padding: 5px; } }`

You can copy and paste this more detailed example code into http://less2css.org/ to see the errors on each of the commented out lines.

``` less
////////////////////////////////////////
// This portion compiles just fine
////////////////////////////////////////

@thinScreen: ~"(max-width: 800px)";
@shortScreen: ~"(max-height: 600px)"; 

/* Match only @thinScreen */
@media @thinScreen {  .Container { margin-bottom: 80px; } }

/* Match only @shortScreen */
@media @shortScreen {  .Container { margin-bottom: 20px; } }

/* Match either @thinScreen or @shortScreen */
@media @thinScreen, @shortScreen { .Container { padding: 20px; } }

// You can combine the Media Query variables within a variable and have it outputted correctly.
/* Match both @thinScreen AND @shortScreen */
@tinyScreen: @thinScreen ~" and " @shortScreen;
@media @tinyScreen { .Container { padding: 5px; } }


////////////////////////////////////////
// However, attempting to combine the media queries with "and"
// to match both thin screens and short screens returns an error.
////////////////////////////////////////

//@media @thinScreen and @shortScreen { .Container { padding: 5px; } }
//@media @thinScreen ~"and" @shortScreen { .Container { padding: 5px; } }


//////////////////////////////////////// 
// This issue prevents not just combining media queries, 
// but specifying "only screen and" before the variable 
// as well. The following examples all produce errors:
////////////////////////////////////////

//@media only screen and @thinScreen { }
//@media ~"only screen and" @thinScreen { }
//@only: ~"only screen and ";
//@media @only @thinScreen { };

```

Tested in 1.3.3 and 1.4.0 with no luck. Any workarounds other than the combined variable or will this bug just have to be squashed?
