### ISSUE TITLE
Expand Mixin definitions

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#1342]
**Update Apr 26, 2015 - with some more familiarity with the language and parser, I'm dropping the second part of the proposal. I still think it's a valid question about allowing the author to use the three most common selector forms as mixins.**

**Update on my update from 2 seconds ago. I realized that the remainder of the proposal Leads to ambiguity with the proposal for accessing namespaced properties. (#1848)  So fuck it, closing.** 

---

I have a proposal for some expansion of mixin syntax that might make usage a bit easier.

## Drop the dot notation requirement

It seems somewhat arbitrary that mixins need to start with a dot. They're not really a class selector, nor used as one. It seems like I should just be able to do this.

```css
my-mixin(@var) {
  // mixin stuff
}
.one {
  my-mixin(red);
}
```

~~## Allow mixin "assignment"~~

~~Many times, when I've changed a CSS3 property to a CSS3 mixin, I have to adjust not just the property name but the way in which the value is declared.~~

~~I add parentheses, my code coloring changes, it feels somewhat inelegant. It would be much quicker if I could do this:~~

```css
my-box-shadow(@shadow) {
  -moz-box-shadow: @shadow;
  box-shadow: @shadow;  
}
.box {
  my-box-shadow: @shadow;
}
```

~~The entire value (between the colon and the semi-colon) is passed to a mixin with a single variable declaration, even if that value has commas. (This would only work for mixins with only one variable, but could work quite elegantly.) It makes LESS feel even more like an extension of CSS.~~

~~Now, for the magic secret sauce, where these ideas can be even more powerful.~~

~~By doing things this way, you can expand write mixins that gracefully support CSS3 properties. In other words, you don't have to re-write anything. You could just install a mixin library.~~

~~Observe:~~

```css
box-shadow(@shadow) {
  -moz-box-shadow: @shadow;
  box-shadow: @shadow;
}
.box {
  box-shadow: 1px 2px black;
}

// Outputs

.box {
  -moz-box-shadow: 1px 2px black;
  box-shadow: 1px 2px black;
}
```

~~If the author makes a mistake and also includes the prefix version, I believe we have a current pull request to collapse those properties anyway, making the CSS the same size.~~

~~The last usage is not the only goal, as I think un-dotted mixins and mixin assignment is a good idea on its own merit.~~
