### ISSUE TITLE
Make mixin matching smarter with comma-delimited values

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#1343]
In 1.3.3 or thereabouts, we allowed you to separate your arguments to mixins semi-colons, and not just commas. Previously, if you wanted to pass in a value with commas, you had to escape it.

Previous syntax:

``` css
.mixin(@var) {
  property: @var;
}
.test {
  .mixin(~"blah, blah, blah");
}
```

But with semi-colons, you can fix this. However, when we have a single comma-delimited value, we need to append a semi-colon at the end, which leads to an awkward `;);` pattern.

``` css
.mixin(@var) {
  property: @var;
}
.test {
  .mixin(blah, blah, blah;);  // works, but is ugly
}
```

In the old old days of LESS, the commas were treated as extra arguments, and were simply dropped. However, since 1.3, mixins are required to match, if you omit the escaped string and omit the enclosed semi-colon, you get an error:

```
.test {
  .mixin(blah, blah, blah);
}

// Outputs
Runtime error: No matching definition was found for `.mixin(blah, blah, blah)`
.test {  .mixin(blah, blah, blah);}
```

Let's make the parser smarter. Assume that if I'm a) passing in arguments with commas, b) there are no matching mixin definitions, c) that mixin definition WOULD match if this is, in fact, a single, comma-delimited values, then infer semi-colon separation.

So that this just works:

``` css
.mixin(@var) {
  property: @var;
}
.test {
  .mixin(blah, blah, blah);
}
```

I think this would make a lot of library authors and LESS writers happy.
