### ISSUE TITLE
FATAL ERROR: JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by ghost** [less/less.js#1347]
it does not work:

``` css
.search {
  -ms-flex: 1;
  -webkit-flex: 1;
  flex: 1;
}
```

the error occurs:

``` bash
FATAL ERROR: JS Allocation failed - process out of memory
Process finished with exit code 5
```

And this work:

``` css
.search {
  -webkit-flex: 1;
  -ms-flex: 1;
  flex: 1;
}
```

P.S. Win7 64bit, Node.js v0.10.2, Grunt + grunt-recess module (LESS 1.3.3)
