### ISSUE TITLE
LESS minifier breaking media queries on possible comment parse

### ISSUE THREAD

**Issue by bmcminn** [less/less.js#1349]
Posted this initially on the PrePros issues, https://github.com/sbspk/Prepros/issues/55

Problem persisted when minifying compiled LESS file with native LESS minifier with PrePros 1.5 on Windows 7 64-bit. Confirmed this same problem in Codekit's use of the LESS minifer (YUI compression) on Mac OSx 10.8.

EDIT: Possibly related issue https://github.com/cloudhead/less.js/issues/284

---

Noticed this in Chrome Version 27.0.1453.94m however it doesn't seem to affect FF 21, not sure about others.

This is a default media query definition per [`main.css` - line 223](https://github.com/h5bp/html5-boilerplate/blob/master/css/main.css#L223) in the HTML5 Boilerplate template. 

``` css

@media print,
       (-o-min-device-pixel-ratio: 5/4),
       (-webkit-min-device-pixel-ratio: 1.25),
       (min-resolution: 120dpi) {
    /* Style adjustments for high resolution devices */
    // a {
    //   font-size: 4rem;
    // }
}


/**===================================================**\
/**  PRINT STYLES
/**===================================================**/
@media only print {
  // *                             { background: @trans !important; box-shadow: none !important; color: @black !important; text-shadow: none !important; }
  a,
  a:visited                     { text-decoration: underline; }
  a[href]:after                 { content: " (" attr(href) ")"; }
  abbr[title]:after             { content: " (" attr(title) ")"; }

  /** MANUALLY TRUNCATED FOR BREVITY **/
}
```

When compressing the above LESS/CSS, the minified source breaks resulting in the following result:

`@media print,(-o-min-device-pixel-ratio:5/@media only print{a,a:visited{text-decoration:`

Looks like the minifier has an issue with `/` chars in `@media` definitions and I'm assuming treats it as a delimiter for a comment.

This particular issue causes `@media` scope to bleed into my `only print` media query, so my print styles are shown regardless of which media mode is enabled when my compressed CSS file is being used.
