### ISSUE TITLE
Splat for mixins

### ISSUE THREAD

**Issue by dy** [less/less.js#1354]
A suggestion.
It might be useful to have splats feature for mixins.
Now I do this:

``` less
.bshad(@sh: none){  
    -webkit-box-shadow: @sh;
    -moz-box-shadow: @sh;
    box-shadow: @sh;
}
.bshad(@sh1, @sh2){  
    -webkit-box-shadow: @sh1, @sh2;
    -moz-box-shadow: @sh1, @sh2;
    box-shadow: @sh1, @sh2;
}
.bshad(@sh1, @sh2, @sh3){  
    -webkit-box-shadow: @sh1, @sh2, @sh3;
    -moz-box-shadow: @sh1, @sh2, @sh3;
    box-shadow: @sh1, @sh2, @sh3;
}
.bshad(@sh1, @sh2, @sh3, @sh4){  
    -webkit-box-shadow: @sh1, @sh2, @sh3, @sh4;
    -moz-box-shadow: @sh1, @sh2, @sh3, @sh4;
    box-shadow: @sh1, @sh2, @sh3, @sh4;
}
```

But it’d be much more useful to have this:

``` less
.bshad(@shadows...) {
-webkit-box-shadow: @shadows;
-moz-box-shadow: @shadows;
box-shadow: @shadows;
}
```

The same with calling:

``` less
@shads: 1px 2px 3px black, 2px 3px 4px gray;
.bshad(@shads...); 
```
