### ISSUE TITLE
Named arguments confusion

### ISSUE THREAD

**Issue by dy** [less/less.js#1355]
Faced with trouble when tried to implement different behavior of function with the same number but different name of arguments:

``` less
.extrude(@angle, @amount){
  @x: (cos(@angle) * @amount);
  @y: (sin(@angle) * @amount);
  .extrude(@x: @x, @y: @y);
}
.extrude(@x, @y){
  @shad:(@x * .2) (@y * .2) 0 0 gray,
        (@x * .4) (@y * .4) 0 0 gray,
        (@x * .6) (@y * .6) 0 0 gray,
        (@x * .8) (@y * .8) 0 0 gray,
        (@x * .9) (@y * .9) 0 0 gray,
        (@x * 1.0) (@y * 1.0) 0 0 gray;
  .box-shadow(@shad);
}

.test{
  .extrude(@x: 5px, @y: 6px);
}
```

raises

``` css
Syntax error: Named argument for .extrude @x not found
.test{  .extrude(@x: 5px, @y: 6px);}
```

Possibly it should not fail when I passed the exact names of arguments?
What's correct way to detect exact arguments passed?
