### ISSUE TITLE
Parse error for valid CSS (comments with "{" in function parameters)

### ISSUE THREAD

**Issue by phispi** [less/less.js#1356]
The following valid CSS

``` CSS
.bg {
    background-image: linear-gradient(#333 /*{comment}*/, #111);
}
```

gives

```
ParseError: missing opening `{` in /tmp/jquerymobile.less on line 4, column 1:
3 }
4 
```

with lessc 1.4.0-b4. I admit that this is a strange kind of comment but those kind of comments prevent the default .css from jquery-mobile 1.3.1 from being processed as less file.

I already found out that 

``` CSS
/*{comment}*/
.bg {
    color: #333 /*{comment}*/;
    background-image: linear-gradient(#333 /*comment*/, #111);
}
```

parses without error.

Thanks for developing less! :-)
