### ISSUE TITLE
Ie bug

### ISSUE THREAD

**Issue by orapow** [less/less.js#1358]
less 代码

``` scss
#main {
  background-color: red;
  padding: 10px;
  .c {
    padding: 10px; 
    background-color: blue;
  }
  .v {
    padding: 10px; 
    background-color: green;
  }
}
```

ver 1.4.0 beta
浏览器：ie 8
