### ISSUE TITLE
Loops: Selector Interpolation Bug

### ISSUE THREAD

**Issue by mikebarnhardt** [less/less.js#1360]
This code is broken in 1.3.3 and 1.3.2, but works fine in 1.4 and 1.3.1 (according to less2css.org):

``` css
.margins (@columns, @width) {
    .loop (@i) when (@i > 0) {
    @nth-child: ~":nth-child(@{columns}n+@{i})";
    &@{nth-child} {
      margin-left: (@width + 20px)*(@i - 1);
    }
    .loop (@i - 1);
  }
  .loop (0) {}
  .loop (@columns);
}

.columns (@columns) {
    @width: ( (900px - ((@columns - 1) * 20px)) / @columns );
  width: @width;
  .margins(@columns, @width);
}

li {
  .columns(4);
}
```

I get:

``` css
:nth-child(4n+1) {...}
:nth-child(4n+1) {...}
:nth-child(4n+1) {...}
:nth-child(4n+1) {...}
```

instead of:

``` css
:nth-child(4n+4) {...}
:nth-child(4n+3) {...}
:nth-child(4n+2) {...}
:nth-child(4n+1) {...}
```
