### ISSUE TITLE
Mixins unlocking - nested namespace overwrites mixins in outer namespace

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#1370]
Nested namespaces overwrites mixins mixins in outer namespace:
Sample input:

``` css
.apples(@width) { .bananas() { width: @width; } }

#outer-namespace {
  #namespace {
    // import bananas into nested namespace
    .apples(700px);
  }
  // import bananas into outer namespace
  .apples(600px);
}

#test-outer {
  // this returns width: 700px e.g. mixin imported into nested namespace
  // it should return width: 600px
  #outer-namespace > .bananas(); 
}
```

Actual output:

``` css
#test-outer {
  width: 700px;
}
```

Expected output:

``` css
#test-outer {
  width: 600px;
}
```

Overwriting import happens only if the outer namespace contains a mixin with the same name. Mixins from nested namespaces are not normally imported:

``` css
.apples(@width) { .bananas() { width: @width; } }

#outer-namespace {
  #namespace() {
    .apples(700px);
  }
  // removed the mixin .apples(600px);
}

#test-outer {
  #outer-namespace > .bananas(); 
}
```

works as expected and returns an error:

```
NameError: #outer-namespace > .bananas is undefined
```

Only namespaces that double as ruleset have the bug. Pure namespaces work as expected e.g., following works OK:

``` css
.apples(@width) { .bananas() { width: @width; } }

#outer-namespace {
  #namespace() {
    .apples(700px);
  }
  .apples(600px);
}

#test-outer {
  #outer-namespace > .bananas(); 
}
```

works as expected and this:

``` css
#test-outer {
  width: 600px;
}
```

Tested on less.js 1.4.0 on windows node.js.
