### ISSUE TITLE
Variable and mix-in error reporting bugs when using multiple stylesheets

### ISSUE THREAD

**Issue by PatrickMurray** [less/less.js#1393]
Hi all,

After some learning and messing with less.js, I believe I've found a bug.  When referring to variables or classes defined in another stylesheet, false errors are reported to the user stating that said variable or class is not defined.  When it is.  Even if the mix-in is called after the class included is created (in another stylesheet), an error will still be reported.

_index.html_

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>GitHub Example Index Document</title>
        <link rel="stylesheet/less" type="text/css" href="main.less" />
        <link rel="stylesheet/less" type="text/css" href="styles.less" />

        <script src="less-1.3.3.min.js" type="text/javascript"></script>
    </head>
    <body>
        <div>
            <h1>Hello World!</h1>
        </div>
    </body>
</html>
```

_main.less_

``` css
@maincolor: skyblue;

.center {
    margin:0 auto;
    }
```

_styles.less_

``` css
body>div {
    color: @maincolor;
    .center
    }
```

Image:
![github_big](https://f.cloud.github.com/assets/3487401/726791/dc611aca-e130-11e2-9e27-8974e102e359.png)

Thanks for your time!
- Pat
