### ISSUE TITLE
Possible Bug - &:extend() behaving oddly

### ISSUE THREAD

**Issue by gnomishperson** [less/less.js#1404]
From my understanding of using :extend() the following LESS

``` LESS
.header {
     .header-nav {
        background: red;
        &:before {
            background: blue;
        }
    }
}
```

compiles to:

``` LESS
.header .header-nav { background: red; }
.header .header-nav:before { background: blue; }
```

And adding:

``` LESS
.footer {
    .footer-nav {
        &:extend( .header .nav all );
    }
}
```

Should compile to:

``` LESS
.header .header-nav, .footer .footer-nav { background: red; }
.header .header-nav:before, .footer .footer-nav:before { background: blue; }
```

but I'm getting:

``` LESS
.header .header-nav, .footer .footer-nav { background: red; }
.header .header-nav:before, .footer .footer-nav { background: blue; }
```

So I'm not sure exactly how :extend() handles inheriting from nesting, and I tried reviewing the "test" cases, but they don't have an example that quite works the way I've been utilizing it.

I do know however I feel it's an issue with the parent **&** selector, as if I were to replace **&:before** with say a class ex: .before{} I get the "expected" output.

If I leave out the **.header** in the include from :extend(), then the &:before works correctly, but it then adds .header to the entire include of extend:

``` LESS
.footer {
    .footer-nav {
        &:extend( .header-nav all );
    }
}
```

compiles to:

``` LESS
.header .header-nav, .header .footer .footer-nav { background: red; }
.header .header-nav:before, .header .footer .footer-nav:before { background: blue; }
```

So there I'm getting my desired inheritance of :before, but an unwanted .header parent to .footer .footer-nav.

It may just be my mis-interpretation of :extend(), but was just hoping for some clarification.
