### ISSUE TITLE
Why properties do not override?

### ISSUE THREAD

**Issue by StreetStrider** [less/less.js#1406]
``` css
.a()
{
  x: 1;
}
.b
{
  x: 2;
  .a;
}
```

The result is (less2css):

``` css
.b {
  x: 2;
  x: 1;
}
```

Is that a determined behavior, or an occassion just because CSS overrides rules for us?
