### ISSUE TITLE
Passing ruleset to mixin

### ISSUE THREAD

**Issue by StreetStrider** [less/less.js#1420]
Is there any way to pass rulesets to mixins (in common, save rulesets in variables, makin them first-class citizens)?

For instance, I want to customize color of placeholder:

``` css
.placeholder (@color) {
  &::-webkit-input-placeholder { color: @color; }
  &:-moz-placeholder { color: @color; }
  &::-moz-placeholder { color: @color; }
  &:-ms-input-placeholder { color: @color; }
}
```

But what if we need to customize set of properties. It is possible but providing all of them by parameters. In common it would be useful to pass ruleset.

``` css
.placeholder (@ruleset) {
  &::-webkit-input-placeholder { /* expand @ruleset it here */ }
}
```
