### ISSUE TITLE
Unexpected result when using @arguments as JavaScript string

### ISSUE THREAD

**Issue by Justineo** [less/less.js#1423]
Hi everyone,

Less uses semicolons or comma as parameter separator as documented. So I expected the following .less code
```less
.mixin(...) {
    args: ~`"@{arguments}"`;
}

.test {
    .mixin(1 2 3);
}
```
to produce CSS like this:
```css
.test {
  args: [1 2 3];
}
```
But actually it produces
```css
.test {
  args: [1, 2, 3];
}
```
 So why '1 2 3' produces three array elements here?
