### ISSUE TITLE
Reference import not importing media queries

### ISSUE THREAD

**Issue by Xowap** [less/less.js#1469]
Hi all,

As stated in #1340, I want to use LESS in order to import Bootstrap classes without rendering the full stuff. As of now, it worked pretty well, however Bootstrap 3 came out and the grid system changed completely, including a new mixin that allows you to create your own column classesm, cf [the doc](http://getbootstrap.com/css/#grid-less).

The problem is the following:

Given the following code, it works perfectly fine

``` css
@import "less/bootstrap.less";

.passport-body {
  .make-column(9);
}
```

Output:

``` css
/* here comes the whole bootstrap world that I omitted to paste */
.passport-body {
  position: relative;
  min-height: 1px;
  padding-left: 15px;
  padding-right: 15px;
}
@media (min-width: 768px) {
  .passport-body {
    float: left;
    width: 75%;
  }
}
```

However if I try to make some reference import, here is what I get

``` css
@import (reference) "less/bootstrap.less";

.passport-body {
  .make-column(9);
}
```

Output:

``` css
.passport-body {
  position: relative;
  min-height: 1px;
  padding-left: 15px;
  padding-right: 15px;
}
```

As you can see, the media query part was dropped.

I don't know if this is a bug or a feature, but in any case this is an annoying behavior because it makes it hard to use bootstrap's mixins this way.

Also I'm sorry I couldn't provide a live example, however I'm not using a stable version, which might be why there is a bug :)

For information, I use the commit 4bedef4fd3748257cf04a42c8e0181c0116d754b of lessc

Many thanks!
