### ISSUE TITLE
Relative paths are not properly updated in compiled CSS

### ISSUE THREAD

**Issue by OliverJAsh** [less/less.js#1470]
I have authored my partials so that the paths are relative to the partial file, instead of the file that is importing it. When LESS compiles the CSS into a single CSS file, it should recognise these relative paths and update their relativity to suit the output directory.

I have created [an example project](http://cl.ly/3n1f1Y1f1E16) to demonstrate this problem. Run `node_modules/less/bin/lessc site/css/main.less site/css/compiled/main.css` and then look at the compiled CSS file's contents:

``` css
.example {
  background-image: url('../../img/test.png');
}
body {
  background-image: url('../img/test.png');
}
```

What I actually need is:

``` css
.example {
  background-image: url('../../img/test.png');
}
body {
  background-image: url('../../img/test.png');
}
```

I have tried to use the `--relative-urls` and `rootpath` option, but this does not seem to be a problem that these options can fix. I have authored stylesheets in this way with Sass before and I've had no problems.

To clarify:
- When the `partials/example.less` partial gets bundled into `main.less`, the `background-image` URL of `.example` should be updated to `../img/test.png` from `../../img/test.png`. This is as it is being imported by a file _one directory above_.
- When `main.less` is compiled into `compiled/main.css`, all paths should be prefixed with `../` (I believe this is achievable with the `rootpath` option).
