### ISSUE TITLE
importing same less file into multiple namespaces fails

### ISSUE THREAD

**Issue by pinoniq** [less/less.js#1476]
Wehn trying to import the same less file into multiple namespaces it fails.

e.g.:

i have a settings/color.less file with some declarations that i then use as folows:

``` css
background.less:
#background {
    @import '../settings/color.less';
    .black(@b:@black) {
        background-color:@b;
    }
}

and font.less: 
#font {
    @import '../settings/color.less';
    .black(@b:@black) {
        color:@b;
    }
}
```

It doesn't work.
