### ISSUE TITLE
lessc: Option to compile less file to LESS

### ISSUE THREAD

**Issue by wnr** [less/less.js#1478]
I apologize if this request was already requested, I didn't find any when I searched.
##### Summary

I would like to have the option in the lessc binary to compile a .less file to LESS. Just like it works right now with .less to CSS, but instead .less to LESS. This to be able to compile a .less file which has imports to other .less files, to a complete exportable .less file.
##### Use case

I have a web framework that is built upon bootstrap (lets say 20 .less files). In my framework I have a master .less file that imports all bootstrap and framework .less files, called `framework.less`.

Now, to use the web framework in another web project, I could do a `lessc framework.less > /path/to/web/project/framework.css`. Then I could use all the css styles, etc. However, if I would like the web project the extend the framework further, my only option today is to copy all the framework .less files into the web project and then build upon these.

What I would like to be able to do, is to instead of doing `lessc framework.less > /path/to/web/project/framework.css` I would like to do `lessc -less framework.less > /path/to/web/project/framework.less`. Now, the compiled framework.less file would have inserted the LESS code from the framework .less files, instead of having them imported.
##### Example

**files**
_file.less_

``` less
@base-color: red;

@import "button.less";
@import "input.less";
@import "div.less";
```

_button.less_

``` less
.button {
  color: @base-color;
}
```

_input.less_

``` less
.placeholder {
  color: #eee;
}
```

_div.less_

``` less
@div-padding: 20px;
```

**lessc**

```
lessc -less file.less
```

**output**

``` less
@base-color: red;

.button {
  color: @base-color;
}

.placeholder {
  color: #eee;
}

@div-padding: 20px;
```
