### ISSUE TITLE
Media queries: parentheses needed even without --strict-math=on

### ISSUE THREAD

**Issue by papandreou** [less/less.js#1480]
This example produces different output under less 1.3.3 and 1.4.2:

``` less
.foo (@dpr) {
    @dpi: @dpr * 96dpi;
    @query: ~'(min-resolution: @{dpi})';
    @media @query {
    }
}
.foo(2);
```

Output with less 1.3.3:

``` css
@media (min-resolution: 192dpi) {

}
```

Output with less 1.4.1:

``` css
@media (min-resolution: 2 * 96dpi) {

}
```

Adding parentheses around `@dpr * 96dpi` makes less 1.4.1 output the same as 1.3.3, but this was an unexpected gotcha with the upgrade to 1.4.x.

**Comment by clayzermk1** [comment]
:+1: Also seeing this on less 2.5.1. The suggested workaround of putting parenthesis around the variable in the media query works.

Trivial problem case:
```less
@foo: 10px;
@bar: 20px;
@baz: @foo + @bar;

.test {
  @media (min-width: @baz) {
    color: red;
  }
}
```
Compiled CSS of trivial problem case (invalid):
```css
@media (min-width: 10px + 20px) {
  .test {
    color: red;
  }
}
```

Trivial problem case with workaround:
```less
@foo: 10px;
@bar: 20px;
@baz: @foo + @bar;

.test {
  @media (min-width: (@baz)) {
    color: red;
  }
}
```
Compiled CSS of trivial problem case with workaround:
```css
@media (min-width: 30px) {
  .test {
    color: red;
  }
}
```
