### ISSUE TITLE
Imports with @viewport break source-maps

### ISSUE THREAD

**Issue by dotnetwise** [less/less.js#1493]
having this import in `layout.less`:

``` css
@import url('../../app/vendor/ie10mobile/ie10mobile.less');

html > body.public {
    background: red !important;
}
```

causses all of the subsequent definitions to be pointed to `ie10mobile.less` instead of `layout.less` as this 
![viewportbug](http://content.screencast.com/users/softer/folders/Jing/media/8c6c8e7e-c6b6-4447-85c2-5d5acff80287/2013-08-14_2024.png)

This seems to be caused because of the [`correct CSS`](http://docs.webplatform.org/wiki/css/atrules/@viewport) but I guess `wrong LESS` syntax contained in the `ie10mobile.less`

``` css
@-webkit-viewport {
    width: device-width;
}

@-moz-viewport {
    width: device-width;
}

@-ms-viewport {
    width: device-width;
}

@-o-viewport {
    width: device-width;
}

@viewport {
    width: device-width;
}
```

The generated css is good, but the source map gets broken.
