### ISSUE TITLE
Inconsistent formatted output of margin at-rules in a @page rule

### ISSUE THREAD

**Issue by mdarens** [less/less.js#1495]
Source:

``` Less
@page {
    marks: none;
    @top-left-corner {
        vertical-align: top;
    }
    @top-left {
        vertical-align: top;
    }
}
```

Expected Output:

``` CSS
@page  {
    marks: none;
    @top-left-corner {
        vertical-align: top;
    }
    @top-left {
        vertical-align: top;
    }
}
```

Actual Output:

``` CSS
@page  {
    marks: none;@top-left-corner {
        vertical-align: top;
    }
    @top-left {
        vertical-align: top;
    }
}
```
