### ISSUE TITLE
Postfix usage of & combinator moves selector to the top instead of one level up

### ISSUE THREAD

**Issue by Piedone** [less/less.js#1500]
This might by my misunderstanding but since it's not clearly stated in the documentation let's evaluate.

Given the following LESS:

``` css
.top {
  .bottom {
    .middle & {
      color: black;
    }
  }
}
```

Output is:

``` css
.middle .top .bottom {
  color: black;
}
```

Note that .middle is now before .top. I'd however expect it to move just one level up, before .bottom, like this:

``` css
.top .middle .bottom {
  color: black;
}
```

Is the output the desired one or I am right?
