### ISSUE TITLE
strictMath

### ISSUE THREAD

**Issue by ShootingStarr** [less/less.js#1501]
I use codekit and can not set an option in the console, please tell me which file to change the settings "strictMath:true" ?

``` css
.oval {
  -webkit-border-radius: 20px / 10px;
  -moz-border-radius: 20px / 10px;
  border-radius: 20px / 10px;
}
```

output:

``` css
.oval {
  -webkit-border-radius: 2px;
  -moz-border-radius: 2px;
  border-radius: 2px;
}
```
