### ISSUE TITLE
Unexpected behaviour when using mixins containing media queries, especially if inside media query

### ISSUE THREAD

**Issue by Piedone** [less/less.js#1502]
Hope the title is interesting enough! :-)

Given this LESS:

``` css
.nav-justified {
  @media (min-width: 480px) {
    > li {
      display: table-cell;
    }
  }
}

.menu
{
  .nav-justified();
}

.menu
{
  @media (min-width: 768px) {
    .nav-justified();
  }
}
```

Output:

``` css
@media (min-width: 480px) {
  .nav-justified > li {
    display: table-cell;
  }
}
@media (min-width: 480px) {
  .menu > li {
    display: table-cell;
  }
}
@media (min-width: 768px) {

}
@media (min-width: 768px) and (min-width: 480px) {
  .menu .nav-justified > li {
    display: table-cell;
  }
}
```

The first two blocks are just as I'd expect, but notice two things:
- There's an empty media query.
- In the last block instead of the ".menu > li" selector the resulting selector is ".menu .nav-justified > li". I'd expect the resulting selector to be ".menu > li", just as in the second block.
