### ISSUE TITLE
Automatically remove @keyframes duplicates

### ISSUE THREAD

**Issue by Justineo** [less/less.js#1506]
Hi,

When writing animations I don't want `@keyframes` rules appear in final `.css` files if they are not used (because if we support lots of animations that will be great amount of code). So I put a `@keyframes` rule inside a mixin, like this:

``` less
.play() {
  @keyframes play {
    from {
      margin-top: 0;
    }

    to {
      margin-top: 100px;
    }
  }
}
```

But if I call that mixin for several times, the `@keyframes` rule will also be repeated.

``` less
.test {
  .play();
}

.test2 {
  .play();
}
```

will output (in global scope):

``` css
@keyframes play {
  from {
    margin-top: 0;
  }
  to {
    margin-top: 100px;
  }
}
@keyframes play {
  from {
    margin-top: 0;
  }
  to {
    margin-top: 100px;
  }
}
```

Is there a way to avoid this? (I'm using lessc 1.4.2)
