### ISSUE TITLE
add gsub function

### ISSUE THREAD

**Issue by jakebellacera** [less/less.js#1511]
It would be nice to perform a find and replace on a string using regex. This would prove exceptionally useful with mixins.

---
### gsub(str, regexp, replacement)

`gsub` is essentially a wrapper for [`String.replace()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FString%2Freplace), and the regular expression has the `g` flag<sup>[1]</sup> set. Here are descriptions of each of the params:
- `str` _(String)_ the string we wish to perform the replacement on.
- `regexp` - _(String)_ the regular expression in string form.<sup>[2]</sup>
- `replacement` - _(String)_ the substring that would replace the match found in the regular expression.

`gsub` would return a formatted string.

---
## Use case: high-DPI image mixin

``` less
.hd-background-image (@src, @size) {
  background-image: url(@src);

  @media only screen and (min-resolution: 192dpi) {
    @hdSrc: gsub(@src, "\.([a-zA-Z]{3,4})$", "_2x.$1");

    background-image: url(@hdSrc);
    background-size: @size;
  }
}
```

This would mean that I could structure my project to append `_2x` to the end of my high-dpi images' filenames and it would automagically set it on any elements with the `.hd-background-image` mixin.

---

I currently have a working version [here](https://github.com/jakebellacera/less.js/compare/adding_gsub_function), but I thought I'd submit this as a feature request in case anyone felt like this would be useful before I submit a pull-request.

Thoughts?

<sub>[1] - global match</sub>
<sub>[2] - we'd use `new RegExp()` to create a regular expression from a string.</sub>
