### ISSUE TITLE
Selector Interpolation Compression Error

### ISSUE THREAD

**Issue by kopepasah** [less/less.js#1514]
LESS Version: 1.4.2

---

I am using selector interpolation to implement a main class that I use for stacking styles. Here is an example:

``` css
@module: ~'.builder-module';

@{module} {
    background: @base;
}
```

While this works with the live output, conversion from LESS to CSS in fails.

Using:

``` bash
lessc main.less > styles.css
```

This is the error I receive:

``` bash
ParseError: Syntax Error on line 3 in main.less
3 @{module} {
```

---

I thought this may be an issue with how I was creating the variable so I also tried.

``` css
@module: builder-module;

.@{module} {
    background: @base;
}
```

But get the same error.
