### ISSUE TITLE
Parent scope vs. caller's scope.

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#1522]
Recently, I came across something that looks suprising to me:

``` less
@bar: 41;

.mixin()
{
    foo: @bar;
}

#usage
{
    @bar: 42;
    .mixin(); // outputs foo: 41;
}
```

Assuming the "lazy loading" principle I was expecting that to output foo: 42.

Well, after some thinking I'm not quite sure if "lazy loading" applies here at all
(although mixin does use caller's scope variable if no global `@bar` defined).
It's more like a "scope precedence" thing to be documented eventually, i.e.:
"local scope" > "parent scope" > "caller's scope".

Just in case, here's sort of a workaround I came with to force mixin to take caller's scope variables:

``` less
// this is useful if you need to pass a lot of variables to mixin
// but don't want them to be mixin parameters/arguments:

@bar: 41;

.mixin()
{
    .variables();
    foo: @bar;
}

#usage
{
    .variables() {
        @bar: 42;
        // etc.
    }

    .mixin(); // outputs foo: 42;
}

// it's a weak trick though because the same scope story applies to the .variables mixin itself :(
```
