### ISSUE TITLE
Do not break on CSS4 parent selector

### ISSUE THREAD

**Issue by skerit** [less/less.js#1523]
The current CSS4 draft allows us to write selectors like this:

```css
th! [data-sort-active=true] {
	background-color: #f1f1f1;
}
```

There are polyfills available for browsers that don't support this yet. (which is every single one of them, I guess)

However: LESS won't compile this. It throws an 'Unrecognised input' error.
Couldn't this just be ignored?
