### ISSUE TITLE
Can I use LESS functions in JavaScript evaluation? 

### ISSUE THREAD

**Issue by Pestov** [less/less.js#1532]
Hi. I want rewrite [this SCSS](https://github.com/DarbyBrown/Shade/blob/master/scss/_shade.scss) on LESS. It's look like this:

``` LESS
.shade(@color: #3498db, @depth: 20, @angle: 135deg, @long: false, @fade: false) {
    @ang: (@angle - 90);
    @x: 1.5 * cos(@ang);
    @y: 1.5 * sin(@ang);

    @defineDarken: (lightness(@color)/@depth)/2;
    @darken: ~`(function (long, defineDarken) {var d = (long == "true") ? 0 : defineDarken; return d;})("@{long}", "@{defineDarken}")`;  

    @defineOpacify: (opacity(@color)/@depth);
    @opacify: ~`(function (fade, defineOpacify) {var o = (fade == "true") ? 0 : defineOpacify; return o;})("@{fade}", "@{defineOpacify}")`;

    @thishue: hue(@color);
    @thissaturation: saturation(@color);
    @thislightness: lightness(@color);

    @shadow: ~`(function (depth,x,y,darken,opacify,thishue,thissaturation,thislightness) {
        var shadow = "";
        for(var i=1; i<depth; i++) {
            if (i != depth) {
                shadow += i*x+"px "+i*y+"px 0 hsla("+thishue+", "+thissaturation+", "+thislightness - (i*darken)+", "+1 - (i * opacify)+"), ";
            } else {
                shadow += i*x+"px "+i*y+"px 0 hsla("+thishue+", "+thissaturation+", "+thislightness - (i*darken)+", "+1 - (i * opacify)+");"; 
            }
        }
        return shadow;
    })("@{depth}", "@{x}", "@{y}", "@{darken}", "@{opacify}", "@{thishue}", "@{thissaturation}", "@{thislightness}")`;

    text-shadow: @shadow;   
```

I don't use CSS function and as a result this big bad code. This LESS not work - "Operation on an invalid type". Next issue how i can see result my javascript before compile error? 

A lot of thanks, in advance.
