### ISSUE TITLE
Weird mixin nesting bugs

### ISSUE THREAD

**Issue by sunyatasattva** [less/less.js#1544]
What I am trying to accomplish is build a _sort of “recursive”_ mixin that changes behavior according to the depth it is nested inside itself; specifically, I would like to reuse variables from the parent mixin in the nested one, so, if someone knows a better way to do this and (ideally) provide endless nesting, I'd be grateful.

In the meantime I think I found a few interesting and weird nesting bugs. Here is the minimal use case:

``` CSS
.mixin(@a, @b) {
   a: @a;
   b: @b;

   // First level nesting
   .mixin(@x,@y){
      /* Inherits from parent */
      a: @a;
      b: @b;
      /* Own properties */
      x: @x;
      y: @y;

     // Second level nesting
     .mixin(@bar,@foo){
       /* Inherits from grandparent */
       a: @a;
       b: @b;
       /* Inherits from parent */
       x: @x;
       y: @y;
       /* Own properties */
       bar: @bar;
       foo: @foo;
     }
   }
 }

grandparent {
  .mixin(a,b);

  parent {
    .mixin(x,y);

    child {
      .mixin(bar,foo)
    }
  }
}
```

All of this is nice and dandy, and outputs the correct, expected CSS: notably, the variables gets inherited in the nesting.

Now try to modify the first level nested mixin with a guard (I'll only change the few lines surrounding it to save space):

``` CSS
    // First level nesting
   .mixin(@x,@y) when (@x=@a){
```

Outputs a `Name error: variable @a is undefined` even though not only `@a` is clearly defined above, it is also accessible inside the mixin, as shown by the output of `parent`.

This, however, works:

``` CSS
    // First level nesting
   @_temp: @a;
   .mixin(@x,@y) when (@x=@_temp){
```

So now `parent` and `child` are not outputted in CSS because the first nested level doesn't satisfy the guard. Which is what we expect. If you nest `parent` as such:

``` CSS
   parent{
        .mixin(x,a)
   }
```

Everything works perfectly and the CSS outputs both `parent` and `child`.

Now get everything back to the original example, and change these few lines around `grandparent`:

``` CSS
    grandparent{
        .mixin(a,b);
        .mixin(c,d);
    }
```

Now look at the output in fear. Here are a few things we can notice:
1. Even though `.mixin(c,d)` is not **nested** inside `.mixin(a,b)`, but it is rather a **sibling**, `c` and `d` parameters get mapped to `x` and `y`, as if it was nested.
2. `grandparent parent` is a scary mess: there are some empty comments which indicate that there was some kind of mixin parsing which went awry and didn't output anything. Properties get surprisingly mapped correctly afterwards, though… except that by magic it calls the third nested mixin and assigns `x` and `y` to `bar` and `foo`.
3. `grandparent parent child` is… correct.

Now for another experiment, **put back the guard** as we did above (`when (@x=@_temp)`).

The output does display only `a` and `b` on `grandparent` because the guard worked on the sibling mixin.

**Then edit** `.mixin(c,d)` to `.mixin(c,a)`. Notice the following:

`grandparent parent` and `grandparent parent child` have `c` and `a` mapped to `x` and `y` (while in the previous example they were correctly assigned). Also `.mixin(x,y)` was called at some point but looks quite random.

**Edit** `.mixin(x,y)` to `.mixin(x,a)`: output is the same as two steps above.

**Edit** `.mixin(c,a)` to `.mixin(c,d)`: everything works as expected.
