### ISSUE TITLE
Optimize (remove) style redefinitions

### ISSUE THREAD

**Issue by mar10** [less/less.js#1547]
I have `common.less`:

``` css
.container: {
    color: black;
    background-color: white;
}
```

and `variant_1.less`: 

``` css
@import "common.less";
[...]
.container: {
    color: red;
}
```

My expectation would be, that in the resulting file shadowed CSS rules are removed:  
`variant_1.css`: 

``` css
.container: {
    // 'color: black' should not appear in the output
    background-color: white;
}
[...]
.container: {
    color: red;
}
```

(Using grunt-.contrib-less with optimization, compress and yuicompress on)

I understand that overloading styles _may_ be done to provide a fallback for browsers that don't support the previous style definition.
But here this is not the case.
Maybe add a new decorator such as

``` css
    color: black !no-optimize;
```

?
