### ISSUE TITLE
background file

### ISSUE THREAD

**Issue by szepeviktor** [less/less.js#1551]
Is there a shorter solution?

``` css
.bg-i (@file) when (@file = none) {
    background-image: none;}
.bg-i (@file) when not (@file = none) {
    background-image: data-uri(@file);}
```

Thank you!
