### ISSUE TITLE
@host rule support

### ISSUE THREAD

**Issue by ghost** [less/less.js#1560]
@host rule and ::distributed() pseudo-element support would be nice 
[W3C spec](https://dvcs.w3.org/hg/webcomponents/raw-file/tip/spec/shadow/index.html#host-at-rule)

already using it 
[dart](https://www.dartlang.org/polymer-dart/)
[polymer](http://www.polymer-project.org/)

``` css

      @host {
        div {
          display: block;
        }
      }

      ::distributed(input::placeholder) {
        color: #b3b3b3;
      }
```
