### ISSUE TITLE
Unexpected behavior of ampersand combinator (`&`) within nested rules

### ISSUE THREAD

**Issue by jacobcarpenter** [less/less.js#1575]
I'm running into unexpected behavior using the `&` combinator within nested rules.

Here is a fragment of pseudo-html I'm attempting to style with less.

``` html
<section class="details">
  <div class="info">...</div>
  <table class="info">...</table>
  <div class="info">..</div>
</section>
```

If I write:

``` less
.info {
  margin-top: 12px;

  table& {
    width: 100%;
  }
}
```

as desired, I get:

``` css
.info {
  margin-top: 12px;
}
table.info {
  width: 100%;
}
```

That is, all elements with the `info` class have `margin-top` applied, plus `table` elements with the `info` class get `width: 100%`.

However, if I nest these rules within `details`, the ampersand (`&`) combinator ceases to generate what I expect.

I would expect

``` less
.details {
  .info {
    margin-top: 12px;

    table& {
      width: 100%;
    }
  }
}
```

to turn into:

``` css
.details .info {
  margin-top: 12px;
}
.details table.info {
  width: 100%;
}
```

Instead, it turns into:

``` css
.details .info {
  margin-top: 12px;
}
table.details .info {
  width: 100%;
}
```

Is this a bug, or are my expectations flawed? Thanks!
