### ISSUE TITLE
extend adds same class twice 

### ISSUE THREAD

**Issue by programming-kid** [less/less.js#1581]
i Think there is a bug in @extend function ,not actually bug but its quirky 

Here is what i was trying to do
LESS

``` css
    .box{
    margin: 0 auto 25px;
    border: 1px solid;
    padding: 15px;
    border-radius: 6px;

    }

    .important{
    &:extend(.box all);
        background: #ffe5e5;
        border-color: red;
    }
    .success{
    &:extend(.important all);
    }
```

i got this
CSS

``` css

.box,
.important,
.success {
  margin: 0 auto 25px;
  border: 1px solid;
  padding: 15px;
  border-radius: 6px;
}
.important,
.success,
.success {
  background: #ffe5e5;
  border-color: red;
}
```

I was expecting this
CSS

``` css
.box, .important, .success {
  margin: 0 auto 25px;
  border: 1px solid;
  padding: 15px;
  border-radius: 6px;
}

.important, .success {
  background: #ffe5e5;
  border-color: red;
}

```

i don't understand why is it adding two success classes when it should be ading only one
