### ISSUE TITLE
IE filter concatenate

### ISSUE THREAD

**Issue by XmlmXmlmX** [less/less.js#1587]
Problem: Multiple IE-Filters in various mixins will be overridden by themself.

``` less
.mixin-1() { 
  filter: ~"alpha(opacity=50)"; 
} 
.mixin-2() { 
  filter: ~"progid:DXImageTransform.Microsoft.Shadow(Color='#000000')"; 
}
```

will output this (the first filter will have no effect):

``` less
.result { 
  filter: alpha(opacity=50); 
  filter: progid:DXImageTransform.Microsoft.Shadow(Color='#000000'); 
}
```

but should output this, to get it it work right:

``` less
.result { 
  filter: alpha(opacity=50), progid:DXImageTransform.Microsoft.Shadow(Color='#000000'); 
}
```
