### ISSUE TITLE
Support dot and slash in literal mixin parameter

### ISSUE THREAD

**Issue by Krinkle** [less/less.js#1588]
``` css
.backgrond-image(@src) {
  background-image: url(@src);
}

.foo {
  .backgrond-image(images/foo.png);
}
```

> Syntax error: expected ')' got '.'
> .foo {  .backgrond-image(images/foo.png);}

Would it be feasible to allow dots in literal mixin parameters?

The argument can be quoted, but since CSS allows them to be unquoted (e.g. in `url()`) would be nice if Less would support that as well.
