### ISSUE TITLE
@color: #369; prints #336699

### ISSUE THREAD

**Issue by stefano-bortolotti** [less/less.js#1589]
If I have this code: 

``` css
@textColour: #369; 
h1 { 
   color: @textColour; 
} 
```

I would expect to have in result: 

``` css
h1 { 
   color: #369; 
} 
```

Instead it prints 

``` css
h1 { 
   color: #336699; 
} 
```

Is it possible to optimise it so that it keeps the short syntax? 
thanks
