### ISSUE TITLE
Problem with 0-N arguments when use pattern-matching or guard expressions

### ISSUE THREAD

**Issue by Pestov** [less/less.js#1594]
``` LESS
.mix(@type; ...) {}
.mix(bg; @color, @width)  {
    background: @color;
    width: @width;
}

.mix(color; @color, @fontsize) {
    color: @color;
    font-size: @fontsize;
}

.el {
    .mix(bg; blue, 10px);
}    
```

Compile error `SyntaxError: variable @color is undefined`

Then i rewrite this with guard expressions: 

``` LESS
.mix(@type...) when (@type = bg) {
    .mix(@type, @color, @width)  {
        background: @color;
        width: @width;
    }
}

.mix(@type...) when (@type = color) {
    .mix(@type, @color, @fontsize) {
        color: @color;
        font-size: @fontsize;
    }
}
```

After compile i have empty file. Why? It's bug or my mistake?
