### ISSUE TITLE
Can't extend a nested class (concatenated selector)

### ISSUE THREAD

**Issue by DennisJohnsen** [less/less.js#1597]
Heya guys.

I have found an annoying issue, which is pretty basic use of two mechanics:
I cant extend a class i generate by nesting it using "& {}"

Heres my example:

<pre>
.box {
    padding: @base-spacing;

    &--large {
        padding: @large-spacing;
    }
}

.foo {
    &:extend(.box--large);
}
</pre>

Expected result:

<pre>
.box {
    padding: 24px;
}

.box--large,
.foo {
        padding: 48px;
}
</pre>

What actually happens:

<pre>
.box {
    padding: 24px;
}

.box--large {
    padding: 48px;
}
</pre>

Imo this is very basic use of two mechanics, and it's not like its generated by some kind of wizard looping mixin.
Looking forward to have this fixed :-)

Kind regards, Dennis

**Comment by matthew-dean** [comment]
@guillaume-duchemin Not out-dated. Marked as [`up-for-grabs`](https://github.com/less/less.js/labels/up-for-grabs), so anyone can submit a PR for it at anytime.

**Comment by rejhgadellaa** [comment]
+1

**Comment by kubami19** [comment]
+1

**Comment by acjbizar** [comment]
+1

**Comment by matthew-dean** [comment]
In case someone comes here with a case like @Johns3n's [example](https://github.com/less/less.js/issues/1597#issuecomment-43590949), you can always just convert that to:
```less
.ui {
    &__theme {
        background-image:url(../images/watermark.gif);
        background-position:top left;
        background-attachment:fixed;
        background-repeat:no-repeat;
        &, &--inverted {
            background-image:url(../images/watermark--inverted.gif);
            background-position:top right;
        }
    }
}
```
