### ISSUE TITLE
namespace classes

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [less/less.js#1598]
Hi!

I have a simple grid system which i want to access both via less and inside the browser.

That's why i use classes as a namespace (not ids like in the demo) and reference the class inside the nested code with "&"

``` css
.box {
    .border-box;
    float: left;
    &.xxxx,
    &.xxx,
    &.xx,
    &.x,
    &.mm,
    &.m {
        width: 100%;
    }
    &.xxxo {
        width: 75%;
    }
    /* ... */
}
```

When I call the mixin, i have to write

``` css
nav#sub-nav {
    .box > &.xxxo;
}
```

but I expected

``` css
nav#sub-nav {
    .box.xxxo;
}
```
