### ISSUE TITLE
Exception thrown when using eval result as unit() argument

### ISSUE THREAD

**Issue by ashi009** [less/less.js#1607]
LESS version: 1.5b4

_This is new to the 1.5 version, and 1.4 handles it without error._

Hi all,

I'm trying to use evaluated result as an argument to a built-in function.

```LESS
@-lambda: `widths = [1,2,3].map(function(val) { return Math.pow(10, val); })`;

.someclass {
  width: unit(`widths[1]`, px);
}
```

which throws "error evaluating function `unit`: the first argument to unit must be a number", due to the https://github.com/less/less.js/commit/0465398ab62597cd50f53984e06e923b692cb44b which fixes #1426.

I think the problem is from `tree.JavaScript` [implementation](https://github.com/less/less.js/blob/master/lib/less/tree/javascript.js), which returns everything except string as `tree.Anonymous` node. The `eval` function should return `tree.Dimension` for numeric values instead of `tree.Anonymous`.
