### ISSUE TITLE
Relative paths with repeated parent directories fail

### ISSUE THREAD

**Issue by SLaks** [less/less.js#1609]
Layout:
- sub1
  - entry.less: `@import '../common';`
- common.less: `@import url('common2.less');`
- common2.less: `@import 'sub2/lib';`
- sub2
  - lib.less: `a { background: url(../image); }`

Command: (Less 1.5)

``` sh
lessc -ru sub1/entry.less
```

Actual Output:

``` css
a {
  background: url(../../sub2/../image);
}
```

Expected Output:

``` css
a {
  background: url(../sub2/../image);
}
```

Confusingly, this only happens if `common.less` XOR `common2.less` have `url()` in their `@import` directives.  
Without that, it works as expected.

If they both have `url()`, I get a compilation error; `FileError: '../../sub2/lib.less' wasn't found`, from `@import url('sub2/lib.less')`.

It looks like each `url()` adds an extra `../` to its path.

Adding `url()` to entry.less doesn't change anything.
