### ISSUE TITLE
Default mixin arguments aren't recognized by selector guards

### ISSUE THREAD

**Issue by radium-v** [less/less.js#1613]
Howdy,

I'm trying to use a guarded selector inside a mixin with default vars, like so:

``` less
.a(@v: 0) {
    & when (@v >= 0) {
        prop: @v;
    }
}

.b {
    .a;
}
```

Changing `.b` will allow it to pass though:

``` less
.b {
    @v: 0;
    a;
}
```

Also, changing the mixin works:

``` less
.a(@v: 0) {
    .c(@v) when (@v >= 0) {
        prop: @v;
    }
    .c(@v);
}

.b {
    .a;
}
```

My expectation would be that example 1 would output the `prop` for `.b` by default, since the mixin sets its local var `@v: 0`, but it throws an undefined error.

There's not much documentation around the new features in v1.5.0, so I might be doing it wrong, but it feels like a bug. Thoughts?
