### ISSUE TITLE
nested :extend's

### ISSUE THREAD

**Issue by accerqueira** [less/less.js#1616]
I'm sorry if this is a double post, I looked around for other issues, found some related, but I don't think they are the same use case. Maybe I got the wrong idea on how :extend should work, but I expected this:

```
.css-ancestor .css-node {
  descendant: true;
}

.css-sibling + .css-node {
  sibling: true;
}

.less-ancestor:extend(.css-ancestor all) {
  .less-node:extend(.css-node all) {
    anything: true;
  }
}
```

to be compiled into this:

``` css
.css-ancestor .css-node,
.less-ancestor .css-node,
.css-ancestor .less-node, /* maybe without this selector, since we are talking about descendants of .less-ancestor */
.less-ancestor .less-node {
  descendant: true;
}
.css-sibling + .css-node,
.css-sibling + .less-node { /* maybe without this selector, for same reason as above */
  sibling: true;
}
.less-ancestor .less-node {
  anything: true;
}
```

this is what I got on less 1.5.0, and also [less2css.org](http://less2css.org/):

``` css
.css-ancestor .css-node,
.less-ancestor .css-node,
.css-ancestor .less-ancestor .less-node { /* hmmm, ok... */
  descendant: true;
}
.css-sibling + .css-node,
.css-sibling + .less-ancestor .less-node { /* I think this would be very odd */
  sibling: true;
}
.less-ancestor .less-node {
  anything: true;
}
```

A little more background on what I want...
I want to build a semantic layer, on top of something more general, like bootstrap.
Example:

```
form[role="search"]:extend(.input-group all) {
  input:extend(.form-control all) {
    & + span:extend(.input-group-btn all) {
      & > button:extend(.btn all, .btn-default all) {}
    }
  }
}
```

Hopefully, everything would behave like the form[role="search"] were in fact .input-group's, since that's what I'm saying they extend on.
All elements would see form[role="search"] descendant input's as .form-control's, and behave like so around them, and so on.
The HTML would be as clean as possible with this, no classes where we already know what we want from looking at the parents.

Is there another way to do this? Is this something other people would want and that would not break anything serious? I know you guys must be swamped on issues/requests. Although I'm not familiar with the inner workings of less, I would try to make this happen if it's something that would be accepted/useful.

Thanks for the great work on less!
