### ISSUE TITLE
Allow for pseudo-classes to be used as mixins

### ISSUE THREAD

**Issue by lencinhaus** [less/less.js#1630]
This would be particularly useful when importing an external less library that defines rules on pseudo-classes, an you want to mixin those rules in another class that will be applied to an element that doesn't support the pseudo-class.
See the following example to understand what I mean:

``` css
.class {
  rule: something;
  &:focus {
    color: red;
  }
}

.otherclass {
  .class:focus;
}
```

should compile to:

``` css
.class {
  rule: something;
}

.class:focus {
  color: red;
}

.otherclass {
  color: red;
}
```

I've happened to need this while working with Bootstrap 3: I was trying to mix in the rules from `.form-element:focus` into another class that I wanted to apply to a `div`, which doesn't support the `:focus` pseudo-class. So, I ended up manually copying all the rules from the bootstrap pseudo-class into my other class, which is a really poor solution in a less-based project.
