### ISSUE TITLE
Extending mixins

### ISSUE THREAD

**Issue by LaurentGoderre** [less/less.js#1650]
I"m trying to created nested extension but it is not working

Here is what I am trying that doesn't work:

``` less
.image() {
  background:url('image.jpg');
}

.image1():extend(.image){
  background-position: 0 -912px;
}

.image2():extend(.image){
  background-position: 0 -836px;
}

p {
  test:extend(.image1){}
}

div {
  span:extend(.image1){}
}

p{
  test2:extend(.image2){}
}
```

What does work is removing the parenthesis from the mixins but then they get written to the output.
