### ISSUE TITLE
Better hex to rgba conversation

### ISSUE THREAD

**Issue by panych** [less/less.js#1665]
__Feature request__: better hex to rgba conversation.
__Task__: compact way to convert HEX color with transparency to rgba

Now there are two ways to do that:
```Less
@base-color: #3399cc;

// now we need this color in 20% transparency, it will be rgba(51, 153, 204, 0.2)
// solution #1
body {
    color: rgba(red(@base-color), green(@base-color), blue(@base-color), 0.2);
    // color: rgba(51, 153, 204, 0.2);
}

// solution #2
span {
    color: fade(@base-color, 20%);
     // color: rgba(51, 153, 204, 0.2);
}
``` 

I think that `fade` function is not very appropriate here and we can create new function for this task or update `rgba`. Example:
```less
@base-color: #3399cc;

html {
    color: hex2rgba(@base-color, 0.2);
    // color: rgba(51, 153, 204, 0.2);
}
// or this way
body {
    color: rgba(@base-color, 0.2);
    // color: rgba(51, 153, 204, 0.2);
}
```
