### ISSUE TITLE
Option to overload selector block

### ISSUE THREAD

**Issue by kulor** [less/less.js#1671]
I thought it would be great if I could overload a selector that had been previously defined.

Given you had file a.less
```less
a {
    color: #aaa;
}

button {
    color: #aaa;
    border: 1px solid #aaa;
}
```

If I wanted to have a leaner override of just `button` but take all the other rules (polymorphism) I'd try and do something like this:

b.less
```less
@import "a.less";
button {
    color: #bbb;
}
```

Notice here that I don't care to take the `border` style or `a` tag.

While I understand that CSS is designed to allow for the cascade to override the entire selector (with specificity to boot), working with pre-processed CSS files should help us alleviate these cumbersome issues.

Maybe an `@overload` annotation could live inside the declaration to set the expected behaviour and override previous instances?
