### ISSUE TITLE
mix() returns wrong result for added colors.

### ISSUE THREAD

**Issue by dtinth** [less/less.js#1673]
When sending a color created from adding two colors together to the `mix()` function, 

This is reproducable in LESS 1.4.1 and 1.5.1.
### Test case 1

``` less
a {
  color: mix(#008 + #800, #FFF, 50%);
}
```

Expected result:

```
color: #c480c4;
```

Actual result:

```
color: #880088;
```
### Test case 2

``` less
@a: #222;      // #222
@b: @a + #224; // #446
@c: #888;      // #888

a {
  a: @a;
  b: @b;
  c: @c;
  d: mix(@b, @c, 50%); // should be #667
}
```

Expected result:

``` less
d: #666677
```

Actual result:

``` less
d: #444455
```
### Some more tests:

```
// These example should all equal #999

mix(#333, #fff, 50%) // #999999
mix(#222 + #111, #fff, 50%) // #333333
mix(#333, #eee + #111, 50%) // #FFFFFF
mix(#222 + #111, #eee + #111, 50%) // #999999
mix(#333 + #000, #fff + #000, 50%) // #999999
```
