### ISSUE TITLE
REQUEST: please add a remove()

### ISSUE THREAD

**Issue by stevenvachon** [less/less.js#1683]
This would be awesome for reducing bloat when compiling. For example, I sometimes prefer the look of a regular mixin over a parametric one, but have no use for them outside of compiling.

``` css
.border
{
    border: 1px solid black;
}

#something
{
    .border;
}

remove(.border);
```
