### ISSUE TITLE
parametric mixin issue

### ISSUE THREAD

**Issue by stevenvachon** [less/less.js#1684]
``` css
.transition (@transition)
{
    -moz-transition: @transition;
    -webkit-transition: @transition;
    transition: @transition;
}

#something
{
    .transition(color 1s);  /* works */
    .transition(color 1s, font-size 1s);    /* breaks */
}
```
