### ISSUE TITLE
LESS + GWT spectial escape

### ISSUE THREAD

**Issue by DemkaAge** [less/less.js#1690]
We use LESS in our GWT applications.
- *.less files -(compiler)> \* almost .css files 
-  almost *.css files -(gwt magic)> gwtCssBoundle

We need, for example, render (less): 

``` less
// @sprite 
.navBrowser {
    gwt-image: "navBrowserInactive";
    ...
    .borderRadius(2px);
}
```

to (css):

``` css
 @sprite 
.navBrowser {
    gwt-image: "navBrowserInactive";
    ...
}
```

Maybe something like `e("some text")` or `~"some text"` at the global level.
