### ISSUE TITLE
Comments don't compile correctly

### ISSUE THREAD

**Issue by rinh** [less/less.js#1726]
LESS code:

``` less
#namespace{
    /* comments */
    .do( @img-domain , @version ) {
       image : '@{img-domain}usage/index/r_x.png?v=@{version}';
    }
}

a{ 
    #namespace .do( 'http://123.com' , '123' );
}
```

Resulted Code:

``` less
#namespace {
  /* comments */
}
a {
  image: 'http://123.comusage/index/r_x.png?v=123';
}
```

Expected Code:

``` less
a {
  image: 'http://123.comusage/index/r_x.png?v=123';
}
```
