### ISSUE TITLE
Nested extend selectors don't output all combinations

### ISSUE THREAD

**Issue by chadly** [less/less.js#1729]
I'm using v1.5.1. I see a lot of issues logged around `extend` but I don't think this one is duplicated anywhere. Here is my less:

``` css
.thing {
    font-weight: bold;

    .thing-title {
        font-size: smaller;
    }
}

.thing-title {
    color:red;
}

section {
    &:extend(.thing all);

    h1 {
        &:extend(.thing-title all);
    }
}
```

What I want l the output to be is this:

``` css
.thing,
section {
    font-weight: bold;
}

.thing .thing-title,
section h1 {
    font-size: smaller;
}

.thing-title,
section h1 {
    color: red;
}
```

What is actually output is this:

``` css
.thing,
section {
    font-weight: bold;
}

.thing .thing-title,
section .thing-title,
.thing section h1 {
    font-size: smaller;
}

.thing-title,
section h1 {
    color: red;
}
```

Notice the `.thing section h1`. It never outputs a rule for just plain `section h1`. It seems it is missing the last combination of selectors when generating the css.
