### ISSUE TITLE
Property merging with different properties is broken

### ISSUE THREAD

**Issue by carlos22** [less/less.js#1742]
LESS Code

``` less
/* example: adapted demo from lesscss.org */
.a() {
  transform+: rotateX(30deg);
  background+: red;
}
.b {
  transform+: rotateY(20deg);
  background+: blue;
  .a();
}
```

Output

``` css
.b {
  transform: rotateY(20deg);
  background: blue, rotateX(30deg), red;
}
```

Expected output:

``` css
.b {
  transform: rotateY(20deg), rotateX(30deg);
  background: blue, red;
}
```

LESS Version: 1.5.1 release and 780bef6

It seems that the + 'operator' does not 'recognize' the name of the property. It just adds the values to the last property defined with a '+'. I think the way it behaves (even if it is as intended), it's pretty useless, especially for background and background-size where i would need it...

Live-Demo: http://codepen.io/anon/pen/ItdoC (not sure which version they use, but its 1.5.x, less2css.org still only supports 1.4)
