### ISSUE TITLE
Mixin parameteres used in guards on css selectors are considered undefined

### ISSUE THREAD

**Issue by carlos22** [less/less.js#1750]
Example 1

``` less
.mixin(@colWidth) {

  // ugly inner mixin (works)
  .hide() when (@colWidth <= 0) {
    .inMixinCls {
      dispaly: none;
    }
  } 
  .hide();

}

.mixin(0px);
```

CSS: 

``` css
.inMixinCls {
  dispaly: none;
}
```

Example 2:

``` less
.mixin(@colWidth) {

  // selector with guard (applies also to & when() ...)
  .clsWithGuard when (@colWidth <= 0) {
    dispaly: none;
  }

}

.mixin(0px);
```

Error

```
NameError: variable @colWidth is undefined in mixin-vars2.less on line 4, column 23:
3   // selector with guard (applies also to & when() ...)
4   .clsWithGuard when (@colWidth <= 0) {
5     dispaly: none;
```

I think example 2 should produce the same output as example 1?

Fun fact: Copy the variable into another in the current scope works.
Example: 

``` less
.mixin(@colWidth) {

  // class with guard (applies also go & when() ...
  @colWidth2: @colWidth;
  .clsWithGuard when (@colWidth2 <= 0) {
    dispaly: none;
  }

}

.mixin(0px);
```
