### ISSUE TITLE
Some question with debug the less file with chrome dev tools?

### ISSUE THREAD

**Issue by basecss** [less/less.js#1762]
I found to debug with `less` file, the `less` file line number mapping is incorrect in toolbar.

Here is an example, in my `less` file ( `demo.css` ) , has the follow code:

``` css
#wrap {
    width: 800px;
    height: 300px;
    background: #fff;
    #list {
        list-style: none;
        padding: 0;
        margin: 0;
        li {
            height: 50px;
            line-height: 50px;
            border-bottom: 1px dashed #ccc;
            font-size: 24px;
        }
    }
}
```

And `html` file.

``` html
<div id="wrap">
    <ul id="list">
        <li>Item...</li>
        ......
    </ul>
</div>
```

Then, I generate the `css` file and import in my page. Next, in my chrome checked the **Enable CSS source maps** option to debug the `less` file. I found after the `demo.less` line number always `1`. Even though I selected the `li` element, the `demo.less` file line number not changed to `9` ( in my example ).

As shown in Figure:

![image](https://f.cloud.github.com/assets/5274348/1808045/561fc94a-6d33-11e3-8386-86c99d9fde8b.png)

![image](https://f.cloud.github.com/assets/5274348/1808046/76e9443a-6d33-11e3-94d3-ff7098251eb0.png)

![image](https://f.cloud.github.com/assets/5274348/1808049/8fa3b906-6d33-11e3-90d1-393a39ba9b30.png)

When I click to view the `less` file, Always point the first line and highlight it.

![image](https://f.cloud.github.com/assets/5274348/1808052/e8384a96-6d33-11e3-8d43-6956bdd54617.png)

I think, the correct display should be：when I seleced the `#list` element, the line number should be 5，or I selected the `li` element, the line number should be `9` and so on ( in my example ).

Well. That is why the less file line number mapping inconsistencies.

Please forgive my poor English.
