### ISSUE TITLE
CSS3 saturate filter breaks CSS parsing entirely.

### ISSUE THREAD

**Issue by Redsandro** [less/less.js#1784]
Using this:

``` css
.someFakeId {
    -webkit-filter  : saturate(25%);
}
```

... will break CSS parsing entirely.

I see a reason for this is mentioned in #1299 (namely `saturate` is a reserved keyword), but it was solved in `1.4.1` and closed. (I cannot re-open someone else's issue.)

@lukeapage: 

> saturate now also fixed in 1.4.1 branch

I've got `lesscss.js` `LESS - Leaner CSS v1.4.1` here, and this is still a problem.
