### ISSUE TITLE
Interpolated class names cannot be used in :extend syntax

### ISSUE THREAD

**Issue by Craga89** [less/less.js#1787]
LESS cannot currently use the `:extend` syntax to extend styles which are applied using an "interpolated" selector. For example:

``` less
@className: test;

.@{className}{
  background-color: red;
}

.otherClass:extend(.test){}
```

Is this a bug? Or simply a side effect of the class name interpolation?
