### ISSUE TITLE
negative shade percentage converts hex colour to rgba

### ISSUE THREAD

**Issue by zanona** [less/less.js#1810]
I have noticed that this is happening:

``` css
@color: #269FEB;

body { color: shade(@color, -15%); }

/*Outputs*/
body {
  color: rgba(44, 183, 270, 0.9999999999999999);
}
```

which is a serious problem if you are dealing with IE8- or any other browser which doesn't support RGBA color specification.

When using an hexadecimal colour style by using the `shade` method, the same colour style would be expected back. However, this doesn't seem to happen when using positive values for the shade amount and it's also not applied to every negative values, but only some of them _(probably floating numbers)_
