### ISSUE TITLE
Error in compile Bootstrap 3 files within wrapper (lessc 1.6.1)

### ISSUE THREAD

**Issue by stepanselyuk** [less/less.js#1826]
I want to put all bootstrap styles in a wrapper. I do:

``` less
.bootstrap-wrapper {
  @import "bootstrap.less";
}
```

After import rows and colums don't working correctly. In compiled css-file I found a bug:

``` css
.bootstrap-wrapper .col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
  position: relative;
  min-height: 1px;
  padding-left: 15px;
  padding-right: 15px;
}

.bootstrap-wrapper .col-xs-1, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9, .col-xs-10, .col-xs-11, .col-xs-12 {
  float: left;
}
```

and may be others..

The right variant wrap all elements...:

``` css
".bootstrap-wrapper .col-xs-1, .bootstrap-wrapper .col-sm-1, .bootstrap-wrapper .col-md-1, .bootstrap-wrapper  .col-lg-1, " end etc.
```
