### ISSUE TITLE
Extend within (reference) imported files.

### ISSUE THREAD

**Issue by donaldpipowitch** [less/less.js#1851]
Say I have three files:
````
// fileA.less
.test-a {
  color: red;
}
````
````
// fileB.less
@import (reference) "fileA";

.test-b {
  background-color: green;
  &:extend(.test-a all);
}
````
````
// fileC.less
@import (reference) "fileB";

.test-c {
  &:extend(.test-b all);
}
````

What I expect, if I compile `fileC.less` (comments only to aid the understanding):
````
// .test-a,
// .test-b,
.test-c {
  color: red;
}

// .test-b,
.test-c {
  background-color: green;
}
````

What I get:
````
.test-b,
.test-c {
  color: red;
}
.test-c {
  background-color: green;
}
````

`.test-b` leaks in!

**Comment by assadtony** [comment]
Any updates on this issue? :)

**Comment by SomMeri** [comment]
This should be fixed by #2729 .

**Comment by donaldpipowitch** [comment]
Just wow!

**Comment by SomMeri** [comment]
Re-opening, because it now compiles into 
````less
.test-c {
  background-color: green;
}
````

instead of 
````less
.test-c {
  color: red;
}

.test-c {
  background-color: green;
}
````
