### ISSUE TITLE
Mixin included in a class / referenced file outputs CSS regardless

### ISSUE THREAD

**Issue by mikedidthis** [less/less.js#1885]
Firstly thank you for continuing the effort with less.js! 

I seem to be struggling with mixins inside a class pulled from a reference file.

**Reference File**

`@import (reference) "base/_buttons";`

``` LESS
.button-small {
    background: red;
    border-radius: 3px;
    .font-size(16,24):
}
```

**Usage**

``` LESS
.pages li a {
    &:extend( .button-small );
}
```

**Output**

``` CSS
.button-small,
.pages li a {
    font-size: 16px;
    line-height: 24px;
}
.pages li a {
    background: red;
    border-radius: 3px;
}
```

I expect the rules would be broken over two groups of properties. However, I didn't expect `.button-small` to be included.

If I don't reference `.button-small` at all, the output is as follows:

**Output**

``` CSS
.button-small {
    font-size: 16px;
    line-height: 24px;
}
```

Am I doing something wrong? Are reference files for styles only? Is this a bug?

Any help would be appreciated.
