### ISSUE TITLE
duplicate CSS emitted when including mixin when a same-named class exists

### ISSUE THREAD

**Issue by cvrebert** [less/less.js#1886]
I apologize in advance in the likely event that a relevant issue already exists for this.

``` bash
$ lessc --version
lessc 1.6.3 (LESS Compiler) [JavaScript]
```

Less source file:

``` scss
// Mixin
.clearfix() {
  &:before,
  &:after {
    content: " "; // 1
    display: table; // 2
  }
  &:after {
    clear: both;
  }
}

// Concrete class for the mixin
// (Imagine that the concrete class is optional; some folks will just want the mixin.)
.clearfix {
  .clearfix();
}

// Trying to use the mixin elsewhere
// (Imagine that we can't use `:extend` due to media queries;
// http://lesscss.org/features/#extend-feature-scoping-extend-inside-media )
.foobar {
  .clearfix();
}
```

Output (with comment added):

``` css
.clearfix:before,
.clearfix:after {
  content: " ";
  display: table;
}
.clearfix:after {
  clear: both;
}
.foobar:before,
.foobar:after {
  content: " ";
  display: table;
}
.foobar:after {
  clear: both;
}
.foobar:before, // DUPLICATION!
.foobar:after {
  content: " ";
  display: table;
}
.foobar:after {
  clear: both;
}
```

X-Ref: https://github.com/twbs/bootstrap/pull/12756
