### ISSUE TITLE
desaturate doesn't work correctly with HSV-created colors

### ISSUE THREAD

**Issue by BrianBelhumeur** [less/less.js#1891]
In using 'desaturate' on a color created with hsv(), I find the color that comes out is not what I expect. In the example below, I expect the values for "color" and "background-color" to be identical because the manual assembly of the new hsv() values in "background-color" should be exactly what desaturate() is supposed to be doing in "color". Perhaps Less is running desaturate() as hsl() instead of hsv()?

LESS:

``` less
.colortest(@n, @i: 0) when (@i < @n) {
    @color: hsv(259, 30%, 100%);
    @step: 5%;
    @amount: (@step * @i);

    .rule {
        color: desaturate(@color, @amount);
        background-color: hsv(hsvhue(@color), (hsvsaturation(@color) - @amount), hsvvalue(@color));
    }

    .colortest(@n, (@i + 1));
}
.colortest(5);
```

OUTPUT CSS:

``` css
.rule {
  color: #cbb3ff;
  background-color: #cbb3ff;
}
.rule {
  color: #cbb4fd;
  background-color: #d3bfff;
}
.rule {
  color: #ccb6fb;
  background-color: #dcccff;
}
.rule {
  color: #cdb8f9;
  background-color: #e5d9ff;
}
.rule {
  color: #cebaf7;
  background-color: #eee6ff;
}
```
