### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by ForbesLindesay** [less/less.js#1898]
I've found what I think is a race condition in less.  Unfortunately the minimum example I can come up with involves 5 files.  With the `lessc` command line it then outputs one of two different things at random.  If you add the sync-imports flag, the problem is mitigated.
## Inputs

index.less

``` less
@import "indirect-a.less";
@import "indirect-b.less";

body {
  color: @color;
}
```

indirect-a.less

``` less
@import "variables.less";
@import "override.less";
```

indirect-b.less

``` less
@import "variables.less";
```

variables.less

``` less
@color: red;
```

override.less

``` less
@color: black;
```
## Command

```
lessc index.less
```
## Output

One of the following two options is output at random:

Aprox 95% of the time:

``` css
body {
  color: #000000;
}
```

Aprox 5% of the time:

``` css
body {
  color: #ff0000;
}
```

This occurs with the latest version in npm and with the version currently in the GitHub repo.
