### ISSUE TITLE
Variables: Recursive variables tolerance

### ISSUE THREAD

**Issue by am11** [less/less.js#1911]
With LESS:

``` scss
@a: 1;
@a: @a + 2;

selector {
    property: @a;
}
```

gives:

> NameError: Recursive variable definition for @a.

While in SCSS:

``` scss
$a: 1;
$a: $a + 2;

selector {
    property: $a;
}
```

generates:

``` css
selector {
    property: 3;
}
```

However, without `$a: 1;`, it gives compilation error.

Wouldn't it be better to make LESS behave like SCSS in that regard?
