### ISSUE TITLE
Numbers rounded to 8 precision at 66th line of less file for apparently no good reason

### ISSUE THREAD

**Issue by elgreg** [less/less.js#1924]
OK, this is a really strange bug. For some reason, sometimes numbers in my less are being rounded to -0.00000001. For example, when I run the code below through lessc, the 66th line should be converted to:

``` css
.tasks {
  margin: -384px -144px;
}
```

But instead it comes out as this in versions 1.6.2 and up:

``` css
.tasks {
  margin: -384px -143.99999999px;
}
```

I believe it has to do with the rounding introduced in v1.6.2 (commit 52ba472bb76089e5b2c1d079a29e70cb99f23b15) because of the number of 9s and because it doesn't happen if I use v1.6.1.

Steps to repeat:
1. Copy the less code below and put in a test.less file
2. Run v1.6.2 lessc on it

``` bash
npm install -g less@1.6.2
lessc test.less   
```

Result: weird -143.999999px on line 199

Expected result: -144px on line 199

I tried playing with whitespace, comments, changing names of classes, etc. None of it had any effect. If you have more and more declarations it will start to screw up in more places in other places (see test2.less)

Strangely, if I add in some lines with positive numbers before .tasks there at the bottom, it will just screw up .tasks later. If I add another line with negative numbers, then .tasks is fine, but that new line with negative numbers gets screwed up. 

I played around a lot trying to figure out why it was happening and am happy to answer for things I've tried. The fact that downgrading less works isn't really helping since the version of grunt-less that I'm using keeps install less v1.7.0 which still has this issue.

test.less

``` less
.fast-backward      { background-position: -216px -72px; }
.backward           { background-position: -240px -72px; }
.play               { background-position: -264px -72px; }
.pause              { background-position: -288px -72px; }
.stop               { background-position: -312px -72px; }
.forward            { background-position: -336px -72px; }
.fast-forward       { background-position: -360px -72px; }
.step-forward       { background-position: -384px -72px; }
.eject              { background-position: -408px -72px; }
.chevron-left       { background-position: -432px -72px; }
.chevron-right      { background-position: -456px -72px; }
.plus               { background-position: -408px -96px; }
.plus-sign          { background-position: 0  -96px; }
.minus-sign         { background-position: -24px  -96px; }
.remove-sign        { background-position: -48px  -96px; }
.ok-sign            { background-position: -72px  -96px; }
.question-sign      { background-position: -96px  -96px; }
.info-sign          { background-position: -120px -96px; }
.screenshot         { background-position: -144px -96px; }
.remove-circle      { background-position: -168px -96px; }
.ok-circle          { background-position: -192px -96px; }
.ban-circle         { background-position: -216px -96px; }
.arrow-left         { background-position: -240px -96px; }
.arrow-right        { background-position: -264px -96px; }
.arrow-up           { background-position: -289px -96px; } // 1px off
.arrow-down         { background-position: -312px -96px; }
.share-alt          { background-position: -336px -96px; }
.resize-full        { background-position: -360px -96px; }
.resize-small       { background-position: -384px -96px; }
.minus              { background-position: -433px -96px; }
.asterisk           { background-position: -456px -96px; }
.exclamation-sign   { background-position: 0      -120px; }
.gift               { background-position: -24px  -120px; }
.leaf               { background-position: -48px  -120px; }
.fire               { background-position: -72px  -120px; }
.eye-open           { background-position: -96px  -120px; }
.eye-close          { background-position: -120px -120px; }
.warning-sign       { background-position: -144px -120px; }
.plane              { background-position: -168px -120px; }
.calendar           { background-position: -192px -120px; }
.random             { background-position: -216px -120px; width: 16px; }
.comment            { background-position: -240px -120px; }
.magnet             { background-position: -264px -120px; }
.chevron-up         { background-position: -288px -120px; }
.chevron-down       { background-position: -313px -119px; } // 1px, 1px off
.retweet            { background-position: -336px -120px; }
.shopping-cart      { background-position: -360px -120px; }
.folder-close       { background-position: -384px -120px; width: 16px; }
.folder-open        { background-position: -408px -120px; width: 16px; }
.resize-vertical    { background-position: -432px -119px; } // 1px, 1px off
.resize-horizontal  { background-position: -456px -118px; } // 1px, 2px off
.hdd                     { background-position: 0      -144px; }
.bullhorn                { background-position: -24px  -144px; }
.bell                    { background-position: -48px  -144px; }
.certificate             { background-position: -72px  -144px; }
.thumbs-up               { background-position: -96px  -144px; }
.thumbs-down             { background-position: -120px -144px; }
.hand-right              { background-position: -144px -144px; }
.hand-left               { background-position: -168px -144px; }
.hand-up                 { background-position: -192px -144px; }
.hand-down               { background-position: -216px -144px; }
.circle-arrow-right      { background-position: -240px -144px; }
.circle-arrow-left       { background-position: -264px -144px; }
.circle-arrow-up         { background-position: -288px -144px; }
.circle-arrow-down       { background-position: -312px -144px;}
.tasks                   { margin: -384px -144px; }    // this line will mess up
.circle-arrow-down-tester       { background-position: -312px -144px;}
```

test2.less

``` less
.icon-send               { background-position: -91px  -1px; } // Raise 1px
.icon-star               { background-position: -120px 0; }
.icon-star-empty         { background-position: -144px 0; }
.icon-user               { background-position: -168px 0; }
.icon-film               { background-position: -192px 0; }
.icon-th-large           { background-position: -216px 0; }
.icon-th                 { background-position: -240px 0; }
.icon-th-list            { background-position: -264px 0; }
.icon-ok                 { background-position: -288px 0; }
.icon-remove             { background-position: -312px 0; }
.icon-zoom-in            { background-position: -336px 0; }
.icon-zoom-out           { background-position: -360px 0; }
.icon-off                { background-position: -384px 0; }
.icon-signal             { background-position: -408px 0; }
.icon-cog                { background-position: -432px 0; }
.icon-trash              { background-position: -456px 0; }

.icon-home               { background-position: 0      -24px; }
.icon-file               { background-position: -24px  -24px; }
.icon-time               { background-position: -48px  -24px; }
.icon-road               { background-position: -72px  -24px; }
.icon-download-alt       { background-position: -96px  -24px; }
.icon-download           { background-position: -120px -24px; }
.icon-upload             { background-position: -144px -24px; }
.icon-inbox              { background-position: -168px -24px; }
.icon-play-circle        { background-position: -192px -24px; }
.icon-repeat             { background-position: -216px -24px; }
.icon-refresh            { background-position: -240px -24px; }
.icon-list-alt           { background-position: -264px -24px; }
.icon-lock               { background-position: -287px -24px; } // 1px off
.icon-flag               { background-position: -312px -24px; }
.icon-headphones         { background-position: -336px -24px; }
.icon-volume-off         { background-position: -360px -24px; }
.icon-volume-down        { background-position: -384px -24px; }
.icon-volume-up          { background-position: -408px -24px; }
.icon-qrcode             { background-position: -432px -24px; }
.icon-barcode            { background-position: -456px -24px; }

.icon-tag                { background-position: 0      -48px; }
.icon-tags               { background-position: -25px  -48px; } // 1px off
.icon-book               { background-position: -48px  -48px; }
.icon-bookmark           { background-position: -72px  -48px; }
.icon-print              { background-position: -96px  -48px; }
.icon-camera             { background-position: -120px -48px; }
.icon-font               { background-position: -144px -48px; }
.icon-bold               { background-position: -167px -48px; } // 1px off
.icon-italic             { background-position: -192px -48px; }
.icon-text-height        { background-position: -216px -48px; }
.icon-text-width         { background-position: -240px -48px; }
.icon-align-left         { background-position: -264px -48px; }
.icon-align-center       { background-position: -288px -48px; }
.icon-align-right        { background-position: -312px -48px; }
.icon-align-justify      { background-position: -336px -48px; }
.icon-list               { background-position: -360px -48px; }
.icon-indent-left        { background-position: -384px -48px; }
.icon-indent-right       { background-position: -408px -48px; }
.icon-facetime-video     { background-position: -432px -48px; }
.icon-picture            { background-position: -456px -48px; }

.icon-pencil             { background-position: 0      -72px; }
.icon-map-marker         { background-position: -24px  -72px; }
.icon-adjust             { background-position: -48px  -72px; }
.icon-tint               { background-position: -72px  -72px; }
.icon-edit               { background-position: -96px  -72px; }
.icon-share              { background-position: -120px -72px; }
.icon-check              { background-position: -144px -72px; }
.icon-move               { background-position: -168px -72px; }
.icon-step-backward      { background-position: -192px -72px; }
.icon-fast-backward      { background-position: -216px -72px; }
.icon-backward           { background-position: -240px -72px; }
.icon-play               { background-position: -264px -72px; }
.icon-pause              { background-position: -288px -72px; }
.icon-stop               { background-position: -312px -72px; }
.icon-forward            { background-position: -336px -72px; }
.icon-fast-forward       { background-position: -360px -72px; }
.icon-step-forward       { background-position: -384px -72px; }
.icon-eject              { background-position: -408px -72px; }
.icon-chevron-left       { background-position: -432px -72px; }
.icon-chevron-right      { background-position: -456px -72px; }

.icon-plus               { background-position: -408px -96px; } // not compiling?
.icon-plus-sign          { background-position: 0  -96px; }
.icon-minus-sign         { background-position: -24px  -96px; }
.icon-remove-sign        { background-position: -48px  -96px; }
.icon-ok-sign            { background-position: -72px  -96px; }
.icon-question-sign      { background-position: -96px  -96px; }
.icon-info-sign          { background-position: -120px -96px; }
.icon-screenshot         { background-position: -144px -96px; }
.icon-remove-circle      { background-position: -168px -96px; }
.icon-ok-circle          { background-position: -192px -96px; }
.icon-ban-circle         { background-position: -216px -96px; }
.icon-arrow-left         { background-position: -240px -96px; }
.icon-arrow-right        { background-position: -264px -96px; }
.icon-arrow-up           { background-position: -289px -96px; } // 1px off
.icon-arrow-down         { background-position: -312px -96px; }
.icon-share-alt          { background-position: -336px -96px; }
.icon-resize-full        { background-position: -360px -96px; }
.icon-resize-small       { background-position: -384px -96px; }
.icon-minus              { background-position: -433px -96px; }
.icon-asterisk           { background-position: -456px -96px; }

.icon-exclamation-sign   { background-position: 0      -120px; }
.icon-gift               { background-position: -24px  -120px; }
.icon-leaf               { background-position: -48px  -120px; }
.icon-fire               { background-position: -72px  -120px; }
.icon-eye-open           { background-position: -96px  -120px; }
.icon-eye-close          { background-position: -120px -120px; }
.icon-warning-sign       { background-position: -144px -120px; }
.icon-plane              { background-position: -168px -120px; }
.icon-calendar           { background-position: -192px -120px; }
.icon-random             { background-position: -216px -120px; width: 16px; }
.icon-comment            { background-position: -240px -120px; }
.icon-magnet             { background-position: -264px -120px; }
.icon-chevron-up         { background-position: -288px -120px; }
.icon-chevron-down       { background-position: -313px -119px; } // 1px, 1px off
.icon-retweet            { background-position: -336px -120px; }
.icon-shopping-cart      { background-position: -360px -120px; }
.icon-folder-close       { background-position: -384px -120px; width: 16px; }
.icon-folder-open        { background-position: -408px -120px; width: 16px; }
.icon-resize-vertical    { background-position: -432px -119px; } // 1px, 1px off
.icon-resize-horizontal  { background-position: -456px -118px; } // 1px, 2px off

.icon-hdd                     { background-position: 0      -144px; }
.icon-bullhorn                { background-position: -24px  -144px; }
.icon-bell                    { background-position: -48px  -144px; }
.icon-certificate             { background-position: -72px  -144px; }
.icon-thumbs-up               { background-position: -96px  -144px; }
.icon-thumbs-down             { background-position: -120px -144px; }
.icon-hand-right              { background-position: -144px -144px; }
.icon-hand-left               { background-position: -168px -144px; }
.icon-hand-up                 { background-position: -192px -144px; }
.icon-hand-down               { background-position: -216px -144px; }
.icon-circle-arrow-right      { background-position: -240px -144px; }
.icon-circle-arrow-left       { background-position: -264px -144px; }
.icon-circle-arrow-up         { background-position: -288px -144px; }
.icon-circle-arrow-down       { background-position: -312px -144px; }
.icon-globe                   { background-position: -336px -144px; }
.icon-wrench                  { background-position: -360px -144px; }
.icon-tasks                   { background-position: -384px -144px; }
.icon-filter                  { background-position: -408px -144px; }
.icon-briefcase               { background-position: -432px -144px; }
.icon-fullscreen              { background-position: -456px -144px; }
```
