### ISSUE TITLE
Nesting @media queries does not work with @import

### ISSUE THREAD

**Issue by Elijen** [less/less.js#1927]
We are importing mobile stylesheets like this:

``` css
//Mobile design
@media (max-width: @mobile-width) {
    @import "mobile.less";
}
```

Now I would like to use another media query inside of the mobile.less like this:

``` css
@media (max-height: 460px) {
    .something { display: none; }
}
```

I am getting parse error, but something like this should be generated instead:

``` css
@media (max-width: 460px) and (max-height: 460px) {
   .something { display: none; }
}
```

Note that if I paste the code directly instead of using @import statement it seems to work without errors.
