### ISSUE TITLE
Import with (reference) won't print a mixin that's not inside an element/class (@rule)

### ISSUE THREAD

**Issue by guill3m** [less/less.js#1932]
**Problem:**
Using the `(reference)` option in an `@import` that declares a mixin for `@keyframes` (is not printed inside a class or element, goes directly to the root) won't print the expected `@keyframes` rules.
Works as expected when not adding the `(reference)` option to the `@import`.

**Version of LESS:**
`1.7.0`
Using both CodeKit 2 and Assetic (with the `lessc` compiler) to compile it.

**Example:**
As a zip file: http://cl.ly/2M1s0J2w3T24

And here in the open (both examples are the same, except that the zipped one does have all the vendor prefixes):
```css
/* css3-mixins.less */
.keyframes(@name, @rules) {
  /* using only one vendor prefix for simplicity of the example */
  @-webkit-keyframes @name {
    @rules();
  }
  @keyframes @name {
    @rules();
  }
}
```

```css
/* header.less */
.keyframes(fade-in, {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
});

#logo {
  animation: fade-in 1.25s ease forwards; /* not using vendor prefixes for simplicity of the example */
}
```

```css
/* app.less */
@import (reference) "css3-mixins.less";
@import "header.less";
```

Expected output:
```css
/* app.css */
@-webkit-keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
#logo {
  animation: fade-in 1.25s ease forwards;
}
```

Actual output:
```css
/* app.css */
#logo {
  animation: fade-in 1.25s ease forwards;
}
```
