### ISSUE TITLE
Mixins with media queries using import reference produce invalid CSS

### ISSUE THREAD

**Issue by danhart** [less/less.js#1962]
If you mixin a media query to root (no selector) strange things occur. Also no error is raised.

base.less
```css
@import (reference) "reference";
.test1;
.test2;
```

reference.less
```css
.test1 {
    @media print {
        color: blue;
    }
}

.test2 {
    .nested {
        @media print {
            color: pink;
        }
    }
}
```

Output:
```css
@media print {
  color: blue;
}
```

`.test1` produces invalid CSS, `.test2` produces nothing at all! Tested in 1.7.0.
