### ISSUE TITLE
When using an @import (reference), mixins that contain an & selector get added to the compiled output improperly

### ISSUE THREAD

**Issue by bcullman** [less/less.js#1968]
When I import a less file with the (reference) directive, I expect to see no CSS output from that file. 

However, I am seeing content being output from the imported file when a mixin contains an & selector.

__mixin.less__
```less
.mixin-no-parent-selector() {
  background-color: red;
}
.mixin-with-parent-selector() {
  &:first-child{ //  USING AN & SELECTOR HERE
    background-color: blue;
 }
}
```
__less-for-reference.less__
```less
.container-1 {
   .mixin-no-parent-selector();
}
.container-2{
   .mixin-with-parent-selector()
}
```

__style.less__
```less
/*!
 * styles.less
 */
@import "mixin.less";
@import (reference) "less-for-reference.less";
```

__Expected Output__
```css
/*!
 * styles.less
 */
```

__Actual Output__
```css
/*!
 * styles.less
 */

.container-2:first-child{
    background-color: blue;
}
```
