### ISSUE TITLE
SourceMap configs is confusing when I use a web server for HTML

### ISSUE THREAD

**Issue by tiye** [less/less.js#1985]
Here's my files for demo:

```
➤➤ tree
.
├── css
│   ├── main.css
│   └── main.css.map
├── index.html
└── less
    └── main.less

2 directories, 4 files

➤➤ cat less/main.less
body {
  margin: 0px;
}

➤➤ cat index.html
<link rel="stylesheet" type="text/css" href="css/main.css">
```

And I config Nginx file server's `root` to project root, and visit by `http://drafts/index.html` .
### Command with SourceMap(failed)

First I run this to generate CSS and SourceMap file:

``` bash
lessc less/main.less css/main.css --source-map
```

CSS file is:

``` css
body {
  margin: 0px;
}
/*# sourceMappingURL=main.css.map */
```

`css/main.css.map` look like this:

``` json
{
  "version": 3,
  "file": "css/main.css",
  "sources": [
    "main.less"
  ],
  "names": [],
  "mappings": "AACA;EACE,WAAA"
}
```

In the browser, I got this for the mapped `.less` file:
`http://drafts/css/main.less`
It's the wrong path.
### Command adds `--source-map-basepath`(failed)

The I add basepath here, which points to my project path:

``` bash
lessc less/main.less css/main.css --source-map \
  --source-map-basepath=/Users/chen/Drafts/css/sourcemap
```

``` css
body {
  margin: 0px;
}
/*# sourceMappingURL=main.css.map */
```

``` json
{
  "version": 3,
  "file": "css/main.css",
  "sources": [
    "less/main.less"
  ],
  "names": [],
  "mappings": "AACA;EACE,WAAA"
}
```

Also, it's wrong:
`http://drafts/css/less/main.less`
### Command with more..(right)

After a long while I found this:

``` bash
lessc less/main.less css/main.css \
  --source-map=css/main.css.map \
  --source-map-basepath=/Users/chen/Drafts/css/sourcemap \
  --source-map-rootpath=../
```

``` css
body {
  margin: 0px;
}
/*# sourceMappingURL=../css/main.css.map */
```

``` json
{
  "version": 3,
  "file": "css/main.css",
  "sources": ["../less/main.less"],
  "names": [],
  "mappings": "AACA;EACE,WAAA"
}
```

And finally it's working now..

But as I see, it's a common case that people debug LESS with a Web server.
Is that a bug, or can we make it simpler to config?
