### ISSUE TITLE
Equality check on strings seems off

### ISSUE THREAD

**Issue by roelvanduijnhoven** [less/less.js#1992]
Assume the following sniplets:

``` less
@quotes: 'quotes';

p when (@quotes = 'quotes') {
  color: single-quotes;
}

p when (@quotes = "quotes") { // does not hold
  color: double-quotes;
}
```

``` less
@var: 'light\2D bown';

p when (@var = 'light\2D bown') {
  color: escaped;
}

p when (@var = 'light-bown') { // does not hold
  color: unescaped;
}
```

I would expect all guards to hold. However this is not the case. Apparantly:
- It matters whether a string uses single or double quotes
- Escape characters that are valid in CSS (`\2D`) are not understood

Is this known behaviour (I failed to find anything)?
