### ISSUE TITLE
String interpolation does not properly escape

### ISSUE THREAD

**Issue by roelvanduijnhoven** [less/less.js#1993]
While commenting on #1992 I found another bug. This bug is more serious because one can produce invalid CSS with it.

``` less
@bla: 'dsfs"dsf';

div {
  color: "@{bla}";
} 
```

Or can insert his own CSS rules:

``` less
@bla: 'dsfs";} * { display: none; } div { color: "dsf';

div {
  color: "@{bla}";
} 
```

I guess the later _could_ be abused to insert IE's `behavior:url(script.htc);` or Firefox's `-moz-binding: url(script.xml#mycode);` into the CSS.

The fix is obviously to escape the double quote or replace it with a hexadecimal representation.
