### ISSUE TITLE
Less compiler badly replaces quotes with --clean-css option

### ISSUE THREAD

**Issue by honca** [less/less.js#1996]
Hi,

I have found a way how to use a PHP code in LESS code using e() function. But when I compile this code typing command lessc --clean-css I get unusable result.
Here is the LESS example:

``` css
@BASE_URL: e("<?php echo get_path('project'); ?>");
@IMG_BASE_URL: "@{BASE_URL}/image";

header
{
    background: #377D23 url("@{IMG_BASE_URL}/layout/header-background.2.png") no-repeat center top;
    height: 40px;
    width: 100%;
    z-index: 101;
    background-size: 290px 40px;
    box-shadow: 0 -10px 10px -10px #555555 inset;
}
header.a
{
    background-color: #AE7C4B;
}
header.b
{
    background-color: #927726;
}
```

The current ouput is:

``` css
header{background:#377d23 url("<?php echo get_path('project");?>/image/layout/header-background.2.png") no-repeat center top;
  height: 40px;
  width: 100%;
  z-index: 101;
  background-size: 290px 40px;
  box-shadow: 0 -10px 10px -10px #555555 inset;
}
header.a {
  background-color: #AE7C4B;
}
header.b {
  background-color: #927726;
}
```

But I expect the following output:

``` css
header{background:#377d23 url("<?php echo get_path('project');?>/image/layout/header-background.2.png") no-repeat center top;height:40px;width:100%;z-index:101;background-size:290px 40px;box-shadow:0 -10px 10px -10px #555 inset}header.a{background-color:#AE7C4B}header.b{background-color:#927726}
```

The difference between these output snippets is that in the first one is the string project quoted on the left side with single quote and on the right side is closed up by double quote. But CSS property url uses double quotes for both sides. Compiler seems to have a problem to recognize it, terminates the compression and the rest of code outputs uncompressed. I wonder why the compiler replaces right single quote to double quote?

I use Ubuntu 13.10, lessc 1.7.0.

When I paste this example to the lesstester.com form the output seems to be correct and maybe the bug will be in lessc if so. 

Thanks for your response..
Honca
