### ISSUE TITLE
Ubuntu 14.04 lessc not compiling

### ISSUE THREAD

**Issue by RedactedProfile** [less/less.js#1997]
$ sudo apt-get install nodejs npm 
$ sudo npm install -g less
$ whereis lessc
      lessc: /usr/local/bin/lessc
$ cd /var/www/test
$ lessc test.less > test.css

test.less

``` less
@white: #fff;

#white-box {
  color: @white;
}
```

test.css output:

``` css

```

Empty.

I'm not a less expert by any means, but I'm pretty sure this worked before.

Am I doing anything wrong? Or is this an issue with the version found in the current NPM repo?
