### ISSUE TITLE
how to avoid color name be translated into color value?

### ISSUE THREAD

**Issue by calidion** [less/less.js#2018]
``` Less
.theme-chooser(@c0, @c1, @c3) {
  span.theme-chooser-@{c3} {
    background-color: @c1;
    color: @c0;
    height: 10px;
    width: 20px;
    cursor: pointer;
    border: 2px solid #c4c4c4;
    display: inline-block;
  }
  span.active.theme-chooser-@{c3} {
    background-color: @c0;
    color: @c1;
    border: 2px solid #F4BD13;
  }
}
.theme-chooser(#a9a9a9, #d8d8d8, gray);
```

will result in:

``` Less
span.theme-chooser-#808080 {
  background-color: #d8d8d8;
  color: #a9a9a9;
  height: 10px;
  width: 20px;
  cursor: pointer;
  border: 2px solid #c4c4c4;
  display: inline-block;
}
span.active.theme-chooser-#808080 {
  background-color: #a9a9a9;
  color: #d8d8d8;
  border: 2px solid #F4BD13;
}
```

but i want 

``` Less
span.theme-chooser-gray {
  background-color: #d8d8d8;
  color: #a9a9a9;
  height: 10px;
  width: 20px;
  cursor: pointer;
  border: 2px solid #c4c4c4;
  display: inline-block;
}
span.active.theme-chooser-gray {
  background-color: #a9a9a9;
  color: #d8d8d8;
  border: 2px solid #F4BD13;
}
```
