### ISSUE TITLE
compile error – &:not(&)

### ISSUE THREAD

**Issue by kovchiy** [less/less.js#2026]
```css
.foo {
    &:not(&_bar) {
        color:red;
    }
}
```

compiled to:

```css
.foo:not(&_bar) {
    color: red;
}
```
