### ISSUE TITLE
compile error – &-bar:extend(&)

### ISSUE THREAD

**Issue by kovchiy** [less/less.js#2027]
``` css
.foo {
  font-size:10px;
    &-bar:extend(&) {
    color:red;
  }
}
```

compiled to:

``` css
.foo {
  font-size: 10px;
}
.foo-bar {
  color: red;
}
```
