### ISSUE TITLE
Property merging doesn't work in @font-face

### ISSUE THREAD

**Issue by laughinghan** [less/less.js#2035]
``` css
.font-face {
  src+: a;
  src+: b;
}
@font-face {
  src+: a;
  src+: b;
}
```

results in

``` css
.font-face {
  src: a, b;
}
@font-face {
  src: a;
  src: b;
}
```

(I tried using less2css.org assuming it was like JSBin or JSFiddle, but I couldn't figure out how to save my snippet as a shareable URL, so I'm just pasting it here, is that what is meant by "Include a live example. Please use less2css.org for sharing your isolated test cases."? That's really confusing)
