### ISSUE TITLE
Detached ruleset unlocked from namespaced mixin does not see its namespace scope

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#2038]
I defined a detached ruleset inside a namespaced mixin. The ruleset is unable to see variables defined in its outer namespace.

Less:

``` css
#namespace {
  @variable: in-namespace;
  .unlocker {
    @detached-ruleset: { property: @variable; };
  }
}
#namespace > .unlocker();

#detached-ruleset {
  @detached-ruleset();
}
```

actual output:

```
NameError: variable @variable is undefined in test.less on line 4, column 36:
3   .unlocker {
4     @detached-ruleset: { property: @variable; };
5   }
```

expected output:

```
#detached-ruleset {
  property: in-namespace;
}

```

Edit: I use node.js with lessc 1.7.0 (LESS Compiler) [JavaScript]
Edit 2: this issue is probably related to #2039
