### ISSUE TITLE
Scoping of mixin unlocked from namespaced mixin does not work properly

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#2039]
This is probably related to #2038 

1.) Mixin unlocked from namespaced mixin does not see callers variables.

Less:

``` css
#namespace {
  .unlocker {
    .mixin { 
      property: @variable; 
    }
  }
}
#namespace > .unlocker();

#mixin {
  @variable: in-caller;
  .mixin();
}
```

actual output:

```
SyntaxError: variable @variable is undefined in test.less on line 8, column 1:
7 }
8 #namespace > .unlocker();
9
```

expected output:

``` css
#mixin {
  property: in-caller; 
}
```

2.)  I defined a detached ruleset inside a namespaced mixin. The ruleset is unable to see variables defined in its outer namespace (the #2038 is the same except with detached rulesets).

``` css
#namespace {
  @variable: in-namespace;
  .unlocker {
    .mixin { 
      property: @variable; 
    }
  }
}
#namespace > .unlocker();

#mixin {
  @variable: another;
  .mixin();
}
```

actual output:

```
SyntaxError: variable @variable is undefined in test.less on line 9, column 1:
8 }
9 #namespace > .unlocker();
10
```

expected output:

```
#mixin {
  property: in-namespace; 
}
```

I use node.js with lessc 1.7.0 (LESS Compiler) [JavaScript]
