### ISSUE TITLE
Using @import (reference) with mixins with & selectors output incorrect css

### ISSUE THREAD

**Issue by eamodio** [less/less.js#2047]
First off this might be a dup of https://github.com/less/less.js/issues/1968 or https://github.com/less/less.js/issues/1646 and if so I apologize, but I think this is slightly different than the other 2 and possibly much worse.

Say I have 2 files:
#### ref.less

``` css
.mixin(@selector) {
  &@{selector}, .bar @{selector} {
    color: #fff;
    &:hover {
      color: #000;
    }
  }
}
```
#### root.less

``` css
//@import "ref.less";
@import (reference) "ref.less";

.mixin(~'.foo');

.parent {
  .mixin(~'.child');
}
```

The output of compiling root.less is:
#### root.css - with (reference)

``` css
.foo,
.bar .foo {
  color: #fff;
}
.parent.child,
.parent .bar .child {
  color: #fff;
}
.parent .bar .child:hover {
  color: #000;
}
```

Which is not what I would expect at all, and if I remove the `(reference)` from the `@import` this is what I get (and expect):
#### root.css - without (reference)

``` css
.foo,
.bar .foo {
  color: #fff;
}
.foo:hover,
.bar .foo:hover {
  color: #000;
}
.parent.child,
.parent .bar .child {
  color: #fff;
}
.parent.child:hover,
.parent .bar .child:hover {
  color: #000;
}
```

Thank you in advance for any help you can provide!
