### ISSUE TITLE
Wrong compilation result for a font shorthand property

### ISSUE THREAD

**Issue by Amphiluke** [less/less.js#2050]
Consider the following LESS file (**inc.less**):

``` Less
@some-var: 0.3;
@another-var: percentage(@some-var); // this seems to be the key line

@font-size: percentage(15 / 16);
@line-height: 22 / 15 + 0em;
@font-family: Arial,sans-serif;
```

Say, this file is then imported by another one:

``` Less
@import (reference) "inc";

body {
    font:@font-size @font-family;
}
div {
    font:normal ~"@{font-size}/@{line-height}" @font-family;
}
```

The compilation results in wrong font size and line height:

``` CSS
body {
    font:NaN% Arial,sans-serif
}
div {
    font:normal NaN%/22 / 15 + 0em Arial,sans-serif
}
```

Removing the line where the `@another-var` is declared eliminates the effect. Replacing `@another-var: percentage(@some-var)` with `@another-var: percentage(0.3)` seems to shadow the bug as well (i.e. LESS is compiled correctly).

At the same time abandoning font shorthand notation in favor of individual longhand properties gives a correct compilation result:

``` Less
@import (reference) "inc";

body {
    font-family:@font-family;
    font-size:@font-size;
}
div {
    font-family:@font-family;
    font-size:@font-size;
    font-weight:normal;
    line-height:@line-height;
}
```

results in

``` CSS
body {
    font-family:Arial, sans-serif;
    font-size:93.75%
}
div {
    font-family:Arial, sans-serif;
    font-size:93.75%;
    font-weight:normal;
    line-height:1.46666667em
}
```

Reproduced on Windows, lessc.cmd, versions 1.7.0 and 1.7.1
