### ISSUE TITLE
relative Url() bug

### ISSUE THREAD

**Issue by j1anb1n** [less/less.js#2051]
Here's my directory structure

```
src/
     app/
           base.less
     com/
           font/
                font.svg
           less/
                font.less
```

`src/com/less/font.less` is:

``` css
@font-face {
  font-family: 'xxxx';
  src: url('../font/font.svg');
  font-weight: normal;
  font-style: normal;
}

```

and `src/app/base.less` is :

``` less
import "../com/less/font.less";
```

and build `base.less`, i get these:

``` less
@font-face {
  font-family: 'xxxx';
  src: url('../font/font.svg');
  font-weight: normal;
  font-style: normal;
}
```

it should be:

``` less
@font-face {
  font-family: 'xxxx';
  src: url('../com/font/font.svg');
  font-weight: normal;
  font-style: normal;
}
```
