### ISSUE TITLE
Mixin guards inside mix operators?

### ISSUE THREAD

**Issue by sparanoid** [less/less.js#2071]
I'm creating a dynamic code highlighting theme that can fit every color scheme, so obvious I have to create two version for different colors, on for dark color and another for light ones:

``` css
.code-text (@a) when (lightness(@a) >= 50%) {
  color: lighten(@a, 10%);
}
.code-text (@a) when (lightness(@a) < 50%) {
  color: lighten(@a, 40%);
}

  .c     { color: mix(#999988, .code-text(@link-color), 80%); } // Comment
  .err   { color: mix(#a61717, .code-text(@link-color), 80%); } // Error
```

But I got the following error when compiling:

```
>> ParseError: Unrecognised input in _app/assets/_less/syntax.less on line 18, column 3:
```

Any idea how to make it work? 

Thanks.
