### ISSUE TITLE
foo < 10 = true ?

### ISSUE THREAD

**Issue by pixelass** [less/less.js#2076]
When checking if a keyword or string is smaller than a number it returns `true` while it should return `false` instead.

Look at the tests. I also checked if foo would be smaller than a negative number.

Input:

``` less
.keyword {
    & when (foo > 10) {
        log: fail
    }
    & when (foo <= 5) {
        log: fail
    }
    & when not (foo > 10)
      and not  (foo <= 5) {
        log: pass
    }
}

.string {
    & when ('foo' > 10) {
        log: fail
    }
    & when ('foo' <= 5) {
        log: fail
    }
    & when not ('foo' > 10)
      and not  ('foo' <= 5) {
        log: pass
    }
}

.number {
    & when (6 > 10) {
        log: fail
    }
    & when (6 <= 5) {
        log: fail
    }
    & when not (6 > 10)
      and not  (6 <= 5) {
        log: pass
    }
}

.keyword-vs-negative {
    & when (foo < -10000) {
        log: fail
    }
}
```

Output:

``` less
.keyword {
  log: fail;
}
.string {
  log: fail;
}
.number {
  log: pass;
}
.keyword-vs-negative {
  log: fail;
}

```
