### ISSUE TITLE
Custom-output-path-aware relative-URLs

### ISSUE THREAD

**Issue by am11** [less/less.js#2084]
Please change `toCSS()` so it takes custom output file path and make it produce the output with correct relative `url()`s.

Currently its producing urls relative to the source less file, whereas it should incorporate the intended location of css to be generated.

**Comment by stevenvachon** [comment]
I have this:
```less
// ~/project/node_modules/css-framework/less/include/variables.less
@css-framework-fonts: "../../fonts/";
```
```less
// ~/project/node_modules/css-framework/less/include/fonts.less
@font-face {
  src: url("@{css-framework-fonts}some-font.woff2") format("woff2");
}
```
```less
// ~/project/assets/less/include/variables.less
@css-framework-fonts: "../../../../assets/vendor/css-framework/fonts/";
```
```less
// ~/project/assets/less/include/icon.less
.classname {
  background-image: url("../../images/icons/some-icon.svg");
}
```

With `relativeUrls:true` and `rootpath:":"` in `~/project/gulpfile.js`, the end result is:
```css
/* ~/project/style.css */
@font-face {
  src: url("assets/vendor/css-framework/fonts/some-font.woff2") format("woff2");
}
.classname {
  background-image: url("../images/icons/some-icon.svg");
}
```
when this was expected:
```css
/* ~/project/style.css */
@font-face {
  src: url("assets/vendor/css-framework/fonts/some-font.woff2") format("woff2");
}
.classname {
  background-image: url("assets/images/icons/some-icon.svg");
}
```

**Comment by am11** [comment]
@stevenvachon, I ended up using via API like this:

```javascript
rootpath: path.dirname(
  path.relative(
    path.dirname(absoluteTargetFileName),
    absoluteSourceFileName)
  ).replace(/\\/g, '/') + "/",
```

Full story: https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/Resources/server/services/srv-less.js

I guess this is also applicable in gulpfile. If not then please share that file, might help spotting the issue. :)

**Comment by stevenvachon** [comment]
@am11, that produces:
```css
@font-face {
  src:url("../../../../assets/vendor/css-framework/fonts/some-font.woff2") format("woff2");
}
.classname {
  background-image: url("../../../images/icons/some-icon.svg");
}
```
which is even less correct.
