### ISSUE TITLE
Variable passing to ruleset by a mixin contain a loop

### ISSUE THREAD

**Issue by oltodo** [less/less.js#2098]
Hi,

This is my parametric mixin contain a loop who set a @width variable and provide to ruleset :

```less
.foo (@ruleset) {
    .loop(1);

    .loop (@index) when (@index < 4) {
        @width: 30px * @index;

        .bar {
            @ruleset();
        }

        .loop(@index + 1);
    }
}
```

When I call this mixin twice like that :

```less
.foo({
    width: @width;
});
.foo({
    width: @width;
});
```

I have this output :

```less
.bar {
  width: 30px;
}
.bar {
  width: 60px;
}
.bar {
  width: 90px;
}

.bar {
  width: 30px;
}
.bar {
  width: 30px;
}
.bar {
  width: 30px;
}
```

The first three are correct but the last three stay on `30px` width.

Strangely, the following example has no problem :

```less
.first {
    .foo({
        width: @width;
    });
}

.second {
    .foo({
        width: @width;
    });
}
```

An idea ?
Thanks.
