### ISSUE TITLE
The proposed feature set for :extend

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#2101]
On issue #1155, there was community consensus on the usage of extend in a way that offered flexibility for different use cases but kept things simple through the use of keyword flags. I've pulled out the relevant section/syntax that was agreed upon:
### :extend( _selector_ [exact|any] [shallow|deep] [all])
- **exact** [default] - Match complete selectors (`:extend(.button exact)` matches `.button {}` but not `#main .button a` - **`:extend(.a .b)` is considered an exact match to `.a { .b { } }`)**
- **any** - Match partial selector (`:extend(.button any)` matches `.button {}` **and** `#main .button a`)
- **shallow** [default] - extend only root properties (`.a:extend(.button shallow)` will not include hover in `.button { &:hover { } }`)
- **deep** - extend all nested selectors/properties (`.a:extend(.button deep)` **will** include hover in `.button { &:hover { } }`)
- **all** - set "any" and "deep" to true. Extend all matches, partial and exact, and extend all base and nested properties

**Example:**

```
.b:extend(.a);  // because of defaults, exact=true, shallow=true
.b:extend(.a any);  // exact=false, shallow=true
.b:extend(.a deep);  //exact=true, shallow=false
.b:extend(.a all); // exact=false, shallow=false
```

The reasons, arguments, and use cases for these other uses of `:extend` are documented in issue #1155. After the discussion and consensus, the first case and last case were implemented because they were easier to implement first, but I think the remaining implementation got lost in the noise. I'd love to see the rest of `:extend` implemented as I think these other use cases are still valid and there's various issues that come up here that essentially relate to what's still missing. (See: less/less-docs#177).

I'd love to see the work on `:extend` continue! (And other great ideas, like extending mixins.)

**Comment by matthew-dean** [comment]
What do you think about supporting an (optional) exclamation point on flags for clarity / separation from element selectors?

```
.myarticle {
  &:extend(section aside !all); 
}
```
I know our keywords don't conflict, but it might be intuitive for some because of ```!important```.

**Comment by seven-phases-max** [comment]
Btw., since the PR is coming (@bassjobsen :+1:),  I'd want to stress my concerns about `any` once again: are there any use-cases for it? (of course it can't harm but it's Less tradition to not add something just "because it can be added").

**Comment by seven-phases-max** [comment]
@matthew-dean

exclamation point, could be, though personally more like an idea previously suggested by @lukeapage (I can't find the issue so): to play with caps, e.g.`&:extend(section aside All)` or even `&:extend(section aside ALL);

**Comment by matthew-dean** [comment]
Are there really any use cases for ```all```?  I still doubt it does exactly what people mean for it to do. But, for the sake of argument, since no flag turns two switches to "false", and ```all``` turns two switches to true, the thinking was to support the two missing flags. BUT you may be right in that ```any``` is the least useful of any keyword. It's strange for someone to decide they want to extend a selector greedily in its matching, but not be greedy in its tree consumption.

Personally, if we just add ```deep```, I'm happy (mostly... I'd love to make it default for myself at least... another use case for @plugin ?).

**Comment by seven-phases-max** [comment]
Well, `all` can be used when you want to create just an alias for an existing class (e.g. in your HTML you just want to use `.button` instead of `.btn` everywhere). But I can't invent any for `any`.
Btw., curiously it turned out that there may be different interpretations of the above `any` (but still neither one make too much sense).
So yes, personally I'd also stick with just `deep` for now. (Not forgetting `scope/scoped` of course but that's another story since it probably require quite an implementation that quite orthogonal to all those "flat" matches above).

**Comment by matthew-dean** [comment]
Per the pull request discussion, and reviewing that code, I can actually see where ```any``` could be quite valuable: where you essentially want to piggy-back and group the selectors from one node of a tree. So it allows you to structure a tree logically (for the author), and then join other selectors which have a like appearance as one node, but don't have the same appearance or need the same child inheritance.

Because those two similar selectors can't yet extend a detached ruleset or a mixin, there really is no clean way to refactor and keep a logical structure (and keep your rules minimized). So there's a particular pattern that ```any``` would provide that isn't provided by any other method in Less. Being able to "extract" and extend a node's rules but not it's descendants offers some interesting possibilities.

My guess is simply providing the tool will surface other use cases / patterns like that that aren't immediately obvious.

**Comment by seven-phases-max** [comment]
to correct myself:

>&:extend(section aside All)

My mistake, it's actually exactly the opposite, `extend` keywords should remain case-sensitive and lowercase. It's selectors themselves that are assumed to become case-insensitive there (because by now they are not, ref: #2219), e.g.:
>`extend(body All)` // extends `body all`
`extend(body all)` // extends `body` with `all` flag

**Comment by seven-phases-max** [comment]
@matthew-dean Could you please provide a minimal example that shows the difference between `all` and `any`? Probably if I understand how it is supposed to work (I don't now after all of above stuff :) I could modify the PR to meet the requirements (if changes are not too deep).

**Comment by matthew-dean** [comment]
There are some examples in #2506 but I'll do my best to explain from my perspective in some more detail.

So, the easiest way to understand or test ```any``` and ```deep``` against ```all``` is that all is a conglomerate of those features.

Therefore, there are some examples in which ```any``` and ```all``` should produce the exact same output—namely, when the selector(s) it refers to do not contain nested blocks—just as there are some examples in which ```deep``` and ```all``` should produce the exact same output—namely, when there is an "exact" or complete match of the selector.

So, in #2506, the way I generated the output is simply by taking two cases of ```all``` and generating the output in the current Less engine. Given:
```less
.a button .q {
    color: red;
}
```
These two statements should produce identical output:
```less
.b:extend(button any) {
    background: black;
}
```
```less
.b:extend(button all) {
    background: black;
}
```
Because "all" is basically:
```less
.b:extend(button any deep) {
    background: black;
}
```
```deep``` doesn't change anything here because there is no nesting.

Where you'll see differing behavior for ```any``` and ```all``` is in nested trees, because you're implicitly calling two sets of keywords:
```any``` = ```any shallow``` (since shallow is default)
```all``` = ```any deep```

So, that means that ```any``` will look like ```all``` *at that particular node*, but not in any child nodes. Therefore, given:
```less
.a {
  .b {
    color: red;
    .c {
      line-height: 1;
    }
  }
}
```
Here is what I would expect from each output:
```less
// using all or ALL or !all
.d:extend(.b all) { }

// output today - testable with current parser
.a .b,
.a .d {
  color: red;
}
.a .b .c,
.a .d .c {
  line-height: 1;
}
```

```less
// using any or ANY or !any
.d:extend(.b any) { }

// output today - testable with current parser
.a .b,
.a .d {
  color: red;
}
.a .b .c {
  line-height: 1;
}
```
So, it's pretty straightforward. ```any``` extends the rules at that particular node and then *stops*. For a slightly more extended example:
```less
.d:extend(.b any) { background: blue; }

// output
.a .b,
.a .d {
  color: red;
}
.a .b .c {
  line-height: 1;
}
.d {
  background: blue;
}
```
Or, to demonstrate "joining" to the center node:
```less
.d:extend(.a .b any) { background: blue; }

// output
.a .b,
.d {
  color: red;
}
.a .b .c {
  line-height: 1;
}
.d {
  background: blue;
}
```
**AND**, if you were paying attention, you might have caught that the above is the exact same output as writing:
```less
.d:extend(.a .b) { background: blue; }
```
The reason is that ```.a .b``` is an exact match, so in this case the keywords 
```exact shallow``` = ```any shallow```
because the selector passed to extend was an exact (computed) selector.

So, it actually should be really testable, because it should behave like ```all``` on that matching node, and then look like it "matched nothing" (or, essentially, don't extend anything) on any nested block after that (and therefore behaves like.

I think that should be pretty comprehensive. The important thing to remember is just that all of this behavior is *already there* in ```:extend```; it was just never separated into its two components. So it's fairly easy to compare and intuit the output, because all along, you've seen pieces of these behaviors with and without the ```all``` keyword.

Does this help clarify?
