### ISSUE TITLE
error when parsing new /deep/ combinator for CSS Shadow DOM

### ISSUE THREAD

**Issue by ryanwatkins** [less/less.js#2111]
When attempting to parse a CSS that uses new syntax /deep/ for Shadow DOM, the parser throws and error.  This causes an issue writing CSS for use with Polymer and web components.

Ex:

``` css
body /deep/ paper-button.positive {
  background: #4285f4;
}
```

Returns:

```
Parse error: Unrecognised input
body /deep/ paper-button.positive {  background: #4285f4;
```

See: http://dev.w3.org/csswg/css-scoping/#deep-combinator
