### ISSUE TITLE
Mixin wrongly called 

### ISSUE THREAD

**Issue by jdeniau** [less/less.js#2127]
Hi,

I have a bug with this example

``` css
.row(@layout: fixed) { 
    display: table;
    table-layout: @layout;
}

.col() { 
    display: table-cell; 
}

.row { .row() }
.row > *, .col { .col() }
```

output: 

``` css
.row {
  display: table;
  table-layout: fixed;
  display: table-cell;
}
.row > *,
.col {
  display: table-cell;
}
```

If I add the parameter `fixed` as an argument to .row, no problem, if I remove the `.row > *,` code, no problem (but that's not what I want)
