### ISSUE TITLE
Can't use comments in the middle of selectors

### ISSUE THREAD

**Issue by ngyikp** [less/less.js#2178]
I have this CSS code:

``` css
.a .b {color:red}
.a /*h3*/ .b {color:red}
```

However, I can't compile it with less:

```
D:\>lessc --version
lessc 1.7.5 (Less Compiler) [JavaScript]

D:\>lessc test.less out.css
ParseError: Unrecognised input in D:\test.less on line 2, column 11:
1 .a .b {color:red}
2 .a /*h3*/ .b {color:red}
3

```
