### ISSUE TITLE
Using :extend inside a mixin does not extend.

### ISSUE THREAD

**Issue by kopepasah** [less/less.js#2187]
Let me preface this by stating that this mixin is probably edge case, but I created it to alleviate over nesting while maintaining one selector name for elements (e.g. `.top-nav`, `.top-nav-utility`, `#top-nav-open`, et cetera). This way, I only have to change the name on the `.selector()` mixin if I change the name in the auto generated html.

---

I've created a `.selector()` mixin that works like so:

``` css
.selector( @name, @content ) {
    @content();
}
```

**Usage Example**

``` css
.selector( ~'top-nav', {
    .@{name} {
        background: blue;

        .clearfix();

        .inner {
            &:extend( .container );
        }
    }

    #@{name}-open {
        &:extend( .button );
    }
} );
```

---

When using the selector with `:extend` the extended portion does not, for lack of a better word, extend. All other code outputs as expected.

Any idea what might be causing this?
