### ISSUE TITLE
Extend syntax inconsistency (was "ParseError: Unrecognised input" on extends)

### ISSUE THREAD

**Issue by lusitania** [less/less.js#2198]
If I lint this file by `lessc -l file`:

```
.something {
    color: red;
}
body {
    nav {/* a lot more lines */
        ul {
            color: blue;
            /*v1*/
            li:extend(.something);
            /*v2
            li {
                &:extend(.something);
            }*/
        }
        /*v3
        ul li:extend(.something); */
    }
}
```

I receive a message that isn't even pointing me in the direction of the error:

```
ParseError: Unrecognised input in file on line 5, column 2:
4 body {
5       [red] nav { /* a lot more lines */ [/red]
6               ul {
```

There are two issues:
- The parser accepts only _v2_ of the the three expressions that appear equivalent to me. My understanding of less is limited so I'm expecting to have overlooked something. I'd appreciate some feedback.
- In this particular case the `ParseError` message is not helpful. Guessing from the rarity of misleading messages I've seen so far I'd blame extend. But I should investigate this further.

**Comment by seven-phases-max** [comment]
Reworking this to a more generic ticket and rising the priority.
I.e. basically, the `Extend` has two different syntax variants one of which is inconsistent:
```less
y {y: y}

foo {
    x:extend(y);    // OK
    &:extend(y);    // OK
    x:extend(y)  {} // OK
    &:extend(y)  {} // error
    // but:
    x&:extend(y) {} // OK again
}
```
The fourth form is expected to work too.
Also related to #2179.
