### ISSUE TITLE
Variable interpolation doesn't work with pseudo selectors

### ISSUE THREAD

**Issue by SimonHarte** [less/less.js#2201]
LessCSS:

``` css
.icon(@position, @unicode) {
    &:@{position} {
        content: '\@{unicode}';
    }
}

.icon-heart {
    .icon(after, '2665');
}
```

Expected:

``` css
.icon-heart:after {
    content: '\2665';
}
```

Result:

```
ParseError: Unrecognised input in
.icon(@position, @unicode) {
    &:@{position} {
```
