### ISSUE TITLE
Support for @counter-style rule

### ISSUE THREAD

**Issue by futekov** [less/less.js#2204]
The new [counter-style rule](http://www.w3.org/TR/2014/WD-css-counter-styles-3-20140826/#cyclic-system) gives an error in Less because the `@` rule is unrecognized:

``` css
@counter-style triangle {
  system: cyclic;
  symbols: ‣;
  suffix: " ";
}
```

PS - Would it be possible to add support for `@unknown` rules, or will this clash with variables, this will also solve lots of similar issues in the future when new `@` rules emerge.
