### ISSUE TITLE
Bug: extend doesn't work when appended on nested selector with &

### ISSUE THREAD

**Issue by SimonHarte** [less/less.js#2206]
Tested this with [http://less2css.org/](http://less2css.org/), experienced it in a project with LessJS 1.7.1:

LessCSS:
```css
.icon-heart {
  content: '\2661';
}

.myModule {
  .test {
    &.active:extend(.icon-heart) {}
  }
  
  .test2 {
    &.active {
      &:extend(.icon-heart);
    }
  }
}
```

Expected:
```
.icon-heart,
.myModule .test.active,
.myModule .test2.active {
  content: '\2661';
}
```

Result:
```
.icon-heart,
.myModule .test2.active {
  content: '\2661';
}
```
