### ISSUE TITLE
/deep/ selector is lost when using &

### ISSUE THREAD

**Issue by David-Mulder** [less/less.js#2221]
The following less (how do you add syntax highlighting for less?)

``` less
a b {
    c: 'd';
    &[e]{
        f: 'g';
    }
}
/deep/ b {
    c: 'd';
    &[e]{
        f: 'g';
    }
}
```

generates the following css (see the comments)

``` css
a b {
  c: 'd';
}
a b[e] { /* it works as expected here */
  f: 'g';
}
 /deep/ b { /* and the deep selector is supported */
  c: 'd';
}
b[e] { /* but missing /deep/ here */
  f: 'g';
}
```
