### ISSUE TITLE
Less could use stricter name resolution

### ISSUE THREAD

**Issue by jonsa** [less/less.js#2229]
I'm not sure if I should call this a bug or a feature request, but this recently bit me.

_this is simplified code and not production code_

``` css
.placeholder(@color: #333333) {
    &::-webkit-input-placeholder  { color: @color; }
}
input {
    .placeholder();
}
.placeholder {
    background: #ffffff;
}
```

which will output

``` css
input {
    background: #ffffff;
}
input::-webkit-input-placeholder {
    color: #333333;
}
.placeholder {
    background: #ffffff;
}
```

I'm not sure if this is by design, but I propose stricter name resolution where `.name != .name()`
