### ISSUE TITLE
Cannot use selectors defined with pseudoselectors as a mixin

### ISSUE THREAD

**Issue by bendavis78** [less/less.js#2244]
According to the docs,  "Any CSS class, id or element ruleset can be mixed-in that way". 

If this rule has been defined in external.css file:

``` css
.foo-rule:before {
    content: "\f061";
}
```

I should be able to use it as a mixin in my less code:

``` css
@import (less) url('//example.com/css/external.css')
a.foobar {
    color: red;
    .foo-rule;
}
```

Which should result in the following compiled css:

``` css
a.foobar {
    color: red;
}
a.foobar:before {
    content: "\f061";
}
```
