### ISSUE TITLE
Import as less through a function

### ISSUE THREAD

**Issue by mailvidi** [less/less.js#2248]
myTables.css

``` css
.myClass {
  height: 50px;
  width: 50px;
}
```

dummy.less

``` css
@tables: 'myTables';

.getClass(@module) {
  @import (less) '@{module}.css';
}

.test {
  .getClass(@tables);
}
```

Error:

```
SyntaxError: variable @module is undefined in dummy.less on line 8, column 3:
.test {
  .getClass(@tables);
}
```

Any reason why I'm getting this error?

PS: However, just to confirm, I'm able to import "myTables.css" as less outside the function.
## 

Regards,
VS
