### ISSUE TITLE
Logical operator support

### ISSUE THREAD

**Issue by am11** [less/less.js#2266]
Don't know what spec has to say about it, but logically this code: 

``` scss
.foo {
    height: 1/2 ==   0.5 ?   3 : 2;
}

.bar {
  sanity: 1/2 ==   0.5;
}
```

Should compile to 

``` css
.foo {
  height: 3;
}

.bar {
  sanity: true;
}
```

(at least this is how SASS do it)

Currently it throws:

``` cmd
ParseError: Unrecognised input in C:\temp\foo.less on line 2, column 5:
1 .foo {
2     height: 1/2 ==   0.5 ?   3 : 2;
3 }
```
