### ISSUE TITLE
Suggestion for pseudo selectors

### ISSUE THREAD

**Issue by pronebird** [less/less.js#2273]
Hi,

As I see recent versions of less accept `> div {}` without self-reference to current scope. I believe a year ago that wouldn't work without `& >`. But I might be wrong.

Example:

``` css
div {
  > div {
    color: blue;
  }
}
```

which naturally transforms into

``` css
div > div { color: blue; }
```

However this is not the same for pseudo selectors like `:hover`.

Example:

``` css
.btn{
  :hover {
    color: blue;
  }
}
```

transforms into:

``` css
.btn :hover { color: blue; }
```

Wouldn't it make sense to accept `:hover` the same way we accept `> div` and generate valid CSS?

LESS without & looks much cleaner :)
