### ISSUE TITLE
Nested attribute selectors have quotes added

### ISSUE THREAD

**Issue by jsdevel** [less/less.js#2287]
I have the following less:

``` less
      div {
        > [class^=col-] {                                                               

          >label {                                                                     

          }                                                                            

          >div.component {                                                             


            .dropdown-menu {                                                           

            }                                                                          

            &.datepicker {                                                             
              .dropdown-menu:before,                                                   
              .dropdown-menu:after {                                                   

              }                                                                        
            }                                                                          

            >[ch-rateplan-dropdown] {                                                  

              .dropdown-menu {                                                         
                  height: 50px;                
              }                                                                                                                                            
            }                                                                                                                                               
          }                                                                            
        }    
      }                                                                          
```

I would expect to see output like this:

``` css
div>[class^=col-]>div.component>[ch-rateplan-dropdown] .dropdown-menu{height:50px;}
```

Instead I'm seeing this:

``` css
div>[class^="col-]>div.component>[ch-rateplan-dropdown"] .dropdown-menu{height:50px;}
```

Notice the double quotes.  Is there something I'm doing wrong?
