### ISSUE TITLE
Cannot inherit from class, which name contains variable

### ISSUE THREAD

**Issue by tompazourek** [less/less.js#2306]
Class `.other` can inherit properties from class `.something` like this:

``` less
.something { ... }
.other {
    ...
    .something;
}
```

However if the `.something` class contains variable in its name, it's impossible:

``` less
@prefix: abc;

.@{prefix}-something { ... }
.other {
    .@{prefix}-something; // error
}

.other {
    .abc-something; // error as well
}
```

When I am using third party library, which has classes in the form of `.@{prefix}-something` (e.g. Font-Awesome icons), I cannot inherit from them.

Or is there some way, which I am missing?
