### ISSUE TITLE
:extend(... all) doesn't work reliably

### ISSUE THREAD

**Issue by berarma** [less/less.js#2328]
Following LESS code:

``` less
.a {
  margin: 0;
}
.b {
  padding: 0;
}
.a .b {
  margin: 10;
}
.c:extend(.a all) {}
.d:extend(.b all) {}
```

produces:

``` css
.a,
.c {
  margin: 0;
}
.b,
.d {
  padding: 0;
}
.a .b,
.c .b,
.a .d {
  margin: 10;
}
```

Instead of:

``` css
.a,
.c {
  margin: 0;
}
.b,
.d {
  padding: 0;
}
.a .b,
.c .b,
.a .d,
.c .d {
  margin: 10;
}
```

Notice the lack of ".c .d" selector in the first output.

This complicates using Bootstrap in a semantic way. Example:

``` less
.mypanel:extend(.panel all, .panel-default all) {}
.mypanel-heading:extend(.panel-heading all) {}
```

needs to become:

``` less
.mypanel:extend(.panel all, .panel-default all) {}
.mypanel-heading:extend(.panel-heading all, .panel-default > .panel-heading all) {}
```

Tested on less 1.7.5 and 2.1.1. I'm new to LESS. I couldn't find any existing issue that I could relate to this.
