### ISSUE TITLE
Mixin delegates

### ISSUE THREAD

**Issue by kreopt** [less/less.js#2331]
Not sure if this feature is not implemented, but i don't find the way to do this and issues creaded earlier.

I'd like to write some generic mixins taking other mixins as parameters such this:

``` css
.clickable(@hoverEffect, @activeEffect){
   &:hover{.@{hoverEffect}();}
   &:active{.@{activeEffect}();}
}

.active_delegate(){background:#aaa;/* something more complicated here...*/}
.hover_delegate(){background:#ddd;/*...*/}
.active_delegate--dark(){background:#666;/*...*/}
.hover_delegate--dark(){background:#333;/*...*/}

.button{
  background: #fff;
  .clickable(hover_delegate, active_delegate);
}

.button--dark{
  background:#000;
  .clickable(hover_delegate--dark, active_delegate--dark);
}
```
