### ISSUE TITLE
Unable to reference to a variable that's part of an imported file

### ISSUE THREAD

**Issue by mailvidi** [less/less.js#2332]
Hi,

I'm having trouble referencing to a variable that's part of an imported file. Could you please help?

Here's a sample usecase:
###### myLibrary/1.0.0/link.css:

``` css
a {
  text-decoration: none;
}
```
###### variables.less:

``` less
@version: e('1.0.0');
```
###### myFile.less:

``` less
@import 'variables.less';

.customFunction() {
  @import (less) 'myLibrary/@{version}/link.css';
  // @import (less) 'myLibrary/1.0.0/link.css'; <-- This works!!!
}

.customFunction();

```
###### Current Output:

```
SyntaxError: variable @version is undefined in myFile.less on line 7, column 1:
6 
7 .customFunction();
8 
```
###### Desired Output:

``` css
a {
  text-decoration: none;
}
```

Regards,
VS
