### ISSUE TITLE
Inheriting with selectors

### ISSUE THREAD

**Issue by mailvidi** [less/less.js#2335]
###### parent.css

``` css
.their-divA .their-divB {
  display: inline-block;
}
```
###### child.less

``` less
@import (less, reference) 'parent.css';

.myFunction() {
  .my-divA:extend(.their-divA all) {}

  .my-divB:extend(.their-divB all) {}
}

.myFunction();
```
##### Current Output

```
.my-divA .their-divB,
.their-divA .my-divB {
  display: inline-block;
}
```
##### Desired Output

```
.my-divA .my-divB {
  display: inline-block;
}
```

Any pointers please?

Thanks!
~VS
