### ISSUE TITLE
LeSS Optimization. (LeSS/CSS to LeSS)

### ISSUE THREAD

**Issue by electricessence** [less/less.js#2348]
I've been looking into finding a tool that will take LeSS (or CSS for that matter) and optimize it or at least have a way to add optimization rules.

For example:

``` css
.nav-bar {
   color: blue;
   padding: 3px;
}
.nav-button {
  color: white;
  background: black;
}
```

Should convert to:
``` css
.nav {
   &-bar {
      color: blue;
      padding: 3px;
   }
   &-button {
      color: white;
      background: black;
   }
}
```

Obviously there could be a long list of rules that do something like this.  Also note that this conversion could happen deeper in the tree that the root.

The purpose for this would be to take either existing CSS or LeSS files and normalize them for further development.   I've looked at a few tools, but it seems ideal to use the exiting LeSS parser and allow for a flag to export an optimized LeSS version instead of the resultant CSS.

I'd be willing to contribute to this, but I wanted to see where everyone's head is at with this, or maybe I missed a tool somewhere that did this.
