### ISSUE TITLE
Add inequality operator for guards

### ISSUE THREAD

**Issue by SLaks** [less/less.js#2349]
Mixin / ruleset guards currently support every comparison operator except for inequality (`!=` or `<>`).

Can you add that?

Motivation: I'm making a ruleset parameter which can be invoked with an optional parameter that controls a nested ruleset.

```css
.defineStuff({
  .someclass {
     ...
    &:before when (@label != '') {
      content: @label;
    }
  }
});
```

The `@label` parameter will be passed by some invocations of `defineStuff()`.
