### ISSUE TITLE
Replace breaks on keywords within mixin invocations

### ISSUE THREAD

**Issue by SLaks** [less/less.js#2351]
**Source**:

``` css
@keyword: test;
.test {
    content: replace(@keyword, '(^[a-z])', '.$1');
}
a {
    .test();
}
```

**Actual Result**: 

``` css
.test {
  content: .test;
}
a {
  content: ..test.;
}
```

**Expected Result**:

``` css
.test {
  content: .test;
}
a {
  content: .test;
}
```

**Workarounds**:
Turning the keyword into a string fixes this: `e(replace('@{keyword}', '(^[a-z])', '.$1'))`

Also, this only happens if the `replace()` call is inside a mixin invocation.
