### ISSUE TITLE
Guards on pseudo-classes produce syntax error

### ISSUE THREAD

**Issue by SLaks** [less/less.js#2352]
Source:
```css
a:hover when (1=1) {
	color: red;
}
```

Error:

    expected ')' got '='
