### ISSUE TITLE
FYI: less syntax is now highlighted on GitHub Flavored Markdown!

### ISSUE THREAD

**Issue by am11** [less/less.js#2362]
Last time I checked, 

<pre>
```less

```
</pre>

wasn't giving syntax highlighting. I reported that to GHM support team, who forwarded me to the issue tracker of syntax highlighting lib project on bitbucket (http://bitbucket.org/birkenfeld/pygments-main/issues), where they had this request for less since 2012. Meanwhile I was using `css` or `scss` for less syntax.

The good news is, it is now implemented (not sure if pygments lib received the lexer support, coz the issue bb-780 is still opened). So this:

```less
@keyframes rotate {
    0% {
        transform: rotate(0deg);
    }

    100% {
        transform: rotate(180deg);
    }
}
body {
  color: blind;
}
```

works! :)

Happy new year! :fireworks:
