### ISSUE TITLE
NameError with nested mixins

### ISSUE THREAD

**Issue by MarcelGerber** [less/less.js#2366]
Using this LESS code:
``` LESS
#grid {
  .core (@gridColumnWidth, @gridGutterWidth) {
    .span (@columns) {
      width: (60px * @columns) + (20px * (@columns - 1));
    }
  }
}

.container {
  #grid > .core > .span(12);
}
```

(This is actually a reduced test case from the [Bootstrap 2.3.1 code](https://github.com/twbs/bootstrap/blob/eb24718add4dd36fe92fdbdb79e6ff4ce5919300/less/navbar.less#L196-L200))

Result (2.2.0 behavior):
```
NameError: #grid > .core > .span is undefined in style.less on line 10, column 3:
9 .container {
10   #grid > .core > .span(12);
11 }
```

Expected (1.7.5 behavior):
``` CSS
.container {
  width: 940px;
}
```

**Comment by lukeapage** [comment]
Well the code is a bit wrong.. either do this

```less
#grid {
  .core (@gridColumnWidth, @gridGutterWidth) {
    .span (@columns) {
      width: (60px * @columns) + (20px * (@columns - 1));
    }
  }
}

.container {
  #grid > .core(100, 100);
  .span(12);
}
```
or
```less
#grid {
    .span (@columns) {
      width: (60px * @columns) + (20px * (@columns - 1));
    }
  .core (@gridColumnWidth, @gridGutterWidth) {
  }
}

.container {
  #grid > .span(12);
}
```

I think it is now correctly failing because you are trying to run a mixin inside a paramaterised mixin.

@seven-phases-max does that sounds right to you too?
