### ISSUE TITLE
Properties merging and the !important keyword

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#2367]
Properties marked as !important are merged in two different ways:
* Properties marked with !important keyword are merged separately from normal properties.
* The !important is treated as another identifier expression in a list.

Example:
````
.transform {
  transform+_: skew(30deg);
  transform+_: rotate(90deg);
  transform+_: scale(2,4) !important;
  transform+_: scale(3,3) !important;
}

.transition {
  transition+: width 2s;
  transition+: height 2s !important;
  transition+: transform 2s !important;
}
````

compiles into:
````
.transform {
  transform: skew(30deg) rotate(90deg);
  transform: scale(2, 4) scale(3, 3) !important;
}
.transition {
  transition: width 2s, height 2s !important, transform 2s !important;
}
````

I would expect it to compile into:
````
.transform {
  transform: skew(30deg) rotate(90deg);
  transform: scale(2, 4) scale(3, 3) !important;
}
.transition {
  transition: width 2s;
  transition: height 2s, transform 2s !important;
}
````

The example mixes `+_` and `+`, because I wanted to use code that make some sense. Both `+_` and `+` work the same way, difference is in used expressions. E.g. the `transform` in the above example works because `scale()` resembles a function. The  `transition` does not work, but if I replace `2s` by `s()`, then merge will work correctly:
````
.wrong-css-correct-merge {
  transition+: width 2s;
  transition+: height s() !important;
  transition+: transform s() !important;
}
````

compiles into:
````
.wrong-css-correct-merge {
  transition: width 2s;
  transition: height s(), transform s() !important;
}
````

**Comment by SomMeri** [comment]
Somewhat related note: following works fine:

````
@variable: scale(2,4) !important;

.transform {
  transform+_: rotate(90deg);
  transform+_: @variable;
  transform+_: scale(3,3) !important;
}
````

result:
````
.transform {
  transform: rotate(90deg);
  transform: scale(2, 4) scale(3, 3) !important;
}
````

**Comment by seven-phases-max** [comment]
Currently reviewing the merging code and stepped into this:

> I would expect it to compile into:
```less
.transform {
  transform: skew(30deg) rotate(90deg);
  transform: scale(2, 4) scale(3, 3) !important;
}
.transition {
  transition: width 2s;
  transition: height 2s, transform 2s !important;
}
```

I would not. I do not see any reason for the values having `!important` to form a separate property This do not make any sense, i.e. notice that in your expected result the non-important properties would not have any effect at all (thus it's basically equal to removing them from the output CSS completely).

So my expectation for the result of the example would be simply:
```less
.transform {
    transform: skew(30deg) rotate(90deg) scale(2, 4) scale(3, 3) !important;
}
.transition {
    transition: width 2s, height 2s, transform 2s !important;
}
```
(After all, if I *did* write a dumb code I expect the dumb result - no guesswork please).
But the issue with double `!important` stays the same of course.
