### ISSUE TITLE
more strong convert function

### ISSUE THREAD

**Issue by littledu** [less/less.js#2379]
I want to solve the `rgba` for old ie, the code maybe:
```
background-color:rgba(207,10,60,0.5);
filter:progid:DXImageTransform.Microsoft.gradient(enabled='true',startColorstr='#7FCF0A3C', endColorstr='#7FCF0A3C');
```

`startColorstr=#7F...` , `7F` is from opacity(0.5). In less, no function convert. Can you supply more strong function in less?

Maybe the function called like:

**LESS:**
```
opacity-no-text(#cf0a3c,.5);
```

**CSS**
```css
background-color:rgba(207,10,60,0.5);
filter:progid:DXImageTransform.Microsoft.gradient(enabled='true',startColorstr='#7FCF0A3C', endColorstr='#7FCF0A3C');
```

just a example. that is all.

i'm so sorry, my english is so poor, thanks!

**Comment by matthew-dean** [comment]
You can do this already:

```less
.test {
    @color: rgba(207,10,60,0.5);
    @msColor: argb(@color);
    background-color: @color;
    filter: ~"progid:DXImageTransform.Microsoft.gradient(enabled='true',startColorstr='@{msColor}', endColorstr='@{msColor}')";
}
```
--output:
```css
.test {
  background-color: rgba(207, 10, 60, 0.5);
  filter: progid:DXImageTransform.Microsoft.gradient(enabled='true',startColorstr='#80cf0a3c', endColorstr='#80cf0a3c');
}
```
