### ISSUE TITLE
Ampersand in LESS

### ISSUE THREAD

**Issue by thehung2224** [less/less.js#2388]
I'm confused about double ampersand behaviour in LESS compiler.

```
.box-item{
	&__info{
		&--normal, &--left{
			padding-left: 11px;
			padding-right: 11px;

			h4{
				font-size: @delta;
			}
		}

		&--normal{
			.item-price{
				float: right;
			}

			h4{
				display: inline-block;
				margin-bottom: 10px;
			}
		}
	}
}
```
How can I write extend `.item-price` and `h4 {margin-bottom: 10px}` classes of `&--normal` inside `&--normal, &--left` instead of writing in the new line. I'm bad in English so hope you can understand what I say. Thank in advance.

**Comment by lukeapage** [comment]
The better place for queries like this is stack overflow - The issues list is for reporting problems with less.

Please also include what output you want so the problem is clear. If you put some expected output on this issue I will reply if there is an easy answer.

**Comment by thehung2224** [comment]
Hi,

This is what I expected output:

```css
.box-item__info--normal,
.box-item__info--left {
  padding-left: 11px;
  padding-right: 11px;
}
.box-item__info--normal h4,
.box-item__info--left h4 {
  font-size: 1.5em;
}
.box-item__info--normal .item-price {
  float: right;
}
.box-item__info--normal h4 {
  display: inline-block;
}
```

**Comment by lukeapage** [comment]
I think that is the output I get.. what is different from what you want?

**Comment by thehung2224** [comment]
Hi @lukeapage 

Yes, I mean can write `.item-price` inside one line, like this:

```
.box-item{
	&__info{
		&--normal, &--left{
			padding-left: 11px;
			padding-right: 11px;

			h4{
				font-size: @delta;
			}

			& + &{
				.item-price{
					float: right;
				}

				h4{
					display: inline-block;
				}
			}
		}
	}
}
```
I only know plus sign in LESS selector.

**Comment by lukeapage** [comment]
okay, but what do you want? What is the output css you are trying to achieve? & includes all parent selectors upto that point and `& + &` does the same, with the addition that if you have comma seperated selectors they will be 'multiplied'

**Comment by thehung2224** [comment]
Hi,

This is the output css I'm trying to achieve:

```css
.box-item__info--normal,
.box-item__info--left {
	padding-left: 11px;
	padding-right: 11px;
}
.box-item__info--normal h4,
.box-item__info--left h4 {
	font-size: 1.5em;
}
.box-item__info--normal .item-price {
	float: right;
}
```
Then, I write this LESS syntax:

```
.box-item{
	&__info{
		position: relative;
		padding: 35px 0 15px 0;

		&--normal, &--left{
			padding-left: 11px;
			padding-right: 11px;

			h4{
				font-size: @delta;
			}

			& , & .item-price{
				float: right;
			}
		}

		&--left{
			padding-top: 20px;
			
			h4{
				margin-bottom: 10px;
			}
		}
	}
}
```
Will produce:

```css
.box-item__info--normal,
.box-item__info--left {
	padding-left: 11px;
	padding-right: 11px;
}
.box-item__info--normal h4,
.box-item__info--left h4 {
	font-size: 1.5em;
}
.box-item__info--normal,
.box-item__info--left,
.box-item__info--normal .item-price,
.box-item__info--left .item-price {
	float: right;
}
```

Can you give any advice to make this code works as I expected. Thank you so much.
