### ISSUE TITLE
!important keyword with parametric mixin

### ISSUE THREAD

**Issue by Craigy-** [less/less.js#2394]
Mixin:

```css
.size(@width: auto; @height: auto) {
  .set-width(@size) when (ispercentage(@size)) {
    width: @size;
  }
  .set-width(@size) when (isnumber(@size)) and not (ispercentage(@size)) {
    width: unit(@size, px);
  }
  .set-width(@size) when not (isnumber(@size)) and not (ispercentage(@size)) {
    width: auto;
  }
  .set-height(@size) when (ispercentage(@size)) {
    height: @size;
  }
  .set-height(@size) when (isnumber(@size)) and not (ispercentage(@size)) {
    height: unit(@size, px);
  }
  .set-height(@size) when not (isnumber(@size)) and not (ispercentage(@size)) {
    height: auto;
  }

  .set-width(@width);
  .set-height(@height);
}
```

If I call it like: `.size(100%)`, CSS compiles as well.
If I call it like: `.size(100%) !important`, I see an error "NameError: variable @size is undefined".

Less v1.7 compiles two calls, but v2.0 thrown an error. Can you help?
