### ISSUE TITLE
Redundant spaces

### ISSUE THREAD

**Issue by gera2ld** [less/less.js#2397]
No redundant space is shown when I use a cmd of `lessc ...`.
When compressed with a node script (even with the same file and CSS text), redundant spaces come out.

This a simple example:
``` javascript
var less=require('less');
less.render('*{-webkit-transform:scale(-1,1);}\na{transform:scale(1,-1);}',{
    compress:true
},function(e,r){console.log(r.css);});
```
The compressed text should be
``` css
*{-webkit-transform:scale(-1,1);}a{transform:scale(1,-1);}
```
but
``` css
*{-webkit-transform:scale(-1, 1);}a{transform:scale(1, -1);}
/* Redundant spaces:         ^                        ^   */
```
instead.
