### ISSUE TITLE
Variable interpolation doesn't work in attribute selector after a `-`

### ISSUE THREAD

**Issue by gogoout** [less/less.js#2399]
less:
```css
.layout-for-name(@name) {
  [layout-@{name}] {
	box-sizing : border-box;
	display    : flex;
  }
  [layout-@{name}=column] {
	flex-direction : column;
  }
  [layout-@{name}=row] {
	flex-direction : row;
  }
}
.layout-for-name(sm);
```

expected:
```css
 [layout-sm] {
	box-sizing : border-box;
	display    : flex;
  }
  [layout-sm=column] {
	flex-direction : column;
  }
  [layout-sm=row] {
	flex-direction : row;
  }
```

currently:
````
    expected ']' got 'l' in file ...
````

-------------------------------------------------

**But Variable interpolation in the attr selector without a `-` works**

less:
```css
.layout-for-name(@name) {
  [@{name}] {
	box-sizing : border-box;
	display    : flex;
  }
  [@{name}=column] {
	flex-direction : column;
  }
  [@{name}=row] {
	flex-direction : row;
  }
}
.layout-for-name(sm);
```

output:
```css
  [sm] {
	box-sizing : border-box;
	display    : flex;
  }
  [sm=column] {
	flex-direction : column;
  }
  [sm=row] {
	flex-direction : row;
  }
```

**Comment by seven-phases-max** [comment]
To be more specific it's not just "after `-`" but anywhere at the left part of the `attr` if `@` is not its first char:
```
[@{var}]        // OK
[@{var}=@{var}] // OK
[foo@{var}]     // Err.
[@{var}@{var}]  // Err.
```

**Comment by bassjobsen** [comment]
Cause the following code throws an error, i think this issue will be related to https://github.com/less/less.js/issues/1375

```less
[a b] {p:1;}
```
