### ISSUE TITLE
Twice generated output

### ISSUE THREAD

**Issue by devalexqt** [less/less.js#2403]
If I have 3-way structure:

main.css
``` less
@import "css/index.less";
@import "css/infobox.less";
@import "css/spinner.less";
@import "css/header.less";

.page-main-container{
	width: 100%;
	min-height: 500px;
	text-align: left;
	text-indent: 15px;
	color: @color-text-normal;
}
```
header.less
``` less 
@import (less) "css/header_animation.less";// if its included then time by time render generate twice output. 
.header-layer{
	position: absolute;
	width: 200%;
	top:0px;
	bottom: @main-header-height;
}
```
If in second file I include '@import "css/header_animation.less" ' then system generate output twice in same random case.
![less - node server js 2015-01-21 15 52 56](https://cloud.githubusercontent.com/assets/865007/5837193/a5b1ecd6-a185-11e4-8337-f1f8851fa19d.png)

``` javascript
		 if(extention=="less"){
		 	console.log("==========>less")
			less.render(data.toString(),{paths: rootpath,compress:false}, function (err, data) {
				if (err){console.log("==>cant parse less file, err: "+err);res.statusCode=404;res.end(); return};
				sendPage(data.css,"text/css")//[css,imports]
				console.log("less "+req_file)
				//console.dir(data)
			})//less
```
