### ISSUE TITLE
mixin with namespace bring odd things in

### ISSUE THREAD

**Issue by MrRaindrop** [less/less.js#2409]
the test less code:
```less
.a.b {
    color: blue;
}

.a {
    .b {
        color: green;
    }
}

.d {
    .a > .b;
}
```

generated css:

```css
.a.b {
  color: blue;
}
.a .b {
  color: green;
}
.d {
  color: blue;  /* this is the odd thing I refered in the title of this issue */
  color: green;
}
```
I suppose this is a bug?.. If not, please point out my misunderstanding（I'm new to less & I'm learning it）
