### ISSUE TITLE
Compile Less in browser returning the compilation as text. Is that possible?

### ISSUE THREAD

**Issue by mreis1** [less/less.js#2419]
Is there a way to give a less file contents as text to the less plugin and get the compilation as text response?

```js
// colors in object to be injected into the page
var colorVars = {
  c1: 'red',
  c2: 'green',
  c3: 'black'
}

// colors in object to be injected into the page
$.get('some.txt', function(stylesheetModel){
     var stylesToCompile = _.template(stylesheetModel)(variables) //underscorejs parses the stylesheet and replaces it with variables
   
   var compiledStyles = less.compile(stylesToCompile); //compile basic stylesheet with custom variables into a text file
   .......
  })
```

Where inside the txt we have a model to be parse by underscore and then compiled by the less engine return the styles as text. 

```less
.body{
    color: <%= c1 %>;
    background:  <%= c2 %>;
}

.headers{
   h1{
      color: darken(<%= c3 %>,30%);
      border: 1px solid lighten(<%= c3 %>,30%);
   }   
}
.....
```
