### ISSUE TITLE
!important tag changing mixin with nested checks

### ISSUE THREAD

**Issue by leigeber** [less/less.js#2421]
So this issue is a little obscure but it bit us today when using !important with one of our more complex mixins. Below is a stripped down example:

```less
.testMixin () {
	.topCheck () {
		.nestedCheck() {
			margin: 5px;
		}
		.nestedCheck();
	}
	.topCheck();
}
.class1 {
	.testMixin() !important;
}
.class2 {
	.testMixin();
}
```

This outputs the following:

```css
.class1 {margin: 5px !important}
.class2 {margin: 5px !important}
```

The issue being here that adding !important to the first mixin call permanently attaches it to any subsequent calls. It only appears to be present when there are 2 levels of nested functions inside the outer mixin. We are using Less 2.3.1.
