### ISSUE TITLE
Parsing a list breaks with comments in the definition

### ISSUE THREAD

**Issue by tomekwi** [less/less.js#2431]
```less
@list:
    a 1, // Some comment
    b 2;

.for (@i: 1) when (@i <= length(@list)) {
    @item: extract(@list, @i);
    @name: extract(@item, 1);
    @{name} { value: extract(@item, 2); }
    .for(@i + 1);
}
.for();
```

Piping the above through `lessc` outputs weird stuff:
```css
a {
  value: 1;
}
 {
  value: b;
}
```

I'd rather expect:
```css
a {
  value: 1;
}
b {
  value: 2;
}
```

For the record, with this input the result is as expected. Just the comment has been deleted:
```less
@list:
    a 1,
    b 2;

.for (@i: 1) when (@i <= length(@list)) {
    @item: extract(@list, @i);
    @name: extract(@item, 1);
    @{name} { value: extract(@item, 2); }
    .for(@i + 1);
}
.for();
```

I'm running `lessc 2.3.1 (Less Compiler) [JavaScript]`.
