### ISSUE TITLE
Classes with the parent selector in their name – can't use them as mixins

### ISSUE THREAD

**Issue by tomekwi** [less/less.js#2434]
Similar to #2216, but it's still there in v2.3.1 .

```less
.a {
  &-b {
    some: stuff;
    }
  }

.c {
  .a-b;
  }
```

Piped through lessc, this throws a
```
NameError: .a-b is undefined in ... on line 8, column 3:
7 .c {
8   .a-b;
9   }
```

Just for the record, without the `.c` definition everything works as expected:
```sh
$ cat <<EOF | lessc -
> .a {
>   &-b {
>     some: stuff;
>     }
>   }
> EOF

.a-b {
  some: stuff;
}
```
