### ISSUE TITLE
css calc( {percentage} -/+ {pixel amount} ) outputs as calc({percentage - pixel amount as percentage})

### ISSUE THREAD

**Issue by andrew-luhring** [less/less.js#2438]
example:

### less:
```less
a {

  left : calc(50% - 40px);
  width: 40px;
}
```

gets compiled as:

### css

```css
a {
  left: calc(50% - 40%);
  width: 40px;

}

/* or */

a {
  left: 10%;
  width: 40px;
}
```

What do?

**Comment by radium-v** [comment]
Is Strict Math enabled when you build? http://lesscss.org/usage/#command-line-usage-strict-math

You could try escaping the value:

```less
a {
  left: calc(~"50% - 40px");
  width: 40px;
}
```
