### ISSUE TITLE
LESS Affected by Particular CSS Comment

### ISSUE THREAD

**Issue by jlukic** [less/less.js#2450]
This seems a bit crazy, but please check out the test case zip and you can confirm.

[Test Case](https://dl.dropboxusercontent.com/u/2657007/testcase.zip)

**Summary**

Imported file that includes the specific comment `/* End Config */` will not compile after first time. 

**To Reproduce**

File
```less
@import (multiple) "file2";

#foo {
  foo: 'foo';
}

@import (multiple) "file2";

#bar {
  bar: 'bar';
}
```

Importing this file as `file2` will cause `#foo` rules not to appear in output
```less
@some: 'value';

/* End Config */
```

Importing this file as `file2 will have all output appear normally (notice "zonfig")
```less
@some: 'value';

/* End Zonfig */
```
