### ISSUE TITLE
/deep/ selector is lost when is followed by spaces

### ISSUE THREAD

**Issue by luisvt** [less/less.js#2455]
for example:

```less
html /deep/ {
  input {
    color: blue;
  }

  button {
    color: red;
  }
}
```

should be compiled as:

```css
html /deep/ input {
  color: blue;
}
html /deep/ button {
  color: red;
}
```

but instead is compiled to:

```css
html input {
  color: blue;
}
html button {
  color: red;
}
```

**Comment by bassjobsen** [comment]
In Less `/deep/` has been implemented as a combinator (see also: https://github.com/less/less.js/issues/2023) a combinator should always be followed by an selector (see: also https://github.com/less/less.js/issues/1949)

For the same reason for instance the following code does not work too:

```less
p + {
p {
c:1;
}
}
```

In you situation you should write:

```less
html  {
 /deep/ input {
    color: blue;
  }

  /deep/ button {
    color: red;
  }
}
```
