### ISSUE TITLE
:extend doesn't work with nested blocks

### ISSUE THREAD

**Issue by tomekwi** [less/less.js#2460]
```less
.mother {
  parent: rules;

  .child {
    child: rules;
  }
}

.father {
  &:extend(.mother);
}
```

This outputs:
```css
.mother,
.father {
  parent: rules;
}
.mother .child {
  child: rules;
}
```

I'd rather expect:
```css
.mother,
.father {
  parent: rules;
}
.mother .child,
.father .child {
  child: rules;
}
```

Criticism welcome :)
