### ISSUE TITLE
Overwrite variables with the ones passed to less.render()

### ISSUE THREAD

**Issue by kuus** [less/less.js#2466]
How can I pass variables to the render function so to overwrite the ones defined in the less code I'm parsing?

From the following code:
```less
less.render('@tint: 'red'; .el { color: @tint) }', {
  myVars: { '@tint': 'blue' }
});
```
I'd like to get this output:
```css
.el {
  color: blue
}
```

It is maybe already possible but I can't find it in the docs.
Using `globalVars` in the object (in the second argument of `less.render`) doesn't override the variables defined in the less code.

**Comment by kuus** [comment]
sorry, I had to use `modifyVars`. 
```less
less.render('@tint: 'red'; .el { color: @tint) }', {
  modifyVars: { '@tint': 'blue' }
});
```
You can close this.
