### ISSUE TITLE
Please provide a way to merge lists

### ISSUE THREAD

**Issue by rjgotten** [less/less.js#2467]
While there are `extract` and `length` functions available, there is currently no function available to merge two lists together. This is **not** equivalent to simply listing two list-type variables in succession, which produces a list of lists. E.g.

```less
.join-test( a b c ; 1 2 3 );
.join-test(@first, @second) {
  @joined : @first @second;
 length : length(@joined);
}

// OUTPUT:
length : 2;
```

Using a `@param...` rest parameter or the special `@arguments` variable and passing in two lists similarly produces (or atleast; seems to produce) a list of lists. These three cases are all behaving as expected, ofcourse: it should be possible to assemble lists of lists.

However, this leaves us without a way to concatenate lists or to concatenate elements to existing lists. As the LESS language heavily relies on tail recursion for iteration, I'd expect there to be a common supported pattern to aggregate head values into one joined list as is common with list manipulation in functional languages (with or without the use of list comprehension).

I'm thinking of something like the following:

```less
.map(@list, @ruleset) {
  @n : length(@list);

  .iterator(0);
  .iterator(@i, @aggregator...) when (@i < @n) {
     @item : extract(@list, @i+1);

     // ( ... Insert some arbitrary logic mapping `@item into `@mapped` ... )
     @mapped : ??? 

     // Use a 'join' function to concatenate the mapped item to the existing list 
     // and iterate further.
     .iterator(@i+1, join(@aggregator, @mapped));
   }
  }

 .iterator(@i, @aggregator...) when (@i = @n) {
    // After having run the entire list, perform some action with the
    // mapped result, e.g. passing it off to a detached ruleset via
    // the calling scope's closure.
    & {
      @mapped_list : @aggregator;
      @ruleset();
    }
  }
}
```

There is a  `+:` syntax available for merging CSS properties into lists as well. An alternative over a `join` function would be to widen that syntax to include variable support. Somehow that does not feel quite right though.
