### ISSUE TITLE
How can I fix this with less?

### ISSUE THREAD

**Issue by ND-linwei** [less/less.js#2495]
@media screen\9{
}

**Comment by SomMeri** [comment]
You can put escaped value into variable and print media query from it:
````less
@variable: ~"screen\9";
@media @variable {
  h1{property: value;}
}
````

compiles into:
````
@media screen\9 {
  h1 {
    property: value;
  }
}
````
