### ISSUE TITLE
Feature: Allow setting arguments to empty rulesets in mixin definitions

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#2496]
It'd be super nice to able to set a default for a mixin argument to an empty ruleset in the mixin definition.

```less
.mixin(@size: 30px; @padding: 30px; @additions: {}) {
  height: @size;
  width: @size;
  padding: @padding;
  @additions();
}
```

-----

#### Workaround

The workaround I'm using at the moment isn't too bad.  It'd still be nice if the variables worked in mixin definitions the same way they work in variable definition.

```less
@_RULESET: {}; // Set some variable to an empty ruleset

.mixin(@size: 30px; @padding: 30px; @additions: @_RULESET;) {
  height: @size;
  width: @size;
  padding: @padding;
  @additions();
}
```
