### ISSUE TITLE
::before may shall can contain &.-selectors

### ISSUE THREAD

**Issue by enexusde** [less/less.js#2498]
You know ::before is a pseudo-selector.
In Example: 

I use ::before to add a image to a element. But if the element has a css-class of name "selected" a different image-positions should be used:
```css
 .item {
   display:inline-block;
   width: 16px;
   height: 16px;
   content: ''; 
   &::before{
     background: url(foobar.png) -32px 0px;
     &.selected { <-- support missing
       background-position: -16px 0px;
     }
   }
 }
```
This will create this invalid css:
```css
 .item::before.selected {
```
I expected to become
```css
 .item.selected::before {
```

Workaround:
Split the declarations: 
```css
 .item {
   display:inline-block;
   width: 16px;
   height: 16px;
   content: ''; 
   &::before{
     background: url(foobar.png) -32px 0px;
   }
   &.selected::before {
     background-position: -16px 0px;
   }
 }
```
