### ISSUE TITLE
how to override a mixin ??

### ISSUE THREAD

**Issue by argb** [less/less.js#2532]
in bootstrap there is a mixin 
// Responsive image
//
// Keep images from scaling beyond the width of their parents.

``` less
.img-responsive(@display: block) {
  display: @display;
  max-width: 100%; // Part 1: Set a maximum relative to the parent
  height: auto; // Part 2: Scale the height according to the width, otherwise you get stretching
}
```

note that the last statement-> height:auto ,This is really bad idea,I need to set a fixed size image attribute like `<img width="300px" height="200px".../>`,but you know it don't work, so i want to override the mixin to this:

``` less
.img-responsive(@display: block) {
  display: @display;
  max-width: 100%; // Part 1: Set a maximum relative to the parent
}
```

you know it don't work too,so bad...
bootstrap shouldn't set the style,and less should let me override it,is there any way to fix the problem?

**Comment by seven-phases-max** [comment]
>This is really bad idea,I need to set a fixed size image attribute

Then just set it. You do realize that setting a `height: 200px` after `height: auto` will override the latter, don't you?

Either you can't override a mixin<sup>[**1**]</sup>. Just like you can't override a CSS class for example but just like in CSS you can cascade it and override its properties. 

---
<sup>[**1**]</sup> - unless the initial mixin is defined with [`default() guard`](http://lesscss.org/features/#mixin-guards-feature-conditional-mixins) or so, but this is another story and most likely never be the case in Bootstrap.

**Comment by seven-phases-max** [comment]
I'm pretty sure it shoud be a duplicate of this FR somewhere around though I can't find it right now (related but not the same: #1372).

**Comment by argb** [comment]
height: auto can make thumbnail looks weird ,

media="all"
.img-responsive, .thumbnail>img, .thumbnail a>img, .carousel-inner>.item>img, .carousel-inner>.item>a>img {
  display: block;
  max-width: 100%;
  height: auto;
}
in this case that I have some images use the .thumbnail class,but images' size is different,I want to force set set same size to make sure the page not being mass,but this height:auto style stop me doing it,that's why I think it's wrong.

**Comment by seven-phases-max** [comment]
Again: please use [backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to format your code.

---

>but images' size is different,I want to force set set same size

I think this is more like a question for Bootstrap guys, but in short:
See my example above, you need to fix the size of the container (yes, you will need one container per a thumb (that's quite common pattern actually)) and not the size of the image itself.
And if you still need to set the image size directly for some reason you should not use BS `.thumbnail` class then, just write you own class(es) instead (e.g. `my-fixed-size-thumbnail`).
Yet, again if you remove `height: auto` from `.img-responsive` it just *can't* be named "responsive" anymore simply by definition.

**Comment by argb** [comment]
Anyway,thanks for your kind reply. Goodnight!

**Comment by OrganicPanda** [comment]
It would be great to consider some syntax to make this possible, it seems completely backwards to me.

It makes working with Bootstrap (I would guess the most widely used instance of less) awkward when you need to make changes. If i want to change the padding of buttons by 2px (for example) my CSS gets out put as 
```css
.btn {
  /* ... */
  padding: 8px 24px;
  padding: 6px 24px;
  /* ... */
}
```
Which just seems weird, there is no benefit over simply adding `.btn { padding: 6px 24px }` to my css. I would have thought that less had my back here :(

**Comment by matthew-dean** [comment]
@OrganicPanda 
Even as a contributor and frequent user of Less, I often forget that overriding properties is not simple. More importantly, it's outside the scope of Less. Because of things like:
```css
.row {
  display: table;  // non flexbox browsers
  display: flex;
}
```
Other tools like Pleeeease (or however many e's it has), or other such CSS shimming tools can determine which properties can be safely dropped / minified based on the a) values used and the b) browsers targeted, c) the current usage of those browsers. Tracking all of those components and how they apply to each property is not the goal of Less. Less is a tool for writing CSS, but it doesn't have an opinion on whether your CSS properties are valid or redundant in a particular browser.
