### ISSUE TITLE
Am I crazy, or is it literally impossible to namespace an imported less file?

### ISSUE THREAD

**Issue by GregLancaster71** [less/less.js#2535]
I have spent the last several hours reading, and googling how to accomplish this.  My only goal is to @import four files containing mixins.  However, they are borrowed and repurposed from bootstraps grid system so I need them namespaced.  Why is this damn near impossible to do?  

Can someone help me out here?  Even a decent, in depth tutorial link on scoping would be great.  I mean seriously, several hours just trying to import some damn mixins and variables?  I see bootstrap imports mixins without any issue - but they dont use any name spacing.

**Comment by matthew-dean** [comment]
You mean as in:
```less
#mynamespace {
  .mixin() {
    foo: bar;
  }
}
.demo {
  #mynamespace.mixin();
}
```
Like that?
