### ISSUE TITLE
Feature Request: Support lists for selector interpolation

### ISSUE THREAD

**Issue by SLaks** [less/less.js#2544]
If I interpolate a list variable in a selector, can you expand it into multiple selectors when nesting?

For example:

**Source**
```less
@tags: a, b, code, dd;

@{tags} {
  &:hover {
   color: red; 
  }
}
```

**Current Output**
```css
a, b, code, dd:hover {
  color: red;
}
```

**Desired Output**
```css
a:hover, b:hover, code:hover, dd:hover {
  color: red;
}
```
