### ISSUE TITLE
red, green and blue functions return float instead of integer

### ISSUE THREAD

**Issue by olmokramer** [less/less.js#2549]
Take following snippet:
```less
@color: #f59e47;

@new-color: saturate(@color, 10%);

@color-cursor: rbga(
  red(@new-color),
  green(@new-color),
  blue(@new-color),
  .8
);

.cursor {
  background-color: @color-cursor;
}
```
it produces this:
```css
.cursor {
  background-color: rbga(254.7, 158, 61.3, 0.8); /* note the illegal floats */
}
```
but I would expect it to produce this: (according to the docs it should)
```css
.cursor {
  background-color: rbga(255, 158, 61, 0.8);
}
```
This happened with `lessc` version `2.5.0`
