### ISSUE TITLE
Parent selectors and multiple classes

### ISSUE THREAD

**Issue by matb33** [less/less.js#2552]
```less
.example {
  background-color: white;
}

html.supports-color {
  .example {
    background-color: red;
    &.doesnt-support-red & {
      background-color: green;
    }
  }
}
```

I'd expect this rule to be generated:
```css
html.supports-color.doesnt-support-red .example {
  background-color: green;
}
```

However, I believe the `&` in `&.doesnt-support-red` doesn't carry its significance when changing selector order in this manner, and probably results in `.doesnt-support-red html.supports-color .example { ...`

**Comment by seven-phases-max** [comment]
#1075 is probably what will fit this use-case...

---
Rhe method you're suggesting, i.e. "changing `&` meaning and binding it to a specific parent selector element basing on the particular count/position of the `&` itself", is probably too specific and cryptic, e.g:
```
a.b {
    .c {
        .d {
            background-color: red;
            &.e & {
                background-color: green;
            }
        }
    }
}
```
What would you expect in this case?

**Comment by matb33** [comment]
I'd expect:

```css
a.b .c .d {
  background-color: red;
}
a.b.e .c .d {
  background-color: green;
}
```

**Comment by matb33** [comment]
To be clear, I am not suggesting changing the meaning of `&` nor basing anything on counts and positions. Just tack the selector (i.e. `&.e`) to the front, but take into account the fact that the `&` implies it should be combined with the top-most selector instead of preceding it.

**Comment by seven-phases-max** [comment]
>Just tack the selector to the top-most selector, but take into account the fact that the `&` implies it should be combined with the top-most selector instead of preceding it.

Hmm, no. This is not how it was made to work originally (there's nothing special any the top-most selector to behave differently). And this way it will just break [existing behaviour](http://lesscss.org/features/#parent-selectors-feature-changing-selector-order). So I'm afraid this is not going to be changed. 

---
For your specific use-case just add some unique class/id to the `html` element and the following code will produce equivalent CSS styles:
```
.html.supports-color {
  .example {
    background-color: red;
    .doesnt-support-red& {
      background-color: green;
    }
  }
}
```

**Comment by matb33** [comment]
Based on your example suggestion, I believe you haven't understood what I'm explaining. Also, your example won't work, you'll get:

```css
.doesnt-support-red html.supports-color .example {
  background-color: red;
}
```

Assume that `doesnt-support-red` and `supports-color` are Modernizr classes that are both added to the `<html>` class.

For example: `<html class="doesnt-support-red supports-color">`

In order for your example to "work", we'd need the following to work:

```less
html.supports-color {
  .example {
    background-color: red;
    &.doesnt-support-red & {
      background-color: green;
    }
  }
}
```
