### ISSUE TITLE
Saturating a gray scale value turns red

### ISSUE THREAD

**Issue by jennevdmeer** [less/less.js#2557]
Saturating a gray scale value turns the result red while this should stay gray (unless I'm missing something).

![less example/ photoshop/ expected result](http://i.imgur.com/T891gRJ.png)

## Less used to create example
```less
@size: 10px;
@colors: #333, #666, #ccc, #737d1d, #ad46b5, #2eccdc, #600, #c00, #060;

div {
	border: @size solid black;
	display: inline-block;
	padding: @size;
	margin: @size;
	width: 150px;
	text-align: center;
}

.loop(@i: length(@colors)) when (@i > 0) {
	@color: extract(@colors, @i);

	div:nth-child(@{i}) {
		background-color: @color;
		border-color: saturate(@color, 100);

		color: contrast(@color);
	}
	.loop(@i - 1);
}
.loop;
```
