### ISSUE TITLE
Guard in mixin in namespace throws internal error

### ISSUE THREAD

**Issue by SLaks** [less/less.js#2558]
Source:

```less
@q: true;
#a.b();

#a {
	.b() when (@q) {
	}
}
```

Error: `Syntax error: Cannot read property 'variable' of undefined`

This happens because `env.frames` contains `undefined`
