### ISSUE TITLE
Relative data-uri option

### ISSUE THREAD

**Issue by JedWatson** [less/less.js#2560]
Apologies if I've missed the mark with this one - the documentation doesn't actually explain the path resolution behaviour so I'm guessing a bit.

From what I can tell, the `data-uri(...)` function will find files relative to the _entry_ less file's location on disk. This makes sense, it's similar to how `url(...)` will point to a location relative to the css file that ends up being loaded in the browser, regardless of whether the less code was in another directory (e.g an include).

I'm developing a component that can be used across multiple projects, published on npm + bower. Providing assets in components is tricky, so I am hoping to use the `data-uri` feature to inline image resources (i.e icons) for the component.

Anyone using the component can include my component's less file in their project's stylesheet like this:

```
@import "../node_modules/react-select/less/component.less";
```

This has a lot of other benefits (developers can override the theme variables, etc.)

However, in this scenario `data-uri` breaks because I can't know the relative path from their LESS file to my bundled static images (which are provided in `node_modules/react-select/images`).

If there were a way to use a **relative** data-uri function (where the path is relative to the less file being processed and not the entry point) then bundling the component would be as simple as adding the line above, and my component's less could inline the images like

```
background-image: data-uri("../images/dropdown.png");
```

So it could either be a function that lets me access the current directory of the less file and build the URL from that (like node's `__dirname` variable) or it could more simply be an argument / different function name. some examples:

```
background-image: data-uri(current-path() + "../images/dropdown.png");
// or
background-image: data-uri("!../images/dropdown.png");
// or
background-image: data-uri("../images/dropdown.png", true);
// or
background-image: relative-data-uri("../images/dropdown.png");
```

I personally think that the `relative-data-uri` function name is clearest, but really anything that lets me achieve this would be brilliant!

**Comment by seven-phases-max** [comment]
What about just providing a path variable so that a library user could adjust the path on his own when necessary? E.g.:
```less
// user code

@react-select-path: "../node_modules/react-select";
@import "@{react-select-path}/less/component.less";

// ...................................
// your code (i.e. the component.less)

@react-select-path: ".."; // default value

something {
    background-image: data-uri("@{react-select-path}/images/dropdown.png");
}
```

This is common approach to handle such things (for example [1](https://github.com/twbs/bootstrap/blob/v3.3.4/less/glyphicons.less#L13), [2](https://github.com/FortAwesome/Font-Awesome/blob/v4.3.0/less/path.less) etc.)

Also see [--relative-urls](http://lesscss.org/usage/#command-line-usage-relative-urls) (currenty this option applies to `data-uri` as well).

---

As for things like `current-path()`, probably it will do the trick for a static CSS rulesets, but becomes absolutely useless for a more generic libraries (e.g. within a mixin such function will return a path of the file where the mixin is invoked instead of where it's defined).
