### ISSUE TITLE
Compile option to keep mixins as classes in output

### ISSUE THREAD

**Issue by CBung** [less/less.js#2563]
Would it be possible to have an option to keep mixins as classes in the output source? This would really help when doing SMACSS type development.

    .mixin(){ color: red; }
    p { .mixin }

Could output:

    p { color: red; }

Or

    .mixin { color: red; }
    p { color: red; }

**Comment by seven-phases-max** [comment]
Hmm, I'd say unlikely (use-case?). At least my -1 for that.
```less
.mixins {
    .mixin-1() {
        color: red; 
    }
    
    .mixin-3() {
        color: green;
    }
}
```
and use like (all names are obvoisly up to you):
```less
p {.mixins.mixin-1}
a {.mixins.mixin-2}
```
then when you need all those "mixins" to appear in the CSS, just write
```less
.mixins; // trah-tee-bee-douh!
```

and... boom, they are all there.
