### ISSUE TITLE
Variable/List merging/concat functions and language features

### ISSUE THREAD

**Issue by KevinMartin** [less/less.js#2564]
I was looking through the feature documentation, and I noticed we can easily merge *properties*, but not *variables*.

I noticed #2467, but I felt like this should be part of the core language. Some examples:

```less
// Example 1 - Sometimes, you just want it to be more reader friendly (especially if you have long lists):
@comma: a b c;
@comma+: d e f;

@space: a b c;
@space+_: d e f;

// Suggested Parser Interpretation:
@comma: a b c, d e f; // A parent list that contains two child lists with 3 items in each.
@space: a b c d e f; // One super list with 6 items within it.
```

```less
// Example 2 - Sometimes, you have special conditions:
@base: g h i;

& when (@condition = true) {
    @base+: j k l; // There might be a scoping issue here?
}

.special-mixin();
.special-mixin() {
    @base+: m n o;
}

// Suggested Parser Interpretation:
@base: g h i, j k l, m n o;
```

```less
// Example 3 - As functions (suggested as a plugin in #2467; maybe naming could be different?)
@first: a b c;
@second: d, e, f;

@merged: merge(@first, @second);
@concated: concat(@first, @second);

// Suggested Parser Interpretation:
@merged: a b c, d e f; // A parent list that contains two child lists with 3 items in each.
@concated: a b c d e f; // One super list with 6 items within it.
```

While creating my own mixin to simulate Example 3, I found a kind of discrepancy...
```less
// LESS
.merge(@rest...) {
  @joined: @rest;
}

.test1 {
  @first: a b c;
  @second: d, e, f;
  .merge(@first, @second);

  firstLength: length(@first);
  secondLength: length(@second);
  joinedLength: length(@joined);
  joinedList: @joined;
}

.test2 {
  @first: a b c;
  @second: d e f;
  .merge(@first, @second);

  firstLength: length(@first);
  secondLength: length(@second);
  joinedLength: length(@joined);
  joinedList: @joined;
}

// Expected Output
.test1 {
  firstLength: 3;
  secondLength: 3;
  joinedLength: 2;
  joinedList: a b c, d e f;
}
.test2 {
  firstLength: 3;
  secondLength: 3;
  joinedLength: 2;
  joinedList: a b c, d e f;
}

// Actual Output
.test1 {
  firstLength: 3;
  secondLength: 3;
  joinedLength: 2;
  joinedList: a b c d, e, f;
}
.test2 {
  firstLength: 3;
  secondLength: 3;
  joinedLength: 2;
  joinedList: a b c d e f;
}
```

The suggested core language improvements and functions could definitely help clarify/fix/prevent the above issue and allow the Examples to executed.

**Comment by seven-phases-max** [comment]
>`@comma+: d e f;`

This is simply impossible because of declarative nature of the language. Less variables are actually immutable and stateless, so you cannot *modify* the value of a variable but can only redefine/override it with a *new* variable of the same name. For the same reason you cannot do anything like `@var: @var + 1;` too. And for the same reason you cannot have a mixin or a built-in function that *modifies* a variable value (both can only produce a modified copy). (See also a notice about corresponding "property merge" syntax below).

>I noticed #2467, but I felt like this should be part of the core language.

I'm afraid things like "felt" are not quite something that can become a rationale to put a feature into the core.
Beside #2467, earlier there're were several suggestions to add `join/concat`-like funtions to the core (for example https://github.com/less/less.js/issues/1785#issuecomment-31884999 + a few more), but overall community demand for this stuff seems too be pretty negligible (yet?). For example compare #2467//#1857 to #1075 or #1177 to actually "feel" the difference ;). 
So in context of "community demand" it would be much more helpful to just stamp `+1` in #2467 (and purpose your syntax idea there) instead of creating a new sort of duplicated ticket.

---

Either way for list/array manipulation functions see [`less-plugin-lists`](https://github.com/seven-phases-max/less-plugin-lists).
Also see related #1857 (same hint: simply put your +1 there).

---
<sub>
Regarding of the property merge feature, strictly speaking its syntax is a direct violation of CSS and Less "declarativness", i.e. the property merge statements are clearely imperative. Forunately this is not a critical defect (yet) because CSS properties are currently "write-only" and every non-duplicated property/value pair should appear in the CSS output (yet another help there is that `property: value` and `property+: value` statements create two independent property "layers"). But for sure this will become a problem when/if we decide to implement #2433 or so.
</sub>

**Comment by seven-phases-max** [comment]
I'm not closing this ticket yet (just in case anyone wnats to express an opinion on the partucular syntax). But honestly, aside form special syntax, this is really no more then just a duplicate of #2467 and if you believe there're some reasons for such have dedicated syntax rathe than trivial functions please express this idea there (closed issues/feature-requests can be reopened at any moment).

**Comment by matthew-dean** [comment]
@seven-phases-max How would that reflect on #2433? That is, if we could treat properties like variables, does that mean it would conflict with property merging? It seems not quite right to say it's impossible, but just that it's difficult with the current code?

**Comment by seven-phases-max** [comment]
@matthew-dean
>It seems not quite right to say it's impossible, but just that it's difficult with the current code?

I would not say it's imposible or even difficult at all. It's just will create a weird mix of imperative and declarative stuff that pretty hard to follow with LL and LDW in mind, e.g.:
```
// less:
div {
    p+: 1;
    p : 2;
    p+: 3;
    x : property(p);
}

// -> css:
div {
    p: 1, 3;
    p: 2;
    x: ?; // p is 2 at this point, but id not we appended 3 in the end?
}
```

It could be considered like nothing bad at all (-> just declare "don't use merging if you read properties, the result is undefined/unspecified"). But this certainly is not something to model normal Less variables concatenation after.

**Comment by matthew-dean** [comment]
Actually, your example seems straightforward to me. Less specifies that properties are merged only if both are marked as mergeable. I don't know what current *behavior* is, but the following would be my expectation:
```
// less:
div {
    p+: 1;  // p = 1, but is "marked" mergeable
    p : 2;   // p = 2. it is not marked mergeable. since it is a later declaration in the scope, final value is 2
    p+: 3;  // p = 3, and is marked mergeable, however the only other mergeable declaration has been overwritten in scope by a subsequent non-mergeable declaration, so nothing is merged
    x : property(p);  // p is 3
}
```
If the output is as you just specified (I just checked, and it is, yikes), this is an error in implementation. The ```+:``` syntax marks mergeability, but that cannot take precedence over the cascade (last declaration wins). If Less is simply looking for mergeable properties, and merging them wherever they occur in scope, that's incorrect because it changes declaration order. We can't do that for the same reason we don't do ```@media``` block merging.

That is, the last declaration of ```p+: 3``` *cannot move*. It is still a declaration of a value of 3 at that position in the rules. Because of the ```+``` it can "consume" preceding mergeable declarations, but it can't be moved to previous values. That's an error. If no previous mergeables existed, the final value would not move its position, as in:

```
// less
div {
    p : 2;
    p+: 3;
}

// css
div {
  p: 2;
  p: 3;
}
```
Now I would consider an argument that the final value could be ```1, 3```, but that would seem to violate the intent of merging, which is to only produce that behavior when all property declarations are marked as such. But, you could say, that declaratively, merging happens for the last value because of previous mergeables in-scope. So, maybe it's more declarative to have it as ```1, 3```, I don't know. But, however you slice it, a final value of 2 is wrong, and you note yourself: didn't we append 3 at the end? A value of 2 is a serious bug.

The other Less quirk that makes this issue weird is that Less leaves conflicting declarations in final rules for no understandable reason.

That is:
```
// css
div {
  p: 2;
  p: 3;
}
```
Because of CSS, the value of p is always 3. To include previous property declarations is weird. One might say it's there because it existed in the source Less, but that seems overly dogmatic. In reality, a property only ends up with one value, just like a variable.

As to this: 

> Regarding of the property merge feature, strictly speaking its syntax is a direct violation of CSS and Less "declarativeness", i.e. the property merge statements are clearly imperative. 

Maybe. There isn't 100% consensus on the categories or differences between those two terms. But, yes, in general I think we try to implement things based on "traditional declarativeness". In this case, however, pragmatism wins. The nature of CSS (mostly a problem of CSS3), combined with how Less defines mixins, means that authors inevitably have encountered situations of wanting to declare "optional partial overwrites" of declarations, since CSS3 defines some "shorthand" syntax for which there is no way to separate into individual longhand declarations, which breaks with the CSS 2.1 model. Merging is a legitimate practical solution and meets Less's core directive, which is to make writing and managing CSS easier. Less's core directive is not to make sure all features pass a declarative test, even though it's important to do as much as possible for consistency.

As far as this feature, if we addressed that bug and quirk of Less regarding properties, then this request in relation to variables would, I think, make more sense. Meaning, it would make it clear that properties end up with only one value, (and don't move), so incorporating variables into similar declarations wouldn't seem as far-fetched.

**Comment by matthew-dean** [comment]
Yes, thinking about it more, the final value should probably be ```1, 3```. The way these declarations should probably be thought about is like this.

```
// less:
div {
    p+: 1;
    p : 2;
    p+: 3;
}

// -> css (not desired output, but effectively)
div {
    p: 1;
    p: 2;
    p: 1,3;
}
// -> css (ideal output)
div {
    p: 1,3;
}
```

**Comment by seven-phases-max** [comment]
>The other Less quirk that makes this issue weird is that Less leaves conflicting declarations in final rules for no understandable reason.

There's reason to leave non identical property values in the ourput (most obviouse example):
```css
div {
   background: rgb(200, 54, 54); /* Hello IE6 etc. */
   background: rgba(200, 54, 54, 0.5); 
}
```
