### ISSUE TITLE
incorrect compilation

### ISSUE THREAD

**Issue by ademaro** [less/less.js#2565]
gulp-less (last version 3.0.3) compiles these lines wrong:
https://github.com/twbs/bootstrap/blob/master/less/forms.less#L54-L55

```css 
input[type="radio"],
input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9; // IE8-9
  ...
}
```
into this: 
```css
input[type="radio"],
input[type="checkbox"] {
  margin: 1px 0 0;
}
```
instead of:
```css
input[type="radio"],
input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9;
}
```
