### ISSUE TITLE
Lighten color more than 50% won't compile

### ISSUE THREAD

**Issue by fanart** [less/less.js#2582]
The lighten color more than 50% is not working. i.e. color: lighten(red, 60%); but it works with percentage lower than 50%.

**Comment by seven-phases-max** [comment]
>won't compile 

So what error message do you get?

>is not working

Please read [Reporting Issues](https://github.com/less/less.js/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by jasonwilliams200OK** [comment]
@fanart

```less
.test {
  color: lighten(red, 50%);  // and any value higher than 50%
}
```

results in:

```css
a {
  color: #ffffff; /* white */
}
```

which is correct. This is in accord with [CSS3 HSL specification](http://en.wikipedia.org/wiki/HSL_and_HSV#Conversion_from_RGB_to_HSL_or_HSV) (algorithm).
