### ISSUE TITLE
 less-plugin-clean-css has some problem of "background" property

### ISSUE THREAD

**Issue by fangge** [less/less.js#2584]
The less-plugin-clean-css@1.5.0 has something wrong with compressing the “background” property.

```css
#wrap1{background: url(../img/bg.jpg) no-repeat center 0}
```

compress to
```css
#wrap2{background:url(../img/bg2.jpg)no-repeat center bottom}
```
"no-repeat" sticking together with ")"

This results in IE8 does not recognize this property
