### ISSUE TITLE
Transparency can't be lightened or darkened and no error message

### ISSUE THREAD

**Issue by lukeaus** [less/less.js#2588]
Now I am aware that its illogical to lighten or darken transparency...

that being said, it would be good if an attempt to do so threw an error

Im using an older version of lessc (2.0.0-beta.0)so this may have been fixed already, but I couldn't find any existing issues.

I had a function:
```less
.btn-common (
    @color-text: @white,
    @color-bg: @brand-primary,
    @color-border-top: lighten(@color-bg, 5%),
    @color-border-bottom: darken(@color-bg, 20%),
  ) {
  .BorderRadius;
  .NoBorderNoShadow;
  color: @color-text !important;
  background-color: @color-bg !important;
  background-image: none !important;
  border-left: none;
  border-right: none;
  border-top: 2px solid @color-border-top !important;
  border-bottom: 2px solid @color-border-bottom !important;
}
```
and then I was calling this function
```less
  .btn-common(@drkgrey, transparent);
```

which didn't work, and took me a while to figure out what was going on

this does work however
```less
  .btn-common(@drkgrey,
              transparent,
              transparent,
              transparent);
```
So basically it would be good to throw an error if attempting to lighten or darken transparent

Thanks team Less!
