### ISSUE TITLE
Double class name in selector

### ISSUE THREAD

**Issue by kirill-konshin** [less/less.js#2589]
When LESS version of Twitter Bootstrap is wrapped with a class:

```less
.Bootstrap {
    @import "bower_components/bootstrap/less/bootstrap";
}
```

It produces:

```css
.Bootstrap .Bootstrap .nav:before,
.Bootstrap .Bootstrap .nav:after {
  content: " ";
  display: table;
}
```

All other definitions are correctly wrapped with only one `.Bootstrap` class.

Definition of .nav:

```less
.nav {
  &:extend(.clearfix all);

...

.clearfix() {
  &:before,
  &:after {
    content: " "; // 1
    display: table; // 2
  }
  &:after {
    clear: both;
  }
}
```
