### ISSUE TITLE
`@import (important)` for higher "specificity" variables

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#2590]
~~I've thought recently about how theming and overriding would be so much easier if I could specify that my definitions are `!important`.  That is,~~

```less
// my.variables.less
@theme-var: value !important;

// 3rd-party-library.variables.less
@theme-var: default value;

// 3rd-party-library.core.less
.this {
  uses: @theme-var; // → `value`
}
```

~~In other words, `!important` would do for Less variables what it does for CSS properties: increase the "strength" of the declaration.~~

~~I realize this may cause headaches (`!important` in variables is already a question in #2374) but it seems like a super useful feature for a major use case for Less.~~

### Edit:

Sorry, just noticed this is a duplicate of #1401 (I forgot to search closed issues).  I'm gonna leave the issue open for the `@import (important)` suggestion (see below) since many of the objections brought up in 1401 don't really apply there.  I'll change the issue title, for clarity.
