### ISSUE TITLE
url  Compile

### ISSUE THREAD

**Issue by YYQH** [less/less.js#2598]
```less
.IE6Background(@url: none) when (isstring(@url)){
    background-image: url('@{url}');
    _background-image: none;
    _filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src="@{url}",enabled=true,sizingMethod="crop");
}
.banner-des-bg4ie6{
	.IE6Background('../img/ui.png');
}
```
after Compile, I find the same url param ,but output two result
```less
.banner .banner-img .banner-descript .banner-des-bg4ie6 {
  background-image: url('../lib/img/ui.png');
  _background-image: none;
  _filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src="../img/ui.png", enabled=true, sizingMethod="crop");
  margin: 0 -168px;
}
```
