### ISSUE TITLE
Support json (to pass in arrays)

### ISSUE THREAD

**Issue by thecotne** [less/less.js#2601]
so i have project https://github.com/thecotne/square-file-icons
i want change from lodash template to less
since it makes more sens for me to generate css with less

but i can't pass json to less.js
i can pass strings
but not objects and arrays of objects

i will be nice to support something like this 

```css
@foreach(@glyphs as @glyph) {
	.@{glyph.name} {
		content: "\\@{glyph.char}";
	}
}
```

glyphs is array of objects passed from modifyVars

**Comment by seven-phases-max** [comment]
You actually can pass array of values via `modifyVars`, e.g: `@glyphs: a, b, c, d, e, etc;`
I.e. "Arrays" in Less are just plain CSS comma and whitespace separated value lists. For more details and tips see:
* http://stackoverflow.com/questions/23658087
* http://stackoverflow.com/search?tab=relevance&q=%5bless%5d%20array
* http://stackoverflow.com/search?tab=votes&q=%5bless%5d%20loop
*etc.

**Comment by thecotne** [comment]
this `extract(extract(@array, ),2)` looks very weird (from one of links)
why not `@array[@iterator][2]` ?


what about objects?

i want something like this to work with less code above
```js
less({
	modifyVars: {
		glyphs: [
			{
				name: 'first glyph',
				char: '1'
			}, {
				name: 'second glyph',
				char: '2'
			}, {
				name: 'x glyph',
				char: 'x'
			}
		]
	}
})
```


also simple things like foreach must be simple not complex like this
```
.example_module {
    .-(@i: length(@colors)) when (@i > 0) {
        @name: extract(@colors, @i);
        &.@{name} {background: @@name}
        .-((@i - 1));
    } .-;
}
```

**Comment by seven-phases-max** [comment]
>why not  @array[@iterator][2]  ?

Because Less is a CSS extension, not a JavaScript or PHP extension... (and CSS `[]` is a radically different thing).
If you're looking for a PHP-like CSS scripting consider Sass.

Technically, for an icon list you don't even need any array and a loop at all (as it can be generated via ["list of mixins"](http://stackoverflow.com/a/26435364/2712740)), e.g.:
```less
.glyphs() {
    // "array" of icons
    .-(foo, "a");
    .-(bar, "b");
    .-(baz, "c");
    .-(qux, "d");
}

// generate icons classes:

& {
    .glyphs()
    .-(@name, @icon) {
        .@{name} {
            content: @icon
        }
    }
}
```
