### ISSUE TITLE
Using :extend with BEM

### ISSUE THREAD

**Issue by dangreen** [less/less.js#2608]
This code doesn't work.

```less
.purchase__actions {

	&__cell {
		display: inline-block;
		width: 50%;
		box-sizing: border-box;

		&--full:extend(&) {
			width: 100%;
			padding: 0 15px !important;
		}
	}
}
```
