### ISSUE TITLE
Math not computed for media queries

### ISSUE THREAD

**Issue by dandv** [less/less.js#2625]
```less
@size: 40px;

svg {
    width: @size * 2;  // great: 80px

    @media (max-width: 2 * @size) {  // wrong: "2 * 40px"
      display: none;
    }
}
```

=>

```css
svg {
  width: 80px;
}
@media (max-width: 2 * 4px) {
  svg {
    display: none;
  }
}
```

**Comment by seven-phases-max** [comment]
Known issue. See #1480. As workaround always use parens for values used in media queries, e.g.
```less
@size: 40px;

svg {
    @media (max-width: (2 * @size)) {
        display: none;
    }
    
    @foo:  (50px + 25); // !
    @media (bar: @foo) {
        display: inline;
    }
}
```
