### ISSUE TITLE
Possible wrong compiled css

### ISSUE THREAD

**Issue by dosten** [less/less.js#2635]
Hi there!

I have a problem with some compiled css, after some research i've found the solution, the steps to reproduce are:

```less
// test.less

@import "mixins";

.widget {
	@import "desktop";
}
```

```less
// mixins.less

.clearfix() {
  &:before,
  &:after {
    content: " "; // 1
    display: table; // 2
  }
  &:after {
    clear: both;
  }
}

.make-row() {
  margin-left:  0;
  margin-right: 0;
  &:extend(.clearfix all);
}
```

```less
// desktop.less

.clearfix {
	.clearfix();
}

.wizard {
	.wizard-step {
		background-color: #fff;
		.make-row();
	}
}
```

Running `lessc test.less > test.css` the compiled css is:

```css
// test.css

.row {
  margin-left: 0;
  margin-right: 0;
}
.widget .clearfix:before,
.widget .clearfix:after,
.widget .row:before,
.widget .row:after,
.widget .widget .wizard .wizard-step:before,
.widget .widget .wizard .wizard-step:after {
  content: " ";
  display: table;
}
.widget .clearfix:after,
.widget .row:after,
.widget .widget .wizard .wizard-step:after {
  clear: both;
}
.widget .wizard .wizard-step {
  background-color: #fff;
  margin-left: 0;
  margin-right: 0;
}
```

The problem is the double `.widget`, so, that styles are not used.
The solution is to define the clearfix outside of `.widget` but this adds `.clearfix` to the "global scope"

This is the expected behaviour? My LESS version is 2.2.0.

Thanks in advance.

**Comment by seven-phases-max** [comment]
No, this is actually expected output. See #2052 and #1850.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #1850.

**Comment by dosten** [comment]
@seven-phases-max Thanks

**Comment by seven-phases-max** [comment]
Just in case, I'd also remark that such (Bootsrap-like) relations between `.clearfix` class and .clearfix` mixin is quite unoptimal (they use this mostly for backward compatibility with there were no `extend`).
An oposite relation would be more handy:
```less
// auxiliary class to be never be used directly
.clearfix_ {
  &:before,
  &:after {
    content: " "; // 1
    display: table; // 2
  }
  &:after {
    clear: both;
  }
}

// mixin:
.clearfix() {&:extend(.clearfix_ all);}

// usage:
.make-row() {
    .clearfix();
}
```
That way (beside being less verbose in use) you also won't have to modify all appearances of `extend(.clearfix...` when the feature is improved or a better pattern comes out.
