### ISSUE TITLE
ParseError: Unrecognised input while using IE7,8,9 "\9" hack when value is in parentheses or in quotes

### ISSUE THREAD

**Issue by petetnt** [less/less.js#2636]
I was trying to include [SweetAlert's css](https://github.com/t4t5/sweetalert/blob/master/dist/sweetalert.css#L697) in my master stylesheet with `@import (less) 'sweetalert.css'` when `less` threw the ParseError

``` css
ParseError: Unrecognised input in C:\xyz\bower_components\sweetalert\dist\sweetalert.css on line 702, column 32:
701 .sweet-alert .sa-icon.sa-error .sa-line.sa-left {
702   -ms-transform: rotate(45deg) \9;
703  }
```

Turns out that every value that has paranthesis/quotes and has the [\9-hack](http://stackoverflow.com/a/8004962/2138943) fails. It is parsed correctly, however, for other values.

``` css
.class {
  color: #000\9; //works
  transform: rotate(-45deg); //works
  transform: rotate(-45deg)\9; //fails
  background-image: url("test.png"); //works
  background-image: url("test2.png")\9; //fails
  content: "test"; //works
  content: "test"\9; //fails 
}
```

``` bash
lessc -v
lessc 2.5.1 (Less Compiler) [JavaScript]
```
