### ISSUE TITLE
cache the parsing of an import if it was already seem before 

### ISSUE THREAD

**Issue by royriojas** [less/less.js#2640]
Hi guys, 

I just notice the build for a somehow complex less file was taking **about 4s**. I did some debug and found that the imports are parsed several times. Even when it was already previously parsed.

I have made a simple change to the import-manager as a proof of concept

https://github.com/royriojas/less.js/commit/b84e7c6a51f3f6221eb31ac3e1639caaa7c1c57f

with that small change the build time was reduced to **1.5s**, I guess because in my use case some files: (constants, mixins and others) were included several times from different files

The change I did is very naive, and we can make sure we create a cache for each instance of the less object created. 

Also, if we keep a file cache of files that were already parsed, this will a build be reduced to just milliseconds. Are there any plans of enabling something like that. Would be really nice to have.

**Comment by seven-phases-max** [comment]
This makes sense, though I'm afraid te implementation has to be a bit more complicated to take certain edge case into account (`@imports` may be context depended).

Consider the following example:

```less
// master.less
a {
    @i: 1;
    @import (multiple) "a";
}

b {
    @i: 2;
    @import (multiple) "b";
}
```
```less
// a.less
@import "b@{i}";
```
```less
// b1.less
div {
    color: red;
}
```
```less
// b2.less
div {
    color: blue;
}
```

But it's not that really complicated as it may look. Taking into account every `@import` except `(multiple)` implies [`(once)`](http://lesscss.org/features/#import-options-once), for simplicity I guess it would be fine can keep the same simple cache code and just don't use it for `multiple`. More over since `once` means the already imported (and those cached ) file should *not* be evaluated at all, there's no need for such cache at all - the compiler may safely completely skip reading/parsing a duplicated (non-`(multiple)`) import at all (somewhere earlier in the code).
