### ISSUE TITLE
get-unit in guards

### ISSUE THREAD

**Issue by Craigy-** [less/less.js#2647]
It is possible to make `get-unit` workable in mixin guards?
Like this:
```less
.mixin(@value) when not (get-unit(@value)) {
}
```
This hepls to separate non-unit values.

**Comment by SomMeri** [comment]
Would some of the following solve your issue? 

The result of `get-unit` can be compared to identifiers and escaped values:
````less
.mixin(@value) when (~"px" = get-unit(@value)) {
  escaped-true:get-unit(@value);
}
.mixin(@value) when not (~"px" = get-unit(@value)) {
  escaped-false:get-unit(@value);
}
.mixin(@value) when (px = get-unit(@value)) {
  identifier-true:get-unit(@value);
}
.mixin(@value) when not (px = get-unit(@value)) {
  identifier-false:get-unit(@value);
}

.mixin(@value) when (~"" = get-unit(@value)) {
  empty-true:get-unit(@value);
}
.mixin(@value) when not (~"" = get-unit(@value)) {
  empty-false:get-unit(@value);
}

px {
  .mixin(10px)
}

cm {
  .mixin(10cm)
}

empty {
  .mixin(10)
}
````

compiles into:
````less
px {
  escaped-true: px;
  identifier-true: px;
  empty-false: px;
}
cm {
  escaped-false: cm;
  identifier-false: cm;
  empty-false: cm;
}
empty {
  escaped-false: ;
  identifier-false: ;
  empty-true: ;
}
````
