### ISSUE TITLE
Variable doesn't evaluate when used with @media

### ISSUE THREAD

**Issue by petrbrzek** [less/less.js#2650]
Less version: 2. 5. 1.

Example:

```
@max-columns: 4;
@tile-size: 300px;
@tile-margin: 20px;
@content-container-max-width: (@tile-size + @tile-margin * 2) * @max-columns;



.project-manager__content-container {
  color: blue;
  width: @content-container-max-width;

  @media (min-width: @content-container-max-width) {
    color: red;
  }
}
```

Result:

```
.project-manager__content-container {
  color: blue;
  width: 1360px;
}
@media (min-width: (300px + 20px * 2) * 4) {
  .project-manager__content-container {
    color: red;
  }
}
```

**Comment by petrbrzek** [comment]
I found a workaround but it's obviously super ugly

```
@content-container-max-width: (@tile-size + @tile-margin * 2) * @max-columns;
@max-width: unit(~`(function(){var a = @{content-container-max-width}; return a;}())`, px);
```

**Comment by seven-phases-max** [comment]
See #1480. E.g.:
```less
@content-container-max-width: (@tile-size + @tile-margin * 2) * @max-columns;

@media (min-width: (@content-container-max-width)) {
    color: red;
}
```
