### ISSUE TITLE
Need to break the inheritance for nested class

### ISSUE THREAD

**Issue by AjithR04** [less/less.js#2657]
I have tried to compile the less to css using less.render function. I need to break the nested class inheritance from parent class. Is there a way to do this?

```less
// control.less 
 @widget: ""; // default value  
 .h-table when (@widget = Table) {   
  &.h-content, .h-td{
    background-color: #3c3c3c;    
  }   
  .h-td{ // I want here to break the inheritance.
    font: red;
  }
  }
```
The output likes below
```css
.h-table.h-content,
.h-table .h-td {
  background-color: #3c3c3c;
}
.h-table .h-td {
  font: red;
}
```
But I need the output as 
```css
.h-table.h-content,
.h-table .h-td {
  background-color: #3c3c3c;
}
.h-td { // I would like to have this as a separate class
  font: red;
}
```
I have searched any property like 'not' or ! to avoid the inherited parent class, sorry but I couldn't found it. Can you have any property to do this?

Please refer the below sample for reference
http://codepen.io/anon/pen/rVRWoy?editors=101

**Comment by lukeapage** [comment]
use `& when (... ` for your if,  then have `.h-table` inside and `.h-td` at the end.

**Comment by seven-phases-max** [comment]
Just do not nest that `.h-td` inside `.h-table` , e.g.:
```less
@widget: Table;

& when (@widget = Table) {
    .h-table {
        &.h-content, .h-td {
            background-color: #3c3c3c;
        }
    }
    .h-td {
        font: red;
    }
}
```

(Also, just to avoid some misunderstanding in the future, note that by "inheritance" they usually refer to inheriting properties of one style with another (by mixins and extend), and it  has nothing to do with nesting or any other hierarchy relations between selectors/elements like in your example).

---
Also please not the issue tracker is for issue/bug reports only. For a generic "How-To" questions consider using for example [SO](http://stackoverflow.com/questions/tagged/less).
