### ISSUE TITLE
Comments not preserved in referenced includes

### ISSUE THREAD

**Issue by betaorbust** [less/less.js#2675]
## Problem
When a file is included with `(reference)` in-property comments are stripped out. This breaks the only workaround to #2674. 

#### Input
```LESS
// test.less
@import (reference) 'imported-file.less';
.my-test{
    .my-mixin();
}
```
```LESS
// imported-file.less
.my-mixin(){
    color: red /* comment that should be there */;
}
```

#### Output

``` CSS
.my-test {
  color: red;
}
```

#### Expected Output
```CSS
.my-test {
  color: red /* comment that should be there */;
}
```
