### ISSUE TITLE
element& confusion, does not go back 1 level?

### ISSUE THREAD

**Issue by phillip-haydon** [less/less.js#2676]
If I have LESS setup like:

```css
#settings {
    .controls {
        ... styles
    }
} 
```

And I want to say, "Apply these styles to all elements of .controls inside settings"

"Except when the .controls is on a span tag, do something else..."

```css
#settings {
    .controls {
        ... styles
        background: red;
        span& {
            background: green;
        }
    }
} 
```

I would expect

```css
#settings .controls {
    .....
}

#settings span.controls {
   .....
}
```

Except I get:

```css
#settings .controls {
    .....
}

span#settings .controls {
   .....
}
```

This to me makes no sense at all, am I doing this wrong or is this something not supported by LESS?
