### ISSUE TITLE
Why doesn't :extend() compile with gulp-less?

### ISSUE THREAD

**Issue by SetTrend** [less/less.js#2682]
I created an :extend expression following the Less documentation. But gulp-less doesn't compile it.

What's wrong with these expressions?

```css
html
{
    &:extend(body);
}

body
{
    height: 100%;
}
```
or

```css
html:extends(body)
{
}

body
{
    height: 100%;
}
```
