### ISSUE TITLE
element selectors cannot be used in mixins

### ISSUE THREAD

**Issue by refractalize** [less/less.js#2690]
It seems that element selectors can't be used as mixins:

```less
.mixin input {
  background-color: red;
}

.thing {
  .mixin input;
}
```

Produces:

```
ParseError: Unrecognised input in path/file.less on line 6, column 15:
5 .thing {
6   .mixin input;
7 }
```

Whereas this works perfectly, as you'd expect:

```less
.mixin .input {
  background-color: red;
}

.thing {
  .mixin .input;
}
```

Am I doing it right, or is this broken?
