### ISSUE TITLE
When mixin name matches the class name

### ISSUE THREAD

**Issue by Craigy-** [less/less.js#2709]
I have a mixin:
```less
.clearfix() {
  &:before,
  &:after {
    content: " ";
    display: table;
  }
  &:after {
    clear: both;
  }
}
```
And a class with the same name (for use in html):
```less
.clearfix {
  .clearfix;
}
```
Now when I apply mixin .clearfix, for example:
```less
header {
  .clearfix;
}
```
I get such a result:
```less
header:before,
header:after {
  content: " ";
  display: table;
}
header:after {
  clear: both;
}
header:before,
header:after {
  content: " ";
  display: table;
}
header:after {
  clear: both;
}
```
Is any way to remove duplicates?
