### ISSUE TITLE
Extend and variables namespaces

### ISSUE THREAD

**Issue by bpaugam** [less/less.js#2714]
Hello !

This works:
```less
#app {
    & {
        @bg: red;
        @yellow: yellow;
        .body {
            background: red;
            color: yellow;
        }
    }
	&:extend(#app .body);
}
```
and transpiles to:
````less
#app .body,
#app {
  background: red;
  color: yellow;
}
```

But once the namespace is variabilized, it does not:
```less
@namespace: ~"#app";

@{namespace} {
    & {
        @bg: red;
        @yellow: yellow;
        .body {
            background: red;
            color: yellow;
        }
    }
	&:extend(@{namespace} .body);
}
```
This second example compiles to:
```less
#app .body {
  background: red;
  color: yellow;
}
```
Thus the extend declaration is ignored, and this error is thrown: "extend ' #app .body' has no matches".

Am I doing something wrong ?
