### ISSUE TITLE
A file imported by reference and then normally 

### ISSUE THREAD

**Issue by SomMeri** [less/less.js#2716]
Main test.less:
````less
div-direct {
  @import (reference) "file.less";
}

show-all-content {
  @import "file.less";
}
````

file.less:
````less
/*
  tralala
*/
.fix {
  fix: fix;
}
.something {
  @import (reference) "file-2.less";
}
````

file-2.less:
````less
/* tralala nested file */
should {
  be: invisible;
}
````

compiles into:
````less
div-direct .fix {
  fix: fix;
}
div-direct .something should {
  be: invisible;
}
````

It should be (plus or minus comments):
````less
show-all-content .fix {
  fix: fix;
}
````
