### ISSUE TITLE
Compiler error with v-2.5.3

### ISSUE THREAD

**Issue by FangzhengTian** [less/less.js#2721]
Hi,

I'm learning less using Less Web Development Essentials - Second Edition. In the sample code I tried to use the most recent less compiler to compile the code but it gives me "Unrecognized Input" error while I tried to compile with v-2.0.0 it got compiled successfully. Can you explain why this happen? The code is:
```less
/* general styles, example settings */

body{ background-color: lightblue;}
div
{
width:500px; 
height:50px; 
margin: 0 auto; //center content
margin-bottom:10px;
}

/* mixins */
.roundedcornersmixin(@radius: 10px)
{
    -webkit-border-radius: @radius;
    -moz-border-radius: @radius;
    border-radius: @radius;
}

#header{
background-color: red;
.roundedcornersmixin();
}

#content{
background-color: white;
min-height: 300px;
.roundedcornersmixin(20px);
}

#footer{
background-color: navy;
.roundedcornersmixin(20px);
}
```
