### ISSUE TITLE
"extend" the puesdo selector ": before" doesn't work inside media query of bootstrap 

### ISSUE THREAD

**Issue by ravikiranr26** [less/less.js#2722]
extend doesn't work inside a media query, with a pusedo selector before. The content seems not to appear inside the class '.two' upon hover 

```less
/* icon.less file */

.icon-chev:before {
    content: "\g106";
}

/* my.less file */

@media (min-width: @screen-sm-min) {
.one {
    &:hover {
        .two {
                &:extend(.icon-chev all);
                color: #fff;
        }
    }
  }
}
```
