### ISSUE TITLE
Removing null variables

### ISSUE THREAD

**Issue by zephraph** [less/less.js#2724]
SASS has a feature that I particularly like: any variable with the value null is not transpiled into the final output. I'm building a theming system that specifies a lot of variables for some base classes. Every class won't use each variable, so in those cases I would like the transpiled output to effectively remove any items where the variable is null. 

Here's an example

```less
// defaults
@width: null;
@background: null;

// definition file
.big-box {
  background-color: @background;
  width: @width;
}

// theme file
@width: 300px;
```

Ouputs
```
.big-box {
  width: 300px;
}
```

This is a very crude example, but I hope it gives you an idea of what I'm trying to achieve. One solution thought of was to write a post-process plugin that simply went through and removed all the `null` values. That would work, but it's a bit of a hack. Is there any way I can currently accomplish this, and if not, would it be something that there's interest in having?

**Comment by zephraph** [comment]
That's not exactly what I meant. I know that I can use guards. The issue is, I'll have maybe 50+ variables per theme file. Any of those may and or may not be used. Guards get really heavy at that point.

**Comment by matthew-dean** [comment]
Well, TBH, it seems like a backward construction, to add things like properties/values _without_ guards, and then flagging them after the fact for removal. It sounds like designing yourself into a corner, then wanting a feature to get out of it, no?

**Comment by zephraph** [comment]
Have you done much with semantic-ui? I'm trying to build a theming system very similar to what they're doing. There's a base definition that builds out a scaffold style that has variables plugged in at all the interesting places. Then there are variable files that are imported to essentially give a designer somewhat of a "visual api" for them to work with. Essentially that's what I want to accomplish with the caveat that if something isn't needed I don't want to pollute my final output with that variable.

**Comment by zephraph** [comment]
I'll just use a post-processing plugin or PostCSS to do this.

**Comment by kerry-iclasspro** [comment]
There is also the use case of wanting to override an upstream variable to nothing.  We could technically set the value to `inherit` but I do think Sass handles this better by completely removing the property when null.

```less
// Company defaults
@some-var: 100px;
```

```less
// Project defaults 
@some-var: null;
```

```less
// something.less
.some-selector {
  font-size: 16px;
  height: @some-var;
}

// yields
.some-selector {
  font-size: 16px;
  height: null;
}

// desired
.some-selector {
  font-size: 16px;
}
```
