### ISSUE TITLE
Namespace interpolation

### ISSUE THREAD

**Issue by jeremieca** [less/less.js#2728]
Hello,

Is it possible to use namespace interpolation in Less ? 
     
     @color: "yellow";
      
     .example {
         #top-@color;                   // Use of #top-yellow namespace
         .inNamespaceMixin();
     }

Thanks !

**Comment by seven-phases-max** [comment]
I've [answered](http://stackoverflow.com/questions/33825992) it at SO. (copying the answer just for reference):
```less
Use parametric namespace instead (Notice namespaces and mixins are actually the same thing - i.e. the former is a purely logical abstraction).

@color: yellow;

 #top(yellow) {
     .square(@param) {
         width: @param;
         height: @param;
     }
 }

 .example {
     #top(@color); // use yellow #top namespace
     .square(10px);
 }
```
