### ISSUE TITLE
Import namespaced modules, or named paths

### ISSUE THREAD

**Issue by kvcrawford** [less/less.js#2730]
Say I have a project with the given folder structure

```
my_project
|-- bower_components
    |-- bootstrap
      |-- less
        |-- bootstrap.less
        |-- variables.less
        |-- etc.
|-- src
  |-- less
      |-- my_project.less
      |-- variables.less
```

And I'm compiling LESS with 

```javascript
paths: [
  './src/less/'
  './bower_components/bootstrap/less/'
]
```

If I were to call `@import 'variables.less';`, I presume that it would import my `src/less/variables.less` file since it is the first in the path.

I would like to be able to do `@import 'bootstrap/variables.less'`.

I could set my path instead to `./bower_components/` and then call `@import 'bootstrap/less/variables.less'` but that doesn't seem quite as efficient or ideal.

Is this already possible? Is there something I'm missing?

**Comment by seven-phases-max** [comment]
You can use [variables in import statements](http://lesscss.org/features/#variables-feature-import-statements). E.g.:
```less
@bootstrap: './bower_components/bootstrap/less'; // can be set via options as well
@import '@{bootstrap}/variables.less'.
```
