### ISSUE TITLE
Reuse parent style with `&`

### ISSUE THREAD

**Issue by jpdatalicious** [less/less.js#2734]
This is possible with Less?

```less
.my-btn {
 &--raised {
    &:extend(.btn, .btn-raised);
    &:hover {
      &:extend(.btn:hover, .btn-raised:hover);
    }
 }

  &--raised--white {    
    .&--raised; // I need to reuse the previous selector style ??
    background-color: #fff;
 }
}
```

**Comment by seven-phases-max** [comment]
Please not the issue thracker is not a support forum or a sort of, and it's primarily meant only for issue/bug-reports (as well as for feature requests). For "How-To"/"Can-I" question please use [SO].

---
As for the question, no, it is not possible (there're proposed #2101 and #2200- so eventually you could use `extend` there). Meantime either combine duplictated styles in the same ruleset, e.g.:
```less
.my-btn {
    &--raised, &--raised--white {
        &:extend(.btn, .btn-raised);
        &:hover:extend(.btn:hover, .btn-raised:hover) {}
    }
    &--raised--white {background-color: #fff}
}
```
Or move duplicated stuff to a "normal" mixin:
```less
.my-btn {
    &--raised {
        .raised-button();
    }
    
    &--raised--white {
        .raised-button();
        background-color: #fff;
    }
}

.raised-button() {
    &:extend(.btn, .btn-raised);
    &:hover:extend(.btn:hover, .btn-raised:hover) {}
}

```

Both methods are actually same clear and effective.
