### ISSUE TITLE
Complex DR definition works as at-rule

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#2825]
A variable definition with a value that ends with an unnamed ruleset, e.g.
```less
@var: x {y: z};
```
is interpreted as an unknown at-rule, thus resulting in:
```css
@var : x {
  y: z;
}
```

This is most likely a result of #2783. (Before #2783, such code resulted in a error, i.e. it's not a regression but more like an overlooked side-effect).
See also related https://github.com/less/less.js/issues/2270#issuecomment-61634539.
