### ISSUE TITLE
null string for compiling

### ISSUE THREAD

**Issue by kbdsbx** [less/less.js#2831]
```less

/* making .display-block */
.make-classes () {
    @item : ~"";
    .make-classes( @item );
}

/* making .xs-display-block */
.make-classes ( @class ) when ( iskeyword( @class ) ) {
    @item : ~"@{class}-";
    .make-classes( @item );
}

/* inner function */
.make-classes ( @class ) when ( isstring( @class ) ) {
    .@{class}display-block { display: block; }
}

.make-classes ();

.make-classes( xs );

```

If I want to taking `.display-block` into some class as :

```less
.shi {
    .display-block;
}
```

it will be tell me 
> NameError: .display-block is undefined on line 21, column 5:

but if I using `.xs-display-block`

```less
.shi {
    .xs-display-block;
}
```

It's works.

so... Is that the null string are not supporting when compiling?
