### ISSUE TITLE
Parser should report error

### ISSUE THREAD

**Issue by raducoravu** [less/less.js#2842]
With this LESS fragment:

      .tip {
          font-size: 1em;
          line-height: 1.2em: 
         margin: 20px 0px 30px 0px;
         }

the "line-height" value ends with a ":" instead of ";" and the parser should report an error. It does not.

**Comment by infotexture** [comment]
Oddly enough, if a line comment is added to the invalid line, the parser recognizes the error:

```less
.tip {
	font-size: 1em;
	line-height: 1.2em: 		// Trailing colon should be a semicolon
	margin: 20px 0px 30px 0px;
	}
```

In this case, the parser responds with:

    ParseError: Unrecognised input on line 3, column 20:
