### ISSUE TITLE
Extending concatenated selectors

### ISSUE THREAD

**Issue by zerkms** [less/less.js#2857]
Assuming that I have a `LESS` like this

```less
.layout {
  &__sidebar {
    color: red;
  }
}

.layout__sidebar {
  background-color: yellow;
}

.foo {
  &:extend(.layout__sidebar);
}
```

I expect it to be compiled into

```css
.layout__sidebar,
.foo {
  color: red;
}
.layout__sidebar,
.foo {
  background-color: yellow;
}
```

but it compiles to

```css
.layout__sidebar {
  color: red;
}
.layout__sidebar,
.foo {
  background-color: yellow;
}
```

What my expectations are based on:

1. on the documentation about `:extend`
2. on the fact that something very similar works fine

```less
.layout {
  &.sidebar {
    color: red;
  }
}

.layout.sidebar {
  background-color: yellow;
}

.foo {
  &:extend(.layout.sidebar);
}
```

Codepen demos:

1. with classname string concatenation http://codepen.io/zerkms/pen/vGJvBV
2. with just combination of class names http://codepen.io/zerkms/pen/oxeJYP

Would you consider this a bug? If not, it must be explicitly noted in the documentation that the selector strings concatenation does not work with `:extend`

Thanks.

PS: I also asked a question on stackoverflow http://stackoverflow.com/q/36322581/251311
