### ISSUE TITLE
Detached ruleset scopes affected —— Recording an error report

### ISSUE THREAD

**Issue by golegen** [less/less.js#2868]
When I refer to the code in the manual for testing,I found the detached ruleset scopes affected.
( use webstorm and less 2.6.1)
View code,Please visit  [Less manual](http://lesscss.org/features/#detached-rulesets-feature-scoping)

Reads as follows

> 
Variable and mixins accessible form definition win over those available in the caller:
```less
@variable: global;
@detached-ruleset: {
    // will use global variable, because it is accessible
    // from detached-ruleset definition
    variable: @variable; 
};
selector {
    @detached-ruleset();
    @variable: value; // variable defined in caller - will be ignored
}
```
compiles into:
```css
selector {
    variable: global;
}
```
> 

### If you add additional code in front of manual reference code,for example:
```less
//additional code
@testvalue: 2px;
#test {
    width: @testvalue;
}

//manual reference code
@variable: global;
@detached-ruleset: {
    // will use global variable, because it is accessible
    // from detached-ruleset definition
    variable: @variable; 
};
selector {
    @detached-ruleset();
    @variable: value; // variable defined in caller - will be ignored
}
```
compiles into:
```css
#test {
    width: 2px;
}
selector {
    variable: value;
}
```
The value of `variable`:  `global` becomes `value`;
I can only record as an error report.
