### ISSUE TITLE
feature: Add compiler directives for deprecation warnings

### ISSUE THREAD

**Issue by nerdgore** [less/less.js#2875]
As less frameworks get older and larger there is a need to mark parts of your css as deprecated, making the move to a new version of the framework easier.

Consider the removal or renaming of a selector:

```less
.u-align-left {
  @deprecate(.u-alignment-left)
  text-align: left;
}
.u-alignment-left {
  float: left;
}
```

The compiler could output something along the lines:
```
.u-align-left: This selector is deprecated and will be removed, use .u-alignment-left instead
```

This may be related to #1459 as a specific use case. However, personally I feel that deprecation should be handled on the compiler level.
