### ISSUE TITLE
Using a variable in a mixin call

### ISSUE THREAD

**Issue by vrbvillor** [less/less.js#2885]
Such as
```less
.lt(){
    left:0;
    top:0;
}
```
when I use a variable
```less
@n : lt;
.@{n}();
```
The second line of the second passage of code, I want to call the `.lt()`. How to realize it? THANKS.

**Comment by seven-phases-max** [comment]
Currently it's impossible to call a mixin indirectly (i.e. by name as variable value). 
However depending on your specific use-case there're several nearly equal methods to achieve indirect calls.

(The feature itself was proposed among other variations in https://github.com/less/less.js/issues/965#issuecomment-25328937. But since #965 itself is closed because its initial idea ([DRs](http://lesscss.org/features/#detached-rulesets-feature)) is implement I suppose this one needs a dedicated ticket. So I'm not closing this one yet (but eventually it's most likely to be replaced by one with more detailed info).

**Comment by matthew-dean** [comment]
This should do the trick.
```less
@lt: {
    left:0;
    top:0;
};
@n : lt;
@x : @@n;
@x();
```
And if you have multiple matching `.lt` mixins, you can of course do:
```less
@lt: { .lt() };
.lt() {
    left:0;
    top:0;
}
.lt() {
    color: red;
}
rules {
	@n : lt;
	@x : @@n;
	@x();
}

// this will output
rules {
  left: 0;
  top: 0;
  color: red;
}
```

**Comment by seven-phases-max** [comment]
That's all too verbose. Old-school methods may result in a more compact workaround (though I'm intentionally not providing any in this case since it would be pretty useless w/o knowing the actual use-case/case (i.e. why exactly `n` is a variable). Otherwise it's not clear how it would be different from just :
```less
.lt() {
    left:0;
    top:0;
}

.n() {.lt}
.n();
```
