### ISSUE TITLE
Global vars fail when a url is used

### ISSUE THREAD

**Issue by kevbook** [less/less.js#2900]
__Use-case: url path, I want to pass S3 path for images__

* lessc 2.7.1
* node v4.4.5

// Less file
```css
body {
  background: @COLOR_URL;
}
```

// CLI
```bash
$ lessc index.less --global-var='COLOR_URL=red'
body {
  background: red;
}
```
But with url (the character "/") gives an error

```bash
$ lessc index.less --global-var='COLOR_URL=http://google.com'

ParseError: Unrecognised input in /index.less on line 1, column 17:
1 @COLOR_URL: http://google.com;
```

**Comment by seven-phases-max** [comment]
The error is expected since
```less
@COLOR_URL: http://google.com;
```
is not valid variable declaration for obvious reasons - `http://google.com` is not valid CSS value.
(Use [escaping](http://lesscss.org/features/#features-overview-feature-escaping) if you need an arbitrary string as a variable value).

**Comment by seven-phases-max** [comment]
Closing as expected behaviour.

**Comment by kevbook** [comment]
Well, it doesn't matter if its an expected CSS value because Less doesn't parse and match CSS attribute types to available CSS values. If you do the same thing with the below CSS, it fails even after escaping.

```
background: url('@{COLOR_URL}/bg.png');
```

**Comment by matthew-dean** [comment]
@kevbook He means you can't just type a naked URL in Less any more than you can in CSS.

**Comment by seven-phases-max** [comment]
> because Less doesn't parse and match CSS attribute types to available CSS values. 

It does actually (either way, unquoted `http://google.com;` means nothing but `http` identifier followed by `:` operator followed by `//google.com` comment).

>`background: url('@{COLOR_URL}/bg.png');`

You're missing the point, the valid code would be:
```less
@quoted-string: "http://google.com";
@escaped-string: ~"http://foogle.com";

div {
    a: url('@{quoted-string}/bg.png'); // OK
    b: url('@{escaped-string}/bg.png'); // OK
    c: url(~'@{quoted-string}/bg.png'); // OK
    // etc.
}
```
Thus the proper command line for your use-case would be:
`lessc index.less --global-var='COLOR_URL="http://google.com"'`
or
`lessc index.less --global-var="COLOR_URL='http://google.com'"`
and so on.
