### ISSUE TITLE
Selector interpolation: Shouldn't variables be evaluated before the code parse?

### ISSUE THREAD

**Issue by cusspvz** [less/less.js#2909]
I'm working with less for a while. I've used selector interpolation about 4 or 5 times, but I did not had the need to include nested classes over it until now.

So I've came across on what I think it could be a potential issue.
Here's a test case:

### Input
```less
@theGoodThings: ~".food, .beer, .sleep, .javascript";

@{theGoodThings} {
  &:after {
  font-weight: bold;
  }
}
```

### Output
```less
.food, .beer, .sleep, .javascript:after {
  font-weight: bold;
}
```

### Output I was expecting:
```less
.food:after, .beer:after, .sleep:after, .javascript:after {
  font-weight: bold;
}
```
