### ISSUE TITLE
Using a dynamically via-parent-operator-generated class

### ISSUE THREAD

**Issue by singha-cz** [less/less.js#2934]
Hi, 
I'm getting the "_Error: .weight-400 is undefined_" message when trying to **use a dynamicaly generated (via parent operator) class name**. 

Is there any way how to make this work?

`.weight{`    
`	&-100 { font-weight: 100; }`
`       &-200 { font-weight: 200; }`
	`&-300 { font-weight: 300; }`
	`&-400 { font-weight: 400; }`
	`&-500 { font-weight: 500; }`
	`&-600 { font-weight: 600; }`
	`&-700 { font-weight: 700; }`
`}`

`h1{`
	`.weight-400;`	
`}`

**Comment by Justineo** [comment]
See #1399.

**Comment by seven-phases-max** [comment]
Merging to #1399. Also regarding this particular example and considering https://github.com/less/less.js/issues/1399#issuecomment-33680478 and https://github.com/less/less.js/issues/2702#issuecomment-144826702 I'd just suggest to write it in opposite (first "normal" mixin then CSS class) e.g.:
```less
.weight(@v) {
    font-weight: @v; 
}

.weight {
    .w(100);
    .w(200);
    .w(300);
    .w(400);
    .w(500);
    .w(600);
    .w(700);
    .w(800);
  	.w(@v) {&-@{v} {.weight(@v)}}
}

h1 {
    .weight(400);
}
```

See also #2749.
