### ISSUE TITLE
Weird extra space

### ISSUE THREAD

**Issue by Sogomn** [less/less.js#2960]
Following snippet:
```less
.content {
  margin: 0;
  padding: 0;

  ul {
    margin: 0;
    padding: 10px;
    width: 150px;
    list-style-type: none;
    text-align: center;
    font-size: 15pt;
    background-color: @background-list;
    box-shadow: @bottom-shadow, @side-shadow;

    li {
      a {
        text-decoration: none;
        color: @foreground;

        /*Here's the problem*/
        :hover {
          color: @foreground * 1.25;
        }
      }
    }
  }
}
```

Compiles to this:
```css
.content {
  margin: 0;
  padding: 0;
}

.content ul {
  margin: 0;
  padding: 10px;
  width: 150px;
  list-style-type: none;
  text-align: center;
  font-size: 15pt;
  background-color: #eceef2;
  box-shadow: 0 6px 3px -5px black, 5px 0 3px -5px black, -5px 0 3px -5px black;
}

.content ul li a {
  text-decoration: none;
  color: #777777;
}

/*Here*/
.content ul li a :hover {
  color: #959595;
}
```

The extra space after `a` seems to invalidate the `:hover` (at least on Firefox).
