### ISSUE TITLE
Invalid nested media query merge with "or" condition, when a variable is used for sub-media query

### ISSUE THREAD

**Issue by unhawkable** [less/less.js#2964]
Invalid media query is compiled when using a variable containing a media query definition with OR conditions (either with comma or "or"-keyword). Top media query should be prepended to each sub-query.

Less:

```
@highdpi: ~"(-webkit-min-device-pixel-ratio: 1.25), (min-device-pixel-ratio: 1.25), (min-resolution: 1.25dppx)";
.bg {
    @media (max-width: 1000px) {
        background: url(bg-small.png);

        @media @highdpi {
            background: url(bg-small@2x.png);
        }
    }
}
```

Output:

```
@media (max-width: 1000px) {
  .bg {
    background: url(bg-small.png);
  }
}
@media (max-width: 1000px) and (-webkit-min-device-pixel-ratio: 1.25), (min-device-pixel-ratio: 1.25), (min-resolution: 1.25dppx) {
  .bg {
    background: url(bg-small@2x.png);
  }
}
```

Expected output - "(max-width: 1000px) and " before each comma-separated part:

```
[...]
@media (max-width: 1000px) and (-webkit-min-device-pixel-ratio: 1.25), (max-width: 1000px) and (min-device-pixel-ratio: 1.25), (max-width: 1000px) and (min-resolution: 1.25dppx) {
[...]
```

_On the other hand, it compiles fine, when not using a variable:_

```
.bg {
    @media (max-width: 1000px) {
        background: url(bg-small.png);

        @media (-webkit-min-device-pixel-ratio: 1.25), (min-device-pixel-ratio: 1.25), (min-resolution: 1.25dppx) {
            background: url(bg-small@2x.png);
        }
    }
}
```

**Comment by seven-phases-max** [comment]
This is more a feature request than a bug. Less is not supposed to understand what is inside those `~""` ([anywhere](http://lesscss.org/features/#features-overview-feature-escaping), not just for media queries). So it's expected for Less to never know about any commas or other special symbols there.

Technically, the code like above ("list of media queries in an escaped string") is more like an old quirk/syntax-workaround rather than ever considered proper code (yet again because of `~""` itself). In today's Less, the proper pattern to achieve the same stuff would be using anonymous/detached rulesets/mixins instead of "the magic value variable", e.g.:
```less
.highdpi(@rules) {
	@media (-webkit-min-device-pixel-ratio: 1.25), 
      	   (min-device-pixel-ratio: 1.25), 
      	   (min-resolution: 1.25dppx) {
        @rules();
    }
}

.bg {
    @media (max-width: 1000px) {
        background: url(bg-small.png);

        .highdpi({
            background: url(bg-small@2x.png);
        });
    }
}
```
or similar methods.

Related to #1421 and similar issues/requests.
---
Note that even as a feature request (if proposed) this feature will have to use different syntax instead of `~""` anyway, i.e. the example is never supposed to work as expected above - so I'm not marking this as "feature request" (as the FR would require a little bit more insight).

Merging to #1421 maybe?
