### ISSUE TITLE
Sourcemap will not link to correct line if media query is inside selector

### ISSUE THREAD

**Issue by morganfeeney** [less/less.js#2974]
When I compile Less with a sourcemap, and in the less file add a media query inside a selector like so:

```less
.post .title {
  @media(min-width: 700px) {
    display: flex;
  }
}
```

...and then using Chrome inspector try to find the ruleset is always at the end of the file. However when I wrap the entire ruleset in a media query like so:

```less
@media(min-width: 700px) {
  .post .title {
    display: flex;
  }
}
```

There is no issue and can find the ruleset on the correct line.

If it helps I am using Node and compile Less using grunt and the plugin grunt-contrib-less, I'm not sure if it is a Less issue and was wondering if this is something to be expected with Less sourcemaps.
