### ISSUE TITLE
LESS equivalent for selector variable evaluation

### ISSUE THREAD

**Issue by Fristi** [less/less.js#298]
In SASS:

``` sass
$theme: a

.myselector-#{$theme}
  padding: 3px
```

Output

``` css
.myselector-a
{
  padding: 3px;
}
```

Would be great to have in LESS
