### ISSUE TITLE
what about dynamic variable names?

### ISSUE THREAD

**Issue by markentingh** [less/less.js#2983]
for example:
```
@prefix:"my";
@suffix:"color";

.color(@name, @color){
    @tmp:~"@{prefix}-@{name}-@{suffix}";
    @{tmp}:@color;
}

.color(~"red",#cc0000);

body{background:@my-red-color;}
```

is something like this possible, where I define a custom variable name "@my-red-color" via a function, then use that custom variable as a property value?

**Comment by seven-phases-max** [comment]
For the feature-request see #2702 (there're were also earlier threads but so far no good use-cases were suggested). From your example it seems like you're just looking for some sort of namespacing, though exact example/pattern would vastly depend on your actual use-case (after all it's not so easy to imagine how `.color(~"red", #cc0000);` could be better than `@my-red-color: #cc0000;` and when actually one need to change those prefixes and suffixes w/o actually changing `background: @my-red-color;`).

So here just a generic minimal namespacing example:
```less
.theme(my) {
    @red:  #c00;
    @blue: #00c;
}

.theme(your) {
    @red:  #933;
    @blue: #339;
}

body {
    .theme(my);
    color:      @red;
    background: @blue;
}

p {
    .theme(your);
    background: @blue;
    // etc.      
}

// etc.
```
(Related: https://github.com/less/less-meta/issues/12).
