### ISSUE TITLE
[Bug] Mixin matching fails in &{} blocks

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#2984]
I would have thought this certainly would have been found by someone in the past, but I couldn't find a matching issue.

In short:
```less
.defaults() {
  foo: bar;
}
.test1 {
  .defaults();
}

& {
  .defaults() {
    bar: foo;
  }
  .test2 {
    .defaults();
  }
}
```
Expected output:
```less
.test1 {
  foo: bar;
}
.test2 {
  foo: bar;
  bar: foo;
}
```
Actual output:
```less
.test1 {
  foo: bar;
}
.test2 {
  bar: foo;
}
```
Interestingly, it's not a mixin visibility issue, because this:
```less
.defaults() {
  foo: bar;
}
.test1 {
  .defaults();
}

& {
  .test2 {
    .defaults();
  }
}
```
...produces this output:
```less
.test1 {
  foo: bar;
}
.test2 {
  foo: bar;
}
```

**Comment by seven-phases-max** [comment]
I'd rather sayd it's a dark corner not really a bug. Curiously I saw this before and thought of it as abehaviour I would actually expect. I.e. a mixin call "matches all suitable mixins from *the same* (upward closest) scope" and not "matches all mixins from *all* scopes". The former actually makes more sense to me from "Less have a Scope" point of view.

**Comment by rjgotten** [comment]
I've always thought of this as a (sadly not well-documented) feature, rather like @seven-phases-max describes as well.

All the candidate mixins are 'signatures' (in the method overloading sense) of the same 'mixin'. With proper scope overriding, if any one mixin definition is provided at a closer scope then that one definition should be considered an entirely new 'mixin' definition that contains only one 'signature' and *should* whole-sale replace the mixin definitions that resides in scopes that are further out.


Wouldn't you end up in a world of cross-contaminated hurt if candidate mixins would be searched for all the way up to the global scope? You could have some very unintended side-effects that way.

**Comment by seven-phases-max** [comment]
Yep, yet in another words:
```less
.foo {
    .bar();
    .bar() {
        color: red;
    }
}

// in a far far away galaxy:
.bar() {
     color: blue;
}
```
`.foo` is expected to be `red` not `blue`.
