### ISSUE TITLE
Stdin input and `--relative-urls` option produces wrong urls

### ISSUE THREAD

**Issue by jhnns** [less/less.js#3038]
When:

- the content is passed via stdin
- and the `--relative-urls` option is used
- and the imported file is two directories up (`../../`)

the generated urls are wrong.

Actual output:

```css
.b {
  background-image: url("b/b/test.jpg");
}
```

Expected output

```css
.b {
  background-image: url("../../b/b/test.jpg");
}
```

---

I've created a [small test repository](https://github.com/jhnns/less-relative-urls-bug) that demonstrates the bug. The problem is [somewhere along these lines](https://github.com/less/less.js/blob/43ab0b872248ec34186bd8c245904d9a0f5d7825/lib/less/import-manager.js#L89-L97) and can be reproduced with less `2.x` and `less@3.0.0-alpha.1`. `alpha.2` is throwing an unrelated error.
