### ISSUE TITLE
No import(-once) happens, if file already imported to another scope

### ISSUE THREAD

**Issue by thybzi** [less/less.js#3039]
When I use common import (without `multiple`), the file seems not to be imported if it was already imported into another scope. 

This behavior is not obvious and produces unexpected errors. Is that a bug?

Reproduces in current version of LESS (2.7.2), and as well in upcoming 3.0.

A minimal fileset to reproduce:

**variable.less**
```less
@some-variable: 'some-value';
```

**main.less**
```less
@media all {
    @import 'variable';
}
@import 'variable';

element {
    content: @some-variable;
}
```

_Expected CSS output_:
```css
element {
    content: 'some-value';
}
```

_Actual output (exception):_
```
NameError: variable @some-variable is undefined in main.less on line 7, column 14:
6 element {
7     content: @some-variable;
8 }
```
