### ISSUE TITLE
Common import(-once) doesn't happen after reference-import

### ISSUE THREAD

**Issue by thybzi** [less/less.js#3040]
One more strange and unexpected import case.

Common import (without `multiple`, but with expected CSS output) doesn't happen if the same file was already reference-imported earlier.

The fileset to reproduce:

**main.less**
```less
@import 'foo';
@import 'bar';
```

**bar.less**
```less
@bar-height: 42px;

.bar {
    height: @bar-height;
}
```

**foo.less**
```less
@import (reference) 'bar';

.foo {
    padding-top: @bar-height;
}
```

_Expected CSS output for `main.less` compiled:_
```css
.foo {
    padding-top: 42px;
}

.bar {
    height: 42px;
}
```

_Actual CSS output for `main.less` compiled:_
```css
.foo {
    padding-top: 42px;
}
```
