### ISSUE TITLE
 SyntaxError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by zvuv** [less/less.js#3044]
I am writing a LESS plugin that provides a zvg function which returns encoded XML for an inline SVG image. It works fine, the output CSS file is generated and the background image appears  on the page but the editor displays the above error message associated with the background image statement.
```less
@svg: zvg(@xml, viewBox(25,25,100,100),toURL('-z'),  log());

.exb {
   background-color: transparent;
  **background-image:url(@svg);**
}
```

If I type in the actual encoded XML instead of @SVG, no error appears.

` background-image: url(data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%2...);`

I've stepped through my code and the LESS code - doesn't seem to throw an exception.

As I said, things work anyway, but if I release the code like this, users are going to be unhappy with the error message.

Thanks, Adam

**Comment by seven-phases-max** [comment]
I'm afraid it's impossible to suggest anything just from the code above. Apparently the error is related to the value (most likely its type) you return from the function, so the corresponding snippet from the plugin code itself will be more helpful.

**Comment by seven-phases-max** [comment]
Apparently the error is the same as in:
```less
.exb {
    @svg: zvg();
    background-image: url(@svg);
}
```
But the key weirdness is how it is compiled to CSS with the error (while it's supposed to stop immidiately)? So the first question is: are you sure it's not accidentally compiled twice? (e.g. first w/o plugin enabled so it prints the error and stops, and only then with plugin enabled so it passes and generates the CSS).

**Comment by zvuv** [comment]
Yes - something similar.  Turns out less itself had no problem with it but some knowitall syntax checker that was hooked into the IDE was putting in its 2c worth.   Thanks for pointing me in that direction.

While I have your attention, what is a good strategy for exception handling in a plugin? Less traps most exceptions itself and usually discards the error messages.  Makes diagnostics difficult.

Thanks, Adam

**Comment by seven-phases-max** [comment]
>what is a good strategy for exception handling in a plugin?

Do you mean for you own debugging/diagnostics or in a release version?

>Less traps most exceptions itself and usually discards the error messages.

This makes sense since it does not want to scare an ordinal user with JS stack dump.

>Makes diagnostics difficult.

Yep, sort of. Personally I usually just log everything important in tricky places and when it comes too tricky I just run it in a debugger. Though when it comes to (diagnostic) exception handling *in* a plugin it's not a big deal to put your own exception handler right at the beginning of a function of interest and print all the error info on your own.

**Comment by seven-phases-max** [comment]
>Turns out less itself had no problem with it but some knowitall syntax

Btw., in that regard, I would suggest the function to return already `url`ed data, i.e..:
```less
@svg: zvg(...); // <- url(data);
.exb {
    background-image: @svg;
}
```
This at least will help to minimize confusion when it goes wrong for some reason.

**Comment by calvinjuarez** [comment]
I did something similar to encode my SVGs the way you're doing.  You should be able to use the formatting function (`%()`) to do what you need.

```less
.exb {
  @svg: zvg(@xml, viewBox(25,25,100,100),toURL('-z'),  log());
  background-image: e(%('url("data:image/svg+xml;charset=UTF-8,%s")', @svg));
}
```
