### ISSUE TITLE
Div in complex arithm expressions results in a wrong unit value.

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#3047]
```less
div {
    @value: 1px;
    a: @value * 1rem;       // 1px  - ok
    b: @value * 1px * 1rem; // 1px  - ok
    d: @value / 1px;        // 1px  - ok
    c: @value / 1px * 1rem; // 1rem - unexpected
    e: @value / 1px + 0rem; // 1rem - unexpected
}
```
`c` and `d` results above contradict with http://lesscss.org/features/#features-overview-feature-operations stating the result should have a leftmost unit of an expression (i.e. all expressions above should produce `1px`). Tests cover only [`@a / @b /@c` expression](https://github.com/less/less.js/blob/v2.7.2/test/less/variables.less#L107) which accidentally produces the expected result.
Related to #2418 and #2472.
