### ISSUE TITLE
Addition dynamic function ("Mixin name interpolation").

### ISSUE THREAD

**Issue by kbdsbx** [less/less.js#3050]
Sometimes we should make function in compiling time, like this:

```less
@{prefix}-@{function-name}-@{suffix} () {
};
```

Because we expert the function which don't output to the finial .css file, but it can be used in compiling time. if any function has been output, the finial .css file is so large. ( 400 line come to 20000+ line etc. )

In current occasion, it has been output:

```css
.prefix-function-suffix () {
}
```

**Comment by seven-phases-max** [comment]
Please provide more details on *what* you're trying to achieve (instead of *how* you *think* you could do that).
Usually a code like in your example is an XY-problem - similar [to this](https://github.com/less/less.js/issues/2702#issuecomment-144727038) for example (I.e. if you provide your actual use-case I can give a hint on the *proper* way of handling it w/o the dreadful interpolations).

**Comment by kbdsbx** [comment]
Sorry for you, English isn't my native language.

This is code fragment:

```less
// library.less
.media-select ( @tag, @value, @min ) when ( @min > 0 ) {
    @{tag} {
        @media ( min-width: @min ) {
            @value();
        }
    }
}
```

first called:

```less
// library.less
.media-select ( 'xs-none', { display : none }, 768px );
```

next:

```less
// project.less
.page {
    .xs-none;
}
```

In the end, It is output:

```css
@media ( min-width: 768px ) {
    .xs-none {
        display: none;
    }
}

@media ( min-width: 768px ) {
    .page {
        display: none;
    }
}
```

I hopes it didn't output ``.xs-none`` in the final project.css, but ``.page`` did.

```css
/* in fantasy */
@media ( min-width: 768px ) {
    .page {
        display: none;
    }
}
```

In current version, the only way to not outputting mixin is append the "()" after the style name like this:

```less
.mixin () {            // It can't be output.
    display: none;
}
.page {
    .mixin;
}
```

But when the style name is variables or include variables, It doesn't work.

```less
// library.less
.media-select ( @tag, @value, @min ) when ( @min > 0 ) {
    @{tag}() {          // error.
        @media ( min-width: @min ) {
            @value();
        }
    }
    ~"@{tag}()" {          // error.
        @media ( min-width: @min ) {
            @value();
        }
    }
    @_tag : @tag + "()"
    @{_tag} {          // error again.
        @media ( min-width: @min ) {
            @value();
        }
    }
}
```
