### ISSUE TITLE
Whitespaces in a property name do not fail

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#3051]
Example:
```less
.for-each {
    me is not: a loop;
}
```

CSS output:
```css
.for-each {
    meisnot: a loop;
}
```
Expected result: a error message.

This seems to be a regression of `v2.0.0` (`v1.7.5` works as expected).
