### ISSUE TITLE
when recalled function, the return values is can't be cover.

### ISSUE THREAD

**Issue by kbdsbx** [less/less.js#3052]
```less
.test( @a, @b ) {
    @x : @a;
    @y : @b;
}

.test2 {
    .test( 15px, 20px );
    margin: @x @y;

    .test( 20px, 25px );
    margin: @x @y;
}
```

It must be:
```css
.test2 {
    margin: 20px 25px;
}
```
but now it is:
```css
.test2 {
    margin: 15px 20px;
}
```
