### ISSUE TITLE
Do not evaluate "and" expression if first part is already false

### ISSUE THREAD

**Issue by roberthartung** [less/less.js#3057]
Hey, I just came across a bug (at least in my opinion). When You write an expression like in my example, both parts of the "and" will be tested, regardless if the first part is already false.

```
#mixin(@color) when (iscolor(@color)) and (luma(@color) > 50%) {
  color: #000 !important;
}

#--mixin-fixed(@color) when (luma(@color) > 50%) {
  color: #000 !important;
}

#mixin-fixed(@color) when (iscolor(@color)) {
  #--mixin-fixed(@color);
}

.test {
  //#mixin(#ffffff); // works
  #mixin(false); // does not work
  //#mixin-fixed(#ffffff); // works
  //#mixin-fixed(false); // works
}
```

```
RuntimeError: error evaluating function `luma`: a.luma is not a function on line 1, column 44:

1 #mixin(@color) when (iscolor(@color)) and (luma(@color) > 50%) {
2   color: #000 !important;
```

The code fails with an exception. I need such kind of behaviour in one of my projects, where I can set variables/parameters to non-color values (false) to disable specific styles. I have a fix in-place but it would be great, if this could be fixed / improved!

I am using less in the browser (worker) but also tested it with the latest version over at less2css.org

**Comment by seven-phases-max** [comment]
This makes sense (Though I'm afraid it will be quite tedious to implement).

For your particular use-case (assuming you're aware of the [contrast](http://lesscss.org/functions/#color-operations-contrast) and need something different), a "two stage test" workaround will do the trick (with [`default()`](http://lesscss.org/functions/#misc-functions-default) and (to simplify even more) [argument-pattern-matching](http://lesscss.org/features/#mixins-parametric-feature-pattern-matching) it would not be very bloating), e.g.:
```less
.mixin(none) {
    /* not a color */
}

.mixin(@color) when (default()) {
    & when (luma(@color) >= 20%) {
        color: white;
    }
    & when (luma(@color) < 20%) {
        color: black;
    }
}

// usage:

foo {
    .mixin(green);
}

bar {
    .mixin(red);
}

baz {
    .mixin(none);
}
```

Or alternatively:
```less
.mixin(none) {
    /* not a color */
}

.mixin(@color) when (default()) {
    color: @c;
    .-;
    .-() {@c: white}
    .-() when (luma(@color) < 20%) {@c: black}
}

// same usage
```
