### ISSUE TITLE
'@import (reference)' Bug

### ISSUE THREAD

**Issue by baijunjie** [less/less.js#3071]
keyframes.less
```css
.keyframes(@animation_name) {
    @keyframes @animation_name {
        from { opacity: 0; }
        to   { opacity: 1; }
    }
}
```

styles.less
```css
@import "keyframes.less";
.keyframes(opacity-animation);
```
output:
```css
@keyframes opacity-animation {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```

styles.less
```css
@import (reference) "keyframes.less";
.keyframes(opacity-animation);
```
output:
```css
// empty ???
```
