### ISSUE TITLE
Wrong color encoding for SVG background-images

### ISSUE THREAD

**Issue by 7R5N** [less/less.js#3086]
Setup: 
I define a SVG file as a data background-image, and want to fill it with an less color variable:
`background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="8"><path d="M1,1 L12,8 24,1 23,0 12,6 2,0" fill="@{my-text-color}"/></svg>');`
Less compiles the color variable to a hex value. 

Firefox can’t (and won’t!) execute the 'fill' attribute when a hex color with a "#" is defined (cf. https://bugzilla.mozilla.org/show_bug.cgi?id=1245461), because the specs say the "#" must be replaced by "%23" (cf. https://tools.ietf.org/html/rfc3986#section-3.5). 

The LESS compiler should compile color variables _inside_ a url/data with replacing the "#" sign to meet the specs.

**Comment by seven-phases-max** [comment]
>The LESS compiler should compile color variables inside a url/data with replacing the "#" sign to meet the specs.

I don't think it should - other contexts may require another formats (having *nothing* to do with CSS and thus Less color values) and this is just beyond Less scope. In other words, the fact that you can use some external language (SVG in your case) inside CSS does not mean Less has to know anything about that language (i.e. SVG or *any other*).
I'm afraid in such cases the duty to convert to the appropriate format is on you, e.g.:
```less
@value: #123456;

div {
    @svg-value: escape(@value);
    background-image: url('data:image/svg+xml,<svg ... fill="@{svg-value}"/></svg>');
}
```

**Comment by 7R5N** [comment]
Okay, I got your point, and I can fully follow your argumentation: It sounds right that LESS shouldn’t compile anything other than CSS. 
And, thank you very much for the code example.

**Comment by chrispahm** [comment]
The above solution didn't work for me when the LESS variable was defined using another LESS function:

```less
@ui-fg:     hsl(@ui-hue, @ui-saturation, @ui-lightness - 72%);

div {
    @svg-value: escape(@ui-fg);
    background-image: url('data:image/svg+xml,<svg ... fill="@{svg-value}"/></svg>');
}
```

In this case, the compiled CSS contained **fill="undefined"**, and therefore didn't render correctly.
After reading the documentation of the [escape](http://lesscss.org/functions/#string-functions-escape) function, I found it only takes a string as an argument. 
Therefore, the solution was to use [variable interpolation](http://lesscss.org/functions/#string-functions-escape):

```js
@ui-fg:     hsl(@ui-hue, @ui-saturation, @ui-lightness - 72%);

div {
    @svg-value: escape("@{ui-fg}");
    background-image: url('data:image/svg+xml,<svg ... fill="@{svg-value}"/></svg>');
}
```

This should be a more general solution, as it will also work with the above example.
Just leaving this here in case somebody experiences the same issue!
