### ISSUE TITLE
dynamically generated variables can't be overwrite

### ISSUE THREAD

**Issue by clownvary** [less/less.js#3091]
I defined a parametric mixin

```less
.create-color(@color:black)
{
@test-color:@color;
}
.create-color();
.create-color(red);
```
then using it in other file
```less
body{
background-color:@test-color;
}
```
the `background-color` will always `black`, why not be `red`?
thanks!
