### ISSUE TITLE
Can we have css pseudo-classes nesting a selector?

### ISSUE THREAD

**Issue by e200** [less/less.js#3095]
Can we have a similar syntax for css pseudo-classes, so instead of:
```less
a:hover {
    text-decoration: underline;
}
a:active {
    color: red;
}
a:visited {
    color: green;
}
```
we can use:
```less
a {
    :hover {
        text-decoration:underline;
    }
   :active {
        color: red;
    }
    :visited {
        color: green;
    }
}
```
It's simple and more readable.

**Comment by calvinjuarez** [comment]
Check out http://lesscss.org/features/#parent-selectors-feature.

In your case, you can write it like this:

```less
a {
    &:hover {
        text-decoration:underline;
    }
    &:active {
        color: red;
    }
    &:visited {
        color: green;
    }
}
```
