### ISSUE TITLE
[Proposal] Module scope for less

### ISSUE THREAD

**Issue by Aqours** [less/less.js#3102]
```less
// component-a.less
@componet-name: a;
.@component-name {
  // ...
}

// component-b.less
@componet-name: b;
.@component-name {
  // ...
}

// index.less
@import "component-a.less";
@import "component-b.less";
```
Sometime we write less like this. `@component-name` is conflict in two less file.
So should we implement module scope like es2015 by using `{}`;

e.g:
```less
// component-a.less
@this-is-global-var: y;
{
    @componet-name: a;
    .@component-name {
      // ...
    }
}

// component-b.less
{
    @componet-name: b;
    .@component-name {
      // ...
    }
}

// index.less
@import "component-a.less";
@import "component-b.less";
```
