### ISSUE TITLE
use named arguments together with advanced arguments syntax "@variable..."

### ISSUE THREAD

**Issue by normanzb** [less/less.js#3103]
```less
.mixin-inner(@a:1px;@b:2px)
{
    border-top-width: @a;
    border-bottom-width: @b;
}

.mixin-outer(...)
{
    .mixin-inner(@arguments...)
}

.test
{
    .mixin-outer(@a:3px;@b:4px);
}
```

Above code throws exception says "Named argument for .mixin-outer @a not found". Since it accepts "random" variables, isn't this a valid usage?

**Comment by rjgotten** [comment]
No this isn't a valid usage.

The `...` variadic parameter in `.mixin-outer(...)` is _unnamed_ and it will match any number of parameters in a call signature, which are also _unnamed_.

Because these are all unnamed parameters, you cannot use named arguments with the mixin and expect that to work. Those names _do not exist_ in the mixin declaration signature and thus will not match. (That's literally what the error message is telling you...)

**Comment by normanzb** [comment]
Is that possible to making this ticket into a feature request then? 

It is very inconvenient that for named argument you always need to copy paste the exact arguments to the wrapping mixin, it would be nice that "..." truely accept "random" variables rather than limited just to list.

Do you think it is technically possible/worth to make that change ?

**Comment by rjgotten** [comment]
Conceptually it's a bad idea. The reason to use named arguments is that you're looking for a very, very specific signature of the mixin that you want to execute. Making named arguments also match a variadic `...` parameter goes directly against that philosophy.

Moreover, it becomes highly unpredictable when you tread into the territory of partial matches. E.g. should the call `.mixin(@a:3px, @b:4px)` match the declaration `.mixin(@a, ...) { }` or should it not?


And what about the declaration `.mixin(@a...)` ? Here's a dirty little secret: named arguments _already_ mix pretty badly with named variadic parameters. If a named variadic parameter is called with named arguments, the variadic nature of the parameter is ignored and it no longer absorbs the remaining arguments. E.g.

```less
.variadic(@a...) {
  value : @a;
}

.test-named {
  .variadic(@a:foo; bar);
}

.test-unnamed {
  .variadic(foo; bar);
}
```

currently outputs

```css
.test-named {
  value: foo;
}
.test-unnamed {
  value: foo bar;
}
```


(Also; please don't call them "random" variables. The correct technical term is _unnamed arguments_.)

**Comment by normanzb** [comment]
I think the "very specific" signature can be traced back to  deepest referenced mixin, in my example,  you can trace the "specific" signature from .mixin-inner, which is a named arguments mixin. So that is not against the philosophy.

in your example, tracing back to the place where `@a` is used, argument `@a` is used as a list rather than named mixin, in my opinion, in this case, it should truly thrown an error rather than proceeding forward.

**Comment by rjgotten** [comment]
You're advocating that the 'special' `@arguments` variable somehow retains the names of the arguments and feeds them forward? 

Ok; that could work from the viewpoint of a sound type system. 

However, being privy to a few of the details on how `@arguments` works, I can already tell you that it won't be easy to put into the codebase.

**Comment by seven-phases-max** [comment]
Just to agree with @rjgotten. The feature will require quite specific/exceptional implementation.

The very purpose of the `@arguments` is to return a list of the argument values. Sure it can keep hidden arg names internally so that the `...` expander later could try to use them too, but that would be pretty kludgy (since hidden internal names will require yet another dedicated Less object type instead of regular `list`). 

I would suggest to write a plugin with the corresponding function (i.e. `arguments()` to use instead of `@arguments`, as elarlier it was mentioned that the concept of special variables is flawed anyway)... Unfortunately this would open another problem:
```less
.outer-mixin(...) {
    .inner-mixin(my-custom-named-args()...);
}
```
so you'll have to use something like:
```less
.outer-mixin(...) {
    @var: my-custom-named-args();
    .inner-mixin(@var...); // ok
}
```
But this brings back the problem of the special type... The "named-args-list" is an exceptional internal type used only in the specific mixin matching code and there'no facilities to use such value (assign it to a variable, pass it to a mixin etc etc.) in any regular Less statements. 

Either way, adding the "feature request" label (yet again remarking that this does not have to be `@arguments...` or any other specific syntax mentioned above).
