### ISSUE TITLE
Improved parent selector support for :host ?

### ISSUE THREAD

**Issue by TremayneChrist** [less/less.js#3126]
https://developers.google.com/web/fundamentals/web-components/shadowdom#styling

It's hard to understand how to create shared styles for native and custom elements (light vs shadow DOM)

### Example:

button.less
```less
button {
  .shared-style;
}
```

my-custom-button.less
```less
:host {
  .shared-style;
}
```

../shared/button-styles.less
```less
.shared-style() {
  &:hover {
    color: red;
  }
}
```

CSS output
```css
button:hover {
  color: red;
}
```
```css
:host:hover {
  color: red;
}
```

This is incorrect as `:host` requires any other selectors to be placed inside of parentheses.

For example:
```css
:host(:hover) {
  color: red;
}
```

This can be fixed for `:host` by doing:
```less
.shared-style() {
  &(:hover) {
    color: red;
  }
}
```

The problem is that this then breaks the `button` styles which is not ideal when sharing styles between native and custom elements - it all gets a bit complicated.

Breaking up the mixin into smaller parts is an option, however, as `:host` always requires parentheses, could {less} automatically output them in the CSS?

**Comment by seven-phases-max** [comment]
Well, on one hand I can guess how tempting it may seem to just "fix" the compiler to do "the right thing". On the other hand this is clearly would be the same "guess the user intentions" stuff as in #1942 (Generally rejected because we'll end up with lotsa exceptional non-maintainable spagetti stacks instead of strict and straight-forward selector rendering rules. Or in other words: normally we should try to not break the "identical code should produce identical result" rule or it will break you in return).

Notice that the example is basically the same as for example:
```less
:not{
  .shared-style; // same wrong result
}
```
etc. And for a big picture all this can be reduced to the completely artificial and ridiculous:
```
dy {
    &bo {color: red}
}
```
->
```css
dybo {color: red} /* uhmm, shouldn't this be body instead? */
```

So I'd rather said this (fairly reasonable) use-case needs some fundamentally different idea/design-pattern.

**Comment by TremayneChrist** [comment]
Hey @seven-phases-max 

I agree that the compiler should not just be the answer to fixing it.
I also agree that your examples above should compile as they are written.

You would use `:not` in completely different ways though (at least from what I can imagine).

```less
// Like you said, it's the same issue as :host, however, this is very confused selector
// and is unlikely the share styles as they return very different elements.
// If they did share styles, they are likely to be minimal with simple selectors.
button, :not {
  &[attr] {
    color: red;
  }
}

// Also looks unlikely, but imagine the :host is compiled separately in another file.
// Both elements are buttons, for example, so they can share a large amount of styles.
button, :host {
  &[attr] {
    color: red;
  }
}
```

Currently we are wrapping `:host` selector after compilation, which is fine, and maybe just a plugin is the answer.

**Comment by seven-phases-max** [comment]
Observation `#1` the following code would do the trick if `extend` could work within parens (or at least  did not have the limitation of being the last element of a selector):
```less
.shared-style() {
    &:hover {
        color: red;
    }
}

button {.shared-style}
host_  {.shared-style}

// adapter:

:host(:extend(host_ all)) {} // fail: currently`extend` does not work in parens
```
