### ISSUE TITLE
missing units after compilation 

### ISSUE THREAD

**Issue by parulmahajan1992** [less/less.js#3144]
@var1: 2em;
@var2: 1/2em;

#myClass{
width: @var1*@var2 ;
}

Output for this is:
#myClass{width:1em};

But if we interchange the variables as:
#myClass{
width: @var2*@var1 ;
}

Output for this is:
#myClass{width:1};

em is missing. :(

**Comment by seven-phases-max** [comment]
Please use [backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to format your code.
---
I suppose it's a result of the #3047 bug.
Quick workaround:
```less
@var1: 2em;
@var2: 1/2em*1em;

#myClass{
    width: @var2*@var1;
}
```
