### ISSUE TITLE
Parser ignores strings at an unknown at-rule prelude (thus failing at `{` and `;` there)

### ISSUE THREAD

**Issue by sylingd** [less/less.js#3147]
I used less to write some user styles for [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/), it have some special syntaxs, for example, this extension support `regexp("Regular expression")`. So the following codes will work well on Stylish:

```css
@-moz-document regexp("(\d{0,15})") {
	a {
		color: red;
	}
}
```

But it can not work with less.js:
![tim 20180102004110](https://user-images.githubusercontent.com/5326684/34469247-a8beaeca-ef55-11e7-9fd2-e72f76270752.png)

The less.js says:
```
ParseError: Unrecognised input. Possibly missing opening '{' on line 1, column 32:

1 @-moz-document regexp("(\d{0,15})") {
2 	a {
```

Is there a way to ignore the characters between quotation marks? Or are there other ways to solve this problem?
Thank you

**Comment by rjgotten** [comment]
You can insert literal content using a string that is 'unquoted' via the `~` operator.
What might work for you is something like:

```less
@-moz-document regexp(~'"(\d{0,15})"') {
  a {
    color : red;
  }
}
```

If that still messes with the parser, you may consider moving the expression contents into a variable first:
```less
@regexp : ~'"(\d{0,15})"';
@-moz-document regexp(@regexp) {
  a {
    color : red;
  }
}
```
