### ISSUE TITLE
Question: Means of deriving resolved mixins

### ISSUE THREAD

**Issue by cirrusdeveloper** [less/less.js#3154]
Hi,

I have a requirement to parse less files and output them as JSON, with variables and mixins "resolved". This is straightforward to do for variables (and is done already by several libs/grunt plugins).

Looking for any pointers on how to achieve this for mixins?

thanks.

**Comment by seven-phases-max** [comment]
Mmm, I'm not quite sure I can understand how a "resolved mixin" would look like? Or do you mean only "non-parametric mixins" (i.e. ordinal CSS rulesets)?

**Comment by cirrusdeveloper** [comment]
Hi, thanks for coming back to me. My understanding of the terminology isn't great but basically, exhaustively expanding the parametric mixins to enumerate all possible styles..for instance say I had the less source:

.parametricMixin(@param1: @somevar1; @param2: @somevar2; @param3: @somevar3) {
  font-size: @param1;
  font-weight: @param2;
  color: @param3;
}

.mixinA() {
  .parametricMixin(@var1; @var2; @var3);
}

.mixinB() {
  .parametricMixin(@varX; @varY; @varZ);
}

I'm expected to produce something like:

.mixinA {
  font-size: a;
  font-weight: b;
  color: c;
}

.mixinB {
  font-size: x;
  font-weight: y;
  color: z;
}

**Comment by cirrusdeveloper** [comment]
Hi, is part of a product requirement, a non CSS-based system that nonetheless wants to specify styling using Less. I need to transform the Less sources so that they can referenced from "not CSS" and read relatively easily. Appreciate your thoughts, thanks again.

**Comment by seven-phases-max** [comment]
>I need to transform the Less sources so that they can referenced from "not CSS"

Well, it's simply impossible in a general (unless you're about to write your own Less->Something-Else transpiler). Sure if your limit your Less project to trivial-values-global-scope variables and mixins, something like that could work to a certain degree.
 But why should it be so indirect? If you need other thing (language/tools) to modify styling, why do not specify this in that "other language" and then simply generate corresponding vars/mixins? 
E.g. if I need a javascript script to specify a value of Less variable then I simply set that variable, either by generating text direct via corresponding functions (`modifVars` etc), I do not need to read that variable form a less source and, more over, the variable do not have to be even defined in the said less source at all. 
Or in other words, if some other language/tool is supposed to be a "center" of styling then it should be just that - "the center of styling" - thus all variable values, property sets etc. are to be defined right there (in whatever usable format) and then converted to corresponding Less (or whatever preprocessor) code. Not upside-down.

**Comment by martinfitzg** [comment]
Hey Max,
      The UI for the system been described here is all generated from meta data that is generated on the server, and sent the the client (browser), when it receives the data it has an interpreter that can create the UI.  

Up until now we have we have less generate the CSS at build time when we package up the product and this worked great, but now we have to give the server the ability to over write certain aspects of the "default" styling of certain elements.  I.E. change a background color or the style / weight of a certain peace of text etc.  

The interpreter that runs on the client can over write these values programmatic, which means the server has to send the raw values for these (when it needs to) in the metadata.  

Our less files are all ready the central place that we store these values, so it makes since for us to reuse these for reference in the server when trying to get the value for a certain attribute such as a color etc to change it from it's default.
The issues were having then is to get the less file in to a  format that server can retrieve the raw values from.

In this example (much like the one above)
```less
@font-size-base: 14px;
@var1: 15px;
@var2: 500;
@Var3: red;

.parametricMixin(@param1: @somevar1; @Param2: @somevar2; @param3: @somevar3) {
font-size: ceil((@font-size-base * 2));;
font-weight: @Param2;
color: @param3;
}

.mixinA() {
.parametricMixin(@var1; @var2; @Var3);
}

.mixinB() {
.parametricMixin(@varx; @vary; @varz);
}

```

We would like to take the above input and generate the bellow json from it, this would give us the capability to retrieve the values as needed on the server but still have less control variables and keep the server / client in sync.  As you have mentioned above we would only expect 0-paramater-mixins to be ultimately be resolved out eg in the example here, there is no mention of "parametricMixin" in the out putted JSON.




```less
{
	font-size-base : '14px',
	var1 : '15px',
	var2 : '500',
	Var3 : 'red',

	.mixinA {
		font - size : '30px',
		font - weight : '500',
		color : 'red',
	}

	.mixinB {
		font - size : x,
		font - weight : y,
		color : z,
	}

}
```
Any help or pointers you could give on achieving the above out put would be greatly appreciated!

Thanks Max,

Regards,
Martin
