### ISSUE TITLE
compile font-family name with unicode is something wrong

### ISSUE THREAD

**Issue by xinglie** [less/less.js#3160]
I have a css rule like this
```css
textarea {
    font-family: 'helvetica neue','wenquanyi micro hei',\5FAE\8F6F\96C5\9ED1, \5B8B\4F53, sans-serif;
  }
```

if i save it to x.less and use less　to compile the file

less tell me
```bash
{ [Error: Unrecognised input]
  type: 'Parse',
  filename: 'input',
  index: 67,
  line: 2,
  callLine: NaN,
  callExtract: undefined,
  column: 56,
  extract: 
   [ 'textarea {',
     '    font-family: \'helvetica neue\',\'wenquanyi micro hei\',\\5FAE\\8F6F\\96C5\\9ED1, \\5B8B\\4F53, sans-serif;',
     '  }' ],
  message: 'Unrecognised input',
  stack: undefined }
```

is there i miss something?
