### ISSUE TITLE
Is is possible to set a default value with mixins?

### ISSUE THREAD

**Issue by blachawk** [less/less.js#3175]
If I have the following setup...

```
.box(@value) {
    width: @value;
    height: @value;
}
.bigBox() {
    .box(500px);
}
```
In the above example, I would like to set a default value for width and height if `(500px)` is not set. Is this possible with LESS?

Thanks!

**Comment by seven-phases-max** [comment]
Yes:
```less
.box(@value: 500px) {
    width: @value;
    height: @value;
}
.bigBox() {
    .box();
}
```
For more examples see http://lesscss.org/features/#mixins-feature-mixins-parametric-feature.
