### ISSUE TITLE
Variables are undefined inside namespace defined with parenthesis.

### ISSUE THREAD

**Issue by imkremen** [less/less.js#3183]
I'll try append `()` to my namespace because I don't want it appear in my CSS output, but in this case mixins doesn't see variables.

Reproduced in version 2.7.3 and 3.0

#### Here example:
```less
#ns() {
  @p: 8px;
  .box() {
    padding: @p;
  }
}
.elem {
  font-size: 32px;
  border: 1px solid;
  #ns.box;
}
```

#### Output:
```
SyntaxError: variable @p is undefined in C:\Users\vgre.ISD\Desktop\New folder (2)\ns.less on line 11, column 4:
10    border: 1px solid;
11    #ns.box;
12 }
```

#### Expected output:
```css
.elem {
  font-size: 32px;
  border: 1px solid;
  padding: 8px;
}
```

### Here [Codepen](https://codepen.io/imkremen/pen/oEJMjG)

**Comment by seven-phases-max** [comment]
It should not per #2093.  In short: formally `#ns() {...}` is not a namespace anymore. By invoking `#ns.box` you do not actually invoke `#ns` mixin itself so `@p` is really never defined (In future it's possible for Less  to support something like this via `#ns().box()` syntax or so, but for now there's no such syntax).
The proper code for your goal would still be:
```
#ns {
    @p: 8px;
    .box() {
        padding: @p;
    }
}
```
There's no reason for `#ns` to have `()` there. Unless you're doing something else (like having regular CSS rulesets with-in `#ns`) - in that case you''ll have to use "full expansion" like `#ns; .box;`.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #3183.

**Comment by imkremen** [comment]
@seven-phases-max so, maby we need to corect docs?
#### features-overview.md
> Note: append `()` to your namespace if you don't want it to appear in your CSS output i.e. `#bundle .tab`.

**Comment by seven-phases-max** [comment]
@imkremen 
>Note: append `()` to your namespace if you don't want it to appear in your CSS output i.e. `#bundle .tab.`

I did notice the newer docs version has such recommendation - yes, it may be misleading. I.e turning namespaces into parametric mixins is normal procedure but only if you understand what you're actually doing. As a generic tip it's definitely harmful.
The proper primary example for namespaces should look like this:
```less
#bundle {
  .button() {
    display: block;
    border: 1px solid black;
    background-color: grey;
    &:hover {
      background-color: white
    }
  }
  .tab() { ... }
  .citation() { ... }
}
```
It's tempting to move all these `()` to `.bundle` itself for the sake of shorter code, but counting it's not going to work if the namespace contains variables (also a typical namespace usage) to be used by member mixins - yes, the section should not start the way it is now.
