### ISSUE TITLE
calc() with escaped strings removes parenthesis

### ISSUE THREAD

**Issue by oBusk** [less/less.js#3191]
In 3.0 calculations in `calc()` are now only done on runtime, as stated in [changelog.md](https://github.com/less/less.js/blob/v3.0.0/CHANGELOG.md). Previously, since content of `calc()` was being calculated, things that wanted to be kept had to be espaced as such:

```less
// input
.a {
  @v: 10px;
  height: calc(~'100%' - ((@v  * 3) + (@v * 2)));
}

// output
.a {
  height: calc(100% - 50px);
}
```

After upgrading to **3.0** the result is

```less
// input
.a {
  @v: 10px;
  height: calc(~'100%' - ((@v  * 3) + (@v * 2)));
}

// Expected output
.a {
  height: calc(100% - ((10px * 3) + (10px * 2)));
}

// Actual output 
.a {
  height: calc(100% - (10px * 3) + (10px * 2));
}
```

### Workaround

This can currently be fixed by not escaping;

```less
// input
.a {
  @v: 10px;
  height: calc(100% - ((@v  * 3) + (@v * 2)));
}

// output
.a {
  height: calc(100% - ((10px * 3) + (10px * 2)));
}
```
