### ISSUE TITLE
Font-family with colour name is converted to hex

### ISSUE THREAD

**Issue by thany** [less/less.js#3192]
Suppose this line of Less code:

```less
h1 { font-family: Impact Black, serif; }
```

Will outpus as:

```css
h1 { font-family: Impact #000, serif; }
```

That's wrong. Font-family is not a colour property, but a comma-separated list of names. If there happens to be a name that is also a CSS colour name, it should *not* be converted to hex.

Workaround is to quote the font name. But quoting font names in CSS is not required if the font name only contains a few letters and a space. Quoting is required for other special characters.

See also: https://mothereff.in/font-family
