### ISSUE TITLE
Calc function considers 100% as 100px

### ISSUE THREAD

**Issue by eylult** [less/less.js#3193]
width: calc(100% - @nav-width);

In a function such as above, the 100% is considered as 100px. So if the nav-width is equal to 20px, the width will always return 80px regardless of the 100% measurement. 

We started seeing this issue in 3.0. We don't have the issue after reverting back to 2.7.3.

**Comment by matthew-dean** [comment]
I'm not sure I follow. If anything, versions before 3.0 would have ignored units for any expression.

For instance,
```less
.box {
  @nav-width: 80px;
  width: calc(100% - @nav-width);
}
```
with default options in 2.x would result in:
```less
.box {
  width: calc(80%);
}
```
