### ISSUE TITLE
maybe some bug in less 3.0.1

### ISSUE THREAD

**Issue by lialosiu** [less/less.js#3195]
sorry for my poor English.... m(_ _ )m

this less (just an example):

```less
@cols: 1, 2;

.a(@i: length(@cols)) when (@i > 0) {
  @divider: e(extract(@cols, @i));
}
.a;

.b(@j: 1) when (@j < length(@cols)) {
  @divider: e(extract(@cols, @j));
}
.b;
```

will cause exception in less 3.0.1
![image](https://user-images.githubusercontent.com/1682158/38132721-de76a9fe-343e-11e8-8eac-250c08a6e7d4.png)

but in less 2.7.3, run so far so good.
![image](https://user-images.githubusercontent.com/1682158/38132733-ecd2dad6-343e-11e8-88a4-7a67975b0f66.png)

maybe some bug at here?
exception throwed in this line:
https://github.com/less/less.js/blob/b873737f5aa19c7b48f88743cafcf5aa47ac0ed2/lib/less/parser/parser-input.js#L67

because `current` is a number value `2`:

![image](https://user-images.githubusercontent.com/1682158/38133039-10a56c0c-3440-11e8-9777-e49955a0a5bc.png)

any solution?
