### ISSUE TITLE
Compile less mixin to file where it was called

### ISSUE THREAD

**Issue by gadzhimari** [less/less.js#3197]
Hi. I didn't find anything in docs for this case. I have two common components styles(Button and Link) in react application which has sometimes the same view. And I declared common styles in mixin.less file. But the problem is, when I look at chrome inspector and see that the output css came from mixin.less file instead of file where it was called. For example,
```
// mixin.less
.setSize(@size) {
   font-size: @size;
}
```
And this is calling above mixin
```
// Button.less
.setSize(16px);
```
```
// Link.less 
.setSize(16px); // output from mixin.less, but I want to compile that portion of css to isolated component style file
```

**Comment by seven-phases-max** [comment]
Honestly I'm not sure I understand if you're talking about *sourcemaps* (the thing you see in the browser inspector) or just about destination css files.
The concrete example (copy-paste of all this) from the inspector would be helpful (especially since a `react` framework may vastly interfere in how the things are actually compiled).

**Comment by seven-phases-max** [comment]
Also (if its about *sourcemaps*) I wonder if it could be a consensus about that. E.g. notice that if I see some:
`border: 1px solid shmoo;` code I'll be wondered where it cames from I'll prefer to see the exact line where it came form and if it's:
```less
.somemixin() {
    border: 1px solid shmoo;
}
```
that'll be it.

Obviously, if that would be:
```less
.somemixin(@foo) {
    border: 1px solid @foo;
}
// and then:
.somemixin(shmoo);
```
I'd like to see the mixin call instead of its definition. 

In other words, general there can be no *the best* general approach, it's very use-case dependend.

**Comment by gadzhimari** [comment]
Yeah, I'm talking about sourcemaps. Here real-world example. I'm calling two mixins from Link.less file. Those mixins declared in mixin.less file. After compilation that I see in devtools
![2018-04-03_18-17-14](https://user-images.githubusercontent.com/1849608/38258570-7fafcdbc-376b-11e8-84d0-b99599d11a9d.png)
Those mixins also called from other components less-files. And I want to in every less file where I call mixins, show this style only in component css-file. Is any possible?

**Comment by seven-phases-max** [comment]
And how for instance a mixin for `.Link_color_blog` looks like?
If it's something like:
```less
.mixin() {
    link: #5db030; // whatever
}

.Link_color_blog {
    .mixin();
}
```
then it's an issue for sure.

If *however* it is something like:
```less
.mixin() {
    &_color_blog {
        link: #5db030; // whatever
    }
}

.Link {
    .mixin();
}
```
it would be the thing I described above, i.e. either outcome is questionable and depends on a use-case.
