### ISSUE TITLE
Syntax error for a function that seems correct.

### ISSUE THREAD

**Issue by lipis** [less/less.js#3218]
When trying to compile the following

```less
@web-font-path: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700";

.web-font(@path) {
  @import url("@{path}");
}
.web-font(@web-font-path);
```

https://github.com/thomaspark/bootswatch/blob/v3.3.7/cosmo/bootswatch.less#L5-L10

I'm getting this error:

```bash
$ ./node_modules/less/bin/lessc cosmo/bootswatch.less
SyntaxError: variable @path is undefined in /Users/lipis/bootswatch/cosmo/bootswatch.less on line 10, column 1:
9 }
10 .web-font(@web-font-path);
11

```

------

Less version: 3.0.4 / macOS
