### ISSUE TITLE
Variable calculations inside `calc()` not calculated.

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#3221]
### Test Case

```less
@a: 10px;
@b: 10px;

.one {
	width: calc(100% - ((@a + @b)));
}
```

### Expected Output (& Output for v2.7.1)

```css
.one {
  width: calc(100% - 20px);
}
```

### Actual Output (lessc v 3.0.4)

(Command: `lessc -sm=on test.less > test.css`)

```css
.one {
  width: calc(100% - 10px + 10px);
}
```

**Comment by matthew-dean** [comment]
Closing as duplicate of #3191.

**Comment by matthew-dean** [comment]
So, I slightly misunderstood this, but it's working as expected. Essentially, the calc() bug was recently fixed and no math is performed within `calc()`. But functions within `calc()` will still perform math on their arguments (unless the inner function is also calc.

Meaning, you can hack 2.x behavior with:
```less
.one {
	width: calc(100% - (min(@a + @b)));
}
```
But there's no need, since the calculated result is the same.

**Comment by matthew-dean** [comment]
> If so, what's the expectation for this?

The above will/should produce 
```css
.foo {
  width: calc(100% - 20px);
}
```
In other words, variables can be evaluated in `calc()`, but the _resulting expression_ won't be. When you write `width: calc(100% - ((@a + @b)));`, each of `@a` and `@b` will be evaluated, but `10px + 10px` (the result) cannot be, because of the nature of `calc()`. It preserves those expressions.
