### ISSUE TITLE
Extension of reference imported selector produces inconsistent output

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#3222]
### Files:

*test.less*
```less
@import (reference) 'test-referenced.less';
@import 'test-extensions.less';
```

*test-referenced.less*
```less
.font-base {
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	letter-spacing: .05em;
}
.clearfix {
	&:before,
	&:after {
		content: " ";
		display: table;
	}
}
```

*test-extensions.less*
```less
.font-extension {
	&:extend(.font-base all);
}
.a-clearfixed-thing {
	&:extend(.clearfix all);
}
```

```lessc test.less```

### v2.7.1 & Expected Output

```css
.font-extension {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  letter-spacing: .05em;
}
.a-clearfixed-thing:before,
.a-clearfixed-thing:after {
  content: " ";
  display: table;
}
```

### v3.0.4 Output

```css
.font-extension {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;letter-spacing: .05em;
}
.a-clearfixed-thing:before,
.a-clearfixed-thing:after {
  content: " ";display: table;
}
```
