### ISSUE TITLE
Vars storing calculations don't crunch the calculation if the var is used in calc()

### ISSUE THREAD

**Issue by calvinjuarez** [less/less.js#3235]
This is likely one of the first workarounds people will try when their calc starts working the way it's designed to (ignoring the content of `calc()`).

Critically, the calculated value of `calc(100% - 10px + 30px)` (as shown in the _v3.5.0-beta_ output) is **_NOT the same_** as the expected and intuitive calculated value of `calc(100% - 40px)`.

## _test.less_
```less
@foo: 10px;

.test {
	@_calculated: (@foo + 30px);
	width: calc(100% - @_calculated);
}
```

## Less 2 Output & Expected
`npm i -g less@2 && lessc --strict-math=on test.less ./test.css`
```css
.test {
  width: calc(100% - 40px);
}
```
_(see https://github.com/less/less.js/issues/3221#issuecomment-400128626)_

## Less 3 Output
`npm i -g less@3.5.0-beta && lessc --strict-math=on test.less ./test.css`
```css
.test {
  width: calc(100% - 10px + 30px);
}
```
