### ISSUE TITLE
[Proposal] Deprecate `is...` functions for actual `is` function

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#3249]
As Less has expanded the list of types that can be assigned to vars, it's forced the expansion of type checking `is...` functions like `iscolor()` `isem()`

Instead, I think these should be deprecated to a single `is()` form, so instead of:
```less
iscolor(blue); 
iskeyword(keyword);
ispixel(10px);
isruleset({ a: b })
```
We would do:
```less
is(color, blue); 
is(keyword, keyword);
is(pixel, 10px);
is(ruleset, { a:b })
```
I don't know if this is useful, but this would also mean you could do:
```less
@type: ruleset;
... is(@type, { a:b })
```
That is, the type could be an eval'd argument. Either way, it seems cleaner vs polluting the function space for all types.
