### ISSUE TITLE
Unexpected calculation

### ISSUE THREAD

**Issue by DongShelton** [less/less.js#3280]
Using less with multiple continuous offset will cause unexpected calculation.
For example, I am using less to write `box-shadow`:
```CSS
.some-style {
  box-shadow: 3px -3px 7px 0 rgba(0, 0, 0, .07);
}
```
And less would compile that to:
```CSS
.some-style {
  box-shadow: 0 7px 0 rgba(0, 0, 0, .07);
}
```
It would calculate the `3px -3px`, that is unexpected, is there a way to avoid that?
