### ISSUE TITLE
is there anyway I can make less only compile the `@import` part ?

### ISSUE THREAD

**Issue by lili21** [less/less.js#3286]
```less
// vars.less
@width: 200px;
@height: 200px;

// style.less
@import './vars.less'

.root {
  width: @width;
  height: @height;
}
```

expect result

```less
//result.less
@width: 200px;
@height: 200px;

.root {
  width: @width;
  height: @height;
}
```
