### ISSUE TITLE
[Question] Option to avoid expand @import url into @font-face definition.

### ISSUE THREAD

**Issue by eusonlito** [less/less.js#3303]
There are any option to avoid expand `@import url` font into `@font-face`?

Before:

```css
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,500,600');
```

After:

```css
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: local('Montserrat Regular'), local('Montserrat-Regular'), url(https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wlhzg.ttf) format('truetype');
}
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 500;
  src: local('Montserrat Medium'), local('Montserrat-Medium'), url(https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_ZpC3gnD-w.ttf) format('truetype');
}
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 600;
  src: local('Montserrat SemiBold'), local('Montserrat-SemiBold'), url(https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_bZF3gnD-w.ttf) format('truetype');
}
```

I need to preserve `@import url` definition instead `@font-face` after less compile.

Thanks!
