### ISSUE TITLE
image-width() breaks data-uri()

### ISSUE THREAD

**Issue by dg** [less/less.js#3309]
Calling image-width() affects output generated by data-uri() in Less 3.8.1

This generates correct base64 output:

```css
a {
	background: data-uri('images/tick.png');
	padding-right: image-width('images/tick.png');
}
```

This generates invalid base64 output:

```css
a {
	padding-right: image-width('images/tick.png');
	background: data-uri('images/tick.png');
}
```
