### ISSUE TITLE
Losing wildcard selector inside mixins with ampersand

### ISSUE THREAD

**Issue by minimit** [less/less.js#3316]
Using gulp-less v4.0.1, so with less v2.6.x || v3.7.1
In this particular case the * selector gets lost in the compiling the mixin:

# Example

```less
.nth-child(@child, @start, @increment, @decrement, @rules) when (@child > 0) {
  .nth-child(@child - 1, @start, @increment, @decrement, @rules);
  &:nth-child(@{child}) {
    @rules();
  }
}

@animation-delay: { animation-delay: @start + (@child * @increment) - (@child * @decrement); };


.content > * {
  animation-delay: 150ms; // @start + @child * @increment
  .nth-child(@child:3, @start:0ms, @increment:50ms, @decrement:0ms, {
    @animation-delay();
  });
}
```

# Result

```less
.content > * {
  animation-delay: 150ms
}
.content > :nth-child(1) {
  animation-delay: 50ms
}
.content > :nth-child(2) {
  animation-delay: .1s
}
.content > :nth-child(3) {
  animation-delay: 150ms
}
```

# Expected Result

```less
.content > * {
  animation-delay: 150ms
}
.content > *:nth-child(1) {
  animation-delay: 50ms
}
.content > *:nth-child(2) {
  animation-delay: .1s
}
.content > *:nth-child(3) {
  animation-delay: 150ms
}
```
