### ISSUE TITLE
Modifying / Wrapping List of Rulesets

### ISSUE THREAD

**Issue by JProffitt71** [less/less.js#3324]
I have a variable length list of color schemes I need to output helper classes for.  Let's say I append these variables to the stylesheet like this:

```
(LESS code)
...
@primary-scheme: {
    @background-color: #f00;
    @text-color: #fff;
}
@secondary-scheme: {
    @background-color: #0f0;
    @text-color: #fff;
}
...
@accent-scheme: {
    @background-color: #00f;
    @text-color: #fff;
}
@scheme-names: primary secondary ... accent;
```

I can easily iterate over these schemes like this:
```
each(@scheme-names, .(@name) {
    @scheme-var: ~"@{name}-scheme";
    @scheme: @@scheme-var;
    (Do stuff with @scheme reference)
}
```

But now I'd like to define some extra helper variables automatically that are really expensive to calculate. Say an `@accent-color` that stands out from both the `@background-color` and `@text-color` without clashing with either of them.

Is there a way that I can calculate these once and reuse them, without knowing how many scheme colors there are going to be ahead of time? I tried doing this:

```
each(@scheme-names, .(@name) {    
    @scheme-var: ~"@{name}-scheme";
    @scheme: @@scheme-var;

    @scheme-auto-var: ~"@{name}-scheme-auto";
    @@scheme-auto-var: {
         (Generate auto vars here)
    }
}
```

But of course you can't dynamically define rulesets or variables so that is a no-go.

I have to do something because these calculations in aggregate get redone several dozen times and add ~20 seconds to each LESS compilation.

If I can't do this cleanly by modifying the ruleset or wrapping it with another one, then I'd appreciate a workaround.

In the end, I just want to do the automatic variable calculations once for each scheme and save them somewhere that I can access them again given just the scheme name. Ideally I'd like to modify the rulesets themselves so the automatic variables are in the same place as the rest of them.

**Comment by JProffitt71** [comment]
Closing this issue since it's documented that you can't define variable variables or variable rulesets. This is a design question and not a problem with the library (incidentally, I fixed it by adding a mixin call to each color scheme ruleset being injected).

**Comment by matthew-dean** [comment]
@JProffitt71 Well you can do some powerful things with maps. Like you could do this:
```less
@primary-scheme: {
    @background-color: #f00;
    @text-color: #fff;
}

@secondary-scheme: {
    @background-color: #0f0;
    @text-color: #fff;
}

@accent-scheme: {
    @background-color: #00f;
    @text-color: #fff;
}

.box(@scheme) {
  color: @scheme[@text-color];
}

.container {
  .box(@accent-scheme);
}
```
So, you can make arbitrary maps of data, and then you can evaluate mixins and pass in whichever theme you want to use, and use a `[]` accessor to return the value from that ruleset.

You can even do:
```less
.box(@scheme) {
  color: @scheme[@background-color];
}

each(primary secondary accent, .(@item) {
  .container-@{item} {
    @name: ~"@{item}-scheme";
    .box(@@name);
  }
})

// outputs

.container-primary {
  color: #f00;
}
.container-secondary {
  color: #0f0;
}
.container-accent {
  color: #00f;
}
```

Does that work for you?
