### ISSUE TITLE
Aliasing Ruleset Lookups for Additional Lookups

### ISSUE THREAD

**Issue by JProffitt71** [less/less.js#3325]
I have these variables defined:

```
@color-schemes: {
    @primary: {
        @color: blue;
        ...
    };
    ...
}
```

And I am iterating over a variable to retrieve some of the rulesets in @color-schemes and use them:

```
each(@theme-color-names, .(@color-name) {
    @scheme: @color-schemes[@@color-name]; // e.g. @color-name = primary
    color: @scheme[@color];
});
```

I get this error:

```
Could not evaluate variable call @scheme at ...
```

As far as I can tell the issue is that LESS thinks `@color-schemes[@@color-name]` is ambiguous like `#library.colors` from the documentation is because it doesn't end with parentheses. But there's no way I can see to make it unambiguous because `@color-schemes[@@color-name]()` doesn't seem to be valid syntax.

**Comment by matthew-dean** [comment]
> As far as I can tell the issue is that LESS can't do lookups on rulesets returned from lookups.

Hmm... looks like a bug. In the meantime, you can actually write:

```less
each(@theme-color-names, .(@color-name) {
    color: @color-schemes[@@color-name][@color];
});
```

**Comment by JProffitt71** [comment]
I was able to circumvent the issue by moving my scheme rulesets to the root and aliasing them without a lookup.

**Comment by matthew-dean** [comment]
@JProffitt71 Ah good that you found another workaround.

**Comment by paulozoom** [comment]
Have a similar situation, where a ruleset that’s retrieved by a lookup can't be iterated on:

```less
@one: {
    @two: {
        foo: red;
        bar: blue;
    };
};

each(@one[@two], {
    .@{key} {
        content: @value;
    }
});
```

I get the following error: `SyntaxError: this.value.genCSS is not a function in test.less on line 10, column 9:`

Interestingly, @key actually works, returning a single `1` — regardless of how many properties there are in `@one[@two]`.
