### ISSUE TITLE
Can’t use @import inside each()

### ISSUE THREAD

**Issue by paulozoom** [less/less.js#3339]
Have this piece of code that imports component files based on a map.

```less
@components: {
    columns: true;
    ratios: false;
};

each(@components, {
    & when (@value = true) {
        @import "components/@{key}.less";
    }
});
```

But I get: `error evaluating function `each`: variable @key is undefined`.

But **it is** defined, because this works:

```less
// LESS
each(@components, {
    & when (@value = true) {
        .test {
            content: @key;
        }
    }
});

// CSS Output
.test {
    content: columns;
}
```
 I wondered whether the `& when` guard was the culprit, but it isn’t, removing it still gives me an error.
