### ISSUE TITLE
a problem of function `e()`

### ISSUE THREAD

**Issue by zhnoah** [less/less.js#3345]
I have a piece of code, that works fine:

```less
// input
.mixin-create-width-style() {
    @list: e("90 100 110");

    each(@list, {
        .w-@{key} {
            width: @value;
        }
    })
}

.a {
    .mixin-create-width-style();
}

// output
.a .w-1 {
  width: 90;
}
.a .w-2 {
  width: 100;
}
.a .w-3 {
  width: 110;
}
```

but, When I want to pass a list string as a parameter:

```less
// input
.mixin-create-width-style(@str) {
    @list: e(@str);

    each(@list, {
        .w-@{key} {
            width: @value;
        }
    })
}

.a {
    .mixin-create-width-style("90 100 110");
}
```

It doesn't work:

```less
// output
.a .w-1 {
  width: 90 100 110;    // It's not I want
}
```

What's wrong with that?
