### ISSUE TITLE
Namespace Name Conflict/Issue

### ISSUE THREAD

**Issue by Jscherbe** [less/less.js#3346]
I think there may be an issue with namespace names. Using certain characters in the namespace make the mixin undefined. I am working in node.js on less 3.9.0 latest. I was attempting to use the word "#Effects()" as my namespace name. 

I was thinking maybe this has something to do with using characters that are used in hex colors? If you using characters out of the hex range (A-F) the error goes away. I have found that names that include "D", "E" and "F" are giving the error. Any combination over two letters gives the error.

To test, I grabbed the documentation example on namespaces (below):

```less
#Library() {
  .colors() {
    primary: green;
    secondary: blue;
  }
}

#Library() {
  .colors() { primary: grey; }
}

.button {
  color: #Library.colors[primary];
  border-color: #Library.colors[secondary];
}

```

I then tried different names for the namespace, the following all result in the mixin being undefined:

- #Effects
- #Effect
- #Def
- #DEF
- #DEFFER
- #ABC
- #ABBF

Example test:

```less
#DEF() {
  .colors() {
    primary: green;
    secondary: blue;
  }
}

#DEF() {
  .colors() { primary: grey; }
}

.button {
  color: #DEF.colors[primary];
  border-color: #DEF.colors[secondary];
}

```
