### ISSUE TITLE
How to use plugin function with some math calc？

### ISSUE THREAD

**Issue by bugkiwi** [less/less.js#3349]
The code looks like this:

```javascript
// less-plugin.js
var isIOS = process.env.IS_IOS ? true :  false;
module.exports = {
    install: function(less, pluginManager, functions) {
        functions.add('f', function(iosValue, androidValue) {
            return (isIOS ? iosValue : androidValue) + 'px';
        });
    }
};
```

```less
// var file
@plugin "./less-plugin"
@M1: f(15, 13);

// less file
.test {
    width: @M1; // work
    height: @M1 - 5; // wrong
}
```

I have try  remove `px` in `f` function，but  the result will been:
```
.test {
    width: 15;
    height: 10;
}
```

and I don't want declare a new var like `@M1_INT`。

Any suggestion?
