### ISSUE TITLE
Feature request: apply only properties evaluated with variables from mixin

### ISSUE THREAD

**Issue by dawidgarus** [less/less.js#3351]
Let's say you have a mixin:
```less
.make-input(@radius) {
  background: #fff;
  border: #000;
  border-radius: @radius;
}
```
And apply it to element:
```less
input {
  .make-input(3px);
}
```
Often you would want to customize element with more specific selector, like:
```less
input.bigger {
  .make-input(5px);
}
```
The obvious drawback is that the properties with didn't change (background, border) will be set and compilation will produce:
```less
input {
  background: #fff;
  border: #000;
  border-radius: 3px;
}
input.bigger {
  background: #fff;
  border: #000;
  border-radius: 5px;
}
```
I propose to introduce a way to apply mixin that will skip properties that are not computed using variables, for example:
```less
input.bigger{
  .make-input(5px) skip-static;
}
```
Which would produce:
```less
input {
  background: #fff;
  border: #000;
  border-radius: 3px;
}
input.bigger {
  border-radius: 5px;
}
```
Main goal is to avoid creating two mixins, like make-input and adjust-input so one can keep all relevant properties together.
Name `skip-static` is just a suggestion.

**Comment by matthew-dean** [comment]
I don't see the need here. It just seems like code refactoring is the answer. After all, why not just write exactly what you have:
```less
input {
  background: #fff;
  border: #000;
  border-radius: 3px;
  &.bigger {
    border-radius: 5px;
  }
}
```
The use case provided doesn't make sense in the way it's abstracted. That is, no mixin seems necessary.

If you're repeating this pattern to multiple classes, you could also do:
```less
.make-input(@radius, @skip-static: false) {
  & when not (@skip-static) {
    background: #fff;
    border: #000;
  }
  border-radius: @radius;
}

input {
  .make-input(3px);
  &.bigger {
    .make-input(5px, true);
  }
}
```
There's no need for extra syntax when you can build the mixin you want with the same pattern, or just not use a mixin at all.
