### ISSUE TITLE
"&" includes all parent selectors

### ISSUE THREAD

**Issue by dreamerblue** [less/less.js#3356]
Class name using "&" will include all parent selectors. Only current parent selector should be included.

It's so confusing. If it's an expected behavior, how to write less to output the expected css below?

Less Version: 3.9.0

### Less

```less
.wrapper {
  .prefix {
    &-a &-b {
      color: #333;
    }
  }
}
```

### Output CSS

```css
.wrapper .prefix-a .wrapper .prefix-b {
  color: #333;
}
```

### Expected CSS

```css
.wrapper .prefix-a .prefix-b {
  color: #333;
}
```

**Comment by seven-phases-max** [comment]
Closing in favour of #1075 (and potentially #3053).

>If it's an expected behavior, how to write less to output the expected css below?

Currently it's something like:
```less
.wrapper {
    @-: ~'.prefix';
    @{-}-a @{-}-b {
        color: #333;
    }
}
```
