### ISSUE TITLE
[] lookup does not handle property merging

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#3369]
Minimal example:
```less
@list: {
    x+: 1;
    x+: 2;
}

div {
    result: @list[x]; // -> `2`, but expected `1, 2`
}
```

**Comment by matthew-dean** [comment]
Hmm, there's nothing explicit about it supporting this variant, but you're probably right it should be supported because of:
```less
.box {
  a+: 1;
  a+: 2;
  b: $a;
}
```
Outputs:
```css
.box {
  a: 1, 2;
  b: 1, 2;
}
```

**Comment by Hallo89** [comment]
This would be really useful for helper functions that work with lists, for example:

```less
.shift-list(@list, @offset, @it: 0) {
  & when (@it < length(@list)) {
    return+: extract(@list, mod(@it + @offset - 1, length(@list)) + 1);
    .shift-list(@list, @offset, @it + 1);
  }
}

body {
  @colors: red, orange, yellow, green, blue;
  @shifted-colors: .shift-list(@colors, 2)[return];
  background: linear-gradient(to right, @shifted-colors);
}
```
Outputs:
```less
body {
  background: linear-gradient(to right, yellow, green, blue, red, orange);
}
```

Which then could, for example, be combined with iterations over multiple elements, giving each element a different list offset.
