### ISSUE TITLE
`if` function shouldn't evaluate its not returned arg

### ISSUE THREAD

**Issue by Horcrux7** [less/less.js#3371]
The sample:

```
@some: foo;

div {
    margin: if((2 > 1), 0, 3px);
    color:  if((iscolor(@some)), darken(@some, 10%), black);
}
```
produce with version 3.9.0 the follow error:

```
RuntimeError: error evaluating function `darken`: color.toHSL is not a function in sample.less on line 5, column 34:
4     margin: if((2 > 1), 0, 3px);
5     color:  if((iscolor(@some)), darken(@some, 10%), black);
6 }
```
it look like that the THEN part is evaluate if the ELSE part should be used.

**Comment by seven-phases-max** [comment]
Did it work before? (Now when you mentioned this I have some doubts... Even if it was me putting that example there. The problem could be not `if` choosing the wrong value, but the arguments themselves [evaluated *before* entering the func](https://github.com/less/less.js/blob/master/lib/less/tree/call.js#L28)).

**Comment by seven-phases-max** [comment]
Did it work before? (Now when you mentioned this I have some doubts... Even if it was me putting that example there. The problem is most likely not `if` choosing the wrong value, but the arguments themselves [evaluated *before* entering the func](https://github.com/less/less.js/blob/master/lib/less/tree/call.js#L28)).

**Comment by Horcrux7** [comment]
I does not know if this has work before. I expect that the person which have write the documentation has it test. In general it is easier to run the code and copy the result as to write the expected result manually.

But if you think this can not work and it is a problem in the documentation then forward this to the documentation team.

I have use this sample only as test code for [JLessC](https://github.com/i-net-software/jlessc) which can evaluate it without an error.

**Comment by seven-phases-max** [comment]
[i]I have use this sample only as test code for JLessC which can evaluate it without an error.[/i]

Just out of curiosity, what is `JLessC` result for:
```less
x {
    a:  if(true, darken(whatever, 10%), 123);
    @x: whatever;
    b:  if(true, darken(@x, 10%), 123);
}
```
?

**Comment by seven-phases-max** [comment]
*I have use this sample only as test code for JLessC which can evaluate it without an error.*

Just out of curiosity, what is `JLessC` result for:
```less
x {
    a:  if(true, darken(whatever, 10%), 123);
    @x: whatever;
    b:  if(true, darken(@x, 10%), 123);
}
```
?

**Comment by seven-phases-max** [comment]
*I have use this sample only as test code for JLessC which can evaluate it without an error.*

Just out of curiosity, what is `JLessC` result for:
```less
x {
    a:  if(true, darken(red, 10%), 123);
    @x: red;
    b:  if(true, darken(@x, 10%), 123);
}
```
?

**Comment by seven-phases-max** [comment]
*I have use this sample only as test code for `JLessC` which can evaluate it without an error.*

Just out of curiosity, what is `JLessC` result for:
```less
x {
    a:  if(true, darken(red, 10%), 123);
    @x: red;
    b:  if(true, darken(@x, 10%), 123);
    @y: darken(@x, 10%);
    c:  if(true, @y, 123);
}
```
?
