### ISSUE TITLE
Error when using css variables without semi.

### ISSUE THREAD

**Issue by honkinglin** [less/less.js#3373]
Hey,I found it will parse error when I import a css like this:
`import './test.css'`

```css
// test.css
.test {
    --animate-margin-top: -30px;
    --animate-transform-vertical: top
}
```

the error detail is:

```
ERROR in ./src/test.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
    --animate-transform-vertical: top
}

Unrecognised input. Possibly missing opening '{'
......
```

I know it's not a good idea to leave CSS without a semicolon at the end，but  it is normal in the less@2.x version，so it kind of confused me.
