### ISSUE TITLE
If statement with color function fails with `inherit` value

### ISSUE THREAD

**Issue by VovanR** [less/less.js#3378]
Example: https://codepen.io/VovanR/pen/qvJEeW?editors=1100
```less
._btn(@color) {
  color: if((iscolor(@color)), darken(@color, 10%), @color);
  background-color: if((iscolor(@color)), green, pink);
}

.btn1 {
  ._btn(yellow);
}

.btn2 {
  ._btn(inherit);
}

body {
  color: lime;
}
```

I try to use `iskeyword` but it fails too
```less
._btn(@color) {
  color: if((iskeyword(@color)), @color, darken(@color, 10%));
  background-color: if((iskeyword(@color)), pink, green);
}
```

But without color function in If statement it works fine. Try to comment `color` rule line
