### ISSUE TITLE
Duplicate import file with absolute and relative path

### ISSUE THREAD

**Issue by gkraser** [less/less.js#3381]
Duplicate import file with absolute and relative path.

Workdir: **W:\p\bug-place\less-dup-import**
with files:

**main.less**
```less
@import "a";
@import "W:\p\bug-place\less-dup-import\a.less";
.bbb{color:red}
```
**a.less**
```less
.aaa{color:blue}
```

output: lessc main.less
```css
.aaa {
  color: blue;
}
.aaa {
  color: blue;
}
.bbb {
  color: red;
}
```

less version: 3.9.0
node version: v10.13.0
OS Windows 7
