### ISSUE TITLE
Variable interpolation don't work with New Feature MAPS

### ISSUE THREAD

**Issue by bhuvsac** [less/less.js#3389]
![Screenshot (6)](https://user-images.githubusercontent.com/3776368/55954416-454ec100-5c7c-11e9-86fb-f55f4940f8f6.png)

**Look at the screen shot,It's printing map property as same as property name not value..**

> this is wired.....

**Comment by seven-phases-max** [comment]
Please do not use screenshots for issue/bug reports - they are too tedious to work with.

---

It should not by design requests. Interpolation by design works only with "pure & clean" variables and does not with *any kind of statements* (e.g. function calls, arithmetic ops, whatever else ops incl. `[]` etc.). In other words, this is basically what the "interpolation" feature is: "put variable values (not statement/expression values!) into a string". 

You need to set your complex statement to a temporary variable and then use it within the interpolation.

There were obviously requests to implement what you expect, but considering the special purpose of the interpolation and even more special purpose of quoted strings, it barely worths the burden. If you have many `url`s like above - just write a wrapper function, for example like this:
```less
// function:

.my-img(@path, @file) {
    return: url('@{path}@{file}');
}

// usage:

.main-bg-container {
    background-image: .my-img(@base-img-path, @image-list[main-bg])[];
}
```

and voilà.

Same way you optionally also would want to hide any repeatable code in the function too, for example):
```less
// function:

.my-img(@image) {
    @file: @image-list[$@image];
    return: url('@{base-img-path}@{file}');
}

// usage:

.main-bg-container {
    background-image: .my-img(main-bg)[];
}
```

**Comment by matthew-dean** [comment]
@bhuvsac Long and short, it has nothing to do with maps, it has to do with the fact that `@{var[lookup]}` is not a valid reference. And since strings only allow `@{var}`, you can't put the map in it directly.

If you didn't follow what @seven-phases-max said, this was the most important part:

> You need to set your complex statement to a temporary variable and then use it within the interpolation

An even simpler example.

```less
@map: {
  main-bg: 'img1.jpg';
}

.main-bg-container {
  @bg: @map[main-bg];
  background-image: url('@{bg}');
}
```
This will output:
```less
.main-bg-container {
  background-image: url('img1.jpg');
}
```
