### ISSUE TITLE
variabilizing the name of a variable that has for value a list

### ISSUE THREAD

**Issue by Phoenixton** [less/less.js#3390]
Hey there,

I've got what might be a question a tad too specific, but maybe someone has external input. 

## The context

I've got a list defined in a file that only contains my LESS variables, so: 

`@header__colors: green, red, blue, yellow;`
`@footer__colors: black, white, pink, yellow;`

In my CSS file, I'm looping on "header" and "footer" like so: 
 
    .createContextStyle(@context){
       .@{context} {
           //code goes here
       }
    }

    .createContextStyle(~'header');
    .createContextStyle(~'footer');

Now in this function, I want to iterate for one particular selector on the elements of the lists. The idea is to say that I want to loop on `~"@{@{context}__colors}"`, the first time with context=header, the second time for context=footer. 

## Problem 

I've followed the code I found [here](https://stackoverflow.com/a/21441220) (the first of the three solutions provided).  But this does **not** work: 

    @colors: `~"@{@{context}__colors}"`;

    .example_module {
        .generateColors(@i: length(@colors)) when (@i > 0) {
            @name: extract(@colors, @i);
            &.@{name} {
                  background-color: ~"@{@{context}--@{name}}"; // I have declared in my code a @header--green: green, suffice to say that the corresponding variables exist, this is a simplified example 
             }
            .generateColors((@i - 1));
        } .generateColors;
    }

## Expected Result

I would like for it to loop on header, fetch @header__colors, loop on the elements of that list, and then go through the same process with footer. 

## Actual Result

What it actually does is consider that @colors is "green, red, blue, yellow"; for header, as in a **single** element (length == 1, I tested it) instead of a list of all those elements. 

**Is that expected behavior** ?

## Good to note 

It *does* work when you specifically declare `@colors: @header__colors;` but it defeats the idea of looping on the context in the first place. 

Does anyone have an idea of what this is caused by? Thanks a lot!

**Comment by matthew-dean** [comment]
@Phoenixton 

This is a question better asked at Stack Overflow, but do you mean like this?

```less
@header__colors: green, red, blue, yellow;
@footer__colors: black, white, pink, yellow;

.example_module {
  each(@header__colors, {
    &.@{value} {
      background-color: @value;
    }
  });
}
```
Generates:
```less
.example_module.green {
  background-color: green;
}
.example_module.red {
  background-color: red;
}
.example_module.blue {
  background-color: blue;
}
.example_module.yellow {
  background-color: yellow;
}
```
