### ISSUE TITLE
Getting [object object], if i try to extend a function from another function..

### ISSUE THREAD

**Issue by shivam250** [less/less.js#3392]
I always use official less-preview for testing purpose.. 
I want to generate dynamic image urls by overriding some properties of function...

look at the example

**This is the less code..**

`@base: "component/img";
.gen-url(@file) {
  return: url('@{base}@{file}');
}
#library() {
    primary: url("img/abc.png");
    secondary: url("img/xyz.png");
}
.button {
  background: #library[primary];
  background: #library[secondary];
}
#library() {
  primary: .gen-url("blue.jpg");
}`

**Output**

`.button {
  background: [object Object];
  background: url("img/xyz.png");
}`

**Comment by kevinramharak** [comment]
Formatted for readability:
```less
@base: "component/img";

.gen-url(@file) {
  return: url('@{base}@{file}');
}

#library() {
  primary: url("img/abc.png");
  secondary: url("img/xyz.png");
}

.button {
  background: #library[primary];
  background: #library[secondary];
}

#library() {
  primary: .gen-url("blue.jpg");
}
```

This happens because calling the mixin returns a anonymous ruleset (or whatever it is called). To use a mixin as a function you have to extract the property from the ruleset like `.mixin-as-function()[property]` or the shorthand `.mixin-as-function[]` which will evaluate to the last declared value of the returned ruleset.

so your less code should be altered to:
```
#library() {
  primary: .gen-url("blue.jpg")[return];
  // or
  primary: .gen-url("blue.jpg")[];
}
```
Please see http://lesscss.org/features/#mixins-feature-mixins-as-functions-feature for the official docs.
