### ISSUE TITLE
Nested negated media queries are merged with normal ones.

### ISSUE THREAD

**Issue by mxjp** [less/less.js#3395]
# The problem:
When compiling nested media queries where one is negated, less merges them which produces css that is not working the same way as it should be working.

The following less code:
```less
@media (min-width: 600px) {
  @media not all and (min-width: 900px) {
    body {
      color: red;
    }
  }
}
```
compiles to an invalid css media query:
```css
@media (min-width: 600px) and not all and (min-width: 900px) {
  body {
    color: red;
  }
}
```

Instead less should detect negated media queries and prevent merging as they can not be merged per spec.
I created a small repository containing the less code, simple setup for compilation and two example documents, one with the broken media query and one with the working css:
https://github.com/mxjp/less-bug-nested-media-queries

### Why not `(min-width: 600px) and (max-width: 899px) {...}` ?
If we have two media queries:
```css
@media (min-width: 600px) and (max-width 899px) {
    body {
        color: red;
    }
}
/* and */
@media (min-width: 900px) {
    body {
        color: blue;
    }
}
```
On some devices, we might hit a point, where the device width is between 899px and 900px, but we would expect, that the first of these media queries applies.
