### ISSUE TITLE
Less fails to parse values from web platform tests:

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#3396]
According to: https://github.com/web-platform-tests/wpt/blob/master/css/css-variables/test_variable_legal_values.html

...Less should be able to parse a block like this for custom properties:

```less
legal css variable values {
  --percentage: 25%;
  --number: 37;
  --length: 12em;
  --time: 75ms;
  --function: foo();
  --nested-function: foo(bar());
  --parentheses: ( );
  --braces: { };
  --brackets: [ ];
  --at-keyword-unknown: @foobar;
  --at-keyword-known: @media;
  --at-keyword-unknown-block: @foobar {};
  --at-keyword-known-block: @media {};
  --cdo-at-top-level: <!--;
  --cdc-at-top-level: -->;
  --semicolon-not-top-level: (;);
  --cdo-not-top-level: (<!--);
  --cdc-not-top-level: (-->);
}
```

However, as expected, Less fails with the at-keywords in custom properties. Since custom property parsing is already permissive with logic for failing over (accepting almost anything until a closing outer semi-colon), it makes sense to allow "variable-like" values in custom properties to pass-through.

**Comment by TheJaredWilcurt** [comment]
Fails on all of these:
```css
--at-keyword-unknown: @foobar;
--at-keyword-known: @media;
--at-keyword-unknown-block: @foobar {};
--at-keyword-known-block: @media {};
```
according to http://lesscss.org/less-preview

**Comment by matthew-dean** [comment]
This also fails but should succeed, according to custom property documentation:
```less
.box {
  --width: ;
}
```
Even though this succeeds:
```
.box {
  width: ;
}
```
