### ISSUE TITLE
Property lookup on rulesets does not work as mixin argument

### ISSUE THREAD

**Issue by ahultgren** [less/less.js#3405]
Example:

```less
#lookup {
  @prop: test;
}

.mix (@var) {
  width: @var;
}

.bar {
  .mix(#lookup[@prop]);
}
```

Expected output:

```less
.bar {
  width: test;
}
```

Actual output:

```
unexpected token 
```

However looking up in a detached ruleset works:

```less
@lookup: {
  @prop: test;
}

.mix (@var) {
  width: @var;
}

.bar {
  .mix(@lookup[@prop]);
}
```

And looking up a rule works as well:

```less
#lookup () {
  prop: test;
}

.mix (@var) {
  width: @var;
}

.bar {
  .mix(#lookup[prop]);
}
```

Also, simply looking up the property (not using it as an argument) works as expected:

```less
.bar {
  width: #lookup[@prop];
}
```

This leads me to believe there's a bug in the mixin argument parser.
