### ISSUE TITLE
Can't apply mixin as varible from a namespace

### ISSUE THREAD

**Issue by ahultgren** [less/less.js#3406]
This might be related to https://github.com/less/less.js/issues/3405:

```less
.mix (@n) {
  value: @n;
}

@var: .mix(var);

#lookup {
  @var: .mix(lookup);
  @bar: bar;
}

.example {
  @var();
  value2: #lookup[@bar];

  // This is what I'm trying to do, since the above works:
  #lookup[@var]();
}
```

Expected:

```css
.example {
  value: lookup;
  value2: bar;
}
```

Actual: unexpected token.

In this case I can't find a workaround using detached rulesets, but since `@var()` works I expect the nested syntax `#lookup[@var]()` to work as well.
