### ISSUE TITLE
Guarded namespace unavailable when calling mixin with ruleset

### ISSUE THREAD

**Issue by ahultgren** [less/less.js#3407]
I keep running into issues today it seems. 

Example:

```less
#media {
  #desktop (@ruleset) {
    @media (min-width: 700px) {
      @ruleset();
    }
  }

  #mobile (@ruleset) {
    @media (max-width: 699px) {
      @ruleset();
    }
  }
}


@switch: demo;

.example {
  #lookup when (@switch = demo) {
    @not-found: 1;
  }

  @found: 2;
  
  #lookup2 {
    @also-found: 3;
  }

  
  #media#desktop({
    // Comment the next line and it will all compile
    error: #lookup[@not-found];
    success1: @found;
    success2: #lookup2[@also-found];
  });
}
```

Expected output:

```css
@media (min-width: 700px) {
  .example {
    error: 1;
    success1: 2;
    success2: 3;
  }
}
```

Actual output: `variable @not-found not found `.

I managed to narrow it down to usage of the guard. Remove it and it works. Put the namespace within the ruleset and it works.

**Comment by matthew-dean** [comment]
Again, this is an unsupported feature and there's nothing in the docs that would suggest this would work. If you're using a ruleset as data (as a map), then you can't use guards and expect to access it, since there's no lookup format for accessing that data.

Closing as not supported.

**Comment by matthew-dean** [comment]
You can however use conditional logic in the value itself, as in:
```less
@switch: demo;
#lookup {
  @not-found: if(@switch = demo, 1, 0);
}
.example {
  @media (min-width: 700px) {
    not-error: #lookup[@not-found];
  }
}
```
