### ISSUE TITLE
Community question about how :extend works / should work

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#3418]
I'm looking at simplifying the `:extend` algorithm, and I came across something in the tests, simplified as.

```less
.bb {
  background: red;
  .bb {
    color: black;
  }
}
.ff:extend(.bb all) {}
```
Now, in short, after rewriting the algorithm, I ended up with a mis-matched output. The current expected output for the second block is:
```less
.bb .bb,
.ff .ff {
  color: black;
}
```
But wait a minute.... if I'm replacing all `.bb` instances with `.ff`, then shouldn't this be the expected output?
```less
.bb .bb,
.bb .ff,
.ff .bb,
.ff .ff {
  color: black;
}
```
Shouldn't extending all `.bb` instances create every variant replacement? Extend is saying, "whereever `.bb` can appear, `.ff` can appear as well". The second version seems more "correct".

I haven't looked yet to see what we have in the way of opened issues around this, but I realized that such behavior could be subjective. But I wonder what the "least surprise" is, behaviorally, around `:extend`, and if how much existing behavior should be preserved.

**Comment by calvinjuarez** [comment]
I think you’re right.  It aligns with what we expect from `&` as well.

**Comment by matthew-dean** [comment]
@calvinjuarez 

If we do that behavior, then this example in the tests becomes a bit crazy:
```less
.replace.replace,
.c.replace + .replace {
  .replace,
  .c {
    prop: copy-paste-replace;
  }
}
.rep_ace:extend(.replace all) {}
```
According to my math, the output should be 5^5 combinations of selectors (right?), so that would be 3,125 selectors.  🤔 

Less's current output is:
```less
.replace.replace .replace,
.c.replace + .replace .replace,
.replace.replace .c,
.c.replace + .replace .c,
.rep_ace.rep_ace .rep_ace,
.c.rep_ace + .rep_ace .rep_ace,
.rep_ace.rep_ace .c,
.c.rep_ace + .rep_ace .c {
  prop: copy-paste-replace;
}
```
Interestingly, Sass's current output is:
```less
.replace.replace .replace, .replace.replace .rep_ace, .c.replace + .replace .replace, .rep_ace.c + .replace .replace, .rep_ace.c + .rep_ace .replace, .rep_ace.c + .rep_ace .rep_ace, .rep_ace.c + .replace .rep_ace, .c.replace + .rep_ace .replace, .c.replace + .rep_ace .rep_ace, .c.replace + .replace .rep_ace, .replace.replace .c, .c.replace + .replace .c, .rep_ace.c + .replace .c, .rep_ace.c + .rep_ace .c, .c.replace + .rep_ace .c {
	 prop: copy-paste-replace;
}
```
Sass's makes no sense in this case, unless it's just bailing when the selectors produced get too high. I guess Less's extend algorithm is essentially a "global" match within the entire selector list of a ruleset.

For the `.bb .bb` example, Sass's extend output is as expected:
```less
.bb, .ff {
	 background: red;
}
 .bb .bb, .ff .bb, .ff .ff, .bb .ff {
	 color: black;
}
```

Update: what seems to be working well is a combination of the two approaches. Basically allowing a combination of two selectors, but anything beyond that is a traditional Less "global" replace.
