### ISSUE TITLE
Dots in classes not working

### ISSUE THREAD

**Issue by IAKNorg** [less/less.js#3425]
Using dots in css is quite easy and it's working fine, while in less it's not.

html

`<span class="class.name">span</span>`

css

`span.class\.name { /* styling */ }`

**Comment by kevinramharak** [comment]
Can you give some more info? What is the input, output and expected output? Putting this code in trough `less@3.10.3` gives the following output:
```css
span.class\.name {
  /* styling */
}
```
That seems correct to me?

**Comment by DVAmora** [comment]
When I try nesting classes it's not working for me.

`.box\.innerbox {
   margin: 10px;
  {
  \.shape
}
}`

**Comment by kevinramharak** [comment]
Well the snippet `.box\.innerbox { margin: 10px; { \.shape } }` is not valid less code. I think you meant `.box\.innerbox { margin: 10px; .\.shape { /* more code here */ } }`. Do not forget that a class selector has to start with a dot. `\.shape` targets the element `<.shape/>` (Tough i doubt that is valid HTML). the snippet `.\.shape` targets the class selector `<element class=".shape" />`.

Try it out here http://lesscss.org/less-preview/. This runs the `3.10.3` version and gives immediate feedback to see if your code is working.

Try to be a bit more verbose if this does not solve your case. Show the input, expected output and actual output. Also post the less version you are using (`lessc -v` should show you). Using your snippets as an example:

*input*:
```less
.box\.innerbox {
  margin: 10px;
  // missing dot at the start on purpose
  \.shape {
     font-size: 16px;
  }
}
```

*expected output*:
```css
.box\.innerbox {
  margin: 10px;
}
.box\.innerbox .\.shape {
  font-size: 16px;
}
```

*actual output*:
```
.box\.innerbox {
  margin: 10px;
}
.box\.innerbox \.shape {
  font-size: 16px;
}
```
