### ISSUE TITLE
Mixin with pseudo selector

### ISSUE THREAD

**Issue by hpohlmeyer** [less/less.js#3427]
This issue is pretty similar to #1838, but the solution does not help me with this problem. I guess less can not deal with pseudo-selectors and pseudo-elements. If that is the case, consider this a feature request. :)

__The case__

I want to inherit some of the ant-design styles for my own styles. I usually do this via mixins, which works pretty well with the exception of pseudo selectors:

```less
// ant-design file, which I am not able to modify

.ant-tag:hover {
  opacity: 0.85;
}
```

```less
// my css file

@import (less) '/node_modules/antd/lib/tag/style/index.css';

.my-tag:hover {
  .ant-tag:hover();
}
```

__Expected result__  
Generate the following output:
```less
.my-tag:hover {
  opacity: 0.85;
}
```

__Actual result__  
Throws an error.
