### ISSUE TITLE
Rendering maps values omits following '!important' statement

### ISSUE THREAD

**Issue by splosch** [less/less.js#3430]
An `!important` statement following maps value retrieval is rendering the values without `!important`

Reproducible on http://lesscss.org/less-preview/

**LESS:**
```less
@colors : {
  primary: blue;
  secondary: green;
}

.foo {
  color: @colors[primary] !important;
}
```

**Current Result:**
```css
.foo {
  color: blue;
}
```

**Expected Result:**
```css
.foo {
  color: blue !important;
}
```

**Workaround**:
```less
.bar {
  color: @colors[primary] ~"!important";
}
```
