### ISSUE TITLE
store variables in less.vars, please ! 

### ISSUE THREAD

**Issue by jonasfrey** [less/less.js#3435]
i use less client side, 
all i want is 

`document.querySelector("body").style.backgroundColor = less.vars["background-color"];`

this is would be so easy

**Comment by matthew-dean** [comment]
Accessing vars is not out of the question, but your use-case is strange. Why isn't your stylesheet simply styling the body?

**Comment by seven-phases-max** [comment]
Juts in case adding a few tricky snippets to test this feature when (and if) developed:

#1:
```less
div {
    color: @color;
}

.mixin() {
    @color: red;        
} .mixin;
```

#2:
```less
@color: darken(@c, 42%);

div.a {
    @c: blue;
    color: @color;
}

div.b {
    @c: green;
    color: @color;
}

.-{@c:red}.-;
```less

#3:
```less
@color: ~'?!';

div {
    color: @color;
}

.foo {
    .bar(@c) {
        return: spin(@c, 180);
    }
}

@color: .foo.bar(blue)[];
```

**Comment by seven-phases-max** [comment]
Juts in case adding a few tricky snippets to test this feature when (and if) developed:

#1:
```less
div {
    color: @color;
}

.mixin() {
    @color: red;        
} .mixin;
```

#2:
```less
@color: darken(@c, 42%);

div.a {
    @c: blue;
    color: @color;
}

div.b {
    @c: green;
    color: @color;
}

.-{@c:red}.-;
```

#3:
```less
@color: ~'?!';

div {
    color: @color;
}

.foo {
    .bar(@c) {
        return: spin(@c, 180);
    }
}

@color: .foo.bar(blue)[];
```

**Comment by seven-phases-max** [comment]
Juts in case adding a few tricky snippets to test this feature when (and if) developed:

`#1`:
```less
div {
    color: @color;
}

.mixin() {
    @color: red;        
} .mixin;
```

`#2`:
```less
@color: darken(@c, 42%);

div.a {
    @c: blue;
    color: @color;
}

div.b {
    @c: green;
    color: @color;
}

.-{@c:red}.-;
```

`#3`:
```less
@color: ~'?!';

div {
    color: @color;
}

.foo {
    .bar(@c) {
        return: spin(@c, 180);
    }
}

@color: .foo.bar(blue)[];
```

**Comment by seven-phases-max** [comment]
Juts in case adding a few tricky snippets to test this feature when (and if) developed:

`#1`:
```less
div {
    color: @color;
}

.mixin() {
    @color: red;        
} .mixin;
```

`#2`:
```less
@color: darken(@c, 42%);

div.a {
    @c: blue;
    color: @color;
}

div.b {
    @c: green;
    color: @color;
}

.-{@c:red}.-;
```

`#3`:
```less
@color: .foo.bar(blue)[];

div {
    color: @color;
}

.foo {
    .bar(@c) {
        return: spin(@c, 180);
    }
}
```
