### ISSUE TITLE
extend(&)

### ISSUE THREAD

**Issue by nexcode** [less/less.js#3450]
```less
.header {
    &__links-item {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 28px;

        &--icon:extend(&) {
            width: 28px;
        }
    }
}
```
output:
```css
.header__links-item {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 28px;
}
.header__links-item--icon {
  width: 28px;
}
```
I expected this:
```css
.header__links-item--icon,
.header__links-item {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 28px;
}
.header__links-item--icon {
  width: 28px;
}
```
Is it possible to achieve such a result somehow?

**Comment by nexcode** [comment]
Is it possible to achieve such a result somehow?

**Comment by seven-phases-max** [comment]
No. `Extend` does not support anything but plain CSS selectors.
The best you can do now is something like:
```less
.header {
    &__links-item {
        &, &--icon {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 28px;
        }

        &--icon {
            width: 28px;
        }
    }
}
```
