### ISSUE TITLE
Variable properties $@ not working within if()

### ISSUE THREAD

**Issue by sabl0r** [less/less.js#3451]
Variable properties are working in general but not if you use them within if() (maybe other functions as well).

The code below gives me this for the "nok" mixin:

> property "100" not found 

I know that this feature is not yet documented (https://github.com/less/less-docs/issues/500), but is this usecase supposed to work or not?

```less
@devices: {
	mobile: 420;
	tablet: 800;
	desktop: 1024;
	widescreen: 1280;
	fullhd: 1440;
}


.nok(@d) {
	@w: if(iskeyword(@d), @devices[$@d], @d);
	width: @w;
}

.ok(@d) {
	@w: if(iskeyword(@d), @d, @d);
	width: @w;
}

.ok {
	.ok(tablet);
	.ok(100px);
}

.nok {
	.nok(tablet);
	.nok(100px);
}
```
