### ISSUE TITLE
How to use contrast() with ratio instead of threshold?

### ISSUE THREAD

**Issue by phun-ky** [less/less.js#3459]
The contrast function is lacking features to match the compass/sass "implementation" and the stylus implementation. I am in the need of doing what Stylus does, for LESS:

```stylus
getCorrectContrastColor($color)
  if(contrast($color, $color-lightestBeige-secondary).ratio > $color-text-wcag-ratio){
    color $color-lightestBeige-secondary
  } else if(contrast($color, $color-brown-secondary).ratio > $color-text-wcag-ratio){
    color $color-brown-secondary
  } else {
    color $color-lightBrown-secondary
  }
```

for SCSS, I had to rely on an external library: 

```scss
@import 'sass-color-helpers/stylesheets/_color-helpers.scss';

@mixin getCorrectContrastColor($backgroundColor) {
  $contrast1: ch-color-contrast($backgroundColor, $color-lightestBeige-secondary);
  $contrast2: ch-color-contrast($backgroundColor, $color-brown-secondary);

  @if $contrast1 > $color-text-wcag-ratio {
    color: $color-lightestBeige-secondary;
  } @else if $contrast2 > $color-text-wcag-ratio {
    color: $color-brown-secondary;
  } @else {
    color: $color-lightBrown-secondary;
  }
}
```

How can I achieve this to produce the same results as in SCSS and LESS? My google fu produced nothing that works, and the closest I've come is with this:

```less
.contrast-ratio(@color1, @color2){
  @luma1: luma(@color1);
  @luma2: luma(@color2);
  
  .c1(@luma1, @luma2) when (@luma1 < @luma2){
    @a:  1 /(unit(@luma1) / unit(@luma2));  
  }
  
  .c1(@luma1, @luma2) when (@luma1 >= @luma2){
    @a: (unit(@luma1) / unit(@luma2));
  }
  
  @result: .c1(@luma1, @luma2)[@a];
}

.getCorrectContrastColor(@color){
  color: @color-lightBrown-secondary;
  & when (.contrast-ratio(@color, @color-brown-secondary)[@result] > @color-text-wcag-ratio){
    color: @color-brown-secondary;
  }
  
  & when (.contrast-ratio(@color, @color-lightestBeige-secondary)[@result] > @color-text-wcag-ratio){
    color: @color-lightestBeige-secondary;
  }
}
```

But this produces incorrect results (and too many `color:` properties..

**Comment by phun-ky** [comment]
Nevermind, made my own mixins to fix the missing LESS feature. Hollar at me if you want me to put it up on npm :)

```less
.ch-color-luminance-raw(@rgb) {
  @result: if((@rgb < 0.03928), @rgb / 12.92, pow((@rgb + 0.055) / 1.055, 2.4, 16));
}

.ch-color-luminance(@color) {
  @red: red(@color) / 255;
  @green: green(@color) / 255;
  @blue: blue(@color) / 255;

  @rgba-lum-raw-red: .ch-color-luminance-raw(@red) [ @result];
  @rgba-lum-raw-green: .ch-color-luminance-raw(@green) [ @result];
  @rgba-lum-raw-blue: .ch-color-luminance-raw(@blue) [ @result];

  @result: 0.2126 * @rgba-lum-raw-red + 0.7152 * @rgba-lum-raw-green + 0.0722 * @rgba-lum-raw-blue;
}

.ch-color-contrast(@color1, @color2) {
  // Adapted from: https://github.com/LeaVerou/contrast-ratio/blob/gh-pages/color.js
  // Formula: http://www.w3.org/TR/2008/REC-WCAG20-20081211/#contrast-ratiodef
  @luminance1: .ch-color-luminance(@color1)[@result] + 0.05;
  @luminance2: .ch-color-luminance(@color2)[@result] + 0.05;
  @ratio1: @luminance1 / @luminance2;
  @ratio: if((@luminance2 > @luminance1), 1 / @ratio1, @ratio1);

  @result: round(@ratio * 10) / 10;
}

.getCorrectContrastColor(@backgroundColor) {
  @contrast1: .ch-color-contrast(@backgroundColor, @color-lightestBeige-secondary)[@result];
  @contrast2: .ch-color-contrast(@backgroundColor, @color-brown-secondary)[@result];

  .contrastColor() when (@contrast1 > @color-text-wcag-ratio){
    color: @color-lightestBeige-secondary;
  }

  .contrastColor() when (@contrast2 > @color-text-wcag-ratio){
    color: @color-brown-secondary;
  }

  .contrastColor() when (default()){
    color: @color-lightBrown-secondary;
  }

  .contrastColor();

}
```

**Comment by Nettsentrisk** [comment]
@phun-ky did you ever make a stand-alone Less mixin for this based on what you posted here? Trying to paper over the problems with the contrast function in a project that uses Less...

**Comment by phun-ky** [comment]
@Nettsentrisk If I understand you correctly, did I make an npm package for this? No, I haven't. Or did you mean something else?

**Comment by Nettsentrisk** [comment]
@phun-ky Either npm or your own private version of the code you ended up using.

I refactored a bit and came up with this (working with Less v. 3.13.1):

```less
.color-luminance-raw(@rgb) {
    @return: if((@rgb <=0.03928), (@rgb / 12.92), pow(((@rgb + 0.055) / 1.055), 2.4));
}

.color-luminance(@color) {
    @red: (red(@color) / 255);
    @green: (green(@color) / 255);
    @blue: (blue(@color) / 255);

    @rgba-lum-raw-red: .color-luminance-raw(@red)[];
    @rgba-lum-raw-green: .color-luminance-raw(@green)[];
    @rgba-lum-raw-blue: .color-luminance-raw(@blue)[];

    @return: ((0.2126 * @rgba-lum-raw-red) + (0.7152 * @rgba-lum-raw-green) + (0.0722 * @rgba-lum-raw-blue));
}

.color-contrast(@color, @contrasting-color) {
    // Formula: http://www.w3.org/TR/2008/REC-WCAG20-20081211/#contrast-ratiodef
    @luminance1: .color-luminance(@color)[];
    @luminance2: .color-luminance(@contrasting-color)[];
    @ratio: (max(@luminance1, @luminance2) + 0.05) / (min(@luminance1, @luminance2) + 0.05);

    @return: (round(@ratio * 100) / 100);
}

.contrast-color(@background-color, @preferred-color: @color-text, @alternate-color: @color-text-alternate) {
    @color-text-wcag-ratio: 4.5;
    @return: if((.color-contrast(@background-color, @preferred-color)[] >=@color-text-wcag-ratio), @preferred-color, if((.color-contrast(@background-color, @alternate-color)[] >=@color-text-wcag-ratio), @alternate-color, if((.color-contrast(@background-color, @color-text)[] >=@color-text-wcag-ratio), @color-text, if((.color-contrast(@background-color, @color-text-alternate)[] >=@color-text-wcag-ratio), @color-text-alternate, if((.color-contrast(@background-color, #fff)[] >=@color-text-wcag-ratio), #fff, #000)))));
}
```
The last function block is based on being able to provide 1 or 2 color alternatives, falling back to a defined text color or a defined alternate text color. If neither of these pass the WCAG contrast test, it falls back to testing white and then selects black by default if none of the prior ones pass, working on the assumption that black will pass when white does not (which might not be correct, but you need to provide some sort of fallback color).

It could perhaps be rewritten to allow for using the Less feature of @rest and passing a list of colors to test in prioritized order, but this should suffice for most scenarios.

The resulting if chain was the most performant way of doing it that I found; using guards with when and running all the contrast tests for every single use of the function led to much worse performance.
