### ISSUE TITLE
using maps with !important keyword leading to wrong output

### ISSUE THREAD

**Issue by Topograph** [less/less.js#3464]
Hi,
i think the following behaviour might be wrong:
this less...

```less
@colors: {
    enabled: #00b4c6;
    selected: #4d4d4d;
    hovered: #dbdbdb;
}

.testClass {
  background-color: @colors[enabled];
    &.active {
       background-color: @colors[selected] !important;
       }
   &.hovered {
       background-color: @colors[hovered];
   }
}
```

...compiles to this css

```css
.testClass {
  background-color: #00b4c6;
}
.testClass.active {
  background-color: #4d4d4d;
}
.testClass.hovered {
  background-color: #dbdbdb;
}

```

notice how the "!important" keyword is omitted in the resulting css.
