### ISSUE TITLE
Functions added by @plugin inside #namespace cannot be referenced

### ISSUE THREAD

**Issue by rjgotten** [less/less.js#3500]
Functions that are added to a `#namespace` by a `@plugin` directive cannot be referenced by mixins residing in the namespace.

Given a simple plugin that adds a `lowercase` function and the following Less sample
```less
#namespaced {
  @plugin "./plugins/lowercase.js";

  .mixin(@value) {
    value : lowercase(@value);
  }
}

.test {
  #namespaced.mixin("FOO");
}
```

the actual output I'd get is:

```css
.test {
  value : lowercase("FOO");
}
```

whereas the expected output would be:

```css
.test {
  value : "foo";
}
```

----
**WORKAROUND**

Problem has two easy workarounds, both of which have issues of their own:
1. make the `@plugin` directive global -- but this leaks it to other stylesheets
2. scope the `@plugin` directive to the mixin -- but this is not practical for multiple mixins and not possible for functions used in `when` mixin guards.

The only bullet-proof workaround is using an unlocking-mixins pattern: That is:
1. nest all the actual mixin functionality of the namespace in _yet another_ mixin;
2. create facade duplicates of the original mixins and put those directly in the namespace; and finally
3. 'unlock' the nested mixins inside inside the facades and chain the call.

E.g.

```less
#namespaced {

  .mixin(@value) {
    #namespaced._();
    .mixin(@value);
  }

  ._() {
    @plugin "./plugins/lowercase.js";

    .mixin(@value) {
      value : lowercase(@value);
    }
}

.test {
  #namespaced.mixin("FOO");
}
```

Needless to say; this is a lot of undesired boilerplate.

**Comment by matthew-dean** [comment]
Can you do: 
```less
& {
  @plugin "./plugins/lowercase.js";
  #namespaced {
    .mixin(@value) {
      value : lowercase(@value);
    }
  }

  .test {
    #namespaced.mixin("FOO");
  }
}
```

Other than workarounds, I don't think this can be reasonably addressed without rewriting the evaluation order algorithm.
