### ISSUE TITLE
output imports is empty.

### ISSUE THREAD

**Issue by underfin** [less/less.js#3508]
```less
// less1.less
@import "./less2.less";
@import "./css.css";
.mixin {
  @import "./less3";
}
body {
  color: red;
}
```
``` js

var css = require("fs").readFileSync("./less1.less", "utf8")

require('less').render(
    css,
    {
      filename: './less1.less',

    },
    (err, output) => {
      console.log( output)
//  {  css: '@import "css.css";\nbody {\n  color: red;\n}\nbody {\n  color: red;\n}\n',imports: []}
    }
)
```
## Bug description
I get empty `imports` output when complier less file.
## Expect behavior
The `imports` should has import references.
