### ISSUE TITLE
How variables in comments

### ISSUE THREAD

**Issue by cipchk** [less/less.js#3510]
Let's say I have the following map and iterate over it with the each-function:

```less
@values: 9, 12, 24;
each(@values, {
  /**
   * Font size, same: @{value}
   */
  .font-size-@{value} {
    font-size: ~"@{value}px";
  }
});
```

Output:

```css
/**
   * Font size, same: @{value}
   */
.font-size-9 {
  font-size: 9px;
}
/**
   * Font size, same: @{value}
   */
.font-size-12 {
  font-size: 12px;
}
/**
   * Font size, same: @{value}
   */
.font-size-24 {
  font-size: 24px;
}
```

How to fill variables in comments, like this:

```css

/**
   * Font size, same: 9
   */
.font-size-9 {
  font-size: 9px;
}
/**
   * Font size, same: 12
   */
.font-size-12 {
  font-size: 12px;
}
/**
   * Font size, same: 24
   */
.font-size-24 {
  font-size: 24px;
}
```

I hope to get comments by parsing css (like `css-tree`) for ide intellisense.

**Comment by matthew-dean** [comment]
The appropriate place to ask this is Stack Overflow, but the quick answer is:
```less
@var: 9;
e("/**
   * Font size, same: @{var}
   */");
```
