### ISSUE TITLE
Comments misplaced

### ISSUE THREAD

**Issue by cipchk** [less/less.js#3511]
Less.js Version: 3.11.1

```less
/** a */
.modal {
  /** b */
  &-header {
    font-size: 12px;
  }
  /** c */
  &-title {
    font-size: 12px;
  }
```

Output:

```css
/** a */
.modal {
  font-size: 12px;
  /** b */
  /** c */
}
.modal-header {
  font-size: 12px;
}
.modal-title {
  font-size: 12px;
}
```

I think it should output:

```css
/** a */
.modal {
  font-size: 12px;
}
/** b */
.modal-header {
  font-size: 12px;
}
/** c */
.modal-title {
  font-size: 12px;
}
```
