### ISSUE TITLE
@gray would be generated as CSS gray

### ISSUE THREAD

**Issue by Huxpro** [less/less.js#3520]
```less
@gray: lighten(black, 50%);
a { color: @gray }
```

would codegen to

```css
a { color: #ccc } /* i.e. CSS gray */
```

change the variable name to `@gray-m` fix the problem and generate `#808080`
I believed this has been a while.
