### ISSUE TITLE
Line comments aren't stripped from @support selector(...)

### ISSUE THREAD

**Issue by thorn0** [less/less.js#3527]
Is this a bug or is this an expected behavior?

Demo: https://jsbin.com/hewizek/4/edit?html,js,console

**Input:**
```less
  @supports selector(
    :focus-visible // *"a"
  ) {
    a { 
      color: red;
    }
  }
```

**Output:**
same as input

**Expected:**
@supports selector(:focus-visible) {
  a {
    color: red;
  }
}
```
