### ISSUE TITLE
How to extract the attributes that only contain the current LESS variables

### ISSUE THREAD

**Issue by bowen0** [less/less.js#3536]
Hey, I'm using LESS to implement a skinning function recently. I want to extract the attributes that only contain the current less variable. Is there any preset API for LESS to implement this function?

// Original less code
```less
// style.less
@color: #fff;
@border-radius: 2px;
.btn-primary {
 color: @color;
 border: @border-radius solid @color;
 height: 20px;
 width: 40px
}
``` 

// Extract attributes
```less
// style.less
.btn-primary {
 color: @color;
 border: @border-radius solid @color;
}
```
