### ISSUE TITLE
How to combine LESS color functions and CSS Variables

### ISSUE THREAD

**Issue by tharangakuma** [less/less.js#3537]
In my project I have a CSS custom variables like this: 
```
:root {
  --primary-color: #e04c4c;
  --secondary-color: #2c2c5e;
  --text-color: #d67900; 
}

```
In my LESS files  I have used LESS color functions to get more colors base on its primary and secondary. This is how its look like: 

```
.component1 {
  background: darken(--primary-color, 10%);
}

.component2 {
  background: lighten(--secondary-color, 5%);
}
```

But when I compile this, it gives an error like this? 
// Undefined_methodError: error evaluating function `darken`:
// Object #<Object> has no method 'toHSL'

Can anybody tell me is there any possible workaround for this particular case? 

Thank you.

**Comment by matthew-dean** [comment]
This is a question for Stack Overflow, not Less issues, but briefly, Less runs at compile-time, not run-time (typically), and `--primary-color` is not a valid Less variable.

You can workaround it like this:

```less
@primary-color: #e04c4c;
@secondary-color: #2c2c5e;
@text-color: #d67900; 

:root {
  --primary-color: @primary-color;
  --secondary-color: @secondary-color;
  --text-color: @text-color; 
}

.component1 {
  background: darken(@primary-color, 10%);
}

.component2 {
  background: lighten(@secondary-color, 5%);
}
```
