### ISSUE TITLE
@import remote stylesheets does not work on 3.12.0

### ISSUE THREAD

**Issue by zaquest** [less/less.js#3541]
Seems like 3.12.0 broke imports for remote stylesheets. For example

```less
@import "https://raw.githubusercontent.com/less/less.js/master/packages/test-data/less/visitorPlugin/visitor.less";

.h1 { font-size: 1px; }
```

compiles on 3.11.3, but on 3.12.0 it throws

```
SyntaxError: The "url" argument must be of type string. Received an instance of Object in /.../test_less_remote_import.less on line 1, column 1:
1 @import "https://raw.githubusercontent.com/less/less.js/master/packages/test-data/less/visitorPlugin/visitor.less";
```

Is this a bug or was the support for remote imports dropped?
