### ISSUE TITLE
rootpath does nothing to absolute url() paths

### ISSUE THREAD

**Issue by gavinbarron** [less/less.js#3552]
Minimal Reproduction using less 3.12.0

fail.less:
```less
.fail {
    background-image: url('/images/absolute.png');
}
.works {
    background-image: url('images/relative.png');
}

```

run:
```bash
lessc -rp=https://mycdn/url/folder fail.less ./out.css
```

out.css
```css
.fail {
  background-image: url('/images/absolute.png');
}
.works {
  background-image: url('https://mycdn/url/folder/images/relative.png');
}
```

Why do I want this behavior? 
During development the images are served by the local web server in the /images directory. 
When publishing all static elements are served out of a folder on the CDN, the folder name is variable.
This is very similar to the issue reported in #2129 but that lacked the clear detail that the image url is absolute
