### ISSUE TITLE
[RFC] Two new functions - flatten() and value()

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#3553]
This is a proposal for two normalizing functions, respectively, `flatten()` and `value()`.

**Reasoning**
Less does some magic behind the scenes to convert CSS values to lists. This can lead to unexpected results:

```less
val1 {
  @set: a b c;
  sets: length(@set);
  first: extract(@set, 1);
}
val2 {
  @set: a b c, x y z;
  sets: length(@set);
  first: extract(@set, 1);
}
```
The output is:
```css
val1 {
  sets: 3;
  first: a;
}
val2 {
  sets: 2;
  first: a b c;
}
```

The intent of the author is that `@set` is a comma-separated tuple of letters. However, a single "value" is not straightforward to define.

**The `value([val])` function**

The `value()` function normalizes lists as a CSS (comma-separated) value. Example:
```less
val1 {
  @set: value(a b c);
  sets: length(@set);
  first: extract(@set, 1);
}
val2 {
  @set: value(a b c, x y z);
  sets: length(@set);
  first: extract(@set, 1);
}
```
The output would be:
```css
val1 {
  sets: 1;
  first: a b c;
}
val2 {
  sets: 2;
  first: a b c;
}
```
Another way to visualize it, is that a CSS value can always be normalized as a nested array i.e. `[['a', 'b', 'c']]` and `[['a', 'b', 'c'], ['x', 'y', 'z']]` 

**The `flatten([val])` function**

Flatten is just a logical inverse of `value()` - That is, instead of converting all values to two-dimensional arrays, it converts all values to one-dimensional arrays, regardless of commas. This can also prevent surprise depending on author intent.

Example:
```less
val1 {
  @set: flatten(a b c);
  items: length(@set);
  first: extract(@set, 1);
}
val2 {
  @set: flatten(a b c, x y z);
  items: length(@set);
  first: extract(@set, 1);
}
```

```css
val1 {
  items: 3;
  first: a;
}
val2 {
  items: 6;
  first: a;
}
```
In the above example, the first item is always `a` no matter what has been added to the value.

**Question: is the name `value()` intuitive as referring to a CSS value? Should it be something like `list()`? `set()`?** 

**Addendum: Another reason for this proposal is to simplify parsing, explained [here](https://github.com/less/less-meta/issues/35).**
