### ISSUE TITLE
Unrecognised input error with valid less input

### ISSUE THREAD

**Issue by ybelenko** [less/less.js#3558]
Input string:
```less
              ﻿
/*=============================================================================
          Color Variables
  =============================================================================*/

/*:::: Site color scheme ::::*/

// Variables
@base-theme-color:        #428bca; // sea blue


/*================ Add your Color Variables Classes here ==================*/

/*== SVG Color Common Class ==*/
.base-color {
  fill: @base-theme-color;
}

a {
  color: @base-theme-color;
}
```
js code:
```js
import { render } from 'less';

const lessScript = document.getElementById('less-colors');

less.render(lessScript.innerHTML, {filename: 'less-colors.less'})
  .then(function(output) {
    console.log(output)
      // output.css = string of css
      // output.map = string of sourcemap
      // output.imports = array of string filenames of the imports referenced
  },
  function(error) {
    console.log(error);
  });
```
Got error output:
```console
[Log] LessError
callExtract: undefined
callLine: NaN
column: 0
extract: ["// Variables", "@base-theme-color: #428bca; // sea blue", ""] (3)
filename: "less-colors.less"
index: 246
line: 10
message: "Unrecognised input"
stack: undefined
type: "Parse"
LessError Prototype
```
