### ISSUE TITLE
Lazy variables of css custom properties with less functions (even if it's overwritten) will break building

### ISSUE THREAD

**Issue by weareoutman** [less/less.js#3563]
For simplify the issue, Assume a third-party-library which contains:

```less
// `library/style.less`
@base-color: green;
@dark-color: darken(@base-color, 50%);

.some-class {
  color: @base-color;
  backgroundColor: @dark-color;
}
```

And my app would like to overwrite the `html > color` to a css custom properties:

```
import "~library/style.less";

:root {
  --primary-color: #fff;
}

html[data-theme="dark"] {
  --primary-color: #000;
}

@base-color: var(--primary-color);
@dark-color: var(--primary-color);
```

In which I want to override both the `@base-color` and `@dark-color` less variables. However, the less will fail with `LessError: error evaluating function `darken`: Argument cannot be evaluated to a color`, even if the `@dark-color` in library is actually overwritten, and no `darken` function should be called.
