### ISSUE TITLE
Conflict between Max of less's built-in function and max of CSS

### ISSUE THREAD

**Issue by bosens-China** [less/less.js#3564]
``` css
.minfont(@font) {
    font-size: max(14px, @font)
}
```

What do I need to do to work correctly?
