### ISSUE TITLE
Reassign of variable value inside a loop?

### ISSUE THREAD

**Issue by alexbleggi** [less/less.js#3585]
Hello everyone!!!

I have a question... Is it possible to reassign a variable value inside a loop???

```less
.tst-container,
.tst-container-fluid {
  .set-container();
}

each(.tst-container-max-widths(), .(@container-max-width-value, @container-max-width-name) {
  .tst-container-@{container-max-width-name} {
    &:extend(.tst-container-fluid);
  }

   @media (min-width: .tst-grid-breakpoints[$@container-max-width-name]) {
    .tst-container {
      max-width: @container-max-width-value;
    }
    
    /* 
     * setting the variable as true
     */
    @extend-grid-breakpoint: true;
    
    each(.tst-grid-breakpoints(), .(@grid-breakpoint-value, @grid-breakpoint-name) {
      & when (@extend-grid-breakpoint) {
        .tst-container-@{grid-breakpoint-name} {
          &:extend(.tst-container);
        }

        /* 
         * I want to exit the loop by reassigning false to the variable
         */
        & when (@container-max-width-name = @grid-breakpoint-name) {
           @extend-grid-breakpoint: false;
        }
      }
    });
  }
});
```
