### ISSUE TITLE
Issue with percent in keyframe animations

### ISSUE THREAD

**Issue by HenriMorlaye** [less/less.js#359]
This does not parse:

``` css
@-webkit-keyframes animate-color
{
  0% {
      color:red;
  }
  50% {
     color:black;
  }
  100% {
      color:yellow;
  }
}
```
