### ISSUE TITLE
floor函数在使用+-*/符号时..新版本需要使用一个()包裹住算式才可以,老版本的不需要...英语不好,中文将就看一下吧!

### ISSUE THREAD

**Issue by zcsoniubi** [less/less.js#3596]
#### 这是改好之后的
```css
@menuWidth: 55px;
@menuHeight: 158px;
@menuTop: 0px;
@menuMargin: 37px;
@menuNum: 8;
.generate-main-menu1(@n, @i: 1) when (@i =< @n) {
    #mainMenu@{i} {
      @num: floor(((@i - 1) / @menuNum));
      .absolute((@menuWidth + @menuMargin) * ((@i - 1) - @num * @menuNum),
                @menuTop + (@menuHeight + @menuMargin) * @num);
    }
    .generate-main-menu1(@n, (@i + 1));
  }
  .generate-main-menu1(4);
```

#### 原先的写法是
```css
@menuWidth: 55px;
@menuHeight: 158px;
@menuTop: 0px;
@menuMargin: 37px;
@menuNum: 8;
.generate-main-menu1(@n, @i: 1) when (@i =< @n) {
    #mainMenu@{i} {
      @num: floor((@i - 1) / @menuNum);
      .absolute((@menuWidth + @menuMargin) * ((@i - 1) - @num * @menuNum),
                @menuTop + (@menuHeight + @menuMargin) * @num);
    }
    .generate-main-menu1(@n, (@i + 1));
  }
  .generate-main-menu1(4);
```
用老的写法新版本less编译就会报异常SyntaxError: Error evaluating function `floor`: argument must be a number
