### ISSUE TITLE
Division of numbers is broken in v4

### ISSUE THREAD

**Issue by MartijnCuppens** [less/less.js#3615]
In Less `<v4`
```less
.selector {
  @number: 4;
  @divider: 2;
  value: @number / @divider;
}
```
compiles to
```less
.selector {
  property: 2;
}
```
In `v4`, it compiles to
```less
.selector {
  property: 4 / 2;
}
```
