### ISSUE TITLE
how to use(or possibility to) mixin with function?

### ISSUE THREAD

**Issue by orlowang** [less/less.js#3617]
in my case
first I use function to create a `.in-10` ...
``` css
@selectors: 5, 10, 20;
each(@selectors, {
    .in-@{value}{
        padding: (@value)px;
    }
});
```
then use `.in-10` as a mixin to `.button`
``` css
.button{
    .background-color:  green;
    .in-10();  /* <--  here to use mixin */
    ...some other
}
```

an error say `.in-10 is undefined`, may I think they are output same time so that `.in-10` is not find, how can I make this work? how to code less in this case?

pls!
