### ISSUE TITLE
Custom function plugin with detached ruleset not outputting without setting the ruleset as root

### ISSUE THREAD

**Issue by tedwash** [less/less.js#3619]
Hi, I'm not sure how to word this exactly. I'm trying to write a plugin that provides a function that can rewrite class selectors. I'm taking a detached ruleset, modifying the child selectors with a visitor, and returning the modified ruleset to be used where the function was invoked.

Repo: https://github.com/tedwash/less-plugin-scoper/blob/main/src/less/plugin/scoped-function.js#L55

Simplified example (minus the visitors)
**LESS**
```less
@plugin "./plugin/scoped-function.js";

.wrapper {
    scoped({
        .foo {
            color: orange;
        }
    });
}
```
**expected output**
```.css
.wrapper .aBCd-foo { color: orange }
```
**actual output (with ruleset.root=true)**
```css
.aBCd-foo { color: orange }
```
**actual output (with ruleset.root=false)**
```css
```

**scoped-function.js**
```js
function scoped(detachedRuleset) {
    const ruleset = detachedRuleset.callEval(this.context);

    // Have to set this to true or nothing will be rendered
    ruleset.root = true;
    return ruleset;
}


module.exports = {
    install: function (_less, _pluginManager, functions) {
        functions.add('scoped', scoped);
    },
};
```

Coincidentally I also get an error when trying to import a file that uses this custom function.
