### ISSUE TITLE
Cannot namespace detached ruleset

### ISSUE THREAD

**Issue by Bilge** [less/less.js#3624]
### Input

```less
#namespace {
  @ruleset: {
    foo: bar;
  }
}

.my-selector {
  #namespace.@ruleset();
}
```

### Output

    ModuleBuildError: Module build failed (from ../node_modules/less-loader/dist/cjs.js):

      .my-selector {
        #namespace.@ruleset();
                 ^
    Unrecognised input

---

Aside, the docs seem really unclear about whether a namespace should be defined as `#namespace` or `#namespace()`, but it doesn't make a difference either way, in this case.
