### ISSUE TITLE
Round with divide is failing to build

### ISSUE THREAD

**Issue by Congelli501** [less/less.js#3634]
Compiling this less source is not working with less 4.1.1:
```less
div {
	width: round(1 / 2);
}
```

Result:
```
ArgumentError: Error evaluating function `round`: argument must be a number in test.less on line 2, column 9:
1 div {
2 	width: round(1 / 2);
3 }
```

Same result with 4.0.0, but working ok with lessc 3.13.1

Expected (as with less 3.13.1):
```css
div {
  width: 1;
}
```
