### ISSUE TITLE
JavaScript evaluation - why forcing "Quotes" on strings?

### ISSUE THREAD

**Issue by chrisjacob** [less/less.js#364]
If the javascript evaluates to `typeof(result) === 'string'` then double-quotes (") wrap the result... why?

JS

``` javascript
localStorage['color'] = "pink";
```

LESS processed clientside

``` css
@color: `
(localStorage.color && localStorage.color !== '') 
? localStorage.color 
: 'blue'
`;

body { background-color: @color; }
```

Resulting CSS

``` css
body {
  background-color: "pink";
}
```

However I need to not have a quoted string...:

``` css
body {
  background-color: pink;
}
```

Line:
https://github.com/cloudhead/less.js/blob/master/dist/less-1.1.4.js#L1849

My current monkey patch is to change:

``` javascript
return new(tree.Quoted)('"' + result + '"', result, this.escaped, this.index);
```

for

``` javascript
return new(tree.Anonymous)(result);
```

... but I haven't yet considered security or other concerns with this patch.

Any tips?

Personally I don't think the quotes should be there by default... since quotes are rarely needed in CSS.
