### ISSUE TITLE
Division make less crash

### ISSUE THREAD

**Issue by lyz810** [less/less.js#3666]
```less
@rpx: 1 / 75rem;
html {
font-size: 2 * @rpx;
}
```
```
npx less index.less
```

output：
OperationError: Operation on an invalid type in ......

This error appears in v4，while normal in v3

Is this a bug, or feature?

The following cases will not throw error in v4
```less
@rpx: (1 / 75rem);
html {
font-size: 2 * @rpx;
}
```

```less
@rpx: 1 / 75rem;
html {
font-size: 2 * (@rpx);
}
```

```less
@rpx: 1rem * (1 / 75);
html {
font-size: 2 * @rpx;
}
```

```less
html {
font-size: 2 * 1 / 75rem; // not throw error, but not correct, as expected feature in https://github.com/less/less.js/releases/tag/v4.0.0
}
```
