### ISSUE TITLE
Variables aliases break unrelated detached rulesets calls

### ISSUE THREAD

**Issue by zaquest** [less/less.js#3677]
I have a piece of code that comes down to the following:

```
@blue: #007bff;
// @primary: @blue;  // Breaks if this line is uncommented

.unlock(@colors, @rules) {
  @rules();
}

.positive(@colors) {
  fg: @colors[dark];
  bg: @colors[light];
}


@fg: { color: @colors[fg]; };


h1 {
  @colors: { light: white; dark: black; };
  @positive: .positive(@colors);
  .unlock(@positive, @fg);
}
```

Without the `@primary` definition it works as expected. However when `@primary` is uncommented I get the following error:

```
SyntaxError: property "fg" not found in ...:
23   @positive: .positive(@colors);
24   .unlock(@positive, @fg);
25 }
```

First two lines and the rest of the code are seemingly unrelated to each other, yet these first two lines somehow break the rest of it.

Checked with 4.1.2 (earlier versions have the same issue, at least as early as 3.12.2).

**Comment by matthew-dean** [comment]
What output are you expecting? What is the use case?

**Comment by zaquest** [comment]
I expect

```css
h1 {
    color: black;
}
```

And I get it as long as `@primary: @blue;` is commented out. So the issue is that additional variable alias breaks style compilation.

My usecase for the code above is implementing color schemes. I want to define a set of base colors (`@colors`) call a mixin on it to translate it to a color scheme (`positive` - black on white, `negative` white on black, and some other variations), and use this color scheme to "unlock" some detached ruleset (`@fg`).

**Comment by Lfan-ke** [comment]
Here is a smaller reproduction (no imports needed), against current `master`:

```less
@a: 1;
@b: @a;   // remove this line and it compiles fine

.positive(@colors) { fg: @colors[dark]; }
@fg: { color: @colors[fg]; };

h1 {
  @colors: { dark: black; };
  @positive: .positive(@colors);
  .unlock(@positive, @fg);
}
.unlock(@colors, @rules) { @rules(); }
```

This throws `property "fg" not found`; deleting the `@b: @a;` line makes it compile to `h1 { color: black; }`.

A few things from narrowing it down:

- The trigger is any variable that aliases another variable (`@b: @a`) anywhere in scope. The name is irrelevant, and a plain value such as `@b: 1;` does not trigger it.
- It only happens with the mixin-call-as-value (`@positive: .positive(@colors)`); a plain detached-ruleset lookup is unaffected.
- At the failing lookup, `@positive` resolves to `{ dark: black; }` (i.e. `@colors` itself) instead of `.positive(@colors)`'s result `{ fg: black; }`, so the `[fg]` lookup misses.

So an unrelated alias seems to shift variable evaluation order just enough to mis-resolve the mixin-call-as-value to its argument.
