### ISSUE TITLE
Do not calculate the aspect-ratio property value

### ISSUE THREAD

**Issue by yisibl** [less/less.js#3679]
**To reproduce:**

```less
.foo {
  aspect-ratio: 144/224;
}
```

**Current behavior:**

```css
.foo {
  aspect-ratio: 0.64285714;
}
```

**Expected behavior:**
I hope to keep the output as it is.

```css
.foo {
  aspect-ratio: 144/224;
}
```
**Environment information:**

- `less` version: https://lesscss.org/less-preview/
- `nodejs` version:
- `operating system`:
