### ISSUE TITLE
Division operation go wrong

### ISSUE THREAD

**Issue by yulei521** [less/less.js#3681]
**To reproduce:**

```less
@fontSize: 24px;
body {
  font-size: @fontSize /  2;
}
```

**Current behavior:**

```
body {
  font-size: 24px / 2;
}
```

**Expected behavior:**

```
body {
  font-size: 12px;
}
```

**Environment information:**

- `less` 4.1.2:
- `nodejs` 14.15.4:
- `operating system`:mac
