### ISSUE TITLE
String colors are not transformed correctly to native less colors using less.tree.Color from a custom plugin

### ISSUE THREAD

**Issue by Gherciu** [less/less.js#3683]
**To reproduce:**
I created a super simple plugin (getColor) that accepts an argument and returns the color of that argument.
Everything works fine (The css is generated correctly and the plugin work)

**But IF** I'm trying to use the value (the color) returned by the plugin in some functions like `fade(...)` or other built-in Less functions
it throws an error:
```
Error evaluating function `fade`: Argument cannot be evaluated to a color
```

**Thats how I'm using it in Less file**
```less
@plugin "getColor";

@primary: getColor('primary');

.selector {
  // without fade works perfect and will output #cccccc
  color: getColor('primary');

  // This line throw the ERROR
  background: fade(@primary, 10%);
}
```

**Thats the plugin file content**
// ./getColor.js
```js
const colors = {
 'primary': '#ccc'
};
module.exports = {
   install: (less, _ , functions) => {
     functions.add('getColor', (arg) => {
       var originalColor = colors[arg.value];
        var preparedColor = originalColor.replace('#', '');
        return less.tree.Color(preparedColor, 1, originalColor );
      });
   }
}
```

**Current behavior:**

Throws and error and say that the color is not valid only when used in built-in functions like `fade(...)`.
But if to use the result of the plugin function without `fade()` the resulted CSS will be correct and the output too thats strange)

**Expected behavior:**

**Environment information:**

 - node: 14
- less: 4.1.2
- os: linux ubuntu

Being hones I spent already 2 days understanding how I should return something from a plugin firstly I encountered this error when I was returning the raw value directly as a string "#ccc" That also doesn't work....Then I noticed somewhere in docs that I need to return these values using `less.tree.Color` but that also doesn't work...pls help(
