### ISSUE TITLE
Modern color function notation works incorrectly

### ISSUE THREAD

**Issue by Greatshock** [less/less.js#3685]
**To reproduce:**

```less
body {
   background: rgb(242 243 245 / 40%);
}
```

**Current behavior:**

Results into CSS:
```css
body {
  color: rgb(242 243 6.125%);
}
```

**Expected behavior:**

```css
body {
   background: rgb(242 243 245 / 40%);
}
```

So modern color function notation works incorrectly. This also might be a duplicate of #3665
