### ISSUE TITLE
Mixin with pseudo selector - 2

### ISSUE THREAD

**Issue by AuracleTech** [less/less.js#3686]
I can't re-open the issue, but this is my issue as well. https://github.com/less/less.js/issues/3427

To put simply

```less
.slot{ border:1px solid gray; width:16px; height:16px; }
.slot:hover{ background:orange; }
.L_slot{ .slot; width:64px; height:64px; }
```

Expected result : `.L_slot` should have the `.slot:hover`, yet it does not acquire it.
Also it is impossible to import from any other way.

**Comment by AuracleTech** [comment]
Edit : Found using 
```less
.slot{ &:hover{border-color:@BlazeOrange;} border:1px solid gray; width:16px; height:16px; }
```

Unexpected... but I guess it fixed my issue, one of those things you gotta know to know I guess...
