### ISSUE TITLE
less parse about inconsistent operation performance

### ISSUE THREAD

**Issue by zhusjfaker** [less/less.js#3692]
**To reproduce:**

```less

// parse ok

@c:20px + 20px * 2px;

.d {
    font-size: @c;
}

// parse ok

@c:20px + (20px * 2px);

.d {
    font-size: @c;
}

// parse fail

@c:20px + 20px / 2px;

.d {
    font-size: @c;
}

// parse ok

@c:20px + (20px / 2px);

.d {
    font-size: @c;
}

```

**Current behavior:**

less.js  the operation of variables is inconsistent in multiplication and division

**Expected behavior:**

consistent behavior

**Environment information:**

- `less` version: 3.13.0
- `nodejs` version: 16.13
- `operating system`: darwin

please do not  forcibly close issue
