### ISSUE TITLE
Produces invalid media query from nested conditions

### ISSUE THREAD

**Issue by Knutas** [less/less.js#3694]
**To reproduce:**

```less
@media (max-width: 500px) {
  @media screen {
    body {
      background-color: red;
    }
  }
}
```

**Current behavior:**

Produces invalid css with `and screen` at the end of the media query.
```css
@media (max-width: 500px) and screen {
  body {
    background-color: red;
  }
}
```

**Expected behavior:**

`screen and` added to the start of the media query.
```css
@media screen and (max-width: 500px) {
  body {
    background-color: red;
  }
}
```

**Environment information:**

http://lesscss.org/less-preview/
