### ISSUE TITLE
Cannot override variable imported via :extend()

### ISSUE THREAD

**Issue by Bilge** [less/less.js#3706]
**To reproduce:**

```less
@color: red;

a {
  color: @color;
}

.foo {
  a:extend(a all) {
    @color: green;
  }
}
```

**Current behavior:**

`.foo a` colour is red.

**Expected behavior:**

`.foo a` colour is green.

**Environment information:**

- `less` version: 4.1.2
- `nodejs` version: v14.15.3
- `operating system`: windows
