### ISSUE TITLE
How to convert maps to variables?

### ISSUE THREAD

**Issue by tczzz** [less/less.js#3733]
I have a map, like below:
```less
  #maps() {
    white: #fff;
    black: #000;
  }
```
Now, I want to convert it to some variable：
```less
@white: #fff;
@black: #000;
```
But I don't know what to do, is there any way?

**Comment by matthew-dean** [comment]
"How to" questions are best posed on Stack Overflow. This is not a bug.

That said, this would be the solution:
```less
#maps() {
  white: #fff;
  black: #000;
}
@white: #maps[white];
@black: #maps[black];
```
