### ISSUE TITLE
Media query express support

### ISSUE THREAD

**Issue by woody-li** [less/less.js#3735]
A new range syntax introduced in [Media Queries Level 4](https://www.w3.org/TR/mediaqueries-4/#width).

The syntax allow query expresses, includes range express.

But i got an error when using the syntax.

**To reproduce:**

```less
@media (400px <= width <= 700px) {
    .main-box {
        display: flex;
    }
}
```

**Current behavior:**

> less: Missing closing ')' in file test.less line no. 1

**Expected behavior:**

Convert to css with the syntax correctly

**Environment information:**

- `less` version: 4.1.3
- `nodejs` version: 16.14.0
- `operating system`: win

**Comment by woody-li** [comment]
@mud1tx Thanks for your reply. I'd like to provide something, but I don't know what to provide.

**Comment by matthew-dean** [comment]
@mud1tx This isn't a bug, it's technically a feature request. So what needs to be added is support for range syntax in media queries. This would need to support merging as well.

That is, right now Less transforms this:
```less
@media screen {
  @media (min-width: 1023px) {
    .selector {
      color: blue;
    }
  }
}
```
...into...
```css
  @media screen and (min-width: 1023px) {
    .selector {
      color: blue;
    }
  }
```
So, tests would need to be added to convert:
```less
@media (400px <= width) {
  @media (width <= 700px) {
    .main-box {
        display: flex;
    }
  }
}
```
into:
```css
@media (400px <= width) and (width <= 700px) {
    .main-box {
        display: flex;
    }
}
```
