### ISSUE TITLE
modifyvars can't resolve externals url variable

### ISSUE THREAD

**Issue by Zebzhong** [less/less.js#3754]
**To reproduce:**

```less
const less = require("less");

let lessStr = `
@color1: 'blue';
@imgUrl: '';
@furl: 'https://qq.com';

body{
  color: @color1;
}

.myImg {
  background: url('@{imgUrl}') no-repeat;
  background-size: contain;
  width: 200px;
  height: 200px;
}

@font-face {
  font-family: 'zbtest';
  src: "url('@{furl}')";
}
.root {
  font-family: 'zbtest';
}
`

less
  .render(lessStr, {
    modifyVars: {
      color1: 'skyblue',
      imgUrl: '../test/qe.png',
      furl: "https://www.baidu.com"
    },
  })
  .then((res) => {
    console.log(res);
  });
```

**Current behavior:**

![image](https://user-images.githubusercontent.com/29706072/191486080-bb3916b4-376f-49d9-96db-f08516050c20.png)

**Expected behavior:**

Can replace externals url variables correctly， Thanks

**Environment information:**

- `less` version: 4.1.3
- `nodejs` version: 14.x
- `operating system`: windows 10
