### ISSUE TITLE
Nested @media blocks are combined in a non-compliant way.

### ISSUE THREAD

**Issue by tsx** [less/less.js#3764]
According to the [CSS spec](https://drafts.csswg.org/mediaqueries-5/#typedef-media-query-list), media type (`screen`, `print` etc) must be first on the list and all the other conditions (for example `(max-width: 800px)`) must follow after the media type.

**To reproduce:**

```less
@media (max-width: 800px) {
  @media screen {
    .selector {color: black}
  }
}
```

**Current behavior:**

Less compiler combines nested media conditions in a way that is not compliant with the spec, putting media type between conditions or after them.

```css
@media (max-width: 800px) and screen {
  .selector {
    color: black;
  }
}
```

**Expected behavior:**

Media type should be put into the first position in the media query, like so:

```css
@media screen and (max-width: 800px) {
  .selector {
    color: black;
  }
}
```

**Environment information:**

- `less` version: **4.1.3**, including the official playground
- `nodejs` version: any
- `operating system`: any

**Additional notes**

Even though it might seem trivial to re-order the example above to produce correct results, it's not always possible since the inner `@media screen` might come from a third party (I'm working with `antd`) that I can't modify.

It seems like most browsers don't mind media conditions being out of spec (or I didn't observe the effects), however this issue prevents me from using https://parceljs.org/ which implements pretty strict standards checking and chokes at the less output, producing `Unexpected token Ident("screen")`. The fixed snippet where media-type comes first is processed correctly by `parcel`.
