### ISSUE TITLE
Support for recently added CSS functionality container-queries

### ISSUE THREAD

**Issue by sneridagh** [less/less.js#3766]
As pointed out by @treponat, it seems support for `@container` queries should be implemented in less.

By tomorrow (12/12/2022) Firefox will release 108 with support for container queries, completing all the major browsers support for the feature. 

### Discussed in https://github.com/less/less.js/discussions/3759

<div type='discussions-op-text'>

<sup>Originally posted by **treponat** November  3, 2022</sup>
Recently some of the browser started to support a new feature that would allow to create responsive design based on the parent element rather than client's viewport. 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries
It would be wonderful if LESS would also start to fully support this feature. 
Currently you can use container functionality in .less files, but the hierarchical structure of css blocks is not working as expected for the container syntax. 
for example
```
.widget.discoverresults, .widget.repositoriesresults {
        container-type: inline-size;
        @container (max-width: 350px) {           
                    .cite {
                        .wdr-authors {
                            display: none;
                         }
                }
         }
}
    
```

would produce this css blocks 

```
.widget.discoverresults,
.widget.repositoriesresults {
  container-type: inline-size;
}
@container (max-width: 350px) {
  .cite .wdr-authors {
    display: none;
  }
}
```
instead of 
```
.widget.discoverresults,
.widget.repositoriesresults {
	container-type: inline-size;
}

@container (max-width: 350px) {

	.widget.discoverresults,
	.widget.repositoriesresults {
		.cite .wdr-authors {
			display: none;
		}
	}
}
```
</div>

**Comment by iChenLei** [comment]
cc @matthew-dean

**Comment by levito** [comment]
I found a workaround with saving the selector to a variable using the plugin https://github.com/seven-phases-max/less-plugin-reflections as suggested here: https://github.com/less/less.js/issues/3053#issuecomment-299707813

```less
.container(@from, @rules) {
  .container(@from, @to: 0, @rules);
}
.container(@from, @to, @rules) {
  @selector: current-selector();

  .return(@selector) when (@from = 0) {
    @container (max-width: @to) {
      @{selector} {
        @rules();
      }
    }
  }
  .return(@selector) when (@to = 0) {
    @container (min-width: @from) {
      @{selector} {
        @rules();
      }
    }
  }
  .return(@selector) when (default()) {
    @container (min-width: @from) and (max-width: @to) {
      @{selector} {
        @rules();
      }
    }
  }
  .return(@selector);
}
```

Usage:
```less
.deeply .nested .selector {
  .container(300px, {
    content: "container min width of 300px";
  }
  .container(0, 700px, {
    .going .deeper {
      content: "container max width of 700px";
    }
  }
}
```

**Comment by matthew-dean** [comment]
Oh I see, you're expecting `@container` to act like `@media` or `@supports`? That's reasonable.

**Comment by sneridagh** [comment]
@matthew-dean yeah, that's the point :) BTW, I forgot to mention that SCSS has already support for this behavior.

**Comment by rejhgadellaa** [comment]
Just ran into this issue. Is there any timeframe on how long this could take to land this in a release? Have to decide if I should wait a few weeks or do everything the old fashioned way for now and then refactor in a couple of months or so?

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, please assign me.

**Comment by matthew-dean** [comment]
@abhishek-kumar-91 Go for it!

**Comment by matthew-dean** [comment]
@abhishek-kumar-91 

I presume that what you'll want to do is [extend from the `Media` tree type](https://github.com/less/less.js/blob/master/packages/less/src/less/tree/media.js). Then you'll probably want to alter [the `media` parser](https://github.com/less/less.js/blob/master/packages/less/src/less/parser/parser.js#L1810) to generalize it for `@container` queries.

This is called [within the `atrule` parser early](https://github.com/less/less.js/blob/master/packages/less/src/less/parser/parser.js#L1923), for `@import`, `@plugin`, and `@media`, as they have special handling rules, so I presume the line will end up looking like:
```js
value = this['import']() || this.plugin() || this.mediaOrContainer();
```

And then, of course, writing css / less tests to verify input / output. Make sense?

**Comment by levito** [comment]
How are things going with this? When working on this, it would be awesome to also support [container style queries](https://ishadeed.com/article/css-container-style-queries/), which I think should be pretty straightforward since it's syntactically very similar to named container queries.

**Comment by tatof** [comment]
Any news on the @container css media queries?

**Comment by puckowski** [comment]
I have a fork of Less.js 4.1.3 that supports container queries. Passes all tests, plus additional tests for container queries.

This:

```css
.widget.discoverresults, .widget.repositoriesresults {
        container-type: inline-size;

        @container (max-width: 350px) {           
            .cite {
                .wdr-authors {
                    display: none;
                }
            }
        }
}
```

becomes this:

```css
.widget.discoverresults, 
.widget.repositoriesresults {
    container-type: inline-size;
}

@container (max-width: 350px) {           
    .widget.discoverresults .cite .wdr-authors,
    .widget.repositoriesresults .cite .wdr-authors {
        display: none;
    }
}
```

I plan on making the fork public sometime later today (07/19/23) and creating a pull request sometime within the next couple of days.

Size of the minified bundle goes up by around 2KB.
