### ISSUE TITLE
Value is not calculated for css --variables

### ISSUE THREAD

**Issue by Dagur** [less/less.js#3800]
**To reproduce:**

```less
.test {
  width: 20px + 40px;  
  --width: 20px + 40px;  
}
```

**Current behavior:**

output is
```css
.test {
  width: 60px;
  --width: 20px + 40px;
}
```

**Expected behavior:**

I expected 
```css
.test {
  width: 60px;
  --width: 60px;
}
```

**Environment information:**

- `less` version: 4.1.3
- `nodejs` version: Whatever http://lesscss.org/less-preview/ uses
- `operating system`: Whatever http://lesscss.org/less-preview/ uses

This can cause unexpected problems when combined with less @variables.

**Comment by matthew-dean** [comment]
This is by design and not a bug. For example, let's say you had this:
```less
.test {
  --width: 20px + foo({ 40: 'px' });
}
```
What should Less do with this? The value you have for `--width` is 100% perfectly valid, and you could be intending to evaluate it as JavaScript, so it couldn't throw an error as an invalid expression. Instead, you have to evaluate it before-hand:
```less
.test {
  @width: 20px + 40px;
  --width: @width;
}
```
Less evaluating at-rules in custom properties has its own add-in side-effects / bugs, but that's what is currently supported.
