### ISSUE TITLE
Adding a default value to a mixin causes arity match failure

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#4234]
**To reproduce:**

In the docs, it describes how mixins match on arity (number of arguments).

That is, you can do this:
```
.mixin(@a) {
  value: @a;
}
.mixin(@a, @b) {
  value: @a + @b;
}

.box {
  .mixin(3);
}
```
This will produce:
```css
.box {
  value: 3;
}
```
However, if you add a default value to the first parameter, like so:

```less
.mixin(@a) {
  value: @a;
}
.mixin(@a: 1, @b) {
  value: @a + @b;
}

.box {
  .mixin(3);
}
```
... then you get the error: `wrong number of arguments for .mixin (1 for 2)`

**Expected behavior:**

I would expect this to still match the first mixin by arity.

Something else that's unexpected is that you can't match the second mixin by arity by doing this:
```less
.box {
  .mixin(@b: 3);
}
```
However, the Less docs don't sufficiently explain (IMO) what the expected behavior should be in that case. Technically, there _is_ a mixin that matches, but it's not clear from the Less docs if overloading mixins means you can "pass over" mixins with only one named argument. I'm really not sure what the behavior should be because the docs don't say, so I'd welcome opinions.

**Environment information:**

Latest Less / Node 16
