### ISSUE TITLE
Container style queries unexpected space

### ISSUE THREAD

**Issue by woody-li** [less/less.js#4235]
**To reproduce:**

https://lesscss.org/less-preview/#eyJjb2RlIjoiQGNvbnRhaW5lciBzdHlsZSgtLXRoZW1lOiBkYXJrKXtcbiAgLm1haW57XG4gICAgY29sb3I6IzAwMDtcbiAgfVxufVxuXG4iLCJhY3RpdmVWZXJzaW9uIjoiNC4yLjAiLCJtYXRoIjoicGFyZW5zLWRpdmlzaW9uIiwic3RyaWN0VW5pdHMiOmZhbHNlfQ==

```less
@container style(--theme: dark){
  .main{
    color: #000;
  }
}
```

**Current behavior:**
There's a space between "style" and the bracket.
```less
@container style (--theme: dark)
```

**Expected behavior:**
No space  between "style" and the bracket.
```less
@container style(--theme: dark)
```

**Environment information:**
- `less` version: 4.2.0

**Comment by haseeb196** [comment]
Maybe this is not a error the less code is correct but some text editors and Markdown renderers might automatically add a space after type and it does not affect the functionality of the code.

**Comment by woody-li** [comment]
@haseeb196 But it doesn't take effect in Chrome when contains a space.
Seems the "style" is recognized as a function.

**Comment by woody-li** [comment]
@matthew-dean I don't ensure it's a function. 
But according to the [specification](https://www.w3.org/TR/css-contain-3/#container-rule), the style syntax: `style( <style-query> )` looks like a function.

Only `Chrome` has implemented the `container style query` so far, and it cannot take effect when a space exists between style and bracket.

**Comment by woody-li** [comment]
Sorry for my mistake, it should be `style`.
Thanks

**Comment by ghazanfarofficial01** [comment]
How can I contribute to this issue?

**Comment by BhushanNalawade** [comment]
How to contribute to this issue?

**Comment by rejhgadellaa** [comment]
Any news on this? Safari 18 now supports container style queries as well, so would be nice to have this fix land in prod. Thnx!

**Comment by rejhgadellaa** [comment]
FWIW, you can work around this issue by escaping the `style()` query:

```css
@container ( ~"style(-theme: light)" )
```

For `@` variables:

```css
@container ( ~"style(-theme: @{theme})" )
```

**Comment by woody-li** [comment]
@matthew-dean The release PR has merged, could you help to release new version to npm.

**Comment by woody-li** [comment]
Fixed in https://www.npmjs.com/package/less/v/4.2.1

**Comment by woody-li** [comment]
Meet another issue:
The space appears again when querying a style without value.

```css
@container style(--x) {
  .x {
    color: red;
  }
}

@container style(--x:1) {
  .x {
    color: red;
  }
}
```
Will convert to
```css
@container style (--x) {
  .x {
    color: red;
  }
}
@container style(--x: 1) {
  .x {
    color: red;
  }
}
```

@puckowski, Please take a look if possible, thanks
