### ISSUE TITLE
Nested @layer rule lost scope

### ISSUE THREAD

**Issue by woody-li** [less/less.js#4242]
**To reproduce:**

https://lesscss.org/less-preview/#eyJjb2RlIjoiLm1haW57ICBcbiAgQGxheWVye1xuICAgICY6OmJlZm9yZXtcbiAgICAgIGNvbG9yOiNmMDA7XG4gICAgfVxuICB9XG4gIEBtZWRpYSBzY3JlZW57XG4gICAgJjo6YmVmb3Jle1xuICAgICAgY29sb3I6IzBmMDtcbiAgICB9XG4gIH1cbiAgQGNvbnRhaW5lciAod2lkdGg+NDAwcHgpe1xuICAgICY6OmJlZm9yZXtcbiAgICAgIGNvbG9yOiMwMGY7XG4gICAgfVxuICB9XG59IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4wIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=

```less
.main{  
  @layer{
    &::before{
      color:#f00;
    }
  }
}
```

**Current behavior:**
Nesting selector `&` lost in `@layer`.
But other @ rules works well, such as `@media`, `@container` etc.
```less
@layer {
  ::before {
    color: #f00;
  }
}
```

**Expected behavior:**
Nesting selector `&` resolved as its scope selector.
```less
@layer {
  .main::before {
    color: #f00;
  }
}
```

**Environment information:**

- `less` version: 4.2.0

**Comment by puckowski** [comment]
Hello,

This Less:

```css
.main{  
  @layer{
    &::before{
      color:#f00;
    }
  }
}
```

becomes

```html
<style type="text/css">@layer {
  .main::before {
    color: #f00;
  }
}
</style>
```

in Less ```4.4.0``` available on npm now at https://www.npmjs.com/package/less/v/4.4.0
