### ISSUE TITLE
less variables cannot be used under the not selector, delimiter

### ISSUE THREAD

**Issue by comewithl** [less/less.js#4244]
**To reproduce:**

```less
@compPrefix: ~'hi';
.@{compPrefix}{
 color:red;
 &:not(.@{compPrefix}-one, .@{compPrefix}-two){
  color:blue
 }
}
```

```less
@compPrefix: ~'hi';
.@{compPrefix}{
 color:red;
 &:not(&-one, &-two){
  color:blue
 }
}
```

**Current behavior:**

```
ParseError: Missing closing ')' in /Users/lar/work/isv/theme_static/test.less on line 4, column 26:
3  color:red;
4  &:not(.@{compPrefix}-one, .@{compPrefix}-two){
5   color:blue
```

**Expected behavior:**
Output like this;
```css
.hi {
  color: red;
}
.hi:not(.hi-one, .hi-two){
  color: blue;
}

```

**Environment information:**

- `less` version: 4.1.2
- `nodejs` version: 16.14.0
- `operating system`: macos

**Comment by woody-li** [comment]
Same issue with nested selector `&`

Works well:
```less
.main{
  :is(.main-a, .main-b){
    color:red;
  }
}
```

Same error:
```less
.main{
  :is(&-a, &-b){
    color:blue;
  }
}
```

Maybe related with #3802?

**Comment by puckowski** [comment]
I believe https://github.com/less/less.js/pull/4290 may resolve this issue.

Fork release https://github.com/puckowski/less.js/releases/tag/4.2.1.2 takes the following Less.js

```css
@compPrefix: ~'hi';
.@{compPrefix}{
 color:red;
 &:not(.@{compPrefix}-one, .@{compPrefix}-two){
  color:blue
 }
}
```

and outputs:

```css
.hi {
  color: red;
}
.hi:not(.hi-one, .hi-two) {
  color: blue;
}
```

Fork release is Less.js 4.2.1 with fixes for:
https://github.com/less/less.js/issues/4252
https://github.com/less/less.js/issues/3737
https://github.com/less/less.js/issues/4258
https://github.com/less/less.js/issues/4264
https://github.com/less/less.js/issues/4268
https://github.com/less/less.js/issues/4267

I'll take a closer look later today.

**Comment by puckowski** [comment]
I believe https://github.com/less/less.js/pull/4290 may resolve this issue.

With the PR the following Less.js:

```css
.main{
  :is(&-a, &-b){
    color:blue;
  }
}
```

becomes:

```css
.main :is(&-a, &-b) {
  color: blue;
}
```

I tested using https://github.com/puckowski/less.js/releases/tag/4.2.1.2
