### ISSUE TITLE
@font-face doesn't respect scope when compiling

### ISSUE THREAD

**Issue by badlydrawnrob** [less/less.js#4251]
**To reproduce:**

You can see the issue [on this preview](http://lesscss.org/less-preview/#eyJjb2RlIjoiOnJvb3Qge1xuICBAZm9udC1mYWNlIHtcbiAgICBmb250LWZhbWlseTogXCJEZWphVnUgU2Fuc1wiO1xuICAgIHNyYzogdXJsKFwiX0RlamFWdVNhbnMtQm9sZFwiKTtcbiAgICBmb250LXN0eWxlOiBub3JtYWw7XG4gICAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgfVxuICAtLWNzcy12YXJpYWJsZTogXCJEZWphVnUgU2Fuc1wiO1xufSIsImFjdGl2ZVZlcnNpb24iOiI0LjIuMCIsIm1hdGgiOiJwYXJlbnMtZGl2aXNpb24iLCJzdHJpY3RVbml0cyI6ZmFsc2V9) — although in my version, I have a file called `root.less` that's importing the `@font-face` code from another file.

The following scope isn't respected:

```less
:root {
  @font-face {
    font-family: "DejaVu Sans";
    src: url("_DejaVuSans-Bold");
    font-style: normal;
    font-weight: 700;
  }
  --css-variable: "DejaVu Sans";
}
```

The CSS variable is scoped to `:root`, but the `@font-face` is outside of root when compiled. I'm not sure if this is by design, or a bug. There is [some conversation](https://stackoverflow.com/questions/67392191/why-should-font-face-be-declared-at-global-scope-outside-of-shadow-dom) about [where it should be defined](https://github.com/w3c/csswg-drafts/issues/1995) — but I feel putting it inside `:root` should be valid.

It just means my css variables are named before the `@font-face` in the `main.css` compiled file — the CSS still seems to work, but it might cause problems in the future.

**Expected behavior:**

I expected the `@font-face` rule to be inside `:root`.

**Environment information:**

Less version 4.2.0 on Mac.
