### ISSUE TITLE
`mask-repeat: no-repeat` being transformed into `mask-repeat: initial` in production mode

### ISSUE THREAD

**Issue by NriotHrreion** [less/less.js#4253]
**To reproduce:**

```less
.box {
  // some other mask options
  mask-repeat: no-repeat;
}
```

**Current behavior:**

In production mode, the above less code will be transformed into:

```css
.box {
  mask-repeat: initial;
  -webkit-mask-repeat: no-repeat;
}
```

**Expected behavior:**

In production mode, it is supposed to be transformed into:

```css
.box {
  mask-repeat: no-repeat;
  -webkit-mask-repeat: no-repeat;
}
```

**Environment information:**

- `less` version: 4.1.3
- `less-loader` version: 11.1.0
- `nodejs` version: 16.17.0
- `operating system`: Windows
