### ISSUE TITLE
Empty calculation passed to css in 4.2.0

### ISSUE THREAD

**Issue by MagpieRook** [less/less.js#4256]
**To reproduce:**

Use any `min` or `max` function alongside a CSS variable. The breaking change in my deployed environment is:

```less
:root {
  --body-max-width: 1200px;
}

#main-content {
  max-width: min(var(--body-max-width), calc(100vw - 20px));
}
```

However, another call to `min` without CSS variables is passed appropriately:

```less
.carousel {
  --caption-width: min(600px, 100%);
}
```

**Current behavior:**

In `4.1.3`, both the `max-width` statement and the `--caption-width` variable are passed as-is to the CSS file. In `4.2.0`, the CSS file produced instead has `max-width: min();`.

**Expected behavior:**

A non-empty `max-width: min();`.

**Environment information:**

- `less` version: 4.2.0
- `nodejs` version: 18.13.0
- `operating system`: (occurs on both windows and mac)

This occurs with `max`, as well, but not `calc`, which makes me think it's related to #3719.
