### ISSUE TITLE
Variable interpolation with math operator like + is not compiling properly

### ISSUE THREAD

**Issue by liuliangsir** [less/less.js#4258]
**To reproduce:**

```less
@a: 1px;
@b: 2px;
@c: @a + @b;

@radio-cls: radio;
@radio-cls-checked: @{radio-cls}_checked;

.@{radio-cls-checked} {
  border-color: #fff;
}
```
Also [here](https://lesscss.org/less-preview/#eyJjb2RlIjoiQGE6IDFweDtcbkBiOiAycHg7XG5AYzogQGEgKyBAYjtcblxuQHJhZGlvLWNsczogcmFkaW87XG5AcmFkaW8tY2xzLWNoZWNrZWQ6IEB7cmFkaW8tY2xzfV9jaGVja2VkO1xuXG4uQHtyYWRpby1jbHMtY2hlY2tlZH0ge1xuICBib3JkZXItY29sb3I6ICNmZmY7XG59IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4wIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=) is a online playground for reproducing the issue above.

**Current behavior:**
```less
._checked {
  border-color: #fff;
}
```

**Expected behavior:**
```less
.radio_checked {
  border-color: #fff;
}
```

**Environment information:**

- `less` version: 4.2.0
- `nodejs` version: N/A
- `operating system`: N/A

**Workaround**
- [solution1](https://lesscss.org/less-preview/#eyJjb2RlIjoiQGE6IDFweDtcbkBiOiAycHg7XG4vKiBAYzogQGEgKyBAYjsgKi9cblxuQHJhZGlvLWNsczogcmFkaW87XG5AcmFkaW8tY2xzLWNoZWNrZWQ6IEB7cmFkaW8tY2xzfV9jaGVja2VkO1xuXG4uQHtyYWRpby1jbHMtY2hlY2tlZH0ge1xuICBib3JkZXItY29sb3I6ICNmZmY7XG59IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4wIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=)
- [solution2](https://lesscss.org/less-preview/#eyJjb2RlIjoiQGE6IDFweDtcbkBiOiAycHg7XG5AYzogQGEgKyBAYjtcblxuQHJhZGlvLWNsczogcmFkaW87XG5AcmFkaW8tY2xzLWNoZWNrZWQ6IH5cIkB7cmFkaW8tY2xzfV9jaGVja2VkXCI7XG5cbi5Ae3JhZGlvLWNscy1jaGVja2VkfSB7XG4gIGJvcmRlci1jb2xvcjogI2ZmZjtcbn0iLCJhY3RpdmVWZXJzaW9uIjoiNC4yLjAiLCJtYXRoIjoicGFyZW5zLWRpdmlzaW9uIiwic3RyaWN0VW5pdHMiOmZhbHNlfQ==)
