### ISSUE TITLE
Lessc to provide preserve comments option

### ISSUE THREAD

**Issue by dkaushik95** [less/less.js#4269]
`lessc` should provide an option for comments to be preserved. Currently it preserves block comments and removes inline or `//` comments.

**To reproduce:**

```less
// Main comment
/** comment with block **/
body {
  width: 100%; // inline comment
}

```

**Current behavior:**

```css
/** comment with block **/
body {
  width: 100%;
}

```

**Expected behavior:**

```css
/** Main comment **/
/** comment with block **/
body {
  width: 100%; /** inline comment **/
}

```

**Environment information:**

- `less` version: `v4.2.0`
- `nodejs` version: `v18.18.0`
- `operating system`: `macos`
