### ISSUE TITLE
Error evaluating a computed variable that is already overriden

### ISSUE THREAD

**Issue by imaliouris** [less/less.js#4275]
**To reproduce:**

```less
@a: 5px;
@b: 3px;
@b: round(@a * 3);
@b: 10px;
@a: "nna";
```

**Current behavior:**

Less throws error ```OperationError: Error evaluating function `round`: Operation on an invalid type```

**Expected behavior:**

Should compile without any error, because less always uses the last declaration of a variable according to [lazy evaluation](https://lesscss.org/features/#variables-feature-lazy-evaluation).
If we use that `@b` it will evaluate as `10px`
i.e.
```less
.some-class {
  width: @b;
}

// will output to css 

.some-class {
  width: 10px;
}
```

**Environment information:**

- `less` version: lessc 4.2.0 (Less Compiler) [JavaScript]
- `nodejs` version: 18.19.1
- `operating system`: Ubuntu 22.04.4 LTS
