### ISSUE TITLE
ParseError with :is() or :matches() containing :has()

### ISSUE THREAD

**Issue by SuperPat45** [less/less.js#4278]
**To reproduce:**

```
:is(:not(:has(>.foo)), :has(>.foo.bar)) {
    overflow: clip;
}
```

**Current behavior:**

Throw a:
ParseError: Missing closing ')'

**Expected behavior:**

No exception has the number of close parenthesis is correct
**Environment information:**

- `less` version: 4.2.0
- `nodejs` version: 20.17
- `operating system`: windows

**Comment by puckowski** [comment]
I submitted a PR #4290 

The following Less

```css
@num: 3;
:nth-child(@{num}) {
  selector: interpolated;
}


a:is(.b, :is(.c)) {
  color: blue;
}

:is(:not(:has(>.foo)), :has(>.foo.bar)) {
  overflow: clip;
}
```

becomes:

```css
:nth-child(3) {
  selector: interpolated;
}
a:is(.b, :is(.c)) {
  color: blue;
}
:is(:not(:has(>.foo)), :has(>.foo.bar)) {
  overflow: clip;
}
```
