### ISSUE TITLE
`@import (less)` doesn't change the relative URLs

### ISSUE THREAD

**Issue by ackava** [less/less.js#4300]
1. Consider following setup

```
   root folder
     | -- app.less
     | -- components
            | -- pinch-zoom.less
            | -- scale.svg
```

2. File `pinch-zoom.less` references `scale.svg`.

`app.less`
```less
@import (less) "./components/pinch-zoom.less";
```

`pinch-zoom.less`
```less
pinch-zoom {
     button {
         background-image: url("./scale.svg");
     }
}
```

Compiling `app.less` results in 

`app.css`
```css
pinch-zoom {
   button {
         background-image: url("./scale.svg");
   }
}
```

However, it should ideally become,
`app.css`
```css
pinch-zoom {
   button {
         background-image: url("./components/scale.svg");
   }
}
```

Becasue `scale.svg` is inside components folder.
