### ISSUE TITLE
At-rule declarations may go missing are or incorrectly merged under certain nesting conditions

### ISSUE THREAD

**Issue by puckowski** [less/less.js#4301]
@jpattishall-ebay raised an issue in https://github.com/less/less.js/issues/4267#issuecomment-2552268095 where they noted ```@media``` and ```@container```  are not properly nesting in some cases.

Currently I see in 4.2.1 [Playground](https://lesscss.org/less-preview/#eyJjb2RlIjoiQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWluLXdpZHRoOiA3NjhweCkge1xuICBAY29udGFpbmVyIChtaW4td2lkdGg6IDUwMHB4KSB7XG4gICAgLnByaW1hcnktY29udGVudCB7XG4gICAgICBmb250LXNpemU6IDFyZW07XG4gICAgfVxuICB9XG59IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4xIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=) I see this:

```css
@media only screen and (min-width: 768px) {
  @container (min-width: 500px) {
    .primary-content {
      font-size: 1rem;
    }
  }
}
```

results in:

```css
@container only screen and (min-width: 768px) and (min-width: 500px) {
  .primary-content {
    font-size: 1rem;
  }
}
```

But I see [4.1.3](https://lesscss.org/less-preview/#eyJjb2RlIjoiQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWluLXdpZHRoOiA3NjhweCkge1xuICBAY29udGFpbmVyIChtaW4td2lkdGg6IDUwMHB4KSB7XG4gICAgLnByaW1hcnktY29udGVudCB7XG4gICAgICBmb250LXNpemU6IDFyZW07XG4gICAgfVxuICB9XG59IiwiYWN0aXZlVmVyc2lvbiI6IjQuMS4zIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=) produced the expected output:

```css
@media only screen and (min-width: 768px) {
  @container (min-width: 500px) {
    .primary-content {
      font-size: 1rem;
    }
  }
}
```
