### ISSUE TITLE
**:not()** with a selector list doesn't expand & symbol

### ISSUE THREAD

**Issue by WORMSS** [less/less.js#4313]
`:not(&--a):not(&--b)` does expand the & symbol into the parent's selector as expected.
`:not(&--a, &--b)` doesn't expand the & symbol into the parent's selector.

**To reproduce:**

```less
.works {
  &:not(&--a):not(&--b):hover {
    background-color: green;
  }
}

.broken {
  &:not(&--a, &--b):hover {
    background-color: green;
  }
}
```

**Current behavior:**

```less
.works:not(.works--a):not(.works--b):hover {
  background-color: green;
}

.broken:not(&--a, &--b):hover {
  background-color: green;
}
```

**Expected behavior:**

```less
.works:not(.works--a):not(.works--b):hover {
  background-color: green;
}

.broken:not(.broken--a, .broken--b):hover {
  background-color: green;
}
```

**Environment information:**

- `less` version: 4.2.2
- `nodejs` version: any
- `operating system`: any

We are currently in the middle of a battle of linters. We are told `:not(a):not(b)` is being classed as `complex, and should be changed to `:not(a, b)` but it appears less forgets to expand when this feature is being used. `4.2.2` at least compiles the syntax (though incorrectly) our older version `4.1.3` just keels over completely.. So I am guessing this is a relatively new feature and hasn't had much usage yet.
