### ISSUE TITLE
Bug when using the plus symbol on `calc` calls inside  `from` expressions for colors

### ISSUE THREAD

**Issue by filipesabella** [less/less.js#4316]
**To reproduce:**

```less
div {
  background: rgb(from blue calc(r + 100) g b);
}
```

**Current behavior:**

Less throws a `Could not parse call arguments or missing ')'` error.

**Expected behavior:**

Should generate:

```less
div {
  background: rbg(from red calc(r + 1));
}
```

**Environment information:**

Running on the official playground is enough to reproduce it:
https://lesscss.org/less-preview

Subtraction works just fine:

```less
div {
  background: rgb(from blue calc(r + 100) g b);
}
```

I also found another bug that might be related. This:

```less
div {
  background: rgb(from blue calc(100 - r) g b);
}
