### ISSUE TITLE
length for property group is always 1

### ISSUE THREAD

**Issue by ackava** [less/less.js#4325]
**To reproduce:**

https://lesscss.org/less-preview/#eyJjb2RlIjoiI2xpYigpIHtcbiAgICAuY29sb3JzKCkge1xuICAgICAgQHByaW1hcnk6IGJsdWU7XG4gICAgICBAc2Vjb25kYXJ5OiBncmVlbjtcbiAgICB9XG4gICAgLnJ1bGVzKEBzaXplKSB7XG4gICAgICBib3JkZXI6IEBzaXplIHNvbGlkIHdoaXRlO1xuICAgIH1cbiAgfVxuICBcbiAgLmJveCB3aGVuICgjbGliLmNvbG9yc1tAcHJpbWFyeV0gPSBibHVlKSB7XG4gICAgd2lkdGg6IDEwMHB4O1xuICAgIGhlaWdodDogKCR3aWR0aCAvIDIpO1xuICB9XG4gIFxuICAuYmFyOmV4dGVuZCguYm94KSB7XG4gICAgQG1lZGlhIChtaW4td2lkdGg6IDYwMHB4KSB7XG4gICAgICB3aWR0aDogMjAwcHg7XG4gICAgICAjbGliLnJ1bGVzKDFweCk7XG4gICAgfVxuICB9IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4yIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=

```less
.print(@list) {
  
  length-is {
    a: length(@list);
  }
}

.print({
  @a: {
    overflow: hidden;
  }
  @b: {
    overflow: hidden;
  }
});
```

**Current behavior:**

Output is:
```css
length-is {
  a: 1;
}
```

**Expected behavior:**

Output should be,

```css
length-is {
  a: 2;
}
```

As I need to iterate recursively to create few combinations, but problem is length is always zero, length works correctly for simple values, but not for property groups.
