### ISSUE TITLE
Absolute url inconsistency in Mix-Ins (less.js 1.1.5)

### ISSUE THREAD

**Issue by CreepGin** [less/less.js#469]
``` css
.bg(@url: "/media/img/black.png") {
    background-image: url("@{url}");
}
body {
    .bg("/media/img/white.png");
}
```

would result in:

``` css
body {
    background-image: url("http://www.mydomain.com/media/css//media/img/bglight.jpg")
}
```

to get around that, one would _have to_ use relative url:

``` css
body {
    .bg("../img/white.png");
}
```
