### ISSUE TITLE
Using mixins creates unecessary duplicated properties

### ISSUE THREAD

**Issue by phobia** [less/less.js#475]
Hi!

Currently, using mixins creates unecessary duplicated properties.

Are there any plans to remedy this, or are there alternative ways around it allready?

Here's an example of what I mean:
## In the stylesheet:

``` css
.mod {
    &.basic {
        margin-bottom: 10px;
        padding: 10px;
    }

    &.soft {
        .basic;
        background: #eee;
    }

    &.highlight {
        .basic;
        background: #ffc;
    }
}
```
## Desired output

``` css
.mod.basic,
.mod.soft,
.mod.highlight {
    margin-bottom: 10px;
    padding: 10px;
}

.mod.soft {
    background: #eee;
}

.mod.highlight {
    background: #ffc;
}
```

This is also what would be the result of using SASS' `@extend`. 
# Actual output

``` css
.mod.basic {
    margin-bottom: 10px;
    padding: 10px;
}
.mod.soft {
    margin-bottom: 10px; /* unecessary duplicate */
    padding: 10px; /* unecessary duplicate */
    background: #eee;
}
.mod.highlight {
    margin-bottom: 10px; /* unecessary duplicate */
    padding: 10px; /* unecessary duplicate */
    background: #ffc;
}
```

I'm sorry if this is a duplicate issue, I'm sure it has come up before, but I couldn't find anything when searching for it.
