### ISSUE TITLE
Custom functions

### ISSUE THREAD

**Issue by heyvito** [less/less.js#520]
Would be nice to have some way to implement custom functions, like:

``` javascript
@function bgIcon(name) {
    return background-image: url("/images/icons/@{name}");
}
```

Implementing the function... 

``` css
a.remove {
    bgIcon(delete.png);
}
```

Result:

``` css
a.remove {
    background-image: url("/images/icons/delete.png");
}
```
