### ISSUE TITLE
flag for excluding style from the current selector

### ISSUE THREAD

**Issue by MarcelloDiSimone** [less/less.js#533]
Feature Request:
I use less mainly because it helps me organize my css declarations. But doing so, leads often to bad code like unnecessary long selectors or even worse: ID's at the end of unnecessary long selectors. So it would be great to have a flag to exclude a "branch" from the current selector tree. For example with a prefixed minus

``` css
.className {
     margin: 0;
     -#id {
           border: 1px solid @black;
          .myClass { float: left; }
     }
}
```

would turn into 

``` css
.className { margin: 0; }
#id { border: 1px solid #999; }
#id .myClass { float: left; }
```

cheers Marcello
