### ISSUE TITLE
Designate a mixin as !important

### ISSUE THREAD

**Issue by reefdog** [less/less.js#547]
When calling a mixin (parametric or otherwise), if the call ends in `!important`, it would be splendid if this `!important` flowed down to all the mixin declarations.

So:

``` css
.bordered {
    border-top: dotted 1px black;
    border-bottom: solid 2px black;
}

#menu a {
    color: #111;
    .bordered !important;
}
```

Would generate:

``` css
#menu a {
    color: #111;
    border-top: dotted 1px black !important;
    border-bottom: solid 2px black !important;
}
```
