### ISSUE TITLE
allow trailing semi-Colon after nested rules

### ISSUE THREAD

**Issue by maxcan** [less/less.js#606]
Coming form the haskell world, I've adopted the leading punctuation list style:

``` css
body
  { margin: 5px
  ; padding: 5px
  ; font-face: serif
  ; }
```

The advantage of this is that its much easier to spot syntax errors and such.

in SCSS I could do the same for nested rules:

```
body 
  { margin: 5px
  ; h1 { ... }
  ; h2 { ... }
  ; } 
```

But in LESS, the semi-colons after nested rules break the syntax.  I'd be interested in working on a patch if the community would adopt it.  Would they?
