### ISSUE TITLE
1.2.1 String interpolation Issue

### ISSUE THREAD

**Issue by glfafn** [less/less.js#613]
``` css
@base-url: "/static";
background:url("@{base-url}/img/test.jpg");
```
#### In 1.1.5

/static/img/test.jpg
##### In 1.2.1 (missing the trailing slash in the start)

static/img/test.jpg
