### ISSUE TITLE
.flubber & {} does not work in client side version of less.js (IE7 only)

### ISSUE THREAD

**Issue by snorripall** [less/less.js#614]
Oh the irony. This  works in all browsers except IE7 when you're using the client-side version of less.js. 

``` css
#foobar{
    display:inline-block;
        .flubber & {
            zoom:1;
            display:inline;
            }
}
```

Should output to

``` css

#foobar{
     display:inline-block;
}

.flubber #foobar {
   zoom:1;
   display:inline;
}

```

So a fix for IE7 would be greatly appreciated.
