### ISSUE TITLE
Use of perspective with FireFox 10

### ISSUE THREAD

**Issue by AndreaBarghigiani** [less/less.js#616]
Hi guys this is my first real issue with LESS.js and it's something that I think most of us will encounter when start to develop 3D effects with FireFox.

The problem can summarize with this phrase:
"I would like to add a measurement to my variable"

That's the real problem! I created a minix to work with the _perspective_ property with FireFox but this browser is going to read the value of the property perspective in pixels, so I tried to do so with this bloc of code:

`````` css
.perspective-w-origin(
    @value: 0,
    @pi: px,
    @orig-x: 50%,
    @orig-y: 50%,
){
    -moz-perspective: @value@pi;
    -webkit-perspective: @value;
    perspective: @value;
    -moz-perspective-origin: @orig-x @orig-y;
    -webkit-perspective-origin: @orig-x @orig-y;
    perspective-origin: @orig-x @orig-y;
}```

This could be helpful for a lot of situations but here's the code generated:
```css
  -moz-perspective: 800 50%;
  -webkit-perspective: 800;
  perspective: 800;
  -moz-perspective-origin: 200px 50%;
  -webkit-perspective-origin: 200px 50%;
  perspective-origin: 200px 50%;
``````

Any Idea on how to solve this?

Thank's!
