### ISSUE TITLE
Dynamic mixin calling

### ISSUE THREAD

**Issue by Anahkiasen** [less/less.js#617]
Not much to say, I just think it would be a good idea if in LESS you could do the following :

``` css
.blue { color: blue }
.red { color: red }

.color(@color) {
   .@{color}
}

div {
   .color(red)
}
```

Resulting in

```
div { color: red }
```

.@{variable} is a proposition of syntax but .@variable, .{variable} or .{@variable} would maybe fit better the LESS syntax, I don't know.
