### ISSUE TITLE
@-khtml-keyframes (CSS3-animation)

### ISSUE THREAD

**Issue by Luzifr** [less/less.js#711]
Hi! I've run into a problem with keyframed CSS3-animations. Using the following keyframe-declaration:

``` css
@-khtml-keyframes glowButton {
    0% {
        -khtml-box-shadow: 0 1px 3px rgba(0, 0, 0, .1);
    }
    100% {
        -khtml-box-shadow: 0 1px 3px rgba(0, 0, 0, .1);
    }
}
```

(vendor-prefix for Konqueror-browser)

… leads to an error message in LESS. You can use every vendor-prefix in animation-keyframe-declarations that you want, but not -khtml-! That produces a "ParseError: Syntax Error" in the less.app and in the browser … 

```
Syntax Error on line 4364
in lessStylesheet on line 4364, column 1:

4364@-khtml-keyframes glowButton {
4365    0% {
```
