### ISSUE TITLE
issue with variable scope in namespaces

### ISSUE THREAD

**Issue by nlac** [less/less.js#719]
Hello,
please check the following code compiled flawlessly by less.js:

``` css
/* mixin library uses a variable from the "caller" namespace #skin */
#lib {
  //@w : @size;
  .rect() {
    width:2*@size;
    height:@size;
  }
}

/* "caller" namespace uses the mixins from #lib in its mixins */
#skin {
 @size : 100px;
  .panel() {
    #lib > .rect();
  }
}

/* constructing actual html class */
div.intro {
  #skin > .panel();
}
```

The issue: if i remove the comment before the `@w : @size;` the compilation fails.

Is there a particular reason why? Why the mixin body can see the `@size` variable and the variable defining rule can't, in the #lib namespace?

Regards, nlac
