### ISSUE TITLE
Mixin string arguments problem

### ISSUE THREAD

**Issue by byashimov** [less/less.js#726]
I use less 1.3 . Got problem with string argument in mixin. Unfortunately I can't explain it due to my english, just look at the code

``` less
.box(@image){
    // Leave this for tests
    height:100px;    width:100px;    display: block;

    // We need this lines
    background: transparent url('@{image}') 0 0 no-repeat;
    *background: transparent;
    // In this line @{image} variable have not been changed for the second time mixin call
    *filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='./@{image}', sizingMethod='scale');
}

.red {
    .box('red.png');
}

.blue {
    .box('blue.png');
}
```

It's compiled to:

``` css
.red {
  height: 100px;
  width: 100px;
  display: block;
  background: transparent url('red.png') 0 0 no-repeat;
  *background: transparent;
  *filter: progid:dximagetransform.microsoft.alphaimageloader(src='./red.png', sizingMethod='scale');
}
.blue {
  height: 100px;
  width: 100px;
  display: block;
  background: transparent url('blue.png') 0 0 no-repeat;
  *background: transparent;
/* As you can see @{image} had been changed just ones, here we have red.png instead of blue.png */
  *filter: progid:dximagetransform.microsoft.alphaimageloader(src='./red.png', sizingMethod='scale');
}
```
