### ISSUE TITLE
Variables in namespace parsing error

### ISSUE THREAD

**Issue by MarSOnEarth** [less/less.js#747]
The Wiki shows the following example:

``` less
#defaults {
    @width: 960px;
    @color: black;
}

.article { color: #294366; }

.comment {
    width: #defaults[@width];
    color: .article['color']; 
}
```

BUT the following fails with 1.3:

``` less
@width: 10px;
#ns {
    @paneW: @width;
}
// and using it
.pane {
    width: #ns[@paneW];
}
```
