### ISSUE TITLE
import a file but override and merge the selectors and properties

### ISSUE THREAD

**Issue by sethaldridge** [less/less.js#772]
We are doing some pretty heavy overwrites to a framework that uses LESS and we've found that in order to customize the library we have to import their code and then add our code to the bottom of it, which allows us to update the base library without overwriting our own changes.

However this adds a lot of extra code we don't need.

What I'm proposing woud be an additional method to how @import works. @extend would allow you to make changes to a specific file and it would overwrite the default options with your changes. 
## Example:

**Updated based on comments to better illustrate usage**
### myFirstFile.less:

``` css
body {
     background:#000;
     color: #fff;
     font: 100% Helvetica, Arial, sans-serif;
}

.container {
     width:940px;
}

.first, .second {
    background: orange;
}

.first {
    color: red;
}

.second {
    color: green;
}
```
### mySecondFile.less

``` css
@extend "myFirstFile.less";

body {
     color: #f00;
     font-size:13px;
}

.container {
     color: pink;
     width: 960px;
}

.first {
    color: #000;
    background: red;
}
```
### Output file mySecondFile.css

``` css
body {
     background:#000;
     color: #f00;
     font: 13px Helvetica, Arial, sans-serif;
}

.container {
     color: pink;
     width:960px;
}

.first, .second {
    background: orange;
}

.first {
    color: #000;
    background: red;
}

.second {
    color: green;
}
```

This would make our files much smaller while allowing us to decouple our changes from the main .LESS files.

Sorry if this is not the preferred way to suggest this change.
