### ISSUE TITLE
#NaN on border-color when parsing rgb command line

### ISSUE THREAD

**Issue by DataHerder** [less/less.js#812]
FYI:

Say I use lessc on a file that simply has this class:

``` CSS
.random {
  border-color: transparent transparent transparent rgb(230,230,230);
}
```

It will output:

``` CSS
.random {
  border-color: #NaNbbaaNaN00NaN00NaN00NaN00NaN #NaNbbaaNaN00NaN00NaN00NaN00NaN #NaNbbaaNaN00NaN00NaN00NaN00NaN #e6e6e6;
}
```

However this will not happen if I run it on this:

``` CSS
.random {
  border-color: transparent transparent transparent #e6e6e6;
}
```

I have tested this on "color" as well so I think this is a global issue.
