### ISSUE TITLE
No operate support for Javascript evaluation

### ISSUE THREAD

**Issue by YuJianrong** [less/less.js#816]
Hi I had found the following code does not work: 

``` LESS
.class {
    @a: `20`;
    @b: 30;
    width: @a + @b ;
}
```

or

``` LESS
.class {
    @a: ~`20`;
    @b: 30;
    width: @a + @b ;
}
```

when the variable comes from javascript evaluation, it cannot be calculated, which I think very important for leave the configuration outside the LESS file.
