### ISSUE TITLE
Feature Request: support color tests in guarded mixins

### ISSUE THREAD

**Issue by lavoiesl** [less/less.js#830]
I would really like to be able to do this:

``` css
.gradient(@startColor: #555, @endColor: #333) when (@startColor = @endColor)  {
  background-color: @startColor;
}
```

At this moment, this code throws an error  that I don’t really understand:

```
Error Output:
TypeError: Cannot call method &#039;charAt&#039; of undefined
    at getLocation (/usr/local/lib/node_modules/less/lib/less/parser.js:212:34)
    at new LessError (/usr/local/lib/node_modules/less/lib/less/parser.js:221:19)
    at Object.toCSS (/usr/local/lib/node_modules/less/lib/less/parser.js:385:31)
    at /private/var/tmp/assetic_less6dnR1T:11:24
    at /usr/local/lib/node_modules/less/lib/less/parser.js:434:40
    at /usr/local/lib/node_modules/less/lib/less/parser.js:94:48
    at /usr/local/lib/node_modules/less/lib/less/index.js:116:17
    at /usr/local/lib/node_modules/less/lib/less/parser.js:434:40
    at /usr/local/lib/node_modules/less/lib/less/parser.js:94:48
    at /usr/local/lib/node_modules/less/lib/less/index.js:116:17
```

Thanks !
