### ISSUE TITLE
Feature request: support checking html element in guards

### ISSUE THREAD

**Issue by lunelson** [less/less.js#833]
It would be nice to be able to write a guard function for a mixin, that could check the html element that it is being declared for. It would look something like this:

```
.set-margins(@font-size) when (element = ul) {margin-left: @font-size * 2;}
```

This is part of a larger approach I am using to build a suite of typographic sizes and measures in to a kind of master mixin. It could be very powerful if there was a way of checking...

**Comment by matthew-dean** [comment]
I don't get how this would work? How is it applied to that element? What is the keyword `element` referencing?

**Comment by seven-phases-max** [comment]
I suppose `element` it's some sort of "use `&` as regular value"... E.g. (pseudo-code):
```Less

.set-margins(@font-size) when (& = ul)  {
      margin-left: @font-size * 2;
      me: &;
}

ul {
    .set-margins(33);
}

```
resulting in:
```css
ul {
    margin-left: 33;
    me: ul;
}
```
I was pretty sure such FR (with `&`-based syntax) already exists, but hmm, can't find...

**Comment by matthew-dean** [comment]
What.... I don't get this at all.

**Comment by seven-phases-max** [comment]
Mmm... basically it's just regular "parent selector" (well, sort of) but also allowed to be used as property value (not just in selector string as it is now), e.g.:
red {
   color: &; // -> red
}
```

**Comment by matthew-dean** [comment]
@seven-phases-max o_O That wasn't the request. It was to guard against the selectors used.

**Comment by seven-phases-max** [comment]
It's basically the same thing obviously any value in guard is a regular value so if it can be used in guards it also can be used anywhere... We don't have special "guard" values. :)

**Comment by matthew-dean** [comment]
@seven-phases-max ...Okay, but then there are even fewer cases where that would have any usefulness.

**Comment by seven-phases-max** [comment]
Maybe. maybe not. Currently the only use-case I can imagine is something around https://github.com/less/less.js/issues/1694#issuecomment-29557813.

**Comment by matthew-dean** [comment]
Btw, this statement isn't true IMO:
```
It's basically the same thing obviously any value in guard is a regular value so if it can be used in guards it also can be used anywhere
```
A guard can have a detached ruleset, can it not? But it can't be used in place of a property's values. There are still rules about where that node type can be used, and `&` is basically a list of selectors. Selectors can only used where selectors can be used, they can't be dumped in as a generic value.

**Comment by seven-phases-max** [comment]
>But a DR can't be used in place of a property's values, even though it's a value passed to a mixin. 

It's artifically supressed at the parsing stage. In fact if you assign a DR to a property within a plugin (i.e. bypassing the parsing stage) it will work (expanding to void though).

**Comment by matthew-dean** [comment]
@seven-phases-max Still, I think you're confusing the issue with your example. That's a whole other deal. Right now the only request is within mixin guards, and referencing `&` as a property value should be opened as a separate issue, if you think that feature is important.

I went through the thread in #1174, which IMO has a much better explanation / use case for this (that is: an actual use case - it would make sense to have closed this issue and left that one open, but nm). Similarly to my comment on that a while back, and what I noted again here, anything like `& =` is an awkward semantic construction. If we just want to match a selector from the caller scope, I would avoid treating `&` as you say as a regular value, and expose a matching function, like ```match()```, as in:
```less
h1, h2, h3, h4 {
    // lots of shared less

    & (when match(h1)) { // or however you would want to do this syntactically
        color: blue;
    }

    & (when match(h2)) {
        color: white;
    }

    & (when  match(h3)) {
        color: yellow;
    }

    & (when match(h4)) {
        color: red;
    }
}
```
The reason why I say that is because `&` represents all of those selectors, but during evaluation, each member of `&` is being expanded, and so _that's_ what you're really trying to match, not all of `&` it self.
