### ISSUE TITLE
Inline variables in curly braces @{} get cached and don't update

### ISSUE THREAD

**Issue by MikeBagos** [less/less.js#836]
Consider the code:

``` css
@border-color: #B2B;

.testme(@culprit: @border-color)
{
   filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='@{culprit}', endColorstr='@{culprit}'); // IE
}

.la {
    .testme();
}

.la2 {
    .testme(#FF0000);
}

.la3 {
    .testme(#FF0110);
}
```

This will wield:

```
.la {
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#bb22bb', endColorstr='#bb22bb');
}
.la2 {
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#bb22bb', endColorstr='#bb22bb');
}
.la3 {
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#bb22bb', endColorstr='#bb22bb');
}
```

Which is incorrect, because the color does not update!
