### ISSUE TITLE
Suggestion: best practices for vendor-prefixed properties in home page examples

### ISSUE THREAD

**Issue by tagliala** [less/less.js#851]
Hi all,

Just a little suggestion...

I noticed that in the home page there are some examples with vendor-prefixed properties, like:

``` css
.rounded-corners (@radius: 5px) {
  border-radius: @radius;
  -webkit-border-radius: @radius;
  -moz-border-radius: @radius;
}
```

As you know, the standard css3 property (`border-radius` in this example) should be placed at the bottom of the class, so new users will see a proper example of css.

Best Regards

GT
