### ISSUE TITLE
:after should be placed at end of css-rule

### ISSUE THREAD

**Issue by willemdewit** [less/less.js#852]
See the following example:

``` css
.test:after {
    &.other-class { background: red; }
}
```

it compiles, but the compiled css is invalid:

``` css
.test:after.other-class {
  background: #ff0000;
}
```

The first rule should have :after at the end.
