### ISSUE TITLE
Cannot tell diff between percentages and pixels

### ISSUE THREAD

**Issue by cyberwombat** [less/less.js#855]
when using guards less cannot tell the diff between percentage values and pixels.

``` css
@width = 100px;

.mixin(@a) when (@a = 100%) {
color:black;
}

.mixin(@width);
```

will cause .mixin to pass the test and have the color black;
