### ISSUE TITLE
Numbers in attribute selectors produce parser errors

### ISSUE THREAD

**Issue by ForbesLindesay** [less/less.js#863]
``` css
ul.wysihtml5-toolbar a[data-wysihtml5-command=bold] {
    font-weight: bold;
}
```

Produces the error:

ParseError: Syntax Error on line 1 ...

1 ul.wysihtml5-toolbar a[data-wysihtml**5-command=bold] {**
2      font-weight: bold;

Where the bold bit is in red on the command line.  There is no way to escape this so I can't fix it.
