### ISSUE TITLE
Duplicated nested mixin rule when @importing multiple times 

### ISSUE THREAD

**Issue by suisho** [less/less.js#884]
This issue is like #49.
When import same file multiple times, I got result that has duplicated nested mixin rule (only nested mixin) 
For example 

_mixin.less

``` less
.mixin() {
  color:yellow;
  .mixin-inner{
    color:red;
  }
}
```

some-block.less

``` less
@import "_mixin";

.some_block{
  .mixin;
  color:red;
}
```

hoge-block.less

``` less
@import "_mixin";
@import "some-block.less";

.hoge_block{
  .mixin;
  color:blue;
}
```

and result 
some-block.less

``` css
.some_block {
  color: yellow;
  color: red;
}
.some_block .mixin-inner {
  color: red;
}
```

hoge-block.less

``` css
.some_block {
  color: yellow;
  color: red;
}
.some_block .mixin-inner {
  color: red;
}
.some_block .mixin-inner {
  color: red;
}
.hoge_block {
  color: yellow;
  color: blue;
}
.hoge_block .mixin-inner {
  color: red;
}
.hoge_block .mixin-inner {
  color: red;
}
```

but expected result 

``` css
.some_block {
  color: yellow;
  color: red;
}
.some_block .mixin-inner {
  color: red;
}
.hoge_block {
  color: yellow;
  color: blue;
}
.hoge_block .mixin-inner {
  color: red;
}
```
