### ISSUE TITLE
Only the first-called parameters used in function call

### ISSUE THREAD

**Issue by Gucin** [less/less.js#945]
I am trying to write a shadow function of LESS.  The code are listed below:

``` LESS
#shadow {
  .shadow-reg(@rgbaColor, @rgbColor, @width, @pX, @pY) {
    -moz-box-shadow: @pX @pY @width @rgbaColor;
    -webkit-box-shadow: @pX @pY @width @rgbaColor;
    box-shadow: @pX @pY @width @rgbaColor;
    /* For IE 5.5 - 7 */
    @hwidth: @width/2;
    filter: progid:dximagetransform.microsoft.shadow(color=@rgbColor, Direction=120, Strength=`parseInt("@{width}".replace(/px/ig, ""))`);
    /* For IE 8 */
   // -ms-filter: "progid:DXImageTransform.Microsoft.Shadow(Strength=2, Direction=120, Color='#989ea1')";
    background: #FFFFFF;
    zoom: 1;
  }
}

.dropShadowDarkSmall {
  #shadow > .shadow-reg(~'rgba(0, 0, 0, 0.5)', ~'#000000', 2px, 0px, 1px);
}

.dropShadowLightSmall {
  #shadow > .shadow-reg(~'rgba(152, 158, 161, 0.35)', ~'#989ea1', 2px, 0px, 1px);
}

```

And the output of class "dropShadowDardkSmall" and "dropShadowLightSmall" are:

``` css
.dropShadowDarkSmall {
  -moz-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5);
  -webkit-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5);
  box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5);
  /* For IE 5.5 - 7 */

  filter: progid:dximagetransform.microsoft.shadow(color=#000000, Direction=120, Strength=2);
  /* For IE 8 */

  background: #FFFFFF;
  zoom: 1;
}
.dropShadowLightSmall {
  -moz-box-shadow: 0px 1px 2px rgba(152, 158, 161, 0.35);
  -webkit-box-shadow: 0px 1px 2px rgba(152, 158, 161, 0.35);
  box-shadow: 0px 1px 2px rgba(152, 158, 161, 0.35);
  /* For IE 5.5 - 7 */

  filter: progid:dximagetransform.microsoft.shadow(color=#000000, Direction=120, Strength=2);
  /* For IE 8 */

  background: #FFFFFF;
  zoom: 1;
}
```

As we can see, the color property of filter are same(both are using the rgbColor of  "dropShadowDarkSmall") . And my LESS version is 1.3.0 and the code are compiled under NodeJS env.
