### ISSUE TITLE
Group media queries

### ISSUE THREAD

**Issue by Soviut** [less/less.js#950]
While the media query bubbling is great:

```less
header {
    color: green;

    @media only screen (max-width: 500px) { color: red; }
}

footer {
    color: green;

    @media only screen (max-width: 500px) { color: red; }
}
```

Less generates fairly bloated code because it repeats the mediaquery selector each time its declared in the less file:

```css
header {
  color: green;
}
@media only screen (max-width: 500px) {
  header {
    color: red;
  }
}
footer {
  color: green;
}
@media only screen (max-width: 500px) {
  footer {
    color: red;
  }
}
```

It would be nice if media queries could be grouped if they're identical:
```css
header {
  color: green;
}
footer {
  color: green;
}

@media only screen (max-width: 500px) {
  header {
    color: red;
  }
  footer {
    color: red;
  }
}
```

**Comment by bassjobsen** [comment]
Since v2 you can use plugins, so see https://github.com/bassjobsen/less-plugin-group-css-media-queries (and https://github.com/bassjobsen/less-plugin-pleeease)

**Comment by matthew-dean** [comment]
Closing since this is supported by a plugin, and isn't a priority to move into core.

**Comment by nfq** [comment]
@gyopiazza I have a question about #issuecomment-17723748 above: why do you need to initialise the mixin? I mean, the CSS compiles without the init. I guess I am trying to understand best practices and usage.

**Comment by seven-phases-max** [comment]
@gyopiazza This is not quite an initialization but just "default" empty definition. It's necessary in case you don't provide your custom `.step*()` mixins (i.e. it's assumed that you may have these things in different files, e.g. "default" `.step*()` definitions and rendering is in some generic utility/library code, while custom `.step*()` definitions is in your theme/project specific code).

**Comment by gyopiazza** [comment]
@nfq It's actually not necessary. Edited :)
Btw, the advantage of this technique is that combining media queries slows down compilation time (a bit).

**Comment by nfq** [comment]
@gyopiazza Thanks for the quick reply. I don't mind the compilation time, and for huge projects, I definitely prefer grouping all media queries at the bottom of the main stylesheet. I tried a few of the plugins but found your way the easiest for our use case and the most convenient. Thanks!!

**Comment by nfq** [comment]
@seven-phases-max Thanks, your answer makes sense. I use less a lot, but haven't yet understood the best way to achieve certain things!

**Comment by bassjobsen** [comment]
Notice that also clean-css support @media merging since v3, and so does the [less-plugin-clean-css](https://github.com/less/less-plugin-clean-css)

with main.less:
```css
header {
    color: green;

    @media only screen (max-width: 500px) { color: red; }
}

footer {
    color: green;

    @media only screen (max-width: 500px) { color: red; }
}
```

`lessc --clean-css="advanced" main.less` outputs:
`footer,header{color:green}@media only screen (max-width:500px){footer,header{color:red}}`

less-plugin-clean-css sets the --skip-advanced true by default you should explicit set the `advanced` option for @media merging
