### ISSUE TITLE
Anchors don't work with a mixin but it does with a class

### ISSUE THREAD

**Issue by Garito** [less/less.js#978]
Hi!
I'm trying to make Twitter bootstrap more semantic (don't like to mix presentation classes in the html markup)

So I'm overwritting sprites.less with this mixin:

``` css
.iconize(@reverse: false) {
  display: inline-block;
  width: 14px;
  height: 14px;
  .ie7-restore-right-whitespace();
  line-height: 14px;
  vertical-align: text-top;
  background-image: url("@{iconSpritePath}");
  background-position: 14px 14px;
  background-repeat: no-repeat;
  margin-top: 1px;
}

.iconize(@reverse) when (@reverse = true) {
  background-image: url("@{iconWhiteSpritePath}");
}

[class^="icon-"],
[class*=" icon-"] {
  .iconize();
}
```

If you're familiar with TB you will note how I take the original [class^="icon-"], [class*="icon-"] code and put it in a new iconize mixin then I call .iconize() from the original rule in order to work all as expected

I know this works using a class because of this code:

``` html
<div class="Borrar">
    <a data-confirmacion="Borro Producto 1?" class="js-confirmar" title="Borrar Producto 1" alt="Borrar Producto 1" href="http://localhost:8080/Datos/Clientes/Sistes/Sites/sistes.net/Tiendas/UnaTienda/Categorias/atletismo/Productos/producto-1/Borrar/">
        <i class="icon-trash"></i>
    </a>
</div>
```

As you can see, there is an i element with a class .icon-trash inside an anchor. In this way the less rules/mixins works as expected

But, I want the mixin in order to not put the i class and make something like:

``` css
.Borrar {
    .iconize();
    .icon-trash;
```

And this work as expected (it shows the icon) but not for the anchor (it doesn't work as an anchor with this code. No cursor change, this don't worry me, and No clickable element)

Could someone point me where is my mistake and how to solve it?

Thanks a lot
