### ISSUE TITLE
Less does not print when @font-face is imported.

### ISSUE THREAD

**Issue by envygeeks** [less/less.js#979]
``` css
// base.less
@import "fonts"
```

``` css
// fonts.less
@font-face {
  font-family: 'Museo Slab 500';
  font-weight: normal;
  src: url('@{font-url}museo-slab-webfont.woff');
}
```

When doing it the above referenced way `lessc` refuses to actually print the `@font-face` but when it's put directly into `base.less` it will parse it.  It seems that `lessc` favors putting everything into a single file if it involves @?
