### ISSUE TITLE
& Combinator Combined With Adjacent Sibling Combinator Problem

### ISSUE THREAD

**Issue by Gabby-Paolucci** [less/less.js#986]
I am having a problem combining the & Combinator with the adjacent sibling combinator.

The following does not compile:

``` css
fieldset
{
    label, .EditingFormLabel
    {
        &:first-child, legend + &
        {
            margin-top: 0;
        }
    }
}
```

I'm forced to use this syntax:

``` css
fieldset
{
    legend
    {
        & + label, & + .EditingFormLabel
        {
            margin-top: 0;
        }   
    }
    label, .EditingFormLabel
    {
        &:first-child
        {
            margin-top: 0;
        }
    }
}
```

It seems like the syntax I am attempting should be valid. I would like to be able to use the same LESS statement for:

``` css
fieldset legend + label
fieldset legend + .EditingFormLabel
fieldset label:first-child
fieldset .EditingFormLabel:first-child
```

Is there something I am missing, is this a bug with LESS, or is LESS just designed for me to use the second syntax?
